### PR TITLE
Images releng account perf jobs

### PR DESCRIPTION
**Pull request by fgelcer**
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
giving it a ride [here](https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/images_on_releng_account/job/perf-during-ops/2/), as we need results anyways

**Comment by fgelcer** [comment]
@roydahan @temichus , if we still want to have perf results this week, please merge this PR ASAP

**Review by fruch — APPROVED** [review]
LGTM

**Comment by temichus** [comment]
@fgelcer  
as i see unit tests unit_tests/test_utils_common.py::TestUtils::test_tag_ami_01 is failed
Could you please fix it?

**Comment by fruch** [comment]
> @fgelcer as i see unit tests unit_tests/test_utils_common.py::TestUtils::test_tag_ami_01 is failed Could you please fix it?

there is probably lot of test failure, in that branch (mostly cause of AMI that are being remove)

I would advice backporting those fixes on their own PR, and not mix it with anything else

we suffer from this on any long running branch, we rarely do PRs into them, so we missing any fixes needed to the unittests

**Review by soyacz — APPROVED** [review]
LGTM

**Pull request merged**
