### PR TITLE
Fixing broken longevity pipeline

### PR DESCRIPTION
**Pull request by fgelcer**
broken due to adding parameters partially

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I gave variables/functions meaningful self-explanatory names
- [ ] I didn't leave commented-out/debugging code
- [ ] I didn't copy-paste code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by bentsi** [comment]
We should think before adding this to the longevity pipeline, that will affect all the pipelines.
@fruch do not merge this
@fgelcer What is the use case? How we ran all longevity jobs till today and the pipeline was not considered "broken"?

**Comment by bentsi** [comment]
Looks for me that this is a special case for manager related jobs, so either put the configuration in the specific YAMLs or create a new type of pipeline

**Comment by bentsi** [comment]
@fruch why did you merge it?

**Comment by bentsi** [comment]
@fruch will create a task to fix your fix
@fgelcer please fix this ASAP

**Comment by fruch** [comment]
Created this task:
https://trello.com/c/0ELMxbrc/1577-refactor-longevity-pipeline-to-remove-manger-related-parameters-out-if-it

**Pull request merged**
