### PR TITLE
fix(test_stop_compaction): fix for reshape tests

### PR DESCRIPTION
**Pull request by soyacz**
Due wrong default value the same test was executed twice.
Also because reshape already happened, the second test didn't
run reshape at all.
Fix is setting proper default value and change compaction strategy
for reshape_on_boot test.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@soyacz @fgelcer backports needed ?

**Comment by fgelcer** [comment]
@soyacz , where did you see it failing? is 5.0 branch affected?

**Comment by fgelcer** [comment]
@fruch , i confirm we saw it on 5.0, so it needs to be backported to 5.0 and 2022.1 please.

**Pull request merged**
