### PR TITLE
Remove the node name from map field

### PR DESCRIPTION
**Pull request by aleksbykov**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [] ~~All new and existing unit tests passed (`hydra unit-tests`)~~
- [] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by aleksbykov** [comment]
Also, maybe write a script which will go through all results and change this fields to new one?

**Comment by roydahan** [comment]
Yes, we will need a script to go over the results and change them.
Do you have a sample JSON with the new result?

**Comment by aleksbykov** [comment]
@Roy,
Sorry forgot to add to commit desc
Now it will look like this:
    "setup_details": {
      "cloud_credentials_path": "~/.ssh/support",
      "db_type": "scylla",
      "run_fullscan": "random, 1",
      "cluster_backend": "aws",
      "user_prefix": "abykov-test-abykov",
      **"db_cluster_node_details": {
        "sys_info": "Linux ip-172-30-0-148.ec2.internal 5.1.8-1.el7.elrepo.x86_64 #1 SMP Sun Jun 9 08:49:11 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux",
        "cpu_model": "Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz"
      },**
      "nemesis_filter_seeds": true,

**Comment by bentsi** [comment]
I am merging this and will create a new task in Trello

**Pull request merged**
