### PR TITLE
Support all compression types in longevity

### PR DESCRIPTION
**Pull request by roydahan**

### CODE REVIEW

**Comment by roydahan** [comment]
Need more testing before I change all other longevity yamls.

**Comment by roydahan** [comment]
@amoskong, we need to backport this to enterprise branch.
(about to send another PR to update all other longevity yamls).

**Comment by amoskong** [comment]
Backported one commit to branch-perf.

commit e4fae84de3108245687fdfd8c1076f60640722ea (HEAD -> branch-perf,
origin/branch-perf)

Author: Roy Dahan <roy@scylladb.com>

Date:   Mon Feb 19 00:45:05 2018 +0200


    Adding 3 more stress_cmds for write & read to work with compression
(all types).



    These cmds use new keyspaces, that's why I need to push the
keyspace_name in case compression is in the stress cmd.

    There might be issues to work with all possible combination of the test
including multi keyspace in round_robin.

    We may want to seperate the multi-keyspace logic to a different test
case in the future and reduce some of the login in test_custom_time.



    (cherry picked from commit 438076a9396627ef63fbf18105b7869d7cae1cb2)

    Signed-off-by: Amos Kong <amos@scylladb.com>

**Comment by roydahan** [comment]
@amoskong, your backport is wrong.
we need it for branch-enterprise not branch-perf.

**Comment by amoskong** [comment]
I had reverted the backport from branch-perf [1].

[1] https://github.com/scylladb/scylla-cluster-tests/commits/branch-perf

There are many conflicts in backporting the patch to branch-enterprise, I'm
trying to solve the conflicts.

**Comment by amoskong** [comment]
Attached a patch, which backported [1] to branch-enterprise, please help to
review.
Details:  reduced threads number of original write/read stress, keep it
same as latest master.

[1] commit 438076a9396627ef63fbf18105b7869d7cae1cb2
<https://github.com/amoskong/scylla-cluster-tests/commit/438076a9396627ef63fbf18105b7869d7cae1cb2>

**Comment by amoskong** [comment]
Backported two commits to SCT branch-enterprise.

330a843 Adding 3 more stress_cmds for write & read to work with compression
(all types).

2a020cc introduce keyspace_name parameter

**Pull request merged**
