### PR TITLE
Fix arm longevities

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by ShlomiBalalis** [comment]
Should only be backported after https://github.com/scylladb/scylla-cluster-tests/pull/4292.
After the 4.6 runs will pass, those 2 prs should be backported to 2021 as well.

**Review by fruch — APPROVED** [review]
LGTM

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by ShlomiBalalis** [comment]
Also, it's important to note that manager was not tested with arm machines before (it was not in the change log of 2.6) so merge it with caution.

**Comment by fgelcer** [comment]
> Also, it's important to note that manager was not tested with arm machines before (it was not in the change log of 2.6) so merge it with caution.

can you please confirm with Releg if 2.6 really supports ARM?
if not, then manager installation must be disabled to these tests until there is support.

**Comment by ShlomiBalalis** [comment]
> > Also, it's important to note that manager was not tested with arm machines before (it was not in the change log of 2.6) so merge it with caution.
> 
> can you please confirm with Releg if 2.6 really supports ARM? if not, then manager installation must be disabled to these tests until there is support.

Both beni and yaron confirmed that it does

**Review by roydahan — APPROVED** [review]

**Pull request merged**
