### PR TITLE
Added RUNTIME_ERROR filter to AWSNode.restart

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I gave variables/functions meaningful self-explanatory names
- [ ] I didn't leave commented-out/debugging code
- [ ] I didn't copy-paste code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by ShlomiBalalis** [comment]
@fruch Is there any reason the restart function does not use the event filter's context manager?

**Comment by fruch** [comment]
@ShlomiBalalis I guess cause it's logic is spanning more then on context.

**Comment by fruch** [comment]
@ShlomiBalalis can you refer to which print newly added that this need to be added ? also backports.

**Comment by fruch** [comment]
@ShlomiBalalis, no backports is needed for this one ?

**Comment by fruch** [comment]
@ShlomiBalalis ping... need backport tags for this one..

**Pull request merged**
