### PR TITLE
refactor(artifact-arm): set manager 2.6 agent installation for arm tests

### LINKED ISSUE #4288: [artifacts-centos8-arm]: Failing due to hard coded manager version which doesn't support arm
In 2021.1.8 we added arm support, since SCT are using manager 2.3 for this version those arm based artifacts are failig

https://jenkins.scylladb.com/job/enterprise-2021.1/job/artifacts/job/artifacts-centos8-arm-test/8/console

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

closes #4288

### CODE REVIEW

**Comment by ShlomiBalalis** [comment]
Since the artifact doesn't require the installation of the manager server, it doesn't require the large backport I thought it did before. Therefore, this pr should suffice. (already tested on centos 8)

**Comment by ShlomiBalalis** [comment]
Also, I can't modify the entirety of the artifact tests to use 2.6, but not other test senarios since they'll require manager server installations as well. This will require a larger backport

**Comment by fruch** [comment]
@ShlomiBalalis can you add the 'Closes: #[relevant issue number]'

So the issue would automatically close once this PR get merged

**Comment by ShlomiBalalis** [comment]
> @ShlomiBalalis can you add the 'Closes: #[relevant issue number]'
> 
> So the issue would automatically close once this PR get merged

In the commit message or the pr description?

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
