### PR TITLE
fix(argus): workaround arguns installation in an old branch

### PR DESCRIPTION
**Pull request by fgelcer**
installation of argus is failing on old branches,
because changes done in Argus, making the early
stages of the test to fail, so the tests are not
even starting.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@fgelcer can paste in how a failure looks like ? also point to a working run if there is one.

**Comment by fgelcer** [comment]
> @fgelcer can paste in how a failure looks like ? also point to a working run if there is one.

example of a working run [here](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/for_xemul/job/5.0_latency-with-nemesis-rbno-control/10/)

the error is as follows:
```
Traceback (most recent call last):
  File "/home/jenkins/slave/workspace/scylla-master/scylla-master-perf-regression-latency-250gb-with-nemesis/scylla-cluster-tests/./sct.py", line 37, in <module>
    from sdcm.argus_test_run import ArgusTestRun
  File "/home/jenkins/slave/workspace/scylla-master/scylla-master-perf-regression-latency-250gb-with-nemesis/scylla-cluster-tests/sdcm/argus_test_run.py", line 19, in <module>
    from argus.db.db_types import TestStatus
ModuleNotFoundError: No module named 'argus'
```

and then:
```
Argus failed to install!
Obtaining argus from git+https://github.com/bentsi/argus#egg=argus
  Updating ./src/argus clone
  Running command git fetch -q --tags
  Running command git reset --hard -q 31b3d89e3163ec62c2904c04723f065db9eabddb
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_editable /tmp/tmp80qcj9gf
       cwd: /home/jenkins/slave/workspace/scylla-master/scylla-master-perf-regression-latency-250gb-with-nemesis/scylla-cluster-tests/src/argus
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 178, in prepare_metadata_for_build_editable
      return hook(metadata_directory, config_settings)
    File "/tmp/pip-build-env-qwv2_19d/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
      poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
    File "/tmp/pip-build-env-qwv2_19d/overlay/lib/python3.10/site-packages/poetry/core/factory.py", line 43, in create_poetry
      raise RuntimeError("The Poetry configuration is invalid:\n" + message)
  RuntimeError: The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
  
  ----------------------------------------
```

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fgelcer** [comment]
need to confirm if we need it on older branches, and also `branch-perf-v13`

**Comment by fruch** [comment]
> need to confirm if we need it on older branches, and also `branch-perf-v13`

branch v13 is using this version:
```
https://github.com/bentsi/argus/archive/refs/tags/v0.5.5.zip
```

so it should be good enough...

**Comment by fgelcer** [comment]
and BTW, the test is now running

**Pull request merged**
