### PR TITLE
refactor(jenkins): remove unused parameter `params'

### PR DESCRIPTION
**Pull request by enaydanov**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [x] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [x] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fruch — APPROVED** [review]
LGTM, I don't even remember the initial reason I've did that...

**Comment by fruch** [comment]
Let me check in siren-tests before we merge, that the pipeline copied there isn't using that in some weird way

**Review by bentsi — APPROVED** [review]

**Comment by enaydanov** [comment]
> Let me check in siren-tests before we merge, that the pipeline copied there isn't using that in some weird way

@fruch any news on this?

**Comment by fruch** [comment]
> > Let me check in siren-tests before we merge, that the pipeline copied there isn't using that in some weird way
> 
> @fruch any news on this?

Now this can be merge, issues were fixed in siren-tests

**Pull request merged**
