### PR TITLE
Update monitoring node branch to 4.4 and fix grafana screenshots

### PR DESCRIPTION
**Pull request by k0machi**
- feature(monitoring): test_default.yaml set monitoring branch to 4.4
- fix(monitorstack/ui): Adjust Panel locator for branch-4.4

Task: scylladb/qa-tasks#1377

Closes #6109

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [x] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [x] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by soyacz — APPROVED** [review]
LGTM

**Review by temichus — APPROVED** [review]

**Comment by soyacz** [comment]
@k0machi please add label if backport needed

**Comment by k0machi** [comment]
Forgot to include a [testing job](https://argus.scylladb.com/test/b0b22734-758e-47b4-b6ec-29e64d212d52/runs?additionalRuns[]=2e86ff7a-5611-42a0-bb9d-fefe103c0d29), seems to work, but now there's only one screenshot.

**Comment by k0machi** [comment]
I would wait for backports to see if master is doing everything correctly.

**Comment by fruch** [comment]
> Forgot to include a [testing job](https://argus.scylladb.com/test/b0b22734-758e-47b4-b6ec-29e64d212d52/runs?additionalRuns%5B%5D=2e86ff7a-5611-42a0-bb9d-fefe103c0d29), seems to work, but now there's only one screenshot.

there no screenshots on the testing job you linked....

now testing #6408, and there no screenshots there as well...

**Comment by fruch** [comment]
@k0machi 

see:
https://jenkins.scylladb.com/blue/organizations/jenkins/sct-github-PRs-scan%2Fscylla-cluster-tests/detail/PR-6408/2/pipeline/89

we still don't have screenshots working

**Comment by k0machi** [comment]
> @k0machi 
> 
> see:
> https://jenkins.scylladb.com/blue/organizations/jenkins/sct-github-PRs-scan%2Fscylla-cluster-tests/detail/PR-6408/2/pipeline/89
> 
> we still don't have screenshots working

I see, I didn't notice the snapshot code being used, will fix

**Comment by temichus** [comment]
@fruch, @soyacz 
This PR https://github.com/scylladb/scylla-cluster-tests/pull/6486 fixes issue with the snapshot 

now we can backport the current PR

**Comment by soyacz** [comment]
> @fruch, @soyacz This PR #6486 fixes issue with the snapshot
> 
> now we can backport the current PR

@temichus mentioned PR updates monitoring to 4.5 - do we need go back to 4.4?

**Comment by k0machi** [comment]
> > @fruch, @soyacz This PR #6486 fixes issue with the snapshot
> > now we can backport the current PR
> 
> @temichus mentioned PR updates monitoring to 4.5 - do we need go back to 4.4?

We need e990605266bbbf5e5a3652aa04c09f944661f3ae from this PR, if it hasn't been FFed yet or backported.

**Comment by fruch** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/6486 is merged and backported.

No point of backporting this change anywhere

If there's need to backport #6486 to more branches let's discuss it there

**Pull request merged**
