### PR TITLE
fix(common.py): add ubuntu 22 to `get_distro_name`

### PR DESCRIPTION
**Pull request by fgelcer**
from previous work, seems like ubuntu 22 was still
missing from this function, and artifacts test was
failing because of it.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by yaronkaikov — APPROVED** [review]

**Comment by fgelcer** [comment]
fixing for because [this job](https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ubuntu2204-test/8/) failed with the following error:
```
ERROR > exception=[Node artifacts-ubuntu2204-jenkins-db-node-15cca4c7-0-1 [34.73.19.216 | 10.142.1.68] (seed: True)] NodeSetupFailed: Unfamiliar distribution: Distro.UBUNTU22
```

**Comment by fgelcer** [comment]
Refs: https://github.com/scylladb/scylla/issues/10669#issuecomment-1162136074

**Comment by fruch** [comment]
@fgelcer why is manager code has to be special ? i.e. this list seem to be exact same list in Distro class. (I know in older manger versions, not all were supported, it shouldn't be the case anymore)

@rayakurl @ShlomiBalalis , 
seem like it was introduce around https://github.com/scylladb/scylla-cluster-tests/commit/5099f7d205ff41e0b701dd441d617be35dc862e8

can we add a task to replace it with a code that look it  up in s3 (like we do for scylla), and not on consistently adding every new release of manager or scylla into those files ?

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
