### PR TITLE
fix(sct_config): Update of the help markdown

### PR DESCRIPTION
**Pull request by fruch**
changed the config parameters to be linkable with anchors
so we can send link directly to the specific parameter in where we need it

### CODE REVIEW

**Comment by bentsi** [comment]
@fruch I checked on https://github.com/fruch/scylla-cluster-tests/blob/update_sct_options_markdown/docs/configuration_options.md#scylla_version
and it looks like the anchor doesn't work...

**Comment by fruch** [comment]
> @fruch I checked on https://github.com/fruch/scylla-cluster-tests/blob/update_sct_options_markdown/docs/configuration_options.md#scylla_version
> and it looks like the anchor doesn't work...

You are right GitHub support only anchors to heading, all other options they kind of break intentally.

**Comment by fruch** [comment]
> > @fruch I checked on https://github.com/fruch/scylla-cluster-tests/blob/update_sct_options_markdown/docs/configuration_options.md#scylla_version
> > and it looks like the anchor doesn't work...
> 
> You are right GitHub support only anchors to heading, all other options they kind of break intentally.

Fixed it, now it's working

**Review by enaydanov — APPROVED** [review]
LGTM

**Pull request merged**
