### PR TITLE
fix(scylla-bench): Use newest version [2022.1]

### PR DESCRIPTION
**Pull request by juliayakovlev**
Use scylla-bench v0.1.14 as retry/timeout configuration issue was fixed there

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by juliayakovlev** [comment]
Running test

**Comment by juliayakovlev** [comment]
Same scylla-bench timeout issue in `2021.1`

**Comment by juliayakovlev** [comment]
Ran the test with terminate and replace nemesis and scylla_bench_version = v0.1.14. Scylla-bench timeout issue has not been reproduced

**Review by fruch — APPROVED** [review]

**Comment by fruch** [comment]
@juliayakovlev 
I've reverted the backport of this one to 2021.1
it was failing to install:
https://jenkins.scylladb.com/view/nexts/job/enterprise-2021.1/job/gemini-/job/gemini-3h-with-nemesis-test/103/

we'll need to handle it on a PR on it's own (while testing)

**Pull request merged**
