### PR TITLE
remove partial_upgrade_downgrade_test.py

### PR DESCRIPTION
**Pull request by amoskong**
It's never used in official testing, and the rollback scenario had been
contained in upgrade_test.py:UpgradeTest.test_rolling_upgrade().

Signed-off-by: Amos Kong <amos@scylladb.com>

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by bentsi** [comment]
fix conflicts

**Comment by amoskong** [comment]
Let's ignore the pylint fail: duplicate-code

```
13:26:43  pylint...................................................................Failed
13:26:43  hookid: pylint
13:26:43  
13:26:43  ------------------------------------
13:26:43  Your code has been rated at 10.00/10
13:26:43  
13:26:43  ************* Module sdcm.prometheus
13:26:43  R:  1, 0: Similar lines in 2 files
13:26:43  ==sdcm.cluster_gce:80
13:26:43  ==sdcm.cluster_openstack:70
13:26:43      @property
13:26:43      def public_ip_address(self):
13:26:43          return self._get_public_ip_address()
13:26:43  
13:26:43      @property
13:26:43      def private_ip_address(self):
13:26:43          return self._get_private_ip_address()
13:26:43  
13:26:43      def _get_public_ip_address(self):
13:26:43          public_ips, _ = self._refresh_instance_state()
13:26:43          if public_ips:
13:26:43              return public_ips[0]
13:26:43          else:
13:26:43              return None
13:26:43  
13:26:43      def _get_private_ip_address(self):
13:26:43          _, private_ips = self._refresh_instance_state()
13:26:43          if private_ips:
13:26:43              return private_ips[0]
13:26:43          else:
13:26:43              return None
13:26:43   (duplicate-code)
13:26:43  R:  1, 0: Similar lines in 2 files
13:26:43  ==sdcm.cluster_openstack:13
13:26:43  ==sdcm.tester:310
13:26:43      service_cls = get_driver(Provider.OPENSTACK)
13:26:43      service = service_cls(user, password,
13:26:43                            ex_force_auth_version=auth_version,
13:26:43                            ex_force_auth_url=auth_url,
13:26:43                            ex_force_service_type=service_type,
13:26:43                            ex_force_service_name=service_name,
13:26:43                            ex_force_service_region=service_region,
13:26:43                            ex_tenant_name=tenant) (duplicate-code)
```

**Comment by bentsi** [comment]
@amoskong please rebase your PR when #1280 will be merged (it fixes the code duplication)

**Comment by bentsi** [comment]
@amoskong please rebase on latest master and resolve conflicts if there are

**Comment by amoskong** [comment]
> @amoskong please rebase on latest master and resolve conflicts if there are

I saw PR #1280  had been merged just now.
Rebased my PR.

**Pull request merged**
