### PR TITLE
fix(eks.py): use correct signature for method

### PR DESCRIPTION
**Pull request by aleksbykov**
MonitorSetEKS inherits  AWSCluster. It overrides the _create_instance method. The signature has been updated to include the previously missing argument, is_zero_node.

### Testing

- [Job with fix](https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/upgrade-scylla-k8s-eks-test/3/execution/node/127/log/)

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by aleksbykov** [comment]
Fix is under test

**Review by grzywin — APPROVED** [review]
LGTM

**Comment by soyacz** [comment]
@aleksbykov where to backport it?

**Comment by soyacz** [comment]
job with fix failed

**Comment by aleksbykov** [comment]
> job with fix failed

it failed by another reason, @grzywin is going to investigate it

**Review by soyacz — APPROVED** [review]
LGTM

**Pull request merged**
