### PR TITLE
fix(tester): make all threads daemonic by default

### PR DESCRIPTION
**Pull request by dkropachev**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [ ] ~~All new and existing unit tests passed (CI)~~
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by roydahan** [comment]
I don't think it's safe to do it the default.
Or at least we need to examine all the cases we use threads.
Do we have places where we expect the thread to continue after the main thread is killed?

**Comment by bentsi** [comment]
Actually in the ThreadPoolExecutor threads are created as daemons by default

See `concurrent/futures/thread.py`

image

**Comment by bentsi** [comment]
image

**Comment by dkropachev** [comment]
Not anymore, It was change in https://github.com/python/cpython/commit/b61b818d916942aad1f8f3e33181801c4a1ed14b#diff-692c518556397eee9681b886c6c7e85af5defbd0759a01f0f39c355d48d1fd75

https://github.com/python/cpython/blob/9bcb76c24f6d3f01e596a439c1521f9099e3fe80/Lib/concurrent/futures/thread.py#L188

```
t = threading.Thread(name=thread_name, target=_worker,                                 args=(weakref.ref(self, weakref_cb),                                       self._work_queue,                                       self._initializer,                                       self._initargs))            
t.start()            
self._threads.add(t)            
_threads_queues[t] = self._work_queue
```

**Comment by dkropachev** [comment]
@roydahan , @bentsi 
Here is the list where it is used:
- running c-s, bench and gemini stress commands
- in disrupt_abort_repair to run repair
- under the hood of ParallelObject, which is used everywhere 
- in alternator tests (scan_table) to run scans
- cassandra library uses it undner the hood
- s3 library uses it to upload/download files

**Review by bentsi — APPROVED** [review]

**Comment by roydahan** [comment]
@bentsi let's  backport this to 4.5.

**Pull request merged**
