### PR TITLE
feature(email_reports): include direct links for the logs

### PR DESCRIPTION
**Pull request by fruch**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- ~~[ ] New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- ~~[ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [ ] All new and existing unit tests passed (CI)
- ~~[ ] I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by fruch** [comment]
Email will now have this `Logs` section:
image

**Review by roydahan — APPROVED** [review]

**Comment by fruch** [comment]
@roydahan do we want this backported to 2020.1 ? 4.2 ?

**Review by aleksbykov — APPROVED** [review]

**Comment by aleksbykov** [comment]
> @roydahan do we want this backported to 2020.1 ? 4.2 ?

Will be good to have on 4.2

**Comment by roydahan** [comment]
Ok, backport to 4.2

**Review by bentsi — APPROVED** [review]

**Pull request merged**
