### PR TITLE
test(k8s): add 'nodetool drain' K8S functional test

### PR DESCRIPTION
**Pull request by vponomaryov**
It covers the https://github.com/scylladb/scylla-enterprise/issues/2808 case.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by fruch** [comment]
@vponomaryov 

Can we run this with the latest 2022.2 and with the latest 5.2, 

and check what the difference between those branches ? so we can check what are the possible root causes for this behavior?

**Comment by vponomaryov** [comment]
> @vponomaryov
> 
> Can we run this with the latest 2022.2 and with the latest 5.2,
> 
> and check what the difference between those branches ? so we can check what are the possible root causes for this behavior?

Probably you wanted to say `5.1` instead of `5.2`?

**Comment by fruch** [comment]
> > @vponomaryov
> > Can we run this with the latest 2022.2 and with the latest 5.2,
> > and check what the difference between those branches ? so we can check what are the possible root causes for this behavior?
> 
> Probably you wanted to say `5.1` instead of `5.2`?

yes, my mistake

**Comment by vponomaryov** [comment]
I ran it:

Scylla 5.1.8 passed ok: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-functional-k8s-local-kind-aws/240/consoleFull
Scylla 2022.2.3 failed with the https://github.com/scylladb/scylla-enterprise/issues/2808 bug as expected : https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-functional-k8s-local-kind-aws/241/consoleFull

**Comment by vponomaryov** [comment]
@fruch what do we do with this?

**Review by fruch — APPROVED** [review]

**Comment by fruch** [comment]
> @fruch what do we do with this?

I was waiting for the clear see that we found the root cause.

It's now fixed and we can introduce it

**Pull request merged**
