### PR TITLE
Remove data_dir/ssl_conf/db.crt from index

### PR DESCRIPTION
**Pull request by aleksbykov**
SSL certificate are auto generated each time SCT runs. Thereforethis file marked as modified in git index  and required the adding to commit. 

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I gave variables/functions meaningful self-explanatory names
- [ ] I didn't leave commented-out/debugging code
- [ ] I didn't copy-paste code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by bentsi** [comment]
@aleksbykov please update the commit message with the reason why we are deleting this. Thanks

**Comment by aleksbykov** [comment]
@amoskong @bentsi is it Ok?

**Comment by amoskong** [comment]
> @amoskong @bentsi is it Ok?

Please add the reason to patch commit log by `git commit --amend`, not just PR description next time.

**Comment by bentsi** [comment]
@aleksbykov please update the *commit message*

**Comment by aleksbykov** [comment]
@amoskong @bentsi Added to commit message

**Pull request merged**
