### PR TITLE
fix(mv si 4d): increase monitor instance type

### PR DESCRIPTION
**Pull request by fgelcer**
during master tier1 runs, we seen monitor having
some dificulties to show dashboards, for more
than one run, so we here increase the instance
type for the monitor, expecting it to work
better for future runs.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
difficulties to show dashboards ? during the run ? when generating snapshot ? did it had any affect on the test ?

**Comment by fgelcer** [comment]
> difficulties to show dashboards ? during the run ? when generating snapshot ? did it had any affect on the test ?

during the run, while trying to cut the time ranges for example... i wasn't unable to see any direct effect in the test though

**Comment by yarongilor** [comment]
Change commit: `increase loader instance type` -> `increase monitor instance type`

**Comment by fgelcer** [comment]
> Change commit: `increase loader instance type` -> `increase monitor instance type`

done

**Comment by fruch** [comment]
> > difficulties to show dashboards ? during the run ? when generating snapshot ? did it had any affect on the test ?
> 
> during the run, while trying to cut the time ranges for example... i wasn't unable to see any direct effect in the test though

I'm guessing lots of cases might suffer from a similar issue, but as long as the data collection works well enough, I think we can live with it.

**Review by fruch — APPROVED** [review]

**Pull request merged**
