### PR TITLE
improvement(perfreport): Adding data with comparision for latest commit

### PR DESCRIPTION
**Pull request by aleksbykov**
Adding to Performance result analyzing and performance report
data with comparision current test result with result for latest commit
in version

Trello: https://trello.com/c/W0aWeFhU
Trello: https://trello.com/c/RNVQtVHM
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I gave variables/functions meaningful self-explanatory names
- [ ] I didn't leave commented-out/debugging code
- [ ] I didn't copy-paste code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@aleksbykov can you attach a screenshot, of the output ?

**Comment by aleksbykov** [comment]
Screenshot from 2020-02-20 11-36-24

**Comment by aleksbykov** [comment]
Screenshot from 2020-02-20 11-37-25

**Comment by bentsi** [comment]
let's be consistent with all our reports. In Microbenchamrking we use:
image

- add "#" before commit hash
- change date format

**Comment by aleksbykov** [comment]
scr1

**Comment by aleksbykov** [comment]
Better version
scr2

**Comment by aleksbykov** [comment]
@Bentsi is it ok?

**Comment by bentsi** [comment]
Yep!

**Pull request merged**
