### PR TITLE
fix(centos-manager-sanity-ipv6): set region to us-east-1

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
To be more aligned with the rest of the manager jobs

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by rayakurl — APPROVED** [review]
Approved

**Comment by rayakurl** [comment]
@scylladb/qa-maintainers - who can review and merge? Thanks

**Review by fruch — APPROVED** [review]
LGTM

**Comment by rayakurl** [comment]
Thanks @fruch !

**Pull request merged**
