### PR TITLE
feature(coredumps): support zstd compressed coredumps

### PR DESCRIPTION
**Pull request by fruch**
if we have coredumps compressed with zstd, we shouldn't compress them again also we should write the proper tool in the download instructions

Ref: scylladb/scylla-machine-image#462
Ref: scylladb/scylladb#18854

### Testing

- [ ]

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Review by soyacz — APPROVED** [review]
LGTM

**Review by vponomaryov — APPROVED** [review]
LGTM

p.s. 

> if we have coredumps compressed with zstd, we should compress them again also we should write the proper tool in the download instructions

we should NOT lose `not` word in statements like this.

**Comment by fruch** [comment]
> LGTM
> 
> p.s. 
> 
> > if we have coredumps compressed with zstd, we should compress them again also we should write the proper tool in the download instructions
> 
> we should NOT lose `not` word in statements like this.

Maybe we'll leave as an exercise for the reader ? 😉

**Comment by fruch** [comment]
> > LGTM
> > p.s.
> > > if we have coredumps compressed with zstd, we should compress them again also we should write the proper tool in the download instructions
> > 
> > 
> > we should NOT lose `not` word in statements like this.
> 
> Maybe we'll leave as an exercise for the reader ? 😉

fixed the commit message and the PR description

**Pull request merged**
