### PR TITLE
fix(hydra): fix tab completion

### PR DESCRIPTION
**Pull request by fruch**
for some time the tab completion we were using wasn't working removed the package that we were using, and switch to using click core tab completion support.

also upgrade fabric/paramiko to get rid of the annying warning, which was part of the breakage of completion as well:
```
CryptographyDeprecationWarning: Blowfish has been deprecated
```

currently we only support bash (even that click supports also zsh and fish, and one can manual setup them if needed)

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
typo in the commit message `hydar` instead of `hydra`

**Comment by soyacz** [comment]
did you test with `ssh_transport: fabric`? 

Also have in mind I also try to publish new hydra version https://github.com/scylladb/scylla-cluster-tests/pull/5741 - I think mine is more safe (just adding deepdiff pkg) and should be merged before this one.

**Comment by fruch** [comment]
> did you test with `ssh_transport: fabric`?

now I did, even that no test case is using it

> 
> Also have in mind I also try to publish new hydra version #5741 - I think mine is more safe (just adding deepdiff pkg) and should be merged before this one.

I know, both are harmless.
first one get reviews would win :)

**Review by vponomaryov — DISMISSED** [review]
LGTM

**Comment by soyacz** [comment]
> > did you test with `ssh_transport: fabric`?
> 
> now I did, even that no test case is using it
> 
> > Also have in mind I also try to publish new hydra version #5741 - I think mine is more safe (just adding deepdiff pkg) and should be merged before this one.
> 
> I know, both are harmless. first one get reviews would win :)

I won :grin:

**Comment by roydahan** [comment]
Hallelujah for this PR.

**Review by soyacz — DISMISSED** [review]

**Review by vponomaryov — APPROVED** [review]
LGTM

**Pull request merged**
