### PR TITLE
feature(monitor-3.3): Switch using monitor-3.3 branch

### PR DESCRIPTION
**Pull request by roydahan**
Switching to a new branch of monitor-3.3 with new dashboards for LWT.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
Let's merge it and if it looks good on tonights run on master, we can backport to 4.4 tomorrow.

**Comment by roydahan** [comment]
I need this merged today

**Comment by roydahan** [comment]
@bentsi to mark as backported?

**Comment by bentsi** [comment]
Da :) adding label
image

**Comment by ShlomiBalalis** [comment]
@bentsi @fruch Can one of you backport it to manager-2.1 as well?

**Comment by fruch** [comment]
@ShlomiBalalis done

**Pull request merged**
