### PR TITLE
improvement(k8s-multitenant): allow to use list of lists for stress cmds

### PR DESCRIPTION
**Pull request by vponomaryov**
Reason: different DB clusters will need it's own commands.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by vponomaryov** [comment]
It was tested lots of times with other dev commits for runnings K8S multi-tenant setup.

**Comment by fruch** [comment]
Stress commands are used in lots of other places, in tests. Is this changed tested also with one of the regular longvity ?

**Comment by vponomaryov** [comment]
> Stress commands are used in lots of other places, in tests. Is this changed tested also with one of the regular longvity ?

I used it with operator and it works there - creation of 1 and 2 clusters. Do you any diff with it? I don't.
Then, I, in fact, only allow to have different structure for options, previous behavior is not touched.

**Comment by bentsi** [comment]
please check why unit tests failed

**Pull request merged**
