### PR TITLE
add read workload at the end of longevity

### PR DESCRIPTION
**Pull request by amoskong**
We have write, counter write, MV workload in current longevity test, this PR added an important read workload for longevity test.

### CODE REVIEW

**Comment by amoskong** [comment]
The added read workload was started after write load run 1+ hour.

image

**Comment by roydahan** [comment]
Please wait with the merge

**Comment by amoskong** [comment]
Sure. However, it won't block the test as counter_write stuck issue.

**Comment by amoskong** [comment]
Updated PR: reduce the read rate (set threads to 500).

**Comment by amoskong** [comment]
Larisa already added read workload, which executes with other workload in parallel.
So we don't need this PR, @roydahan  can we close it?

**Comment by roydahan** [comment]
Yes.

**Pull request closed without merging**
