### PR TITLE
upgrade_test: reload systemd config self-adaptively

### PR DESCRIPTION
**Pull request by amoskong**
Scylla 3.2 introduced some change of scylla-jmx.service, we have to
reload the config during upgrade or rollback.

Currently we only reload the systemd config in reinstall mode, this
patch change it to reload config according to the status result.

Signed-off-by: Amos Kong <amos@scylladb.com>

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
Is it still draft or ready for review?

**Comment by amoskong** [comment]
> Is it still draft or ready for review?

I'm fixing the ci test fail, and try to test the pr by a staging job.

**Comment by roydahan** [comment]
ok, so please assign reviewers only when it's ready for review because it's confusing.

**Comment by amoskong** [comment]
Testing this PR by https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/rolling-upgrade-3.2/job/rolling-upgrade-centos7/2/console  (Running ....)

**Comment by amoskong** [comment]
Update: According to comments from Takuya, we expect the new systemd config to be reloaded automatically. So he will fix scylla (https://github.com/scylladb/scylla-jmx/issues/90).

We can close this PR if the scylla issue will be fixed soon.

**Comment by bentsi** [comment]
@amoskong if daemon-reload should be handled automatically by Scylla services, maybe we can raise Exception and fail upgrade test when finding that Scylla didn't reload the daemon automatically?

**Comment by amoskong** [comment]
> @amoskong if daemon-reload should be handled automatically by Scylla services, maybe we can raise Exception and fail upgrade test when finding that Scylla didn't reload the daemon automatically?

Good, idea. I will send another PR.

We can close this PR because Takuya is fixing the Scylla issue, we don't need this PR any more.

**Pull request closed without merging**
