### PR TITLE
ci(tablets): add scale (multi-ks, multi-cf) CI jobs for testing tablets

### PR DESCRIPTION
**Pull request by vponomaryov**
### Testing

- [scylla-staging/valerii/vp-longevity-5000-tables-with-tablets#5](https://argus.scylladb.com/test/13e30d7f-1fed-44f0-b26c-1a96fdb23564/runs?additionalRuns[]=2458e37b-ef6c-4f25-806e-fd96c8da9b95)
- [scylla-staging/valerii/vp-longevity-multi-keyspaces-with-tablets#3](https://argus.scylladb.com/test/7fd0596d-6ee0-4ecb-ad9f-43b168205f4e/runs?additionalRuns[]=792ab8f1-0a58-484b-b293-d22338cd6b8d)

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevent to this change (if needed)

### CODE REVIEW

**Comment by vponomaryov** [comment]
The 5k tables CI job that uses user profile files depends on the following PR:
- https://github.com/scylladb/scylla-cluster-tests/pull/7316

**Comment by fruch** [comment]
@vponomaryov someone asked for those ? i.e. someone intend to run them in a regular cadence ?

**Comment by vponomaryov** [comment]
> @vponomaryov someone asked for those ? i.e. someone intend to run them in a regular cadence ?

I find this way of speaking as offensive and not professional.

At first, no harm has been committed with this PR.
At second, If it is not needed then I/anyone can close it.
At third, the fix for the user profiles was not asked too, but there are no such questions for some reason.

**Comment by roydahan** [comment]
> I find this way of speaking as offensive and not professional.

I think that @fruch just wanted to know if you got such a request from me or someone else on side track to do it.

**Review by roydahan — APPROVED** [review]

**Comment by fruch** [comment]
> > @vponomaryov someone asked for those ? i.e. someone intend to run them in a regular cadence ?
> 
> I find this way of speaking as offensive and not professional.
> 
> At first, no harm has been committed with this PR.
> At second, If it is not needed then I/anyone can close it.
> At third, the fix for the user profiles was not asked too, but there are no such questions for some reason.

No on said any harm was done.

We talked and discussed the issue with the user profile, and yes it was expected for you to supply a fix for it.

We didn't discuss adding those cases, hence the question.

The tablet folder is currently a set of tests, selected by the team working on tablets, and is triggered in some regular cadence.

I don't want to end up cloning all of the pipelines into the tablet directory, and with syncing with the tablet team.

**Pull request merged**
