### PR TITLE
improvement(k8s-eks): set tags to K8S-EKS launch templates

### PR DESCRIPTION
**Pull request by vponomaryov**
For the moment we set tags only those which will be applied to VMs which will use a specific launch template.
But it is also possible to set tags for the a launch template itself. 
In our case it will allow to filter exisitng launch templates for the purpose of the resource cleanup.

So, set tags to launch templates.

### Testing

- [ ]

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevent to this change (if needed)

### CODE REVIEW

**Comment by vponomaryov** [comment]
It is follow-up PR for the already merged one:
- https://github.com/scylladb/scylla-cluster-tests/pull/7170

Tested here: https://jenkins.scylladb.com/job/scylla-staging/job/valerii/job/vp-functional-eks/66/consoleFull

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@vponomaryov we now missing code that can scan those, and clear them by test_id, as other resources

**Comment by vponomaryov** [comment]
> The cleanup code for the launch templates will be uploaded separately.

It is what I wrote above: `The cleanup code for the launch templates will be uploaded separately.`
It is in progress.

**Comment by fruch** [comment]
> > The cleanup code for the launch templates will be uploaded separately.
> 
> It is what I wrote above: `The cleanup code for the launch templates will be uploaded separately.` It is in progress.

you are right, I've missed that, I've read only the cover letter.

**Comment by vponomaryov** [comment]
PR with cleanup of launch templates: https://github.com/scylladb/scylla-cluster-tests/pull/7174

**Pull request merged**
