### PR TITLE
feature(Azure): support Azure in SCT provision test

### PR DESCRIPTION
**Pull request by soyacz**
Commit adds Azure backend to SCT pipeline provision tests.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@soyacz you probably want to rebase, since I've merged #4920

added there the support for running with sct-runner, you might want to use that.

**Comment by soyacz** [comment]
> @soyacz you probably want to rebase, since I've merged #4920
> 
> added there the support for running with sct-runner, you might want to use that.

Thanks @fruch, I just saw my results and there's problem with ssh connections, using sct-runner should help on Azure.

**Comment by soyacz** [comment]
looks like it works - passed tests.

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
