### PR TITLE
improvement(argus-client): ship argus client within sct

### PR DESCRIPTION
**Pull request by soyacz**
In order to ease update argus client, it was removed from docker image and included in SCT repository. This way we may update argus client without rebuilding hydra image and easily backport it to other sct branches.

Added simple script to streamline this process.

fixes: https://github.com/scylladb/qa-tasks/issues/1766

### Testing

- [X] - [example test](https://argus.scylladb.com/tests/scylla-cluster-tests/6d1c3244-a8c2-4d8a-adc1-ae022ba3100c)

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by soyacz** [comment]
files worth to check: `.pre-commit-config.yaml` where I excluded Argus from it,  `utils/update_argus_client.py` for easy update.
All the files from `argus/` dir come from argus repository, no need to review them (if there's a problem with it, raise issue in Argus project).

**Review by k0machi — DISMISSED** [review]
LGTM, but you seem to have pre-commit failures here.

**Comment by soyacz** [comment]
> > files worth to check: `.pre-commit-config.yaml` where I excluded Argus from it, `utils/update_argus_client.py` for easy update. All the files from `argus/` dir come from argus repository, no need to review them (if there's a problem with it, raise issue in Argus project).
> 
> Will that copied code be needed in old place after merging and backporting this PR? Or in other words will we need to support both places or not?

What do you mean by 'old place'? There's no change in imports (except few updates in Argus client library where 'backend' was removed from it, but this change is not relevant in this context). 

> 
> Have you tried to cherry-pick your changes to one of old SCT branches like `2023.1` to verify absence of dependency collisions?

New approach does not change any dependency I'm not sure what you mean about collisions in that case.

**Comment by vponomaryov** [comment]
> > > files worth to check: `.pre-commit-config.yaml` where I excluded Argus from it, `utils/update_argus_client.py` for easy update. All the files from `argus/` dir come from argus repository, no need to review them (if there's a problem with it, raise issue in Argus project).
> > 
> > 
> > Will that copied code be needed in old place after merging and backporting this PR? Or in other words will we need to support both places or not?
> 
> What do you mean by 'old place'? There's no change in imports (except few updates in Argus client library where 'backend' was removed from it, but this change is not relevant in this context).

This PR has copied code from the Argus repository. So, that original place where you copied it from I called "old place".
And the question is still not answered: will it be needed to be supported in both places?
Or that client code in Argus may just be removed as unneeded?

> > Have you tried to cherry-pick your changes to one of old SCT branches like `2023.1` to verify absence of dependency collisions?
> 
> New approach does not change any dependency I'm not sure what you mean about collisions in that case.

Your approach may simply fail in runtime using unexpected state of dependencies.

**Comment by soyacz** [comment]
> > > > files worth to check: `.pre-commit-config.yaml` where I excluded Argus from it, `utils/update_argus_client.py` for easy update. All the files from `argus/` dir come from argus repository, no need to review them (if there's a problem with it, raise issue in Argus project).
> > > 
> > > 
> > > Will that copied code be needed in old place after merging and backporting this PR? Or in other words will we need to support both places or not?
> > 
> > 
> > What do you mean by 'old place'? There's no change in imports (except few updates in Argus client library where 'backend' was removed from it, but this change is not relevant in this context).
> 
> This PR has copied code from the Argus repository. So, that original place where you copied it from I called "old place". And the question is still not answered: will it be needed to be supported in both places? Or that client code in Argus may just be removed as unneeded?

Old place is going to stay like it is now - Argus Client might be used in future in other repositories/projects. This commit is about moving this dependency from docker image to root dir, and not intended to be modified from here (like we don't modify dependencies in docker image).

> 
> > > Have you tried to cherry-pick your changes to one of old SCT branches like `2023.1` to verify absence of dependency collisions?
> > 
> > 
> > New approach does not change any dependency I'm not sure what you mean about collisions in that case.
> 
> Your approach may simply fail in runtime using unexpected state of dependencies.

Similar like any other dependency update. Anyway we'll need to test it as we had to do it before. Possibly we could create&ship Argus Client unit tests and run it when updating it here.

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
