### PR TITLE
fix(scylla repos): Validating siren backend only relevant repos

### PR DESCRIPTION
**Pull request by yarongilor**
For a siren backend - only the loader repository is relevant.
	all other repos should be ignored.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by yarongilor** [comment]
Tested in: https://jenkins.scylladb.com/job/siren-tests/job/longevity-tests/job/scylla-cloud-longevity-small-data-set-1h-aws/253/

**Comment by enaydanov** [comment]
@yarongilor, can you collaborate with @vponomaryov? He opened a PR with pretty same changes: #3916

**Comment by yarongilor** [comment]
This commit should be added to: https://github.com/scylladb/scylla-cluster-tests/pull/3916

**Comment by vponomaryov** [comment]
> This commit should be added to: #3916

Done

**Pull request closed without merging**
