### PR TITLE
fix(eks pipelines): Set default parameters

### PR DESCRIPTION
**Pull request by dkropachev**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~`
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by vponomaryov** [comment]
Why all these data set in jenkins files and not in the "defaults/k8s_eks_config.yaml"?

**Comment by dkropachev** [comment]
> Why all these data set in jenkins files and not in the "defaults/k8s_eks_config.yaml"?

Pipeline values has priority over defaults.

**Comment by vponomaryov** [comment]
> > Why all these data set in jenkins files and not in the "defaults/k8s_eks_config.yaml"?
> 
> Pipeline values have priority over defaults.

Actually I wanted to say that these values are absent in the "defaults" file and could be set just once there, not having a need to duplicate it in each separate pipeline. You set the same values, so it will solve current goal to have all these values in pipelines.

**Comment by dkropachev** [comment]
> > > Why all these data set in jenkins files and not in the "defaults/k8s_eks_config.yaml"?
> > 
> > 
> > Pipeline values have priority over defaults.
> 
> Actually I wanted to say that these values are absent in the "defaults" file and could be set just once there, not having a need to duplicate it in each separate pipeline. You set the same values, so it will solve current goal to have all these values in pipelines.


longevityPipeline.jenkins defines this params this way:

```
            string(defaultValue: "${pipelineParams.get('post_behavior_db_nodes', 'keep-on-failure')}",
                   description: 'keep|keep-on-failure|destroy',
                   name: 'post_behavior_db_nodes')
```

And passes it to runSctTest.groovy where it is used in the following manner:
```
    export SCT_POST_BEHAVIOR_DB_NODES="${params.post_behavior_db_nodes}"
    export SCT_POST_BEHAVIOR_LOADER_NODES="${params.post_behavior_loader_nodes}"
    export SCT_POST_BEHAVIOR_MONITOR_NODES="${params.post_behavior_monitor_nodes}"
```

As result pipeline values for this set of parameters overrides defaults in any case, that is why you need to set them on jenkins level.

**Review by vponomaryov — APPROVED** [review]
Thanks for clarification, looks good to me.

**Pull request merged**
