### PR TITLE
fix(chaos-mesh): make admission-controller not block it on GKE

### PR DESCRIPTION
**Pull request by vponomaryov**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by vponomaryov** [comment]
Tested here: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-3h-gke/21/consoleFull
The failures that exist there happen after the fixed step here - `admission controller checks`.

**Comment by soyacz** [comment]
I did fix in another way: https://github.com/scylladb/scylla-cluster-tests/pull/5731

**Comment by fruch** [comment]
> I did fix in another way: #5731

@soyacz I think @vponomaryov PR is better in this situation, i.e. it's following the FAQ of chaos mesh.

disabling the auth on the dashboard is not recommand:
https://chaos-mesh.org/docs/manage-user-permissions/#enable-or-disable-permission-authentication

yes, we are not using the dashboard, but it's there (and might be exposed externally ?)

**Comment by soyacz** [comment]
> > I did fix in another way: #5731
> 
> @soyacz I think @vponomaryov PR is better in this situation, i.e. it's following the FAQ of chaos mesh.
> 
> disabling the auth on the dashboard is not recommand: https://chaos-mesh.org/docs/manage-user-permissions/#enable-or-disable-permission-authentication
> 
> yes, we are not using the dashboard, but it's there (and might be exposed externally ?)

Without dashboard you can create experiments only with kubectl - which requires credentials. 
I think by default dashboard is not protected anyway - I don't remember need for playing with these tokens like described in docs.

**Comment by fruch** [comment]
> > > I did fix in another way: #5731
> > 
> > 
> > @soyacz I think @vponomaryov PR is better in this situation, i.e. it's following the FAQ of chaos mesh.
> > disabling the auth on the dashboard is not recommand: https://chaos-mesh.org/docs/manage-user-permissions/#enable-or-disable-permission-authentication
> > yes, we are not using the dashboard, but it's there (and might be exposed externally ?)
> 
> Without dashboard you can create experiments only with kubectl - which requires credentials. I think by default dashboard is not protected anyway - I don't remember need for playing with these tokens like described in docs.

when in installed with kind, I don't really care, but when it's installed on EKS/GKE we need to verify it's not open to the whole world without us known about it

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
