### PR TITLE
Added automatic copy c-s user profile to run_stress_thread

### PR DESCRIPTION
**Pull request by fgelcer**
Moving this logic out of longevity_test.py, since more tests needs it

### CODE REVIEW

**Comment by fruch** [comment]
@fgelcer I think you can remove this logic from `longevity_test.py`

**Comment by fgelcer** [comment]
testing the longevity if it will work properly, without more coding

**Comment by fgelcer** [comment]
i have tried dozens of times to test the longevity with this code (running from my pc) without success. It in general fails with TimeoutError waiting for the db nodes (and i don't know why)

```
< t:2019-07-31 19:33:37,992 f:wait.py         l:62   c:sdcm.wait            p:ERROR > Wait for: None: timeout - 500 seconds - expired
< t:2019-07-31 19:33:37,992 f:wait.py         l:64   c:sdcm.wait            p:ERROR > last error: None
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/sct/sdcm/cluster.py", line 872, in backtrace_thread
    self.get_backtraces()
  File "/sct/sdcm/cluster.py", line 854, in get_backtraces
    self.wait_ssh_up(verbose=False)
  File "/sct/sdcm/cluster.py", line 989, in wait_ssh_up
    wait.wait_for(func=self.remoter.is_up, step=10, text=text, timeout=timeout, throw_exc=True)
  File "/sct/sdcm/wait.py", line 58, in wait_for
    res = r.call(func, **kwargs)
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 358, in call
    do = self.iter(retry_state=retry_state)
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 331, in iter
    raise retry_exc.reraise()
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 168, in reraise
    raise self
RetryError: RetryError[<Future at 0x7f1fec197d90 state=finished returned bool>]
```

**Comment by fgelcer** [comment]
> i have tried dozens of times to test the longevity with this code (running from my pc) without success. It in general fails with TimeoutError waiting for the db nodes (and i don't know why)
> 
> ```
> < t:2019-07-31 19:33:37,992 f:wait.py         l:62   c:sdcm.wait            p:ERROR > Wait for: None: timeout - 500 seconds - expired
> < t:2019-07-31 19:33:37,992 f:wait.py         l:64   c:sdcm.wait            p:ERROR > last error: None
> Exception in thread Thread-6:
> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
>     self.run()
>   File "/usr/lib64/python2.7/threading.py", line 765, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/sct/sdcm/cluster.py", line 872, in backtrace_thread
>     self.get_backtraces()
>   File "/sct/sdcm/cluster.py", line 854, in get_backtraces
>     self.wait_ssh_up(verbose=False)
>   File "/sct/sdcm/cluster.py", line 989, in wait_ssh_up
>     wait.wait_for(func=self.remoter.is_up, step=10, text=text, timeout=timeout, throw_exc=True)
>   File "/sct/sdcm/wait.py", line 58, in wait_for
>     res = r.call(func, **kwargs)
>   File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 358, in call
>     do = self.iter(retry_state=retry_state)
>   File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 331, in iter
>     raise retry_exc.reraise()
>   File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 168, in reraise
>     raise self
> RetryError: RetryError[<Future at 0x7f1fec197d90 state=finished returned bool>]
> ```

succeeded to test this change on longevity (as it had a change itself), and it is not ready to merge

**Comment by roydahan** [comment]
We need to be careful with these backports, I don't know where and how this code was tested.
Although it looks correct now that we have this stress_thread.py, we need to test it with 3.1 longevities BEFORE we backport.

**Comment by fruch** [comment]
@roydahan stress_thread.py is there from when started branch-3.1, we already been using that code in all 3.1 runs.

**Pull request merged**
