### PR TITLE
fix(cloud_monitor.py): send usage report in alphabetic

### PR DESCRIPTION
**Pull request by yaronkaikov**
For a while now, we keep getting the Cloud resource report in Cyrillic

Fixing it

### CODE REVIEW

**Comment by yaronkaikov** [comment]
Verified with https://jenkins.scylladb.com/view/DevOps/job/devops-cloud-resources-report-yaron/2/
image

**Comment by roydahan** [comment]
It’s a feature, not something to “fix”.

**Comment by yaronkaikov** [comment]
> It’s a feature, not something to “fix”.

Have no idea how it's a feature, but anyway, please merge it .

**Comment by fruch** [comment]
> > It’s a feature, not something to “fix”.
> 
> Have no idea how it's a feature, but anyway, please merge it .

@roydahan was trying to make sure people won't filter those emails.

**Comment by fruch** [comment]
@roydahan if you still want to keep your "feature", please close this PR

**Comment by fgelcer** [comment]
> @roydahan if you still want to keep your "feature", please close this PR

i upvote for the fix in this PR

**Pull request closed without merging**
