### PR TITLE
fix(artifacts): skip XFS mount test for non-root install

### PR DESCRIPTION
**Pull request by enaydanov**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [x] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [x] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@enaydanov this isn't covering all cases we need to disable the fstrim-timer check:
see
https://jenkins.scylladb.com/view/master/job/scylla-master/job/artifacts/job/artifacts-ubuntu2004-test/590

also there might be more, on other debian and ubuntu, but they currently failing on something else.

I think this test should be only for pre-installed scylla, on others platforms we aren't disabling that timer, and we shouldn't check it.

**Comment by enaydanov** [comment]
@rayakurl No, this test is about default behavior of `scylla_setup` and we need to test all supported OSes too. 

And the issue on Ubuntu 20.04 is not the same I fixed in this PR.

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@enaydanov @rayakurl seems that https://github.com/scylladb/scylla-cluster-tests/pull/4649 wasn't yet backported, and this one depends on it.

@enaydanov, it the call is to backport both, please do.

**Comment by rayakurl** [comment]
thanks @fruch - 4649 was already in master, therefore it broke some nonroot artifact tests. therefore I needed this commit in master as well  .

**Comment by fruch** [comment]
> thanks @fruch - 4649 was already in master, therefore it broke some nonroot artifact tests. therefore I needed this commit in master as well .

It's now merged, so it's in master. question was if it's need backporting or not.

**Pull request merged**
