### PR TITLE
fix set_hostname: Add workaround to rsyslogd problem

### PR DESCRIPTION
**Pull request by dkropachev**
Fix issue with rsyslogd after hosts is ammended:

rsyslog is not picking up hostname if it is in hosts file
and continue sending messages as localhost
which makes test to fail as following:

13:11:49    File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 358, in call
13:11:49      do = self.iter(retry_state=retry_state)
13:11:49    File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 331, in iter
13:11:49      raise retry_exc.reraise()
13:11:49    File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 167, in reraise
13:11:49      raise self.last_attempt.result()
13:11:49    File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
13:11:49      return self.__get_result()
13:11:49    File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
13:11:49      raise self._exception
13:11:49    File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 361, in call
13:11:49      result = fn(*args, **kwargs)
13:11:49    File "/sct/sdcm/cluster.py", line 3174, in verify_logging_from_nodes
13:11:49      raise Exception(error_msg)

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by amoskong** [comment]
@dkropachev currently the PR has conflicts with latest master.

**Comment by dkropachev** [comment]
> @dkropachev currently the PR has conflicts with latest master.

Thanks amos, it is fixed now

**Comment by dkropachev** [comment]
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/dmitry/job/dmitry-byo-longevity/76/

**Comment by fruch** [comment]
@dkropachev can you elaborate a bit more what this fix is for ? and why it is urgent ? Cause I don't understand why of a sudden we need all those manual changes around with /etc/hosts and /etc/rsyslogd.cfg ?

**Comment by bentsi** [comment]
@fruch Dmitry updated details of the PR

**Pull request merged**
