### PR TITLE
fix(clean-resources): assign backend

### PR DESCRIPTION
**Pull request by amoskong**
Signed-off-by: Amos Kong <amos@scylladb.com>

Fixes https://github.com/scylladb/scylla-cluster-tests/issues/3185

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by amoskong** [comment]
byo: https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/artifacts-docker-test-clone/2/

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@amoskong 

seem like it won't be enough, for some reason the backend is hardcored here, and it would need to be fixed too:
https://github.com/scylladb/scylla-cluster-tests/blob/98a8aab4b3b45a86e807868942860a5528b543e2/sct.py#L159

**Comment by amoskong** [comment]
@fruch you are right, the [byo job](https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/artifacts-docker-test-clone/2) failed.

After changed the hardcode backend in clean_resources(), the new BYO job succeeded.
* https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/artifacts-docker-test-clone/3/console

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
