### PR TITLE
removing as a temporary workaround

### PR DESCRIPTION
**Pull request by fgelcer**
* https://github.com/scylladb/scylla-cluster-tests/issues/1112

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [ ] ~~All new and existing unit tests passed (`hydra unit-tests`)~~
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by roydahan** [comment]
First, I do not want to see temporary workarounds merged to master & backported.
We can change the branch of the job if I approve that.

Second, this change hasn't been approved, I would like to understand why this works perfectly on 3.0 and not working on 3.1.
Something has changed in 3.1 that causes this.

@bentsi please revert changes.

**Comment by fruch** [comment]
maybe we could do a few runs with 3.0.8 to see if c-s hangs the same.

**Comment by roydahan** [comment]
I don't think it's related to scylla version, probably to SCT version.
You can check the longevities of 3.0 and see that we didn't have this issue.

**Comment by bentsi** [comment]
@roydahan as we understand this is c-s issue, do you still want to revert this?

**Pull request merged**
