### PR TITLE
fix(io.conf): remove kernel bug workarounds

### PR DESCRIPTION
**Pull request by soyacz**
As long time passed since kernel bug was fixed, we no longer should need any workaround related to io-tune.

This commit removes everything related to this workaround merged in https://github.com/scylladb/scylla-cluster-tests/pull/1473 Also removes copying any predefined io.conf and io_properties.yaml to ScyllaDB.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by roydahan — APPROVED** [review]

**Comment by soyacz** [comment]
test run passed: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/artifacts-ubuntu1804-nonroot-test/2/

**Comment by soyacz** [comment]
I'll do some more checks

**Comment by soyacz** [comment]
I had to remove also `--no-io-setup` from the `scylla_setup` command to make Scylla happy (can't start without io.conf and io_properties.yaml) - it prolonged test duration by 1-3 minutes but it's more proper way of testing.
test job passed: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/artifacts-ubuntu2204-nonroot-test/4/

**Review by vponomaryov — APPROVED** [review]
LGTM

**Review by yaronkaikov — APPROVED** [review]

**Review by fgelcer — APPROVED** [review]

**Comment by fgelcer** [comment]
@yaronkaikov , you can now run the jobs were failing..

**Comment by yaronkaikov** [comment]
Running https://jenkins.scylladb.com/job/scylla-master/job/offline-installer/658/

**Comment by yaronkaikov** [comment]
> @yaronkaikov, you can now run the jobs that were failing.

@fgelcer Looks like the job passed the problematic point. So we are good :+1, thanks

**Pull request merged**
