### PR TITLE
changing the way we corrupt the data before repair and rebuild, instead of deleting the entire keyspace, we will delete only several sstables

### PR DESCRIPTION
**Pull request by roydahan**

### CODE REVIEW

**Comment by roydahan** [comment]
During longevity of large data sets, we found that deleting the entire keyspace requires too much free space (streaming the entire data from all nodes).
@slivne suggested to change that and delete only several sstables.

This script will try to delete 3 sstables (including all their files) that are larger than 1000M, if won't found, it will try 500M, and so on...

**Comment by slivne** [comment]
when we use leveled the files are 160M .... lets 100M for the size

**Comment by roydahan** [comment]
This should catch it, if it won't find 1000M, it'll try 500M, then 250M, then 125M,..
Or, do you mean you don't want to delete larger files than 160M in leveled scenario?

**Comment by slivne** [comment]
@roydahan its fine lets merge

**Comment by roydahan** [comment]
There is a minor issue that I found and I need to fix.
In some cases I won't necessarily delete 3 file sets and I might delete only 1 or 2.
However, I think it'll be a rare case since we create much more files than running this script.
Anyway, I'll merge it and give it a try with longevity-1TB for the weekend.

**Pull request merged**
