### PR TITLE
fix(hydra): update scylla-driver==3.25.11

### PR DESCRIPTION
**Pull request by fruch**
new verison with the following fixes:

* https://github.com/scylladb/python-driver/pull/199
* https://github.com/scylladb/python-driver/pull/190

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fgelcer — COMMENTED** [review]
i see lots of changes unrelated to the `scylla-driver` changes

**Comment by fruch** [comment]
> i see lots of changes unrelated to the `scylla-driver` changes

this happens when ever we rebuild the docker image, any package we didn't specifically pinned, could be updated.

**Comment by fgelcer** [comment]
provision test on K8s failed, but other than that, LGTM

**Comment by fruch** [comment]
> provision test on K8s failed, but other than that, LGTM

It's failing because of issue I'm dealing with in a different PR.

**Pull request merged**
