### PR TITLE
Backport arm support branch 2021.1

### PR DESCRIPTION
**Pull request by fgelcer**
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
giving it a ride in the following job:
https://jenkins.scylladb.com/view/enterprise-2021.1/job/enterprise-2021.1/job/Reproducer/job/arm-longevity/job/longevity-50gb-3days-arm/4/

**Review by ShlomiBalalis — APPROVED** [review]
Pretty much looks like #4292 and #4307 combined, so looks good to me

**Comment by fgelcer** [comment]
> Pretty much #4292 and #4307 combined, so looks good to me

there are some 3 or 4 PRs of yours + bumping the manager version that i just changed the relevant lines in the `test_default.yaml`

**Comment by fgelcer** [comment]
a new build is running (it was missing manager support to ARM):
https://jenkins.scylladb.com/view/enterprise-2021.1/job/enterprise-2021.1/job/Reproducer/job/arm-longevity/job/longevity-50gb-3days-arm/5/

**Comment by fgelcer** [comment]
@enaydanov @bentsi , this job here now is passing (at least, all the installation phase):
https://jenkins.scylladb.com/view/enterprise-2021.1/job/enterprise-2021.1/job/Reproducer/job/arm-longevity/job/longevity-50gb-3days-arm/7/

ready to merge this one (it is a backport only, all commits are already in master and other branches)

**Comment by fgelcer** [comment]
ping @enaydanov @bentsi

**Review by roydahan — APPROVED** [review]

**Pull request merged**
