### PR TITLE
improvement(stress): add datacenter to c-s command for multi DC test

### PR DESCRIPTION
**Pull request by juliayakovlev**
Cassandra-stress load, when is running on multi DC cluster, sends the requests to one DC only, where loader is located.
It happens because the default load balancing policy in scylla-tools-java is DCAwareRoundRobinPolicy which prefers nodes in the local datacenter. Unless all local nodes are tried, it will not send queries to other nodes in remote DC. If a local datacenter name is not provided the policy will default to the datacenter of the first node it is connected to.

We want that the requests will be sent to all nodes in all datacenters evenly. This commit add datacenter parameter to cassandra stress command

Issue: https://github.com/scylladb/java-driver/issues/211

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by juliayakovlev** [comment]
Test on AWS:
https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/longevity-lwt-24h-multidc-test/16/

Requests per node (region) before this fix - part of the nodes did not get requests:
Screenshot from 2023-04-19 11-42-23


Requests per node (region) with this fix - all nodes get requests:
Screenshot from 2023-04-19 11-44-31

**Comment by soyacz** [comment]
ops dropped from almost 10kops to ~1kops... impact of LWT across dc's?

**Comment by juliayakovlev** [comment]
> ops dropped from almost 10kops to ~1kops... impact of LWT across dc's?

It's just finish of c-s load

**Review by fruch — DISMISSED** [review]
LGTM

**Comment by fruch** [comment]
@juliayakovlev running the integration test, to make sure regular c-s is working.

**Review by soyacz — DISMISSED** [review]

**Review by soyacz — APPROVED** [review]

**Review by fruch — APPROVED** [review]
relevant integration tests are passing

**Pull request merged**
