### PR TITLE
improvement(tester): don't fail on ES errors

### LINKED ISSUE #2759: Elasticsearch errors break whole run
SCT should be tolerant to Elasticsearch errors. It's better to create an CRITICAL or ERROR event instead of raising exception.

Example:

```python
Exception in setUp. Will call tearDown
Traceback (most recent call last):                                                                                                                                    
  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 110, in wrapper                                                                                       
    return method(*args, **kwargs)                                                                                                                                    
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 109, in inner                                                                               
    res = func(*args, **kwargs)                                                                                                                                       
  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 427, in setUp                                                                                         
    self.create_test_stats()                                                                                                                                          
  File "/home/ubuntu/scylla-cluster-tests/sdcm/db_stats.py", line 503, in create_test_stats                                                                           
    self.create()                                                                                                                                                     
  File "/home/ubuntu/scylla-cluster-tests/sdcm/db_stats.py", line 348, in create                                                                                      
    self.elasticsearch.create_doc(index=self._test_index, doc_type=self._es_doc_type,                                                                                 
  File "/home/ubuntu/scylla-cluster-tests/sdcm/es.py", line 40, in create_doc                                                                                         
    self.create(index=index, doc_type=doc_type, id=doc_id, body=body)                                                                                                 
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped                                                                   
    return func(*args, params=params, **kwargs)                                                                                                                       
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 259, in create                                                                 
    return self.transport.perform_request('PUT', _make_path(index, doc_type,                                                                                          
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 314, in perform_request                                                              
    status, headers, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)                                    
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 161, in perform_request                                                
    self._raise_error(response.status, raw_data)                                                                                                                      
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error                                                           
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)                                                               
elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Limit of total fields [1000] in index [lwtlongevitytest] has been exceeded')
```

### PR DESCRIPTION
**Pull request by enaydanov**
Trello: https://trello.com/c/Jq3MTbWh/2409-sct-should-be-tolerant-to-elasticsearch-errors

Fixed #2759

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [x] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [x] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fruch — APPROVED** [review]
LGTM

**Comment by bentsi** [comment]
per our discussion, please rollback the changes to tester

**Comment by fruch** [comment]
@enaydanov, meanwhile we have one more call to elasticsearch:
https://github.com/scylladb/scylla-cluster-tests/blob/master/sdcm/nemesis_publisher.py#L81

would be nice if you'll cover that as well.

**Comment by bentsi** [comment]
@fruch should use `sdcm.es.ES` to avoid such kind of things, all the code that is responsible for talking with ES should be there, please refactor

**Review by bentsi — APPROVED** [review]

**Pull request merged**
