### PR TITLE
improvement(nemesis-generator): Added Jenkins files for azure

### PR DESCRIPTION
**Pull request by Mark-Gurevich**
Added nemesis pipelines for azure

Passed:

1. https://jenkins.scylladb.com/job/scylla-staging/job/mark/job/SCT-Individual-nemesis-azure/job/longevity-5gb-1h-ToggleCDCMonkey-azure/3/
2. https://jenkins.scylladb.com/job/scylla-staging/job/mark/job/SCT-Individual-nemesis-azure/job/longevity-5gb-1h-DecommissionMonkey-azure-test/3/
3. https://jenkins.scylladb.com/job/scylla-staging/job/mark/job/SCT-Individual-nemesis-azure/job/longevity-5gb-1h-RefreshBigMonkey-azure.jenkinsfile/   (Failed only to clean resources)

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
@Mark-Gurevich , while checks are running, please add here the links to the jobs you already ran (it can be in Argus, or Jenkins)

**Review by fgelcer — DISMISSED** [review]
LGTM

**Comment by fgelcer** [comment]
@soyacz , i was talking with @yaronkaikov about running jobs on Azure, and we still have some kind of limitation of resources, so i was now thinking:
1. do we have support to run Azure on any other region than `eastus`?
2. if no, we must add few more regions (let's sync with @yaronkaikov about what are the regions we are going to copy the images to) and add support
3. if yes, then let's try to think of a generic way to use `random` region, so we can have majority of these jobs running in parallel

**Comment by fgelcer** [comment]
> @Mark-Gurevich , while checks are running, please add here the links to the jobs you already ran (it can be in Argus, or Jenkins)

@Mark-Gurevich , checks failed because in the commit message you have a typo in the word `improvement`. please fix the commit message

**Comment by yaronkaikov** [comment]
> @soyacz , i was talking with @yaronkaikov about running jobs on Azure, and we still have some kind of limitation of resources, so i was now thinking:
> 
> 1. do we have support to run Azure on any other region than `eastus`?
> 2. if no, we must add few more regions (let's sync with @yaronkaikov about what are the regions we are going to copy the images to) and add support
> 3. if yes, then let's try to think of a generic way to use `random` region, so we can have majority of these jobs running in parallel

Adding addtional supported regions is part of https://github.com/scylladb/scylla-pkg/pull/3323, currently, we create the image on `eastus` and copy to `eastus2`, `westus` , `northeurope` and `westeurope`

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by soyacz — APPROVED** [review]

**Comment by Mark-Gurevich** [comment]
ping @scylladb/qa-maintainers

**Pull request merged**
