### PR TITLE
Fix non seed nodes list for update db pkg/binary

### PR DESCRIPTION
**Pull request by yarongilor**

### CODE REVIEW

**Comment by roydahan** [comment]
This should fix an issue when the seed is not the first node.
In that case we have 2 nodes that are seed and we will not upgrade one of them.

**Comment by amoskong** [comment]
> This should fix an issue when the seed is not the first node.
> In that case we have 2 nodes that are seed and we will not upgrade one of them.

In _update_db_binary(), the seed_nodes & non_seed_nodes are only effect stop / start scylla. It doesn't effect which nodes's binary will be updated.

If first node isn't seed, it's is_seed would be wrongly set to True, then we won't stop /start its scylla-server, but we will update its binary. The update won't effect without restart.

**Comment by bentsi** [comment]
I am not sure how this fixes something:
`get_seed_nodes` updates `is_seed` parameter so it doesn't matter if you look on what `get_seed_nodes` returned or on `is_seed` param. Am I missing smth.?
```
    def get_seed_nodes(self):
        seed_nodes_ips = self.get_seed_nodes_from_node()
        seed_nodes = []
        for node in self.nodes:
            if node.ip_address in seed_nodes_ips:
                node.is_seed = True  # TODO: check if we need to change the is_seed, later on
                seed_nodes.append(node)
        assert seed_nodes, "We should have at least one selected seed by now"
        return seed_nodes
```
@fruch

**Comment by fruch** [comment]
@bentsi yes, you are missing that get_seed_nodes is changing the is_seed flag, but not returning other node that the flag is True, but this node isn't configured as seed in scylla.yaml.
this fixes the issue for the code calling it now, the proper cleanup of seeds selection should take place in a different PR

**Comment by fruch** [comment]
@bentsi, anything holding this from being merged ?

**Comment by bentsi** [comment]
@fruch how can we get into the situation that the node's `is_seed` flag is set to true but the seed configuration is not reflected in the `scylla.yaml`?

**Comment by fruch** [comment]
@bentsi yes we can, when sct set one node, and the reflector select a different one, we will have two node marked, and only one is acting as seed.

**Pull request merged**
