### PR TITLE
Add longevity-counters-4days-multidc.yaml to `/test-cases`

### PR DESCRIPTION
**Pull request by fruch**
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I gave variables/functions meaningful self-explanatory names
- [ ] I didn't leave commented-out/debugging code
- [ ] I didn't copy-paste code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (`hydra unit-tests`)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
Shall i review it? if so why still in draft mode?

**Comment by fruch** [comment]
You can review it, but the pipeline job for it doesn't work yet
I think it's the first multi region test case we are trying to via the new pipelines, it need a bit more work.

**Comment by fruch** [comment]
@roydahan, do you know what we have missing here ?

I've got to the point this secnerio starting to run but fais to start the load:

```
WARN  05:58:52,393 Error while computing token map for keyspace ad_performance with datacenter eu-west-1scylla_node_west: could not achieve replication factor 3 (found
0 replicas only), check your keyspace replication settings.
WARN  05:58:54,536 Error while computing token map for keyspace ad_performance with datacenter eu-west-1scylla_node_west: could not achieve replication factor 3 (found
0 replicas only), check your keyspace replication settings.

...

com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency LOCAL_QUORUM (1 required but only 0 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency LOCAL_QUORUM (1 required but only 0 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency LOCAL_QUORUM (1 required but only 0 alive)
```

**Comment by roydahan** [comment]
Do you have the cluster up?
It seems like not all nodes in all data centers are available (or maybe the ports are blocked in the SG?)

**Comment by fruch** [comment]
@roydahan I took it down, I had lot of issue with the port, and I've documented each one on the security group in Ireland.

 seem like `scylla-qa-internal/cust_g/data_by_tracking_id.yaml` isn't exactly matching the regions I'm using...

where are those `us-eastscylla_node_east` name are coming from ?

**Comment by roydahan** [comment]
I think it's coming from the c-s command, they have replication strategy as NetworkTopology and the names are taken from the snitch.

**Comment by fruch** [comment]
@roydahan after a second look seem like only one loader is failing, and other 2 loader did start the load

you can re-trigger it here, if you'll have a time to look:
http://jenkins.scylladb.com/job/scylla-staging/job/empty/job/longevity/job/longevity-counters-4days-multidc-test/20/

**Comment by fruch** [comment]
@roydahan, can give it a final review ?

**Pull request merged**
