### PR TITLE
feature(pytest): add pytest-random-order plugin

### PR DESCRIPTION
**Pull request by vponomaryov**
This plugin allows us to run K8S functional tests in random order
using following options:
    --random-order
    --random-order-seed=12321
    --random-order-bucket=module (can also be class, package and global)

Example of running tests in random order and stopping after 1st failure:

    PYTEST_ADDOPTS="--maxfail=1 --random-order" ./sct.py run-pytest \
        functional_tests/scylla_operator --logdir=`pwd`/logs \
        --backend k8s-local-kind \
        --config test-cases/scylla-operator/functional.yaml

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by bentsi — CHANGES_REQUESTED** [review]
need to create new Hydra version

**Comment by soyacz** [comment]
I'd say this requires some info in docs/readme too

**Comment by bentsi** [comment]
agree, @vponomaryov please also update readme

**Comment by vponomaryov** [comment]
> need to create new Hydra version

Done



> I'd say this requires some info in docs/readme too

Done

**Review by dkropachev — DISMISSED** [review]
Please do not forget to tweak docker/env/version to normal version before merging it

**Review by bentsi — APPROVED** [review]

**Pull request merged**
