### PR TITLE
Fix redundant cluster rollout after nodetool_flush_and_reshard test

### PR DESCRIPTION
**Pull request by soyacz**
In `test_nodetool_flush_and_reshard` test cluster configuration is
recovered to original state (cpu count change). But, it looks it is not
recovering to original cluster state because cpu limits value gets wrong
type - instead string, float is supplied.

This fix recovers proper cpu limit value. So there's no need to
additionally rollout cluster after the test.

Also added deepdiff lib as:
Sometimes it would be good to see differences in dictionaries.
E.g. when we want to know what spec parameter of k8s cluster changed
between tests so we decide to rollout it.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by vponomaryov** [comment]
Run a functional tests EKS `CI job with providing following `pytest` parameter: `--random-order` 
We will get this test run somewhere in the middle in 99% cases.

**Comment by soyacz** [comment]
> Need to run a functional tests EKS CI job with providing following `pytest` parameter: `--random-order` We will get this test run somewhere in the middle in 99% cases.
> 
> Also, the `_bring_cluster_back_to_original_state` function still doesn't wait correctly for the end of a rollout even if it is expected. It must not return in miliseconds if it triggered a rollout itself. Expected steps:
> 
> * triggered rollout
> * sleep for minimum time of a Scylla cluster rollout -> ~3min (no data , fast nodes. In common case it is ~12min)
> * wait for rollout to finish.

how about before triggering new rollout we verify if previous rollout did finish with `db_cluster.wait_sts_rollout_restart(len(db_cluster.nodes))` ?

**Comment by vponomaryov** [comment]
> > Need to run a functional tests EKS CI job with providing following `pytest` parameter: `--random-order` We will get this test run somewhere in the middle in 99% cases.
> > Also, the `_bring_cluster_back_to_original_state` function still doesn't wait correctly for the end of a rollout even if it is expected. It must not return in miliseconds if it triggered a rollout itself. Expected steps:
> > 
> > * triggered rollout
> > * sleep for minimum time of a Scylla cluster rollout -> ~3min (no data , fast nodes. In common case it is ~12min)
> > * wait for rollout to finish.
> 
> how about before triggering new rollout we verify if previous rollout did finish with `db_cluster.wait_sts_rollout_restart(len(db_cluster.nodes))` ?

It is adding safety, but not solving the problem.
It must not return unexpectedly fast.

**Comment by soyacz** [comment]
> > > 
> > > * triggered rollout
> > > * sleep for minimum time of a Scylla cluster rollout -> ~3min (no data , fast nodes. In common case it is ~12min)
> > > * wait for rollout to finish.
> > 

@vponomaryov I added this sleep, so there's more stability.
Besides, functional eks test passed: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/operator-functional-eks/7/

Also additional log message revealed 2 tests that make cluster rollout after:
- test_mgmt_backup (due to `{'dictionary_item_added': [root['backups']]}`)
- test_mgmt_repair (due to `{'dictionary_item_added': [root['repairs']]})`)

If we don't care about it, we could skip these keys - in some other task.

**Comment by vponomaryov** [comment]
> > > > * triggered rollout
> > > > * sleep for minimum time of a Scylla cluster rollout -> ~3min (no data , fast nodes. In common case it is ~12min)
> > > > * wait for rollout to finish.
> 
> @vponomaryov I added this sleep, so there's more stability. Besides, functional eks test passed: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/operator-functional-eks/7/
> 
> Also additional log message revealed 2 tests that make cluster rollout after:
> 
> * test_mgmt_backup (due to `{'dictionary_item_added': [root['backups']]}`)
> * test_mgmt_repair (due to `{'dictionary_item_added': [root['repairs']]})`)
> 
> If we don't care about it, we could skip these keys - in some other task.

We care about it. I would like to see all such related fixes in this PR. It may be separate commits, but 1 PR.

**Comment by soyacz** [comment]
> We care about it. I would like to see all such related fixes in this PR. It may be separate commits, but 1 PR.

done

**Review by fruch — APPROVED** [review]
LGTM

**Comment by soyacz** [comment]
@vponomaryov I retested - there are no more redundant cluster rollouts. https://jenkins.scylladb.com/job/scylla-staging/job/lukasz/job/operator-functional-eks/8/

**Review by vponomaryov — APPROVED** [review]
LGTM

**Pull request merged**
