### PR TITLE
[backport]feature(aws): placement group create/list/delete

### PR DESCRIPTION
**Pull request by temichus**
backport into perf-v14  for  https://github.com/scylladb/scylla-cluster-tests/pull/6594 and https://github.com/scylladb/scylla-cluster-tests/pull/6571
 
this commit is:
1) Include provision step into the performance pipeline 2) Add the ability to create load and DB instances within one AWS placement group and config parameter to enable this feature
3) Update i4i Throughput perf test to  use the new feature 4) extend sct.py 'list-resources', 'clean-resourses' to support AWS placement groups

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by temichus** [comment]
I have to include changes in list_instances_aws and clean_resources_according_post_behavior for a successful backport.
under testing now.

**Comment by temichus** [comment]
test pass - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/scylla-master-perf-regression-throughput-non-shard-aware-i4i-test/28/

**Review by soyacz — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@temichus next time doing a PR for backport, please try to keep the commits named and ordered as in master
using `git cherry-pick -x` so they would have the original commits sha mentioned in them
otherwise it's very hard to track which part is where.

**Comment by vponomaryov** [comment]
> @temichus next time doing a PR for backport, please try to keep the commits named and ordered as in master using `git cherry-pick -x` so they would have the original commits sha mentioned in them otherwise it's very hard to track which part is where.

It is easy to address. I would to see it addressed here.

**Comment by temichus** [comment]
> @temichus next time doing a PR for backport, please try to keep the commits named and ordered as in master using `git cherry-pick -x` so they would have the original commits sha mentioned in them otherwise it's very hard to track which part is where.

I can't do git cherry-pick -x`  because there are merge conflicts. - x is only for cherry picks without conflicts

**Comment by fruch** [comment]
> > @temichus next time doing a PR for backport, please try to keep the commits named and ordered as in master using `git cherry-pick -x` so they would have the original commits sha mentioned in them otherwise it's very hard to track which part is where.
> 
> I can't do git cherry-pick -x` because there are merge conflicts. - x is only for cherry picks without conflicts. that is why I make a separate commit, this code are not same as in master

that's not accurate, you can do `cherry-pick -x` but you need to solve the conflicts in the process.
we are doing that for backports all the time.

anyhow without that as traceability, it's hard to tell if something has been backported or not.

the idea of doing those in one PR, is for the sake of testing and validating it's working.

**Comment by temichus** [comment]
@fruch pushed in 2 commits as requested please check

moved to draft as @roydahan asked for more testing

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
> @fruch, I pushed in 2 commits as requested please check
> 
> moved to draft as @roydahan asked for more testing

can you please list the testing being asked ?

**Comment by roydahan** [comment]
I wanted to see 5 runs of throughput test and 5 runs of latency test (with the same AMI in staging) to make sure:
1. We have more or less the same results.
2. Results are more consistent.

Also, if the backport is too big, we may consider branch v15.

**Comment by temichus** [comment]
@roydahan, @fruch 

testing results:

Conclusion: all results look similar to what we currently have in weekly runs(when we are lucky and AWS does not provision instances far from each other)

there are still flaky results for throughput WRITE (10% diff), and latency MIXED (1ms diff) even with using placement group(will investigate in a separate task by running test on the same cluster several times)

detailed results with numbers are below:

current master code with placement group: 
throughput 
W - 308k-321k, weekly run: 330k
R - 385k-392k, weekly run: 385.6k
M - 222k-235k, weekly run: 229k

image
image
image


latency
W - 2.4-2.7, weekly run: 2.8
R - 2.9-3, weekly run: 3.2
M - 4.8-6.5, weekly run: 5.5


image
image
image


This PR code with placement group: 
throughput
W - 304k-335k, weekly run: 330k
R - 372k-391k, weekly run: 385.6k
M - 221k-240k, weekly run: 229k

image
image
image

latency
W - 2.6-2.7, weekly run: 2.8
R - 3-3.1, weekly run: 3.2
M - 5.6-6.4, weekly run: 5.5

image
image
image

**Comment by fruch** [comment]
@temichus do you have compression to without placement groups ?, which is a bit more interesting to see, i think...

**Comment by temichus** [comment]
> @temichus do you have compression to without placement groups ?, which is a bit more interesting to see, i think...

weekly run results have no placement groups, or do you want to see several results without placement groups?

**Comment by fruch** [comment]
> > @temichus do you have compression to without placement groups ?, which is a bit more interesting to see, i think...
> 
> @fruch,
> weekly run results have no placement groups, or do you want to see several results without placement groups?

I wonder if using the placement has shown any improvement.

The results attached here are showing just results from runs with placement. or miss read it ?

**Comment by temichus** [comment]
> > > @temichus do you have compression to without placement groups ?, which is a bit more interesting to see, i think...
> > 
> > 
> > @fruch,
> > weekly run results have no placement groups, or do you want to see several results without placement groups?
> 
> I wonder if using the placement has shown any improvement.
> 
> The results attached here are showing just results from runs with placement. or miss read it ?

results are the same for cases "when AWS without placement group does not provision instances far from each other"
but in the case of running  without a placement group several times we often got big diff in the results 

I am trying to say that this PR will help us to achieve stability of Perf results by using the 'cluster' placement group for test cases that provide low-latency network performance achievement. But does not get higher numbers

**Comment by fruch** [comment]
> > > > @temichus do you have compression to without placement groups ?, which is a bit more interesting to see, i think...
> > > 
> > > 
> > > @fruch,
> > > weekly run results have no placement groups, or do you want to see several results without placement groups?
> > 
> > I wonder if using the placement has shown any improvement.
> > 
> > The results attached here are showing just results from runs with placement. or miss read it ?
> 
> results are the same for cases without placement group "when AWS does not provision instances far from each other"
> but in the case of running  without a placement group several times we often got big diff in the results 
> 
> I am trying to say that this PR will help us to achieve stability of Perf results by using the 'cluster' placement group for test cases that for sure will provide low-latency network performance. But does not get higher numbers
> 

So we can't really demonstrate yet it makes a difference, unless we will run it enough times to not see those big diffs ?

**Comment by temichus** [comment]
> > > > > @temichus do you have compression to without placement groups ?, which is a bit more interesting to see, i think...
> > > > 
> > > > 
> > > > @fruch,
> > > > weekly run results have no placement groups, or do you want to see several results without placement groups?
> > > 
> > > 
> > > I wonder if using the placement has shown any improvement.
> > > The results attached here are showing just results from runs with placement. or miss read it ?
> > 
> > 
> > results are the same for cases without placement group "when AWS does not provision instances far from each other"
> > but in the case of running  without a placement group several times we often got big diff in the results
> > I am trying to say that this PR will help us to achieve stability of Perf results by using the 'cluster' placement group for test cases that for sure will provide low-latency network performance. But does not get higher numbers
> 
> So we can't really demonstrate yet it makes a difference unless we will run it enough times to not see those big diffs ?

Right, until we get bad results we can't say.

Our with @aleksbykov  saga of Stabilizing Throughput perf test is the following:

- before or the result was completely unstable. During our investigation, we saw that in most cases one of 2 nodes is just slower than another. Avi suggested using new, fresh  i4i nodes, and it helped, but not enough.

- The next change according to the bad perf results investigation  was increasing  load concurrency because Scylla was not fully 
loaded

 - And now, bad perf results investigation shows us that 1 or 2 nodes have bigger latency than another.
 The solution is to move the DB cluster and loader under one "[cluster](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html)" placement group
 
 Cluster – packs instances close together inside an Availability Zone. This strategy enables workloads to achieve the low-latency network performance necessary for tightly-coupled node-to-node communication that is typical of high-performance computing (HPC) applications.

**Review by roydahan — APPROVED** [review]

**Comment by temichus** [comment]
@scylladb/qa-maintainers, please merge

**Pull request merged**
