### PR TITLE
get user_agent value from qa keystore

### PR DESCRIPTION
**Pull request by amoskong**

### CODE REVIEW

**Comment by bentsi** [comment]
@amoskong Please remove from Jenkins jobs. I will backport to 3.0

**Comment by amoskong** [comment]
I will remove user_agent parameter from all jenkins jobs.

BTW, keystore doesn't exist in branch-3.0, I have a minimized backport example: https://github.com/amoskong/scylla-cluster-tests/commits/branch-3.0-user_agent_backport

**Comment by bentsi** [comment]
@amoskong very good! I will make a PR from this branch

**Comment by bentsi** [comment]
PR: https://github.com/scylladb/scylla-cluster-tests/pull/729

**Pull request merged**
