### PR TITLE
fix(sdcm/utils/docker.py): Rename to docker_utils.py to avoid module import confusion

### PR DESCRIPTION
**Pull request by dkropachev**
https://trello.com/c/f9D7qxRm/1976-fix-dockerpy-import-confusion

On my system I see following error:
```
  File "/usr/src/scylladb/scylla-cluster-tests/dkropachev3/sdcm/utils/docker.py", line 23, in <module>
    from docker.errors import DockerException, NotFound, ImageNotFound, NullResource

```

ModuleNotFoundError: No module named 'docker.errors'; 'docker' is not a package
It is happening due to the import confusion - python sees local file  named docker.py and confueses it with system package.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by fruch** [comment]
> Don't like the idea. Looks like pretty dirty hack. Imho, it's better to rename file if you are experiencing regular problems with importing `sdcm.utils.docker` It really depends on environment and I have no such problems.
> 
> Suggested name for the module: `docker_utils`

@enaydanov  you've been reading my mind ? since I was thinking about the exact same name :exploding_head: (but didn't got to comment it...)

**Comment by bentsi** [comment]
@dkropachev as suggested, better to rename to `docker_utils`

**Comment by dkropachev** [comment]
> @dkropachev as suggested, better to rename to `docker_utils`

Done

**Comment by dkropachev** [comment]
> Looks great for me, except PR# subject :-)
Fixed

**Pull request merged**
