### PR TITLE
refactor(longevity-50gb): Shorten the 4 days test to 3 days

### PR DESCRIPTION
**Pull request by roydahan**
We would like the test to start on master every Friday morning and end by Sunday morning.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [x] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [x] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by bentsi** [comment]
do we need to backport this?

**Comment by roydahan** [comment]
Not needed to backport.
Only for master now.

BTW, I didn’t change the pipeline file name.
I can if we think it’s necessary.

**Comment by bentsi** [comment]
@roydahan for consistency let's change the pipeline file too

**Comment by fruch** [comment]
> @roydahan for consistency let's change the pipeline file too

that mean to update the job, and it's name, and triggers
(in this case there is only one trigger, only on master, not on branches)

**Comment by roydahan** [comment]
> > @roydahan for consistency let's change the pipeline file too
> 
> that mean to update the job, and it's name, and triggers
> (in this case there is only one trigger, only on master, not on branches)

Exactly, that's why I didn't do that.

**Comment by bentsi** [comment]
need to do that, otherwise, the name will be misleading

**Comment by roydahan** [comment]
Done, changed the name and the name of the job in master + the weekly trigger.
Let's merge.

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
