### PR TITLE
improvement(sct.py/show-logs): Add --update-argus argument

### LINKED ISSUE #7583: Logs and screenshots are not shown in Argus
in case of failure during collect-log stage, logs and screenshots are not updated in Argus and we need to run collect-logs manually and paste to issues (which in turn doesn't look right or requires copy-paste procedure to download log)
We should update argus as soon as log is collected instead of waiting to the end.

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor f417745e-0067-4479-95ee-24c9182267ce`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f417745e-0067-4479-95ee-24c9182267ce)
- Show all stored logs command: `$ hydra investigate show-logs f417745e-0067-4479-95ee-24c9182267ce`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/lukasz/job/scylla-master-perf-regression-latency-650gb-grow-shrink/24/)
[Argus](https://argus.scylladb.com/test/18619447-834b-4c2c-9a77-c87e54a099a8/runs?additionalRuns[]=f417745e-0067-4479-95ee-24c9182267ce)
</details>

### PR DESCRIPTION
**Pull request by k0machi**
This commit adds a flag to the `show-logs` command which allows it to
update Argus with links that have not been submitted to it, either by
network error or other issue preventing `store_logs_in_argus` from
running. The function has been updated to support `update` parameter,
which will fetch the run from Argus and look for missing log links.

Fixes #7583

### Testing

- [x] [Argus](https://argus.scylladb.com/tests/scylla-cluster-tests/50629082-fbee-41a4-8f49-1fac2969b86b)
- [x] [Jenkins](https://jenkins.scylladb.com/job/scylla-staging/job/alexey/job/alexey-argus-testing/102/)

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Review by fruch — APPROVED** [review]
LGTM

**Review by soyacz — APPROVED** [review]
LGTM

**Comment by soyacz** [comment]
@k0machi do we need to backport it?

**Comment by k0machi** [comment]
> @k0machi do we need to backport it?

If backporting, this PR needs get_run support on the client, 6.1 might not have that

**Comment by soyacz** [comment]
> > @k0machi do we need to backport it?
> 
> If backporting, this PR needs get_run support on the client, 6.1 might not have that

yes, but do we need to backport it at all? won't users run this command only from master?

**Pull request merged**
