### PR TITLE
fix(arm artifact tests): Enabled manager agent installation

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
Since manager 3.0 supports arm installation, we can now enable
manager agent installation in arm artifact tests.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by ShlomiBalalis** [comment]
# Please do not backport  before https://github.com/scylladb/scylla-cluster-tests/pull/4930 is merged and backported

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by rayakurl — APPROVED** [review]
LGTM

**Review by roydahan — APPROVED** [review]

**Comment by fruch** [comment]
this doesn't need to be backported

**Comment by rayakurl** [comment]
@fruch , @fgelcer - why do you think that backports are not needed?

**Comment by fgelcer** [comment]
> @fruch , @fgelcer - why do you think that backports are not needed?
i just added a label, after @fruch removed the backport labels...

**Comment by roydahan** [comment]
Ok to backport to 2022.1.
For now, not needed in 5.0.

**Comment by roydahan** [comment]
We will hold the backport till we release 2022.1.0.
I don't want it to somehow fail the tests when trying to release.

**Comment by rayakurl** [comment]
@roydahan - can you please backport now?

**Comment by roydahan** [comment]
Done.

**Pull request merged**
