### PR TITLE
fix(provision): make it work for ipv6

### PR DESCRIPTION
**Pull request by dkropachev**
https://trello.com/c/P7Eo1SdE/4446-provision-fix-issue-with-ipv6

Reason why IPV6 did on work on provisioned instances was that user-data was not executed on them.
There are two reasons for that :
1. We used scylla-based user data for loaders, which was wrong
2. Something in the scripts did not allow it to be executed properly

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Review by fgelcer — DISMISSED** [review]
if it works, then we should get it merged ASAP

**Comment by dkropachev** [comment]
Just run test and it failed, do not merge it.

**Comment by dkropachev** [comment]
Hello tested here - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/dmitry/job/dmitry-byo-longevity-2/118/
It is failed, due to the scylla failure, but sct.

**Comment by fgelcer** [comment]
> Hello tested here - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/dmitry/job/dmitry-byo-longevity-2/118/ It is failed, due to the scylla failure, but sct.

true, the provision worked, but there is still some issue (perhaps a configuration issue) around IPv6.

from job above we see:
```
13:58:26  < t:2021-12-28 11:58:24,412 f:file_logger.py  l:89   c:sdcm.sct_events.file_logger p:INFO  > 2021-12-28T11:58:23+00:00 longevity-10gb-3h-fix-ipv6-db-node-86a3c57c-3 !    INFO |  [shard 0] rpc - client [2a05:d018:eb8:3100:2164:1c99:c83c:a6a3%0]:56770 msg_id 3:  exception "gate closed" in no_wait handler ignored
13:59:00  < t:2021-12-28 11:58:59,657 f:thread.py       l:52   c:cassandra.cluster    p:WARNING > Failed to create connection pool for new host 2a05:d018:eb8:3100:921c:afa1:3112:56b5:9042: < t:2021-12-28 11:58:59,657 f:thread.py       l:52   c:cassandra.cluster    p:WARNING > Failed to create connection pool for new host 2a05:d018:eb8:3100:921c:afa1:3112:56b5:9042:
13:59:00  < t:2021-12-28 11:58:59,657 f:thread.py       l:52   c:cassandra.cluster    p:WARNING > Traceback (most recent call last):
13:59:00  < t:2021-12-28 11:58:59,657 f:thread.py       l:52   c:cassandra.cluster    p:WARNING >   File "cassandra/cluster.py", line 3184, in cassandra.cluster.Session.add_or_renew_pool.run_add_or_renew_pool
13:59:00  < t:2021-12-28 11:58:59,657 f:thread.py       l:52   c:cassandra.cluster    p:WARNING >   File "cassandra/pool.py", line 424, in cassandra.pool.HostConnection.__init__
13:59:00  < t:2021-12-28 11:58:59,657 f:thread.py       l:52   c:cassandra.cluster    p:WARNING >   File "cassandra/cluster.py", line 1620, in cassandra.cluster.Cluster.connection_factory
13:59:00  < t:2021-12-28 11:58:59,657 f:thread.py       l:52   c:cassandra.cluster    p:WARNING >   File "cassandra/connection.py", line 782, in cassandra.connection.Connection.factory
13:59:00  < t:2021-12-28 11:58:59,657 f:thread.py       l:52   c:cassandra.cluster    p:WARNING >   File "/usr/local/lib/python3.10/site-packages/cassandra/io/asyncorereactor.py", line 351, in __init__
13:59:00  < t:2021-12-28 11:58:59,657 f:thread.py       l:52   c:cassandra.cluster    p:WARNING >     self._connect_socket()
13:59:00  < t:2021-12-28 11:58:59,657 f:thread.py       l:52   c:cassandra.cluster    p:WARNING >   File "cassandra/connection.py", line 849, in cassandra.connection.Connection._connect_socket
13:59:00  < t:2021-12-28 11:58:59,657 f:thread.py       l:52   c:cassandra.cluster    p:WARNING > ConnectionRefusedError: [Errno 111] Tried connecting to [('2a05:d018:eb8:3100:921c:afa1:3112:56b5', 9042, 0, 0)]. Last error: Connection refused
13:59:00  < t:2021-12-28 11:58:59,782 f:thread.py       l:52   c:cassandra.cluster    p:WARNING > Host 2a05:d018:eb8:3100:921c:afa1:3112:56b5:9042 has been marked down
13:59:00  < t:2021-12-28 11:58:59,925 f:file_logger.py  l:89   c:sdcm.sct_events.file_logger p:INFO  > 2021-12-28 11:58:59.923: (FullScanEvent Severity.NORMAL) period_type=begin event_id=5c6090ee-bc39-4be5-b7ad-39f3589ce206 node=longevity-10gb-3h-fix-ipv6-db-node-86a3c57c-3 select_from=keyspace1.standard1
13:59:00  < t:2021-12-28 11:58:59,940 f:cluster.py      l:3219 c:cassandra.cluster    p:WARNING > [control connection] Error connecting to 2a05:d018:eb8:3100:921c:afa1:3112:56b5:9042: < t:2021-12-28 11:58:59,940 f:cluster.py      l:3219 c:cassandra.cluster    p:WARNING > [control connection] Error connecting to 2a05:d018:eb8:3100:921c:afa1:3112:56b5:9042:
13:59:00  < t:2021-12-28 11:58:59,940 f:cluster.py      l:3219 c:cassandra.cluster    p:WARNING > Traceback (most recent call last):
13:59:00  < t:2021-12-28 11:58:59,940 f:cluster.py      l:3219 c:cassandra.cluster    p:WARNING >   File "cassandra/cluster.py", line 3531, in cassandra.cluster.ControlConnection._reconnect_internal
13:59:00  < t:2021-12-28 11:58:59,940 f:cluster.py      l:3219 c:cassandra.cluster    p:WARNING >   File "cassandra/cluster.py", line 3553, in cassandra.cluster.ControlConnection._try_connect
13:59:00  < t:2021-12-28 11:58:59,940 f:cluster.py      l:3219 c:cassandra.cluster    p:WARNING >   File "cassandra/cluster.py", line 1620, in cassandra.cluster.Cluster.connection_factory
13:59:00  < t:2021-12-28 11:58:59,940 f:cluster.py      l:3219 c:cassandra.cluster    p:WARNING >   File "cassandra/connection.py", line 782, in cassandra.connection.Connection.factory
13:59:00  < t:2021-12-28 11:58:59,940 f:cluster.py      l:3219 c:cassandra.cluster    p:WARNING >   File "/usr/local/lib/python3.10/site-packages/cassandra/io/asyncorereactor.py", line 351, in __init__
13:59:00  < t:2021-12-28 11:58:59,940 f:cluster.py      l:3219 c:cassandra.cluster    p:WARNING >     self._connect_socket()
13:59:00  < t:2021-12-28 11:58:59,940 f:cluster.py      l:3219 c:cassandra.cluster    p:WARNING >   File "cassandra/connection.py", line 849, in cassandra.connection.Connection._connect_socket
13:59:00  < t:2021-12-28 11:58:59,940 f:cluster.py      l:3219 c:cassandra.cluster    p:WARNING > ConnectionRefusedError: [Errno 111] Tried connecting to [('2a05:d018:eb8:3100:921c:afa1:3112:56b5', 9042, 0, 0)]. Last error: Connection refused
13:59:00  < t:2021-12-28 11:58:59,987 f:thread.py       l:52   c:cassandra.cluster    p:WARNING > Failed to create connection pool for new host 2a05:d018:eb8:3100:921c:afa1:3112:56b5:9042: < t:2021-12-28 11:58:59,987 f:thread.py       l:52   c:cassandra.cluster    p:WARNING > Failed to create connection pool for new host 2a05:d018:eb8:3100:921c:afa1:3112:56b5:9042:
13:59:00  < t:2021-12-28 11:58:59,987 f:thread.py       l:52   c:cassandra.cluster    p:WARNING > Traceback (most recent call last):
13:59:00  < t:2021-12-28 11:58:59,987 f:thread.py       l:52   c:cassandra.cluster    p:WARNING >   File "cassandra/cluster.py", line 3184, in cassandra.cluster.Session.add_or_renew_pool.run_add_or_renew_pool
13:59:00  < t:2021-12-28 11:58:59,987 f:thread.py       l:52   c:cassandra.cluster    p:WARNING >   File "cassandra/pool.py", line 424, in cassandra.pool.HostConnection.__init__
13:59:00  < t:2021-12-28 11:58:59,987 f:thread.py       l:52   c:cassandra.cluster    p:WARNING >   File "cassandra/cluster.py", line 1620, in cassandra.cluster.Cluster.connection_factory
13:59:00  < t:2021-12-28 11:58:59,987 f:thread.py       l:52   c:cassandra.cluster    p:WARNING >   File "cassandra/connection.py", line 782, in cassandra.connection.Connection.factory
13:59:00  < t:2021-12-28 11:58:59,987 f:thread.py       l:52   c:cassandra.cluster    p:WARNING >   File "/usr/local/lib/python3.10/site-packages/cassandra/io/asyncorereactor.py", line 351, in __init__
13:59:00  < t:2021-12-28 11:58:59,987 f:thread.py       l:52   c:cassandra.cluster    p:WARNING >     self._connect_socket()
13:59:00  < t:2021-12-28 11:58:59,987 f:thread.py       l:52   c:cassandra.cluster    p:WARNING >   File "cassandra/connection.py", line 849, in cassandra.connection.Connection._connect_socket
13:59:00  < t:2021-12-28 11:58:59,987 f:thread.py       l:52   c:cassandra.cluster    p:WARNING > ConnectionRefusedError: [Errno 111] Tried connecting to [('2a05:d018:eb8:3100:921c:afa1:3112:56b5', 9042, 0, 0)]. Last error: Connection refused
13:59:00  < t:2021-12-28 11:58:59,989 f:full_scan_thread.py l:74   c:FullScanThread       p:INFO  > Will run command "select * from keyspace1.standard1 bypass cache USING TIMEOUT 4s"
13:59:00  < t:2021-12-28 11:59:00,076 f:thread.py       l:52   c:cassandra.cluster    p:WARNING > Host 2a05:d018:eb8:3100:921c:afa1:3112:56b5:9042 has been marked down
```

**Review by bentsi — APPROVED** [review]

**Comment by fgelcer** [comment]
need to investigate if this is an issue with Scylla, or any configuration missing on SCT side

**Comment by fgelcer** [comment]
@dkropachev , this is not yet fully working (the instance provision seems it is)...
i see in one of the node's yaml this:
```
# Generated by Scylla Machine Image at 2021-12-30 14:40:22.227559
# See '/etc/scylla/scylla.yaml.example' with the full list of supported configuration
# options and their descriptions.
api_address: 127.0.0.1
api_doc_dir: /opt/scylladb/api/api-doc/
api_port: 10000
api_ui_dir: /opt/scylladb/swagger-ui/dist/
auto_bootstrap: true
batch_size_fail_threshold_in_kb: 1024
batch_size_warn_threshold_in_kb: 128
broadcast_rpc_address: 10.0.3.222
cas_contention_timeout_in_ms: 1000
cluster_name: scylladb-cluster-1640875222
commitlog_segment_size_in_mb: 32
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_total_space_in_mb: -1
endpoint_snitch: Ec2Snitch
experimental: false
listen_address: 10.0.3.222
murmur3_partitioner_ignore_msb_bits: 12
native_shard_aware_transport_port: 19042
native_transport_port: 9042
num_tokens: 256
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
read_request_timeout_in_ms: 5000
rpc_address: 0.0.0.0
rpc_port: 9160
seed_provider:
- class_name: org.apache.cassandra.locator.SimpleSeedProvider
  parameters:
  - seeds: 10.0.3.222
write_request_timeout_in_ms: 2000
```

IIUC we are not correctly configuring neither the broadcast, listen nor seed IP addresses, as they are using private IPv4...

**Comment by dkropachev** [comment]
> Connection._connect_socket

There was rolling cluster restart, so it is normal to see these errors when it is ongoing.

**Comment by dkropachev** [comment]
> @dkropachev , this is not yet fully working (the instance provision seems it is)... i see in one of the node's yaml this:
> 
> ```
> # Generated by Scylla Machine Image at 2021-12-30 14:40:22.227559
> # See '/etc/scylla/scylla.yaml.example' with the full list of supported configuration
> # options and their descriptions.
> api_address: 127.0.0.1
> api_doc_dir: /opt/scylladb/api/api-doc/
> api_port: 10000
> api_ui_dir: /opt/scylladb/swagger-ui/dist/
> auto_bootstrap: true
> batch_size_fail_threshold_in_kb: 1024
> batch_size_warn_threshold_in_kb: 128
> broadcast_rpc_address: 10.0.3.222
> cas_contention_timeout_in_ms: 1000
> cluster_name: scylladb-cluster-1640875222
> commitlog_segment_size_in_mb: 32
> commitlog_sync: periodic
> commitlog_sync_period_in_ms: 10000
> commitlog_total_space_in_mb: -1
> endpoint_snitch: Ec2Snitch
> experimental: false
> listen_address: 10.0.3.222
> murmur3_partitioner_ignore_msb_bits: 12
> native_shard_aware_transport_port: 19042
> native_transport_port: 9042
> num_tokens: 256
> partitioner: org.apache.cassandra.dht.Murmur3Partitioner
> read_request_timeout_in_ms: 5000
> rpc_address: 0.0.0.0
> rpc_port: 9160
> seed_provider:
> - class_name: org.apache.cassandra.locator.SimpleSeedProvider
>   parameters:
>   - seeds: 10.0.3.222
> write_request_timeout_in_ms: 2000
> ```
> 
> IIUC we are not correctly configuring neither the broadcast, listen nor seed IP addresses, as they are using private IPv4...



> @dkropachev , this is not yet fully working (the instance provision seems it is)... i see in one of the node's yaml this:
> 
> ```
> # Generated by Scylla Machine Image at 2021-12-30 14:40:22.227559
> # See '/etc/scylla/scylla.yaml.example' with the full list of supported configuration
> # options and their descriptions.
> api_address: 127.0.0.1
> api_doc_dir: /opt/scylladb/api/api-doc/
> api_port: 10000
> api_ui_dir: /opt/scylladb/swagger-ui/dist/
> auto_bootstrap: true
> batch_size_fail_threshold_in_kb: 1024
> batch_size_warn_threshold_in_kb: 128
> broadcast_rpc_address: 10.0.3.222
> cas_contention_timeout_in_ms: 1000
> cluster_name: scylladb-cluster-1640875222
> commitlog_segment_size_in_mb: 32
> commitlog_sync: periodic
> commitlog_sync_period_in_ms: 10000
> commitlog_total_space_in_mb: -1
> endpoint_snitch: Ec2Snitch
> experimental: false
> listen_address: 10.0.3.222
> murmur3_partitioner_ignore_msb_bits: 12
> native_shard_aware_transport_port: 19042
> native_transport_port: 9042
> num_tokens: 256
> partitioner: org.apache.cassandra.dht.Murmur3Partitioner
> read_request_timeout_in_ms: 5000
> rpc_address: 0.0.0.0
> rpc_port: 9160
> seed_provider:
> - class_name: org.apache.cassandra.locator.SimpleSeedProvider
>   parameters:
>   - seeds: 10.0.3.222
> write_request_timeout_in_ms: 2000
> ```
> 
> IIUC we are not correctly configuring neither the broadcast, listen nor seed IP addresses, as they are using private IPv4...

@fgelcer , Could you please point me to the direction where did you find it, i'am going over db archive and see nothing like this one.

Also, In general, this yaml is generated by cloud-init and it is it's normal state in between when node is provisioned and sct did not pick it up yet.

**Comment by fgelcer** [comment]
> @fgelcer , Could you please point me to the direction where did you find it, i'am going over db archive and see nothing like this one.

you can find full logs (and the full `scylla.yaml` files) in [this job](https://jenkins.scylladb.com/view/scylla-4.6/job/scylla-4.6/job/longevity/view/Long%20Longevities/job/longevity-10gb-3h-ipv6-test/9/)

**Comment by dkropachev** [comment]
> > @fgelcer , Could you please point me to the direction where did you find it, i'am going over db archive and see nothing like this one.
> 
> you can find full logs (and the full `scylla.yaml` files) in [this job](https://jenkins.scylladb.com/view/scylla-4.6/job/scylla-4.6/job/longevity/view/Long%20Longevities/job/longevity-10gb-3h-ipv6-test/9/)

Thanks Fabio, that run was ran on a98a341f48eaacf841b7bfe7298d8e7167108bb3, which is saying that this PR was not FF to the branch-4.6 at the time.

**Comment by fgelcer** [comment]
> > > @fgelcer , Could you please point me to the direction where did you find it, i'am going over db archive and see nothing like this one.
> > 
> > 
> > you can find full logs (and the full `scylla.yaml` files) in [this job](https://jenkins.scylladb.com/view/scylla-4.6/job/scylla-4.6/job/longevity/view/Long%20Longevities/job/longevity-10gb-3h-ipv6-test/9/)
> 
> Thanks Fabio, that run was ran on [a98a341](https://github.com/scylladb/scylla-cluster-tests/commit/a98a341f48eaacf841b7bfe7298d8e7167108bb3), which is saying that this PR was not FF to the branch-4.6 at the time.

got you... re-running [in here](https://jenkins.scylladb.com/view/scylla-4.6/job/scylla-4.6/job/longevity/view/Long%20Longevities/job/longevity-10gb-3h-ipv6-test/10/)

**Comment by fgelcer** [comment]
> > > @fgelcer , Could you please point me to the direction where did you find it, i'am going over db archive and see nothing like this one.
> > 
> > 
> > you can find full logs (and the full `scylla.yaml` files) in [this job](https://jenkins.scylladb.com/view/scylla-4.6/job/scylla-4.6/job/longevity/view/Long%20Longevities/job/longevity-10gb-3h-ipv6-test/9/)
> 
> Thanks Fabio, that run was ran on [a98a341](https://github.com/scylladb/scylla-cluster-tests/commit/a98a341f48eaacf841b7bfe7298d8e7167108bb3), which is saying that this PR was not FF to the branch-4.6 at the time.

got you... re-running [in here](https://jenkins.scylladb.com/view/scylla-4.6/job/scylla-4.6/job/longevity/view/Long%20Longevities/job/longevity-10gb-3h-ipv6-test/10/)

**Comment by fgelcer** [comment]
@dkropachev , sorry for storming.. just to confirm, it seems to be working:
```
(6/6) nodes ready
```

**Comment by bentsi** [comment]
no need to backport, 4.6 FF-ed

**Pull request merged**
