### PR TITLE
fix(loader): bring shard awarness back

### PR DESCRIPTION
**Pull request by dkropachev**
https://trello.com/c/fnElfYAu/2397-c-s-fails-with-cannot-initialize-optimized-memory-deallocator-some-data-both-in-memory-and-on-disk-may-live-longer-due-to-garbag

Somewhere on the way to new loader we have introduced cassandra-driver jars into to the lib directory on the loader.
As result c-s started to use cassandra-driver instead of scylla-driver and we lost shard awarness due to that.
This PR is to bring it back.  

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by dkropachev** [comment]
Test - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/dmitry/job/regression-aws-test-throughput-byo/3/

**Comment by fruch** [comment]
:facepalm: as I suspected. 
@bentsi one of many reasons for dockerize c-s (and all our loader tools)

**Comment by dkropachev** [comment]
>  as I suspected.
> @bentsi one of many reasons for dockerize c-s (and all our loader tools)

Agress

**Comment by roydahan** [comment]
Before merge, @eliransin mentioned we aren't using the latest driver, did you update to the latest driver?

**Comment by eliransin** [comment]
@dkropachev where is the script that builds this AMI image. Not that I don't trust you but if the process is manual, we actually
don't have any record of what is actually going on in AMI-V14.
Moreover it is very difficult to trace back problems like that to the AMI image since it is a black box (maybe only to me :slightly_smiling_face: )

**Comment by eliransin** [comment]
Just as an example - I saw that on V11 - V13 in the java_driver folder the checked out version was from 2018 (V3.5 or something where the version of the driver is already V3.11.something). Is this the code used to build the driver or maybe this folder is just there for no reason.

**Comment by dkropachev** [comment]
> Before merge, @eliransin mentioned we aren't using the latest driver, did you update to the latest driver?

Thanks for mentioning , it is 3.7 there, i will update it.

**Comment by dkropachev** [comment]
> Just as an example - I saw that on V11 - V13 in the java_driver folder the checked out version was from 2018 (V3.5 or something where the version of the driver is already V3.11.something). Is this the code used to build the driver or maybe this folder is just there for no reason.
> 

Where I can find it ? 3.10.1 was just published to maven, is that it ? https://mvnrepository.com/artifact/com.scylladb/scylla-driver-core

**Comment by eliransin** [comment]
I looked at the repository tags:
```
$cd java-driver
$git tag | grep scylla
3.10.1-scylla-0
3.10.2-scylla-0
3.7.1-scylla-0
3.7.1-scylla-1
3.7.1-scylla-2
3.7.1_scylla_no_coalescing
4.8.0-scylla-0
4.9.0-scylla-0
```

**Review by bentsi — APPROVED** [review]

**Comment by dkropachev** [comment]
loader-v16 has following features:

- driver: scylla driver 3.10.1
- java: JAVA 11.0.8 2020-07-14 LTS (Oracle JAVA)
- shardawarness: is turned on by default on scylla driver

**Review by roydahan — APPROVED** [review]

**Comment by bentsi** [comment]
do we need to backport this?

**Comment by roydahan** [comment]
For now don’t backport anything.

**Pull request merged**
