### PR TITLE
feature(cluster): remove apt-key refs

### PR DESCRIPTION
**Pull request by benipeled**
Following #5101 we can now remove the apt-key refs

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fgelcer — COMMENTED** [review]
once removing this, does it mean that we won't be able to run on Ubuntu versions older than 22.04 from this branch?

**Comment by fruch** [comment]
> once removing this, does it mean that we won't be able to run on Ubuntu versions older than 22.04 from this branch?

it's not related to a specific ubuntu version, is a way of using the keys, and it available across distros versions. i.e. we have this code running on master for quite some time now.

**Review by fruch — APPROVED** [review]

**Comment by fruch** [comment]
@benipeled just check, and our CI test for GCP is using a prepared image. (i.e. the test isn't install anything)

I think we should test it at least once with on of the ubuntu artifact test (if you test it, just confirm)

**Comment by benipeled** [comment]
Verified with
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/artifacts/job/artifacts-ubuntu2004-test/94/

The job failed on missing scylla-manager package `Unable to locate package scylla-manager-agent` which has nothing with this change

**Comment by fruch** [comment]
> Verified with https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/artifacts/job/artifacts-ubuntu2004-test/94/
> 
> The job failed on missing scylla-manager package `Unable to locate package scylla-manager-agent` which has nothing with this change

The log disagree with you:
```
< t:2022-11-28 21:08:42,714 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Err:5 http://downloads.scylladb.com/downloads/scylla-manager/deb/ubuntu/scylladb-manager-3.0 stable InRelease
< t:2022-11-28 21:08:42,714 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D0A112E067426AB2
< t:2022-11-28 21:08:43,947 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Reading package lists...
< t:2022-11-28 21:08:44,448 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > W: GPG error: http://downloads.scylladb.com/downloads/scylla-manager/deb/ubuntu/scylladb-manager-3.0 stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D0A112E067426AB2
```

seems like manager 3.0 doesn't support the new type of signatures, hence this code can't be remove until we have a released version of manager that does support it.

**Comment by benipeled** [comment]
> > Verified with https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/artifacts/job/artifacts-ubuntu2004-test/94/
> > The job failed on missing scylla-manager package `Unable to locate package scylla-manager-agent` which has nothing with this change
> 
> The log disagree with you:
> 
> ```
> < t:2022-11-28 21:08:42,714 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Err:5 http://downloads.scylladb.com/downloads/scylla-manager/deb/ubuntu/scylladb-manager-3.0 stable InRelease
> < t:2022-11-28 21:08:42,714 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D0A112E067426AB2
> < t:2022-11-28 21:08:43,947 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Reading package lists...
> < t:2022-11-28 21:08:44,448 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > W: GPG error: http://downloads.scylladb.com/downloads/scylla-manager/deb/ubuntu/scylladb-manager-3.0 stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D0A112E067426AB2
> ```
> 

Where are these logs coming from? it doesn't appear on the Jenkins console of the job above 


> seems like manager 3.0 doesn't support the new type of signatures, hence this code can't be remove until we have a released version of manager that does support it.

We're using the same key on both gpg / apt-key and AFAIK manager 3.0 uses the newest key (D0A112E067426AB2)
am I missing something here?

**Comment by fruch** [comment]
> > > Verified with https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/artifacts/job/artifacts-ubuntu2004-test/94/
> > > The job failed on missing scylla-manager package `Unable to locate package scylla-manager-agent` which has nothing with this change
> > 
> > 
> > The log disagree with you:
> > ```
> > < t:2022-11-28 21:08:42,714 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Err:5 http://downloads.scylladb.com/downloads/scylla-manager/deb/ubuntu/scylladb-manager-3.0 stable InRelease
> > < t:2022-11-28 21:08:42,714 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D0A112E067426AB2
> > < t:2022-11-28 21:08:43,947 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Reading package lists...
> > < t:2022-11-28 21:08:44,448 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > W: GPG error: http://downloads.scylladb.com/downloads/scylla-manager/deb/ubuntu/scylladb-manager-3.0 stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D0A112E067426AB2
> > ```
> 
> Where are these logs coming from? it doesn't appear on the Jenkins console of the job above
if we'll print  all log to jenkins, it would crash...

sct full logs are downloadable, and you can get then looking the collect-logs phase - there are link to s3 they are stored in

> 
> > seems like manager 3.0 doesn't support the new type of signatures, hence this code can't be remove until we have a released version of manager that does support it.
> 
> We're using the same key on both gpg / apt-key and AFAIK manager 3.0 uses the newest key (D0A112E067426AB2) am I missing something here?

you tell me, why it's failing to pick up the manager repository.
but we can't merge if it's not working.

**Comment by fruch** [comment]
@benipeled 

in scylla master lists looks like this, i.e. pointing to a local key:
```
deb [arch=amd64,arm64 signed-by=/etc/apt/keyrings/scylladb.gpg] http://downloads.scylladb.com/unstable/scylla/master/deb/unified/2022-11-28T03:03:40Z/scylladb-master stable main
```

the manager 3.0: 
```
deb [arch=amd64,arm64] http://downloads.scylladb.com/manager/deb/unstable/unified-deb/branch-3.0/2022-05-23T15:13:11Z stable main
```

looks to me we'll need manager to be working in the same fashion as scylla, before we merge this change.

**Comment by benipeled** [comment]
tbh, I'm not sure we want to backport it to manager-3.0 - the release is GA (3.0.2 is releasing soon) and the potential damage isn't worth dealing with it,

Let's leave it as it is for now and change it in 3.1

**Comment by benipeled** [comment]
>

> > Yup, you're right, we need to backport [scylladb/scylla-pkg#3049](https://github.com/scylladb/scylla-pkg/pull/3049) and other required changes to the manager-3.0 branch to support this change, I'll take care of it.
> > It's good to see we have a great guard, thanks.
> 
> seems like 5.0/2022.1 doesn't have it
> 
> we need to wait for all active release to have it, before dropping it in SCT (since we test upgrade from those releases)

The change is added on Scylla >= 5.1 and Scylla-Enterprise >= 2022.2 only - we're not going to backport it to early versions

**Comment by roydahan** [comment]
@fruch / @benipeled is this PR still relevant?

**Comment by fruch** [comment]
> @fruch / @benipeled is this PR still relevant?

Yes and I think we can test it again. 

But with rolling upgrades, to validate the change arrived to all working branches

**Comment by k0machi** [comment]
continued in https://github.com/scylladb/scylla-cluster-tests/pull/6984

**Pull request closed without merging**
