### PR TITLE
set default gce_network to qa-vpc

### PR DESCRIPTION
**Pull request by amoskong**
We want to execute all tests inside the qa-vpc. The SCT builders also need
to be moved inside qa-vpc.

### CODE REVIEW

**Comment by roydahan** [comment]
let's hold it till we know how to move the builders to qa-vpc.

**Comment by amoskong** [comment]
I investigated yesterday, we can't directly switch the interface to qavpc
in stop state (I only saw once that the default can be deleted, it can't be
deleted right now).

However, we can execute the switch by cloning, I just cloned builder3 to
qavpc:
*- us-east1-b/instances/public-jenkins-builder3-qavpc*

On Wed, Dec 6, 2017 at 5:51 AM, Roy Dahan <notifications@github.com> wrote:

> let's hold it till we know how to move the builders to qa-vpc.
>
The right order should be:
- clone the builders to qavpc
- release static ip of old builders
- set static ip for clone builders
- test & apply this PR

**Comment by roydahan** [comment]
@amoskong, can we merge this one now?
Do we still want to merge it?
It means that it'll work only from builders...

**Comment by amoskong** [comment]
After merging this we can still use builders out of qavpc, we can use
sct_public_ip

Let me check if it's safe.

**Comment by roydahan** [comment]
OK, we need to communicate clearly to QA.
Also, I would like to make sure all jobs are using private IPs.

**Comment by amoskong** [comment]
We can merge this PR.

If we want to run SCT on instance out of qa-vpc and use gce_network: qa-vpc, we can add a sct_public_ip: xxxx to make nemesis metric works.

If we don't care about the nemesis metrict, we don't need to do anything.

**Comment by roydahan** [comment]
Are you sure?
I think that if you run it from a builder/laptop that isn't in 'qavpc' you'll have to specify gce_network='default' in your YAML.
Otherwise, the test won't proceed behind the step it tries to ssh the nodes...
I know the ports of ssh are open, but this is the current behaviour I saw.

**Comment by amoskong** [comment]
On Mon, Mar 5, 2018 at 10:57 PM, Roy Dahan <notifications@github.com> wrote:

> Are you sure?
> I think that if you run it from a builder/laptop that isn't in 'qavpc'
> you'll have to specify gce_network='default' in your YAML.
> Otherwise, the test won't proceed behind the step it tries to ssh the
> nodes...
>
It doesn't work if ip_ssh_connections is set to `private`, but works for
default public.

> I know the ports of ssh are open, but this is the current behaviour I saw.
>

**Comment by amoskong** [comment]
If we still want to run sct on machine outside qa-vpc, use `private` for `ssh connections`, and we want the test nodes use qa-vpc network. Then it doesn't work.

Conclusion：so if we want to use qa-vpc for test nodes, and private ssh connections, then we `have to` use builders insider qa-vpc.

The Conclusion is current situation, applying the PR or not won't effect this situation.

BTW, can we accept the tests (especial for perf tests) use public ip for ssh connections?

**Comment by roydahan** [comment]
Right, but this PR changes the default network to qavpc.
In case someone run a test from outside qavpc, he can just use the "default" network and it should work.
(IOW we can merge this, but need to warn the team).

Regardless of this PR, default of all should be private IP and remove all public IP from YAMLs.

**Comment by amoskong** [comment]
Talked with Roy, let's close this PR. we don't need to change default gce_network to qa-vpc right now.

**Pull request closed without merging**
