### PR TITLE
fix(managerPipeline): rearanged param order

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fgelcer — CHANGES_REQUESTED** [review]
why such change? it doesn't seem to affect anything, but the reader eyes.
if there is a reason for that, it must be specified in the commit message.

**Comment by ShlomiBalalis** [comment]
> why such change? it doesn't seem to affect anything, but the reader eyes. if there is a reason for that, it must be specified in the commit message.

It's only for the readers eyes.
It's because even I sometimes mix them up. Now the order makes sense:
* server url
* agent url
* manager version number
* target server url
* target agent url
* target manager version number


As opposed to:
* server url
* manager version number
* target manager version number
* agent url
* target server url
* target agent url

**Comment by fgelcer** [comment]
> > why such change? it doesn't seem to affect anything, but the reader eyes. if there is a reason for that, it must be specified in the commit message.
> 
> It's only for the readers eyes. It's because even I sometimes mix them up. Now the order makes sense:
> 
> * server url
> * agent url
> * manager version number
> * target server url
> * target agent url
> * target manager version number
> 
> As opposed to:
> 
> * server url
> * manager version number
> * target manager version number
> * agent url
> * target server url
> * target agent url

if you think it will be very important (reading code IS very important), so add this explanation in the commit message.

**Review by rayakurl — COMMENTED** [review]
I approve the change if it makes more sense to you. But why the  target_manager_version is not below_manger_version ?

**Review by rayakurl — APPROVED** [review]

**Comment by fruch** [comment]
> @ShlomiBalalis now you have a conflict to solve here, also see @fgelcer comment about the commit message.

@ShlomiBalalis ? you still need this PR ?

**Pull request closed without merging**
