### PR TITLE
archive SCT logs to jenkins server

### PR DESCRIPTION
**Pull request by amoskong**
The logs can be viewed on Jenkins webpage, it supports to download of
compressed sub directory.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@amoskong what's wrong with the logs we upload to s3 ? (i.e. the space on jenkins master is a bit limited)

**Comment by bentsi** [comment]
releng is implementing this on their end by @roydahan request. @amoskong please consult before implementing solutions

**Comment by amoskong** [comment]
> releng is implementing this on their end by @roydahan request. @amoskong please consult before implementing solutions

It's TOO crude to close PR without waiting for the discussion.
As you said it's a different solution, no matter it's better or worse.

When I thought it's a problem, I post a PR without opening an issue / trello ticket, or waiting someone get  back from vacation. It's the quick and simple way.

**Comment by amoskong** [comment]
> @amoskong what's wrong with the logs we upload to s3 ? (i.e. the space on jenkins master is a bit limited)

It might be the same reason that why Roy asked releng to archive logs in their end.
I agree uploading to s3 is helpful, it can be an additional solution, but not replacing jenkins log at all.

The logs can be viewed on Jenkins webpage, it supports to download of
compressed sub directory. The log archiving is done by Jenkins, not SCT itself, so it's more stable.

Jenkins space issue is another problem, we can clean it in short period.

**Comment by fruch** [comment]
@roydahan are you o.k. with backporting this to 3.1 ?

**Pull request merged**
