### PR TITLE
longevity-100gb-4h-ReplaceNode.yaml: Make each replace takes longer

### PR DESCRIPTION
**Pull request by asias**
longevity-100gb-4h-ReplaceNode.yaml: Make each replace takes longer
    
- Reduce the nodes from 6 to 4
    
- Increase dataset from 100GB to 300GB

### CODE REVIEW

**Comment by asias** [comment]
@roydahan  FYI.

**Comment by roydahan** [comment]
@asias please send the PR to the rbno branch on my fork and not scylla-master.

**Comment by roydahan** [comment]
Nevermind, I pushed the branch to scylladb and changed the target here.

**Review by roydahan — APPROVED** [review]

**Comment by asias** [comment]
I saw you merged it. Is it ready to start jenkins jobs now?

**Comment by roydahan** [comment]
No, wait.
I just realized I need to change the job to run from scylladb and not from
my fork.

**Pull request merged**
