### PR TITLE
Bloom filter read validation

### PR DESCRIPTION
**Pull request by fgelcer**
PR used only to share code and hold a discussion on the run and results

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
@raphaelsc , started a [run here](https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/responsive_computing/job/read_decommission/2/)

in like 20 - 30 min we will have already access to the monitor node, and in like 3 - 4 hours (i believe) we will have the data prepare done

**Comment by raphaelsc** [comment]
> @raphaelsc , started a [run here](https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/responsive_computing/job/read_decommission/2/)
> 
> in like 20 - 30 min we will have already access to the monitor node, and in like 3 - 4 hours (i believe) we will have the data prepare done

great thanks a lot Fabio!

**Comment by yaronkaikov** [comment]
https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/ for building Scylla and AMI

**Comment by fgelcer** [comment]
> https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/ for building Scylla and AMI

@yaronkaikov , i ended up using this job, and the "build" phase passed, but the AMI failed:
https://jenkins.scylladb.com/job/enterprise-2022.2/job/byo/job/byo_build_tests_dtest/23/

can you please advise?

**Comment by yaronkaikov** [comment]
> > https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/ for building Scylla and AMI
> 
> @yaronkaikov , i ended up using this job, and the "build" phase passed, but the AMI failed: https://jenkins.scylladb.com/job/enterprise-2022.2/job/byo/job/byo_build_tests_dtest/23/
> 
> can you please advise?

Known issue we already solved in master, backport the fix to all branches and now https://jenkins.scylladb.com/job/enterprise-2022.2/job/byo/job/byo_build_tests_dtest/24/ is running, it suppose to pass LMK if it doesn't

**Comment by yaronkaikov** [comment]
> > > https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/ for building Scylla and AMI
> > 
> > 
> > @yaronkaikov , i ended up using this job, and the "build" phase passed, but the AMI failed: https://jenkins.scylladb.com/job/enterprise-2022.2/job/byo/job/byo_build_tests_dtest/23/
> > can you please advise?
> 
> Known issue we already solved in master, backport the fix to all branches and now https://jenkins.scylladb.com/job/enterprise-2022.2/job/byo/job/byo_build_tests_dtest/24/ is running, it suppose to pass LMK if it doesn't

This is the commit 

```
commit 6ff3f38188ba86ade31c6e1f10ff2498c60435d3 (HEAD -> next-2022.2, origin/next-2022.2)
Author: Takuya ASADA <syuu@scylladb.com>
Date:   Thu Oct 19 05:05:37 2023 +0900

    aws: use yaml module for cloud.cfg
    
    On latest master, re.sub() is failing since regex pattern is not matched
    with cloud.cfg on latest Ubuntu image.
    To avoid such problem, we should use yaml module instead.
    
    (cherry picked from commit ab113a85a6a19c52d5d35eb3979d64168e578ea5)
```

**Comment by yaronkaikov** [comment]
> > > > https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/ for building Scylla and AMI
> > > 
> > > 
> > > @yaronkaikov , i ended up using this job, and the "build" phase passed, but the AMI failed: https://jenkins.scylladb.com/job/enterprise-2022.2/job/byo/job/byo_build_tests_dtest/23/
> > > can you please advise?
> > 
> > 
> > Known issue we already solved in master, backport the fix to all branches and now https://jenkins.scylladb.com/job/enterprise-2022.2/job/byo/job/byo_build_tests_dtest/24/ is running, it suppose to pass LMK if it doesn't
> 
> This is the commit
> 
> ```
> commit 6ff3f38188ba86ade31c6e1f10ff2498c60435d3 (HEAD -> next-2022.2, origin/next-2022.2)
> Author: Takuya ASADA <syuu@scylladb.com>
> Date:   Thu Oct 19 05:05:37 2023 +0900
> 
>     aws: use yaml module for cloud.cfg
>     
>     On latest master, re.sub() is failing since regex pattern is not matched
>     with cloud.cfg on latest Ubuntu image.
>     To avoid such problem, we should use yaml module instead.
>     
>     (cherry picked from commit ab113a85a6a19c52d5d35eb3979d64168e578ea5)
> ```

@fgelcer Job passed

**Comment by fgelcer** [comment]
finally we have this job running

**Comment by raphaelsc** [comment]
> finally we have this job running

@fgelcer Hello. could you please provide a link with the status?

**Comment by fgelcer** [comment]
> > finally we have this job running
> 
> @fgelcer Hello. could you please provide a link with the status?

[here is the test](https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/responsive_computing/job/read_decommission/8/) run (but it failed).. i didn't open the logs to investigate it, but it ran for more than a full day, so we may have partial results

**Pull request closed without merging**
