### PR TITLE
fix(docker-backend): start Scylla server as 'scylla' user

### PR DESCRIPTION
**Pull request by dimakr**
In docker backend environment the scylla services are controlled by supervisord.
At the moment the scylla services configuration files in Docker images do not have
user attribute specified (opposite to backends where systemd controls the processes -
there the user is explicitly specified in systemd unit files).
As a result the file permissions of data that the services create are of a user
that starts the processes. In the tests it is usually root user.
Some Nemesis scenarios, when are executed for Docker backend, try to update scylla data on behalf
of 'scylla-test' user and fail with 'permission denied' error.

The change sets the user attribute in scylla-sct Docker files, to explicitly run scylla
services on behalf of 'scylla' user.
It also reverts few changes introduced in the past, where calls of node.remoter.run
method were done differently for Docker backend runs, compared to other backends,
because of the described issue.

The change fixes https://github.com/scylladb/scylla-cluster-tests/issues/6962.

### Testing
The change was tested by executing Nemeses that were previously failing on Docker backend during disruption
with 'permission denied' error, due to the described issue.
With the applied fix the Nemeses are passing:
[LoadAndStreamMonkey on Docker backend](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/dimakr/job/longevity-5gb-1h-docker-test/43/)
[RefreshMonkey on Docker backend](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/dimakr/job/longevity-5gb-1h-docker-test/44/)
[RefreshBigMonkey on Docker backend](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/dimakr/job/longevity-5gb-1h-docker-test/45/)

### PR pre-checks (self review)
- [ ] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders
- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@dimakr 

this looks good, but I think it might break the k8s support, work with @vponomaryov to see how to try it out on k8s base jobs.

**Review by juliayakovlev — APPROVED** [review]
Looks OK, if it will not break k8s, as Israel mentioned

**Comment by vponomaryov** [comment]
> @dimakr
> 
> this looks good, but I think it might break the k8s support, work with @vponomaryov to see how to try it out on k8s base jobs.

K8S doesn't use anything from the `docker/scylla-sct/*` path.
Also, `*.py` files change logic only for the docker backend.
So, it doesn't look harmful for K8S backends.

**Review by vponomaryov — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
> > @dimakr
> > 
> > this looks good, but I think it might break the k8s support, work with @vponomaryov to see how to try it out on k8s base jobs.
> 
> K8S doesn't use anything from the `docker/scylla-sct/*` path.
> Also, `*.py` files change logic only for the docker backend.
> So, it doesn't look harmful for K8S backends.

The logic is based on is_docker that was removed here, I think it might not work on k8s, since it won't be running on scylla user.

I think it should be tested to confirm

**Comment by vponomaryov** [comment]
> > > @dimakr
> > > this looks good, but I think it might break the k8s support, work with @vponomaryov to see how to try it out on k8s base jobs.
> > 
> > 
> > K8S doesn't use anything from the `docker/scylla-sct/*` path.
> > Also, `*.py` files change logic only for the docker backend.
> > So, it doesn't look harmful for K8S backends.
> 
> The logic is based on is_docker that was removed here, I think it might not work on k8s, since it won't be running on scylla user.
> 
> I think it should be tested to confirm

The changed functionality is covered by the `test_nodetool_drain` K8S functional test which uses `stop_scylla_server` and `start_scylla_server` methods. These methods, on it's turn, call the `wait_db_up` method and that one calls the `_report_housekeeping_uuid` which is changed here.

I ran this test locally having the `is_docker = False` and this test passed:
```
functional_tests/scylla_operator/test_functional.py::test_nodetool_drain < t:2024-04-15 11:21:56,624 f:base.py         l:369  c:sdcm.sct_events.base p:INFO  > The run can be interrupted by following critical events:
...
2024-04-15 11:25:37,024 f:remote_base.py  l:521  c:KubernetesCmdRunner  p:DEBUG > Running command "test -e /var/lib/scylla-housekeeping/housekeeping.uuid.marked"...
2024-04-15 11:25:37,094 f:remote_base.py  l:521  c:KubernetesCmdRunner  p:DEBUG > Running command "test -e /var/lib/scylla-housekeeping/housekeeping.uuid"...
2024-04-15 11:25:37,166 f:base.py         l:142  c:KubernetesCmdRunner  p:DEBUG > Command "test -e /var/lib/scylla-housekeeping/housekeeping.uuid" finished with status 0
2024-04-15 11:25:37,167 f:remote_base.py  l:521  c:KubernetesCmdRunner  p:DEBUG > Running command "cat /var/lib/scylla-housekeeping/housekeeping.uuid"...
2024-04-15 11:25:37,264 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > af59b0a8-eed7-11ee-bd28-329efe786b5f
2024-04-15 11:25:37,275 f:base.py         l:142  c:KubernetesCmdRunner  p:DEBUG > Command "cat /var/lib/scylla-housekeeping/housekeeping.uuid" finished with status 0
2024-04-15 11:25:37,275 f:remote_base.py  l:521  c:KubernetesCmdRunner  p:DEBUG > Running command "curl "https://i6a5h9l1kl.execute-api.us-east-1.amazonaws.com/prod/check_version?uu=af59b0a8-eed7-11ee-bd28-329efe786b5f&mark=scylla""...
2024-04-15 11:25:37,418 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2024-04-15 11:25:37,418 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG >                                  Dload  Upload   Total   Spent    Left  Speed
2024-04-15 11:25:38,291 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > ^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M100     2  100     2    0     0      2      0  0:00:01 --:--:--  0:00:01     2^M100     2  100           2    0     0      2      0  0:00:01 --:--:--  0:00:01     2
2024-04-15 11:25:38,313 f:base.py         l:140  c:KubernetesCmdRunner  p:DEBUG > STDERR:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2024-04-15 11:25:38,313 f:base.py         l:140  c:KubernetesCmdRunner  p:DEBUG >                                  Dload  Upload   Total   Spent    Left  Speed
2024-04-15 11:25:38,313 f:base.py         l:140  c:KubernetesCmdRunner  p:DEBUG >               
2024-04-15 11:25:38,313 f:base.py         l:140  c:KubernetesCmdRunner  p:DEBUG >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2024-04-15 11:25:38,313 f:base.py         l:140  c:KubernetesCmdRunner  p:DEBUG > 100     2  100     2    0     0      2      0  0:00:01 --:--:--  0:00:01     2
2024-04-15 11:25:38,313 f:base.py         l:140  c:KubernetesCmdRunner  p:DEBUG > 100     2  100     2    0     0      2      0  0:00:01 --:--:--  0:00:01     2
2024-04-15 11:25:38,314 f:base.py         l:142  c:KubernetesCmdRunner  p:DEBUG > Command "curl "https://i6a5h9l1kl.execute-api.us-east-1.amazonaws.com/prod/check_version?uu=af59b0a8-eed7-11ee-bd28-329efe786b5f&mark=scylla"" finished with status 0
2024-04-15 11:25:38,597 f:kubernetes_cmd_runner.py l:206  c:KubernetesCmdRunner  p:ERROR > Cut off `sudo' from the cmd string: sudo -u scylla touch /var/lib/scylla-housekeeping/housekeeping.uuid.marked (/home/kiparis/projects/scylla-cluster-tests/sdcm/remote/remote_base.py:605:                 return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers))
2024-04-15 11:25:38,597 f:remote_base.py  l:521  c:KubernetesCmdRunner  p:DEBUG > Running command "touch /var/lib/scylla-housekeeping/housekeeping.uuid.marked"...
2024-04-15 11:25:38,702 f:base.py         l:142  c:KubernetesCmdRunner  p:DEBUG > Command "touch /var/lib/scylla-housekeeping/housekeeping.uuid.marked" finished with status 0
2024-04-15 11:25:38,702 f:decorators.py   l:121  c:sdcm.utils.decorators p:DEBUG > END: start_scylla_server <LocalMinimalScyllaPodContainer> (ran 63.505113s)
...
```

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
