### PR TITLE
fix(install_scylla_bench): make it work

### PR DESCRIPTION
**Pull request by dkropachev**
https://trello.com/c/oyVqoA0S/4549-fix-scylla-bench-installation

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Review by enaydanov — APPROVED** [review]

**Review by vponomaryov — APPROVED** [review]

**Review by vponomaryov — APPROVED** [review]

**Comment by fruch** [comment]
@dkropachev you are sure this fix doesn't need to go to 4.6 ? (rest of the recent scylla bench changes are there)

**Comment by dkropachev** [comment]
> @dkropachev you are sure this fix doesn't need to go to 4.6 ? (rest of the recent scylla bench changes are there)

We are doing FF on it, so eventuall it will end up there.

**Comment by fruch** [comment]
> > @dkropachev you are sure this fix doesn't need to go to 4.6 ? (rest of the recent scylla bench changes are there)
> 
> We are doing FF on it, so eventuall it will end up there.

AFAIK we halted the FF, waiting for confirmation that the new AWS loaders are stable enough)

**Comment by fgelcer** [comment]
> AFAIK we halted the FF, waiting for confirmation that the new AWS loaders are stable enough)

my run with loader-v17 seemed good, and the issue (what caused us to spin off new loader) wasn't reproduced...

**Comment by fruch** [comment]
> > AFAIK we halted the FF, waiting for confirmation that the new AWS loaders are stable enough)
> 
> my run with loader-v17 seemed good, and the issue (what caused us to spin off new loader) wasn't reproduced...

that's o.k. but we'll still need to clear it with @roydahan, depends on the current state of 4.6 testing.

**Review by enaydanov — APPROVED** [review]

**Pull request merged**
