### PR TITLE
test(functional): docker functional test with SctConfiguration

### PR DESCRIPTION
**Pull request by fruch**
since now all those docker based tests are reading the docker
images from configuration, it should have the default configuration
to get any of the docker images

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by soyacz — COMMENTED** [review]
@fruch can you split commits where logic was changed from formatting change?

**Comment by fruch** [comment]
> @fruch can you split commits where logic was changed from formatting change?

yeah, (it was done with black anyhow)

**Comment by fruch** [comment]
> > @fruch can you split commits where logic was changed from formatting change?
> 
> yeah, (it was done with black anyhow)

now it's separated

**Review by soyacz — APPROVED** [review]
LGTM

**Review by vponomaryov — APPROVED** [review]

**Pull request merged**
