### PR TITLE
fix(common:get_branched_ami): filter out debug-* AMIs

### PR DESCRIPTION
**Pull request by yaronkaikov**
Following the changes in https://github.com/scylladb/scylla-machine-image/pull/383 , need to update the filter with new prefix

**to merge only after https://github.com/scylladb/scylla-machine-image/pull/383**

### CODE REVIEW

**Review by fruch — COMMENTED** [review]
LGTM

**Review by soyacz — APPROVED** [review]

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by yaronkaikov** [comment]
@soyacz Can you merge this please ?

**Comment by soyacz** [comment]
@yaronkaikov will it affect other branches, like 5.0/2022.1 ?

**Comment by yaronkaikov** [comment]
@soyacz no, only future branches

**Pull request merged**
