### PR TITLE
feature(hydra on MacOS): Add support to run hydra on MacOS

### PR DESCRIPTION
**Pull request by roydahan**
In order to be able to run hydra docker on MacOS using docker desktop, there is a need to mount the docker.sock differently and not trying to impersonate the running user to be able to run inside the docker. This is a problem with the macOS permissions. instead we run as 'root' and mouting the homedir of the user as HOME.

### Testing

- [ ]

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
Tested it on my Mac (M3) and it worked, but I need someone to test it on ubuntu/fedora with docker and podman to make sure I didn't break them.

**Comment by roydahan** [comment]
@soyacz / @vponomaryov possibly you can help with testing it on your local machines and validate I didn't break hydra and podman for linux

**Review by vponomaryov — APPROVED** [review]
Ubuntu22 on core i7 works ok:

```
$ ./docker/env/hydra.sh unit-tests -t test_utils_common.py
There is scylladb/hydra:v1.77-argus-0.12.10 in local cache, using it.
Going to run './sct.py  unit-tests -t test_utils_common.py'...
/usr/local/lib/python3.10/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/usr/local/lib/python3.10/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
logged in as arn:aws:iam::797456418907:user/qa
============================================================================================================================ test session starts =============================================================================================================================
platform linux -- Python 3.10.12, pytest-7.2.0, pluggy-1.5.0 -- /usr/local/bin/python3
cachedir: .pytest_cache
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
rootdir: %path-to%/scylla-cluster-tests/unit_tests, configfile: pytest.ini
plugins: random-order-1.0.4, typeguard-4.3.0
collected 10 items                                                                                                                                                                                                                                                           

unit_tests/test_utils_common.py::TestUtils::test_scylla_bench_metrics_conversion PASSED                                                                                                                                                                                [ 10%]
unit_tests/test_utils_common.py::TestDownloadDir::test_update_db_packages_gce PASSED                                                                                                                                                                                   [ 20%]
unit_tests/test_utils_common.py::TestDownloadDir::test_update_db_packages_none PASSED                                                                                                                                                                                  [ 30%]
unit_tests/test_utils_common.py::TestDownloadDir::test_update_db_packages_s3 PASSED                                                                                                                                                                                    [ 40%]
unit_tests/test_utils_common.py::TestSstableLoadUtils::test_distribute_test_files_to_cluster_nodes PASSED                                                                                                                                                              [ 50%]
unit_tests/test_utils_common.py::TestSstableLoadUtils::test_load_and_stream_waits_for_log_lines PASSED                                                                                                                                                                 [ 60%]
unit_tests/test_utils_common.py::TestSstableLoadUtils::test_load_column_1_data_inventory PASSED                                                                                                                                                                        [ 70%]
unit_tests/test_utils_common.py::TestSstableLoadUtils::test_load_load_and_stream_data_inventory PASSED                                                                                                                                                                 [ 80%]
unit_tests/test_utils_common.py::TestSstableLoadUtils::test_load_multi_column_data_inventory PASSED                                                                                                                                                                    [ 90%]
unit_tests/test_utils_common.py::TestSstableLoadUtils::test_load_not_supported_data_inventory PASSED                                                                                                                                                                   [100%]

============================================================================================================================ slowest 20 durations ============================================================================================================================
0.82s call     test_utils_common.py::TestDownloadDir::test_update_db_packages_s3
0.70s call     test_utils_common.py::TestDownloadDir::test_update_db_packages_gce
0.05s setup    test_utils_common.py::TestSstableLoadUtils::test_distribute_test_files_to_cluster_nodes

(17 durations < 0.005s hidden.  Use -vv to show these durations.)
============================================================================================================================= 10 passed in 1.60s =============================================================================================================================

$ git show HEAD
commit 3403713124578bbb6dcc61007822a25c4cf6b267 (HEAD, roydahan/docker-mac)
Author: Roy Dahan <roy@scylladb.com>
Date:   Mon Oct 14 17:08:45 2024 +0300

    feature(hydra on MacOS): Add support to run hydra on MacOS
    
    In order to be able to run hydra docker on MacOS using docker desktop,
    there is a need to mount the docker.sock differently and not trying
    to impersonate the running user to be able to run inside the docker.
    This is a problem with the macOS permissions. instead we run as 'root'
    and mouting the homedir of the user as HOME.
```

**Comment by soyacz** [comment]
I tried with unit tests (all) and it worked. 
I tried also running simple PR-provision test and also ran without an issue. 
Used docker - I don't have podman installed.

**Pull request merged**
