### PR TITLE
fix(disk-and-cache): use ssh transport for logs

### PR DESCRIPTION
**Pull request by aleksbykov**
Use ssh transport for logs for disk-and-cache
performance tests

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by aleksbykov** [comment]
@roydahan could you merge this PR to branch-perf-v12 only

**Comment by fgelcer** [comment]
@aleksbykov , it would be nice to understand why you need to change it... a bit more context helps to understand the change (even if a simple one)

**Review by fgelcer — APPROVED** [review]
other than the comment above, LGTM

**Comment by aleksbykov** [comment]
> it would be nice to understand why you need to change it... a bit more context helps to understand the change (even if a simple one)

@fabio, i checked the job status and the latest succesful run was from 6.11.2022. after that we switch ubuntu-22.04. 
Job failed because runner can't get the logs from nodes. i think, we don' backport syslog-ng to perf-v12, and runner continue use the rsyslog which is removed by default from ubuntu-22.04. Other jobs regular throughput, latency, latency with nemesis was switched to used log_transport ssh. 
i switch old job to use my pr, and now it is running

**Comment by vponomaryov** [comment]
> > it would be nice to understand why you need to change it... a bit more context helps to understand the change (even if a simple one)
> 
> @fabio, i checked the job status and the latest succesful run was from 6.11.2022. after that we switch ubuntu-22.04. Job failed because runner can't get the logs from nodes. i think, we don' backport syslog-ng to perf-v12, and runner continue use the rsyslog which is removed by default from ubuntu-22.04. Other jobs regular throughput, latency, latency with nemesis was switched to used log_transport ssh. i switch old job to use my pr, and now it is running

Please, write it in the commit message so it could appear in the git commit history and spill the light for the root cause.

**Review by roydahan — APPROVED** [review]

**Comment by roydahan** [comment]
It's a merge to an old branch that is going to die soon.

**Pull request merged**
