### PR TITLE
workaround: Install the python36 version of PyYAML

### PR DESCRIPTION
**Pull request by amoskong**
Reference:
https://docs.scylladb.com/troubleshooting/python-error-no-module-named-yaml/

### CODE REVIEW

**Comment by bentsi** [comment]
do we need to backport it to other branches?

**Comment by amoskong** [comment]
Yes.

**Comment by amoskong** [comment]
Update:

We don't need this workaround for SCT master.
scylla-master uses relocated python3, the `No module named 'yaml'` problem doesn't exist with scylla-master.

So this patch needs to be applied to sct 3.0, and backport to 2019.1

**Comment by amoskong** [comment]
2.3 private repo test will trigger artifact-test and rolling upgrade test (SCT)
- http://jenkins.cloudius-systems.com:8080/job/scylla-2.3/job/2.3-test/job/scylla-2.3-rolling-upgrade-centos-test/173/
- so this PR needs to be backported to branch-2.3

**Comment by roydahan** [comment]
I think it's not needed anymore.
Problem is solved.
@amoskong please confirm and close.

**Comment by amoskong** [comment]
We quickly have a simple fix (https://github.com/scylladb/scylla/commit/6e51a95668b16ac1c6fc41d8d6310c65e80bdefb). At least it fixed the `ModuleNotFoundError` in scylla installation/scylla_setup/scylla_prepare.

Latest 2019.1 rpm already contains this fix, so we don't need this workaround to generate test AMI.

Then we don't need this workaround in SCT & artifact-test.  Thanks.

**Pull request closed without merging**
