### PR TITLE
fix(nemeses): do not run SLA nemeses if authenticator is not defined

### PR DESCRIPTION
**Pull request by juliayakovlev**
SLA feature need that cluster will be configured with authenticator. Not all our longevities run with authenticator. So we need to filter out SLA nemeses.

Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/5793

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@juliayakovlev you have a job that you tested this one with ?

**Review by fruch — DISMISSED** [review]
LGTM

**Comment by fruch** [comment]
@juliayakovlev 

Seems like this won't be enough, please disable this nemesis in same way as the first based on the longevity shares params:
https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-1tb-7days-test/4

This blocking the release

**Comment by juliayakovlev** [comment]
> @juliayakovlev
> 
> Seems like this won't be enough, please disable this nemesis in same way as the first based on the longevity shares params: https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-1tb-7days-test/4
> 
> This blocking the release

@fruch 
Why do you think it is not enough?
I run test and it passed:

```
2023-02-09 19:27:06.923: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=bec899d5-f4eb-4963-93b8-f70156a8d397: nemesis_name=SlaDecreaseSharesDuringLoad target_node=Node longevity-10gb-3h-test-pr--db-node-15007804-3 [16.170.157.156 | 10.0.2.169] (seed: False)
2023-02-09 19:27:08.606: (DisruptionEvent Severity.NORMAL) period_type=end event_id=bec899d5-f4eb-4963-93b8-f70156a8d397 duration=1s: nemesis_name=SlaDecreaseSharesDuringLoad target_node=Node longevity-10gb-3h-test-pr--db-node-15007804-3 [16.170.157.156 | 10.0.2.169] (seed: False) skipped skip_reason=SLA feature can't work without authenticator

023-02-09 19:28:14.769: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=73258827-8837-4a6b-bb60-83c1a822c1d8: nemesis_name=IncreaseSharesByAttachAnotherSlDuringLoad target_node=Node longevity-10gb-3h-test-pr--db-node-15007804-2 [16.170.227.141 | 10.0.3.167] (seed: False)
2023-02-09 19:28:16.401: (DisruptionEvent Severity.NORMAL) period_type=end event_id=73258827-8837-4a6b-bb60-83c1a822c1d8 duration=1s: nemesis_name=IncreaseSharesByAttachAnotherSlDuringLoad target_node=Node longevity-10gb-3h-test-pr--db-node-15007804-2 [16.170.227.141 | 10.0.3.167] (seed: False) skipped skip_reason=SLA feature can't work without authenticator
```


https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/staging-10gb-3h/343/

**Comment by fruch** [comment]
> > @juliayakovlev
> > 
> > Seems like this won't be enough, please disable this nemesis in same way as the first based on the longevity shares params: https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-1tb-7days-test/4
> > 
> > This blocking the release
> 
> @fruch 
> Why do you think it is not enough?
> I run test and it passed:
> 
> ```
> 2023-02-09 19:27:06.923: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=bec899d5-f4eb-4963-93b8-f70156a8d397: nemesis_name=SlaDecreaseSharesDuringLoad target_node=Node longevity-10gb-3h-test-pr--db-node-15007804-3 [16.170.157.156 | 10.0.2.169] (seed: False)
> 2023-02-09 19:27:08.606: (DisruptionEvent Severity.NORMAL) period_type=end event_id=bec899d5-f4eb-4963-93b8-f70156a8d397 duration=1s: nemesis_name=SlaDecreaseSharesDuringLoad target_node=Node longevity-10gb-3h-test-pr--db-node-15007804-3 [16.170.157.156 | 10.0.2.169] (seed: False) skipped skip_reason=SLA feature can't work without authenticator
> 
> 023-02-09 19:28:14.769: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=73258827-8837-4a6b-bb60-83c1a822c1d8: nemesis_name=IncreaseSharesByAttachAnotherSlDuringLoad target_node=Node longevity-10gb-3h-test-pr--db-node-15007804-2 [16.170.227.141 | 10.0.3.167] (seed: False)
> 2023-02-09 19:28:16.401: (DisruptionEvent Severity.NORMAL) period_type=end event_id=73258827-8837-4a6b-bb60-83c1a822c1d8 duration=1s: nemesis_name=IncreaseSharesByAttachAnotherSlDuringLoad target_node=Node longevity-10gb-3h-test-pr--db-node-15007804-2 [16.170.227.141 | 10.0.3.167] (seed: False) skipped skip_reason=SLA feature can't work without authenticator
> ```
> 
> 
> https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/staging-10gb-3h/343/

Look at the results of 1tb case on 2023.1:
```
2023-02-10 01:29:47.837: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=f156e771-e484-4acb-a35a-bd8c27a26bee during_nemesis=SlaIncreaseSharesDuringLoad: type=IOException regex=java\.io\.IOException line_number=1083 node=Node longevity-tls-1tb-7d-2023-1-loader-node-f9243157-1 [16.16.27.104 | 10.0.3.129] (seed: False)
java.io.IOException: Operation x51 on key(s) [374f324e363531323730]: Error executing: (UnauthorizedException): User role500_4d3df4a6 has no SELECT permission on <table keyspace1.standard1> or any of its parents
```

**Comment by soyacz** [comment]
> > > @juliayakovlev
> > > Seems like this won't be enough, please disable this nemesis in same way as the first based on the longevity shares params: https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-1tb-7days-test/4
> > > This blocking the release
> > 
> > 
> > @fruch
> > Why do you think it is not enough?
> > I run test and it passed:
> > ```
> > 2023-02-09 19:27:06.923: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=bec899d5-f4eb-4963-93b8-f70156a8d397: nemesis_name=SlaDecreaseSharesDuringLoad target_node=Node longevity-10gb-3h-test-pr--db-node-15007804-3 [16.170.157.156 | 10.0.2.169] (seed: False)
> > 2023-02-09 19:27:08.606: (DisruptionEvent Severity.NORMAL) period_type=end event_id=bec899d5-f4eb-4963-93b8-f70156a8d397 duration=1s: nemesis_name=SlaDecreaseSharesDuringLoad target_node=Node longevity-10gb-3h-test-pr--db-node-15007804-3 [16.170.157.156 | 10.0.2.169] (seed: False) skipped skip_reason=SLA feature can't work without authenticator
> > 
> > 023-02-09 19:28:14.769: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=73258827-8837-4a6b-bb60-83c1a822c1d8: nemesis_name=IncreaseSharesByAttachAnotherSlDuringLoad target_node=Node longevity-10gb-3h-test-pr--db-node-15007804-2 [16.170.227.141 | 10.0.3.167] (seed: False)
> > 2023-02-09 19:28:16.401: (DisruptionEvent Severity.NORMAL) period_type=end event_id=73258827-8837-4a6b-bb60-83c1a822c1d8 duration=1s: nemesis_name=IncreaseSharesByAttachAnotherSlDuringLoad target_node=Node longevity-10gb-3h-test-pr--db-node-15007804-2 [16.170.227.141 | 10.0.3.167] (seed: False) skipped skip_reason=SLA feature can't work without authenticator
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/staging-10gb-3h/343/
> 
> Look at the results of 1tb case on 2023.1, Those errors leads to critical events that stop the test, we need to disable it
> 
> ```
> 2023-02-10 01:29:47.837: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=f156e771-e484-4acb-a35a-bd8c27a26bee during_nemesis=SlaIncreaseSharesDuringLoad: type=IOException regex=java\.io\.IOException line_number=1083 node=Node longevity-tls-1tb-7d-2023-1-loader-node-f9243157-1 [16.16.27.104 | 10.0.3.129] (seed: False)
> java.io.IOException: Operation x51 on key(s) [374f324e363531323730]: Error executing: (UnauthorizedException): User role500_4d3df4a6 has no SELECT permission on <table keyspace1.standard1> or any of its parents
> ```

@juliayakovlev to be more precise, 1tb case is having set `authenticator` param - therefore it would anyway select this nemesis and fail.

**Comment by juliayakovlev** [comment]
@fruch @soyacz 
Looks like the difference is `authorizer`.
SLA tests has `authorizer: 'ScyllaAuthorizer'`
All other tests: `authorizer: 'CassandraAuthorizer'`

I am adding 'SUPERUSER' to the test roles

**Comment by soyacz** [comment]
> @fruch @soyacz Looks like the difference is `authorizer`. SLA tests has `authorizer: 'ScyllaAuthorizer'` All other tests: `authorizer: 'CassandraAuthorizer'`
> 
> I am adding 'SUPERUSER' to the test roles

I don't understand why. Wasn't it working already?
In your staging job you used `test-cases/longevity/longevity-10gb-3h.yaml` which is not setting authenticator param at all - thus is passing.
In many longevities we set up `AllowAllAuthenticator` which is the same - but it will result False in `if not self.cluster.params.get('authenticator'):` thus failing the test.

**Comment by juliayakovlev** [comment]
> @juliayakovlev
> 
> Seems like this won't be enough, please disable this nemesis in same way as the first based on the longevity shares params: https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-1tb-7days-test/4
> 
> This blocking the release

@soyacz 
As @fruch reported here, cassandra-stress load failed during `longevity-1tb-7days-test` due to role lack permissions:
```
2023-02-10 01:29:47.837: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=f156e771-e484-4acb-a35a-bd8c27a26bee during_nemesis=SlaIncreaseSharesDuringLoad: type=IOException regex=java\.io\.IOException line_number=1083 node=Node longevity-tls-1tb-7d-2023-1-loader-node-f9243157-1 [16.16.27.104 | 10.0.3.129] (seed: False)
java.io.IOException: Operation x51 on key(s) [374f324e363531323730]: Error executing: (UnauthorizedException): User role500_4d3df4a6 has no SELECT permission on <table keyspace1.standard1> or any of its parents
```

The difference between SLA and 1Tb tests is `authorizer`:
SLA tests has `authorizer: 'ScyllaAuthorizer'`
All other tests: `authorizer: 'CassandraAuthorizer'`

Adding permissions to the role should solve the problem

**Comment by fruch** [comment]
> > @juliayakovlev
> > Seems like this won't be enough, please disable this nemesis in same way as the first based on the longevity shares params: https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-1tb-7days-test/4
> > This blocking the release
> 
> @soyacz As @fruch reported here, cassandra-stress load failed during `longevity-1tb-7days-test` due to role lack permissions:
> 
> ```
> 2023-02-10 01:29:47.837: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=f156e771-e484-4acb-a35a-bd8c27a26bee during_nemesis=SlaIncreaseSharesDuringLoad: type=IOException regex=java\.io\.IOException line_number=1083 node=Node longevity-tls-1tb-7d-2023-1-loader-node-f9243157-1 [16.16.27.104 | 10.0.3.129] (seed: False)
> java.io.IOException: Operation x51 on key(s) [374f324e363531323730]: Error executing: (UnauthorizedException): User role500_4d3df4a6 has no SELECT permission on <table keyspace1.standard1> or any of its parents
> ```
> 
> The difference between SLA and 1Tb tests is `authorizer`: SLA tests has `authorizer: 'ScyllaAuthorizer'` All other tests: `authorizer: 'CassandraAuthorizer'`
> 
> Adding permissions to the role should solve the problem

Can you please point to the jobs running the SLA nemesis with this PR ? 

also please rebase this PR before we merge it, so it would remove the skip based on the test case

**Comment by juliayakovlev** [comment]
> > > @juliayakovlev
> > > Seems like this won't be enough, please disable this nemesis in same way as the first based on the longevity shares params: https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-1tb-7days-test/4
> > > This blocking the release
> > 
> > 
> > @soyacz As @fruch reported here, cassandra-stress load failed during `longevity-1tb-7days-test` due to role lack permissions:
> > ```
> > 2023-02-10 01:29:47.837: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=f156e771-e484-4acb-a35a-bd8c27a26bee during_nemesis=SlaIncreaseSharesDuringLoad: type=IOException regex=java\.io\.IOException line_number=1083 node=Node longevity-tls-1tb-7d-2023-1-loader-node-f9243157-1 [16.16.27.104 | 10.0.3.129] (seed: False)
> > java.io.IOException: Operation x51 on key(s) [374f324e363531323730]: Error executing: (UnauthorizedException): User role500_4d3df4a6 has no SELECT permission on <table keyspace1.standard1> or any of its parents
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The difference between SLA and 1Tb tests is `authorizer`: SLA tests has `authorizer: 'ScyllaAuthorizer'` All other tests: `authorizer: 'CassandraAuthorizer'`
> > Adding permissions to the role should solve the problem
> 
> Can you please point to the jobs running the SLA nemesis with this PR ?

https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/staging-10gb-3h/345/ (failed with TestTimeoutEvent)
https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/longevity-1tb-7days-test/4/
https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/longevity-sla-system-24h/57/

> 
> also please rebase this PR before we merge it, so it would remove the skip based on the test case

Actually the PR https://github.com/scylladb/scylla-cluster-tests/pull/5804 cause to SLA longevity do not run the nemeses

**Comment by fruch** [comment]
> > > > @juliayakovlev
> > > > Seems like this won't be enough, please disable this nemesis in same way as the first based on the longevity shares params: https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-1tb-7days-test/4
> > > > This blocking the release
> > > 
> > > 
> > > @soyacz As @fruch reported here, cassandra-stress load failed during `longevity-1tb-7days-test` due to role lack permissions:
> > > ```
> > > 2023-02-10 01:29:47.837: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=f156e771-e484-4acb-a35a-bd8c27a26bee during_nemesis=SlaIncreaseSharesDuringLoad: type=IOException regex=java\.io\.IOException line_number=1083 node=Node longevity-tls-1tb-7d-2023-1-loader-node-f9243157-1 [16.16.27.104 | 10.0.3.129] (seed: False)
> > > java.io.IOException: Operation x51 on key(s) [374f324e363531323730]: Error executing: (UnauthorizedException): User role500_4d3df4a6 has no SELECT permission on <table keyspace1.standard1> or any of its parents
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The difference between SLA and 1Tb tests is `authorizer`: SLA tests has `authorizer: 'ScyllaAuthorizer'` All other tests: `authorizer: 'CassandraAuthorizer'`
> > > Adding permissions to the role should solve the problem
> > 
> > Can you please point to the jobs running the SLA nemesis with this PR ?
> 
> https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/staging-10gb-3h/345/ (failed with TestTimeoutEvent)
> https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/longevity-1tb-7days-test/4/
> https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/longevity-sla-system-24h/57/
> 
> > 
> > also please rebase this PR before we merge it, so it would remove the skip based on the test case
> 
> Actually the PR https://github.com/scylladb/scylla-cluster-tests/pull/5804 cause to SLA longevity do not run the nemeses

If this PR proven to be working and nemesis can work on top of regular test cases, it should replace the changes from #5804

**Comment by juliayakovlev** [comment]
Continue with https://github.com/scylladb/scylla-cluster-tests/pull/5816

**Pull request closed without merging**
