### PR TITLE
scylla management client

### PR DESCRIPTION
**Pull request by larisau**

### CODE REVIEW

**Comment by larisau** [comment]
not ready to merge, will be updated

**Comment by roydahan** [comment]
@amoskong  please review.

**Comment by slivne** [comment]
@larisau - please note that the product name has changed everything now is scylla-manager and not scylla-mgmt - so you will need to update this.

**Comment by larisau** [comment]
This version still exists and should work(http://downloads.scylladb.com/mgmt/rpm/unstable/centos/master).
The new version was build today(http://downloads.scylladb.com/manager/rpm/unstable/centos/branch-1.0/), so I'll switch to this after code testing.

**Comment by slivne** [comment]
it will not exist tomorrow and the repo will change to be http://downloads.scylladb.com/manager/rpm/unstable/centos/master

**Pull request merged**
