### PR TITLE
fix(azure): fix user-data error when creating runner

### PR DESCRIPTION
**Pull request by soyacz**
When creating sct-runner on Azure there's iterating over None error.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fgelcer — APPROVED** [review]
LGTM, but does the SCT runner need to send `user_data`?

**Comment by fruch** [comment]
> LGTM, but does the SCT runner need to send `user_data`?

I think it's the other way around, it doesn't have user-data, hence it was failing

**Comment by fruch** [comment]
@soyacz @fgelcer backport tags ?

**Comment by soyacz** [comment]
@bentsi @fruch Issue is quite severe as fails daily longevity - can we merge it?

**Comment by fgelcer** [comment]
> @bentsi @fruch Issue is quite severe as fails daily longevity - can we merge it?

@soyacz , isn't it needed to 5.0 and 2022.1 branches?

**Comment by soyacz** [comment]
> > @bentsi @fruch Issue is quite severe as fails daily longevity - can we merge it?
> 
> @soyacz , isn't it needed to 5.0 and 2022.1 branches?

No, we didn't backport recent changes there.

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
