### PR TITLE
fix(cluster): dpkg -s for checking if a package is installed

### PR DESCRIPTION
**Pull request by tchaikov**
the return code of `dpkg-query --show` does not imply if a package is installed. this command fails only when the package is not found.

quote from dpkg-query(1)
```
       -W, --show [package-name-pattern...]
           Just like the --list option this will list all packages matching the given patterns. However the output can be customized using the
           --showformat option.

           The default output format gives one line per matching package, each line consisting of the package name and its installed version, separated by
           a tab.  The package name will be architecture qualified for packages with a Multi-Arch field with the value same or with a foreign
           architecture, which is an architecture that is neither the native one nor all.

       -s, --status [package-name...]
           Report status of specified packages. This just displays the entry in the installed package status database.  If no package-name is specified it
           will display all package entries in the status database (since dpkg 1.19.1).  When multiple package-name entries are listed, the requested
           status entries are separated by an empty line, with the same order as specified on the argument list.
```
and verified using

```console
$ dpkg-query --show mutt && echo yup
mutt
yup
$ dpkg-query --status mutt && echo yup
dpkg-query: package 'mutt' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.
```

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by tchaikov** [comment]
@fruch hi Israel, could you help review this change?

**Review by fruch — DISMISSED** [review]

**Comment by fruch** [comment]
@tchaikov did you run into an issue with some SCT tests cause of this ? or you just spotted it during review of something else?

**Comment by tchaikov** [comment]
@fruch the latter. i just spotted this one when working on https://github.com/scylladb/scylla-cluster-tests/pull/5994

**Review by vponomaryov — CHANGES_REQUESTED** [review]
@tchaikov 
Look at the precommit CI test failure [1], it says following:

```
17:25:34  ✖   body's lines must not be longer than 100 characters [body-max-line-length]
```

So, need to update the commit message body to satisfy the 100-characters limit requirement.

[1] https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-cluster-tests/job/PR-5993/1/execution/node/23/log/

**Comment by tchaikov** [comment]
@vponomaryov hi Valerii, thank you for your review. just wrapped the lines which were over 100 chars long.

could you take another look?

**Review by vponomaryov — APPROVED** [review]
LGTM

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
