### PR TITLE
 Add '--abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc' to default scylla commandline params

### PR DESCRIPTION
**Pull request by fruch**

### CODE REVIEW

**Comment by fruch** [comment]
@bentsi I've made two commit here, only 8165df0 need to be backported to 2019.1

**Comment by roydahan** [comment]
@fruch did you happen to test it?
I see now in scylla (utils/logalloc.hh) code that it may be "abort_on_bad_alloc".

**Comment by fruch** [comment]
@roydahan seems like the name from 3.0.4 is `--abort-on-seastar-bad-alloc`
I'll try fetching older version and try to check how it was called before (if existed)

**Comment by fruch** [comment]
@roydahan I've now tested it, but just to make sure.
we are talking about this flag:
https://github.com/scylladb/scylla/commit/9476bc5a31cf527b14f22571d686b195eb5b3956

**Comment by roydahan** [comment]
We need to add all supported aborts for bad_alloc

**Comment by fruch** [comment]
@roydahan I've check this is working on 3.0.4, is it safe to assume it's would work on 2019.1 ? or we need to check it ?

@bentsi 
only 5046c2b needs to be backported (once this PR is approved)

**Comment by roydahan** [comment]
Good, I'm ok to merge.
@bentsi we need it before starting the new runs (today).

**Pull request merged**
