### PR TITLE
fix(upgrade): increase session timeouts in verify_db_data

### PR DESCRIPTION
**Pull request by juliayakovlev**
Increase session timeouts for data validation sdcm.fill_db_data.FillDatabaseData.verify_db_data:
```
cassandra.OperationTimedOut: errors={'10.4.3.124:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.4.3.124:9042
```

### Testing

- [ ]

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevent to this change (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
We need something similar to soft timeout for a CQL session

So 10m would be the hard limit, and soft limit 5m

So we can set a limit while giving it enough time to see how really a CQL stratmet tool to execute

**Comment by fruch** [comment]
> We need something similar to soft timeout for a CQL session
> 
> So 10m would be the hard limit, and soft limit 5m
> 
> So we can set a limit while giving it enough time to see how really a CQL stratmet tool to execute 

Let's raise an issue for building such a thing

**Comment by juliayakovlev** [comment]
> We need something similar to soft timeout for a CQL session
> 
> So 10m would be the hard limit, and soft limit 5m
> 
> So we can set a limit while giving it enough time to see how really a CQL stratmet tool to execute

@fruch  
https://github.com/scylladb/qa-tasks/issues/1599

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
