### PR TITLE
fix(remove unsupported artifacts): few distros are not supported

### PR DESCRIPTION
**Pull request by fgelcer**
as they reached EOL lately, so they are not supported
from Scylla perspective anymore, so this commit
will be removing:
* debian 9
* sles 15
* ubuntu 16

it includes the `jenkinsfile` and the `yaml` config files.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fruch — APPROVED** [review]
LGTM

**Review by ShlomiBalalis — APPROVED** [review]

**Review by roydahan — APPROVED** [review]
Approved, please make sure they're deleted from Jenkins as well.

**Comment by roydahan** [comment]
@rayakurl FYI for master.

**Comment by fgelcer** [comment]
> Approved, please make sure they're deleted from Jenkins as well.

all remove from Jenkins for branches where it was backported

**Comment by fgelcer** [comment]
BTW, @roydahan , did you backport to relevant branches?

**Comment by roydahan** [comment]
No

**Comment by fgelcer** [comment]
@scylladb/qa-maintainers , can please someone backport this one?

**Comment by roydahan** [comment]
I'll do it soon

**Comment by roydahan** [comment]
Done.

**Pull request merged**
