### PR TITLE
improvement(scylla-bench): use newest version with better retries

### PR DESCRIPTION
**Pull request by vponomaryov**
In the `v0.1.16` version of the `scylla-bench` tool was added query retries mechanism handled on this tool level, not buggy driver's one. So, use it by default.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by fruch — APPROVED** [review]
LGTM

**Review by soyacz — APPROVED** [review]

**Review by yarongilor — APPROVED** [review]
LGTM

**Comment by vponomaryov** [comment]
> @vponomaryov just for clarification, on which job this was tested ? only on the reversed queries ?

From job point of view - yes.
Locally I tested all the modes, was deleting pods and observing expected reactions.

**Pull request merged**
