### PR TITLE
gpg: add the 2024 pub key

### PR DESCRIPTION
**Pull request by benipeled**
@fruch the new key added to all places refers to the old one - not sure all of them are in use, please verify and merge

Ref https://github.com/scylladb/scylla-pkg/issues/3738

### CODE REVIEW

**Review by fruch — APPROVED** [review]

**Comment by fruch** [comment]
@benipeled those keys are going to 2024.1 branch ?

**Comment by benipeled** [comment]
> @benipeled those keys are going to 2024.1 branch ?

NO! master only and will be part of releases >5.4,2024.1

**Comment by benipeled** [comment]
@fruch is there auto-CI for such changes or I should manually run one of these artifact-tests?
In addition, I didn't manage to open the PR for next branch - please check it and make sure to edit the target branch before merging

**Comment by fruch** [comment]
> @fruch is there auto-CI for such changes or I should manually run one of these artifact-tests? In addition, I didn't manage to open the PR for next branch - please check it and make sure to edit the target branch before merging

SCT doesn't have next branch.

it can run a few tests, based on labels.

but in this case, manually triggering few of the debian base artifacts test would be enough.

**Comment by benipeled** [comment]
Verified with https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/artifacts/job/artifacts-debian11-test/42/
```
10:55:23  < t:2023-12-25 08:55:21,595 f:sct_config.py   l:1878 c:sdcm.sct_config      p:INFO  > scylla_apt_keys:
10:55:23  < t:2023-12-25 08:55:21,595 f:sct_config.py   l:1878 c:sdcm.sct_config      p:INFO  > - 5E08FBD8B5D6EC9C
10:55:23  < t:2023-12-25 08:55:21,595 f:sct_config.py   l:1878 c:sdcm.sct_config      p:INFO  > - D0A112E067426AB2
10:55:23  < t:2023-12-25 08:55:21,595 f:sct_config.py   l:1878 c:sdcm.sct_config      p:INFO  > - 491C93B9DE7496A7
```

**Comment by soyacz** [comment]
I think we need backports for upgrade jobs, e.g. perf test failed with `NO_PUBKEY 491C93B9DE7496A7`

**Comment by fruch** [comment]
> I think we need backports for upgrade jobs, e.g. perf test failed with `NO_PUBKEY 491C93B9DE7496A7`

In which branch ? @benipeled is that expected?

**Comment by soyacz** [comment]
e.g. `branch-perf-v14`

**Comment by benipeled** [comment]
> > I think we need backports for upgrade jobs, e.g. perf test failed with `NO_PUBKEY 491C93B9DE7496A7`
> 
> In which branch ? @benipeled is that expected?

It's not expected from the binary-sign but if the perf tests start from branch-5.4 and trying to install master packages it will fail since the new key wasn't imported,
This change is not removing old keys but adding a new one, we should have no problem backporting it

**Comment by fruch** [comment]
> e.g. `branch-perf-v14`

we run master releases on this one, so yeah it would need those keys

**Pull request merged**
