### PR TITLE
fix(grafana_snapsho): fix dom selector for monitoring 3.5

### PR DESCRIPTION
**Pull request by aleksbykov**
upgrade to scylla monitoring 3.5 bring new grafana version
and gui changes on pages.
- Updated the css selector to find the correct path to get snapshot
- Added ability to set css selector per page for taking snapshot

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~New configuration option are added and documented (in `sdcm/sct_config.py`)~
- [ ] ~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~
- [ ] ~All new and existing unit tests passed (CI)~
- [ ] ~I have updated the Readme/doc folder accordingly (if needed)~

### CODE REVIEW

**Comment by fruch** [comment]
@bentsi @roydahan, I still think think we should ditch the raintank.io snapshots. in less you'll tell me it's being use daily by people, on bugs investigations (which I don't think is the case)

@aleksbykov I we do keep it, can we think of a way to have an integration test for it ?

**Comment by aleksbykov** [comment]
@fruch what kind of integration test you suggest?
on monitoring side
on on our side.

It highly depends on grafana interface, we can add on our side some sort of intergration tests, but once it failed we have to check grafana and get the valid selectors and fix code again.

**Comment by fruch** [comment]
> @fruch what kind of integration test you suggest?
> on monitoring side
> on on our side.
> 
> It highly depends on grafana interface, we can add on our side some sort of integration tests, but once it failed we have to check grafana and get the valid selectors and fix code again.

on our side, i.e. that once we change the monitor version, that we would clearly see, that it can do snapshots, screenshot and such.

Again, if we decide to keep this feature

**Comment by roydahan** [comment]
@fruch we want to keep it, it's the most useful thing when you get a report that has it.

No need for integration test, every new version that is suggested by Amnon should be tested first using BYO, make sure all works correctly and then we change the version.

**Review by roydahan — APPROVED** [review]

**Pull request merged**
