### PR TITLE
fixed saving setup params in case of multiple dc

### PR DESCRIPTION
**Pull request by larisau**

### CODE REVIEW

**Comment by amoskong** [comment]
@larisau I touched this new problem, can you help to look at it?

Parameter:
```
n_db_nodes: '5 5 5'
```

Error:
```
      Traceback (most recent call last):
        File "sdcm/tester.py", line 129, in wrapper
          return method(*args, **kwargs)
        File "sdcm/tester.py", line 232, in setUp
          self.stats['setup_details'] = self.get_setup_details()
        File "sdcm/tester.py", line 997, in get_setup_details
          p[2] = re.sub('\s', '_', p[2])
      TypeError: 'tuple' object does not support item assignment
```

**Comment by larisau** [comment]
@amoskong can you please add the link to the full log, we have a bit more info there.

**Comment by amoskong** [comment]
@larisau I touched this problem in localhost. Attached the log.

[job_log_n_db_nodes_error.txt](https://github.com/scylladb/scylla-cluster-tests/files/1327163/job_log_n_db_nodes_error.txt)

**Comment by larisau** [comment]
@amoskong please update you branch, I see it's differs from the master, which already has a special treatment for multiple DC parametrer

**Pull request merged**
