### PR TITLE
fix(sla): explicit ServisLevel creation

### PR DESCRIPTION
**Pull request by temichus**
due to implicit servis level creation
by put **cql_result into ```__init__```,
in 2024.3 we start got python exception:
```
"ServiceLevel.__init__() got an unexpected keyword argument"
```
This PR fixes this issue by putting arguments into ```__init__``` explicitly and added additional log message before ```__init__```

### Testing

- [x] tested inhttps://argus.scylladb.com/test/18f3a99f-66ae-4d3a-a528-81a683fc52fa/runs?additionalRuns[]=b5b12efa-5ba9-43b7-af2a-0bbb9264245e,  python error has gone and I  hit issue https://github.com/scylladb/scylla-enterprise/issues/4801

```
< t:2024-10-08 11:51:57,846 f:sla.py          l:86   c:test_lib.sla         p:DEBUG > SERVICE_LEVEL row: {'service_level': 'sl200_0', 'timeout': None, 'workload_type': None, 'shares': 200, 'percentage_of_all_service_level_shares': '12.50%'}
< t:2024-10-08 11:51:57,847 f:sla.py          l:86   c:test_lib.sla         p:DEBUG > SERVICE_LEVEL row: {'service_level': 'sl600_0', 'timeout': None, 'workload_type': None, 'shares': 600, 'percentage_of_all_service_level_shares': '37.50%'}
< t:2024-10-08 11:51:57,847 f:sla.py          l:86   c:test_lib.sla         p:DEBUG > SERVICE_LEVEL row: {'service_level': 'sl800_1', 'timeout': None, 'workload_type': None, 'shares': 800, 'percentage_of_all_service_level_shares': '50.00%'}
```

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by soyacz** [comment]
looks like `percentage_of_all_service_level_shares` was added - shouldn't we validate it in tests?

**Comment by temichus** [comment]
> looks like `percentage_of_all_service_level_shares` was added - shouldn't we validate it in tests?

 not in SCT I think. it should be test.py test.

**Review by soyacz — APPROVED** [review]
LGTM

**Review by aleksbykov — APPROVED** [review]
LGTM

**Pull request merged**
