### PR TITLE
fix(severity.yaml): change reactor stall severity

### PR DESCRIPTION
**Pull request by fgelcer**
changing reactor stall events highest possible
value, by changing it in severity.yaml from
`WARNING` to `ERROR`, so when it will be below
the `TOLERABLE_REACTOR_STALL` it will be `DEBUG`,
but when it goes above that value, now it will be
marked as error.

Fixes: #5342

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by soyacz — APPROVED** [review]
Looks like it will work (as currently above tolerable value is set to warning and below is debug), but strange thing for me is that https://github.com/scylladb/scylla-cluster-tests/blob/master/sdcm/sct_events/database.py#L68 code shows it is setting already as `ERROR`.

**Comment by soyacz** [comment]
ok, I get it `severities.yaml` is defining max severities levels - this file name is misleading

**Review by fruch — APPROVED** [review]
LGTM

**Comment by roydahan** [comment]
Only to 5.1, 2022.2 for now.

**Pull request merged**
