### PR TITLE
fix(upgrade_test): `scylla sstable dump` verify with scylla.yaml

### PR DESCRIPTION
**Pull request by fruch**
since there a fix not yet backported about the order that `scylla sstable dumps` is looking for the schema, we need to pass it the scylla.yaml for it to be able to read EaR sstables

Ref: https://github.com/scylladb/scylla-enterprise/issues/3702
Ref: https://github.com/scylladb/scylladb/issues/16132

#### Testing
- [x] - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/rolling-upgrade-ami-test/3/

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by vponomaryov — APPROVED** [review]
LGTM

**Review by soyacz — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
the change looks great, but didn't really fixed the issue:

```
22:16:42  Command: 'for i in `sudo find /var/lib/scylla/data/keyspace_complex/ -type f |grep -v manifest.json |grep -v snapshots |head -n 1`; do echo $i; sudo /usr/bin/scylla sstable dump-data --scylla-yaml-file /etc/scylla/scylla.yaml --sstables $i 1>/tmp/sstabledump.output || exit 1; done'
22:16:42  Exit code: 1
22:16:42  Stdout:
22:16:42  /var/lib/scylla/data/keyspace_complex/user_with_ck-74e9ddd09f5e11ee96136a49f71ddcaf/me-3gc2_1jb7_03fgg2hq30apvozl70-big-Scylla.db
22:16:42  Stderr:
22:16:42  error processing arguments: could not load schema via : std::invalid_argument (don't know which schema to load: --keyspace and/or --table are not provided)
```

I guess can specific the keyspace and table, assuming there's no multiple tables there..

**Comment by fruch** [comment]
specifying both the yaml and the keyspace/table is working

**Pull request merged**
