### PR TITLE
improvement(scylla-bench): use latest v0.1.18 tag

### PR DESCRIPTION
**Pull request by vponomaryov**
Pulls up the following fix: https://github.com/scylladb/scylla-bench/pull/126

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Review by fgelcer — APPROVED** [review]
LGTM, but was it tested?

**Comment by vponomaryov** [comment]
> LGTM, but was it tested?

Manually, without CI jobs:

```
# scylla-bench -workload=sequential -mode=write -replication-factor=1 -partition-count=1 -clustering-row-count=25 -clustering-row-size=uniform:1024..2048 -concurrency=1 -connection-count=1 -consistency-level=one -rows-per-request=5 -timeout=30s -validate-data -nodes 192.168.100.11
Configuration
Mode:                    write
Workload:                sequential
Timeout:                 30s
Max error number at row: unlimited
Max error number:        unlimited
Retries:
  number:                10
  min interval:          80ms
  max interval:          1s
  handler:               sb
Consistency level:       one
Partition count:         1
Clustering rows:         25
Clustering row size:     Uniform(min=1024, max=2048)
Rows per request:        5
Page size:               1000
Concurrency:             1
Connections:             1
Maximum rate:            unlimited
Client compression:      true
Hdr memory consumption:  426256 bytes

 time   ops/s  rows/s errors max    99.9th 99th   95th   90th   median mean   
Results
Time (avg):      14.676556ms
Total ops:       5
Total rows:      25
Operations/s:    340.6793800943491
Rows/s:          1703.3969004717455
raw latency :
  max:           3.997695ms 
  99.9th:        3.997695ms 
  99th:          3.997695ms 
  95th:          3.997695ms 
  90th:          3.997695ms 
  median:        2.260991ms 
  mean:          2.585395ms
c-o fixed latency :
  max:           4.358143ms 
  99.9th:        4.358143ms 
  99th:          4.358143ms 
  95th:          4.358143ms 
  90th:          4.358143ms 
  median:        2.621439ms 
  mean:          2.926182ms

```

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fgelcer** [comment]
seeing https://github.com/scylladb/scylla-bench/pull/126 on a run of 2023.1 
can we please backport this one?

@scylladb/qa-maintainers

**Comment by fruch** [comment]
> seeing [scylladb/scylla-bench#126](https://github.com/scylladb/scylla-bench/pull/126) on a run of 2023.1 can we please backport this one?
> 
> @scylladb/qa-maintainers

done

**Pull request merged**
