### PR TITLE
fix(cassandra-stress): include all nodes as coordinators

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
Up until now, we've used only the first node as the coordinator.
However, if the first node is down for any reason (like a nemesis), the
stress is DOA. Therefore, I included all of the nodes as coordinators.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fruch — DISMISSED** [review]
LGTM

**Comment by roydahan** [comment]
1. There were several discussions on this and I don't think we had a conclusion about it, @fruch do you?
2. The commit message is wrong, the issue only happens when there is a combination of nemesis_filter_seed, nemesis_during_prepare and the condition that the nemesis currently runs on the first node while we try to start a new stress --> only the new stress will fail.

**Review by roydahan — CHANGES_REQUESTED** [review]
Change the commit message to explain exactly when this needed.

**Comment by fruch** [comment]
> fb98ff2c-594f-4fd2-9f54-117fa32d5ec7

@ShlomiBalalis link to jenkins, or to argus, would be more helpful
what would I do with the test_id ? download the logs/monitor ?

**Comment by roydahan** [comment]
> > 1. There were several discussions on this and I don't think we had a conclusion about it, @fruch do you?
> 
> I think this is the correct thing todo across the board in SCT, all drivers across the board should capable of having multiple contact point, this is the suggested why of using them. if there an issue with that, it's a bug or in scylla or in the driver, which we need to flush out regard
> 
> we should stop assuming we only start stress at the beginning of the test, we are using stress command in all kind of places while destructive operation can take place
> 

So in order to really test it and not just send PR that changes behaviour and let people bump into the issues, we need a run that uses it, use a nemesis that kills node and replace them preferable (e.g. TerminateThenReplace) and start stress new commands during the test (may require to tweak something in order to do it).
 
> > 2. The commit message is wrong, the issue only happens when there is a combination of nemesis_filter_seed, nemesis_during_prepare and the condition that the nemesis currently runs on the first node while we try to start a new stress --> only the new stress will fail.

**Comment by ShlomiBalalis** [comment]
> > > 1. There were several discussions on this and I don't think we had a conclusion about it, @fruch do you?
> > 
> > 
> > I think this is the correct thing todo across the board in SCT, all drivers across the board should capable of having multiple contact point, this is the suggested why of using them. if there an issue with that, it's a bug or in scylla or in the driver, which we need to flush out regard
> > we should stop assuming we only start stress at the beginning of the test, we are using stress command in all kind of places while destructive operation can take place
> 
> So in order to really test it and not just send PR that changes behaviour and let people bump into the issues, we need a run that uses it, use a nemesis that kills node and replace them preferable (e.g. TerminateThenReplace) and start stress new commands during the test (may require to tweak something in order to do it).

This is the exact scenario I ran in https://jenkins.scylladb.com/job/scylla-staging/job/Shlomo/job/cloud-longevity-small-data-set-1h-gcp/ (the same scenario where I ran into this issue in the first place). I thought the first run has already covered it but apparently the nemesis thread only started after the prepare was already ongoing. I reran the job, and if it won't occur this time I will check the change in a more manual fasion.


> > > 2. The commit message is wrong, the issue only happens when there is a combination of nemesis_filter_seed, nemesis_during_prepare and the condition that the nemesis currently runs on the first node while we try to start a new stress --> only the new stress will fail.

I didn not want to be too specific. In any case, I changed the message.

**Comment by roydahan** [comment]
> > > > 1. There were several discussions on this and I don't think we had a conclusion about it, @fruch do you?
> > > 
> > > 
> > > I think this is the correct thing todo across the board in SCT, all drivers across the board should capable of having multiple contact point, this is the suggested why of using them. if there an issue with that, it's a bug or in scylla or in the driver, which we need to flush out regard
> > > we should stop assuming we only start stress at the beginning of the test, we are using stress command in all kind of places while destructive operation can take place
> > 
> > 
> > So in order to really test it and not just send PR that changes behaviour and let people bump into the issues, we need a run that uses it, use a nemesis that kills node and replace them preferable (e.g. TerminateThenReplace) and start stress new commands during the test (may require to tweak something in order to do it).
> 
> This is the exact scenario I ran in https://jenkins.scylladb.com/job/scylla-staging/job/Shlomo/job/cloud-longevity-small-data-set-1h-gcp/ (the same scenario where I ran into this issue in the first place). I thought the first run has already covered it but apparently the nemesis thread only started after the prepare was already ongoing. I reran the job, and if it won't occur this time I will check the change in a more manual fasion.
> 
This is not the exact case.
You need to have multiple stress commands that will start during the test.

> > > > 2. The commit message is wrong, the issue only happens when there is a combination of nemesis_filter_seed, nemesis_during_prepare and the condition that the nemesis currently runs on the first node while we try to start a new stress --> only the new stress will fail.
> 
> I didn not want to be too specific. In any case, I changed the message.

**Comment by fruch** [comment]
> > This is the exact scenario I ran in https://jenkins.scylladb.com/job/scylla-staging/job/Shlomo/job/cloud-longevity-small-data-set-1h-gcp/ (the same scenario where I ran into this issue in the first place). I thought the first run has already covered it but apparently the nemesis thread only started after the prepare was already ongoing. I reran the job, and if it won't occur this time I will check the change in a more manual fasion.
> 
> This is not the exact case. You need to have multiple stress commands that will start during the test.
> 

I think the 1000 keyspaces that works in batches would be fit for this one

**Comment by rayakurl** [comment]
@ShlomiBalalis - please add the job link here. Thanks

**Review by vponomaryov — COMMENTED** [review]
From code point of view I do not see problems. It must work.

**Comment by roydahan** [comment]
I'm worried from the c-s part, that we will have regressions in longevities and no one will remember this change caused it.

**Comment by rayakurl** [comment]
Jenkis job link:
https://jenkins.scylladb.com/job/scylla-staging/job/Shlomo/job/longevity-multi-keyspaces-60h-test/

**Comment by ShlomiBalalis** [comment]
> Jenkis job link: https://jenkins.scylladb.com/job/scylla-staging/job/Shlomo/job/longevity-multi-keyspaces-60h-test/

In this job, I set StopStartMonkey as the only nemesis (Since it's disruptive and it's the nemesis that I consistently ran into the issue with) and set nemesis_filter_seeds to false. The job ran for 34 hours and failed only due to https://github.com/scylladb/scylla-cluster-tests/issues/5082, otherwise there was no issue with the run: d83fd5b6-f8e6-43c8-a384-fad38c81e3e9

**Comment by ShlomiBalalis** [comment]
It is important to note that this scenario has already added the entire node list as coordinators before:
https://github.com/scylladb/scylla-cluster-tests/blob/master/longevity_test.py#L401
(I had to remove it for my run since there was a bug related to it)

**Comment by rayakurl** [comment]
@roydahan , @fruch - the test run for 34 hour before failing due to an unrelated failure.

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by fruch — APPROVED** [review]
LGTM

**Comment by roydahan** [comment]
@fruch I think we should revert this commit.

**Comment by fruch** [comment]
> @fruch I think we should revert this commit.
> 

Why ?

**Comment by roydahan** [comment]
Isn't this the cause for issues like #5380 ?

**Comment by fruch** [comment]
> Isn't this the cause for issues like #5380 ?

yes, but we also need this for other test cases, where we could start with a single node that is down.

I've found the root cause in c-s, the code there is really silly, and easily fixed
https://github.com/scylladb/scylla-tools-java/pull/314

**Pull request merged**
