### PR TITLE
refactor(defaults monitor_branch): Setting monitor branch to 4.0

### PR DESCRIPTION
**Pull request by roydahan**
New monitor release is coming and need to be tested with.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
According to @amnonh  it was tested in BYO and seems to work.

**Comment by fruch** [comment]
https://github.com/scylladb/scylla-monitoring/pull/1738 is fixing the problem, added one more commit here to set the default back to dark.

**Comment by fruch** [comment]
> [scylladb/scylla-monitoring#1738](https://github.com/scylladb/scylla-monitoring/pull/1738) is fixing the problem, added one more commit here to set the default back to dark.

Seem like it's a problem I have introduced in #4730, I've put the timeout on the wrong place on the whole branch including the test log collection.

I'm sending a PR to fix soon

**Comment by fruch** [comment]
this is the PR with the fix: https://github.com/scylladb/scylla-cluster-tests/pull/4761

**Comment by amnonh** [comment]
We can configure the theme to be light or dark, I think it looks worse on
this dashboard, because the QA dashboard is not using scylla monitoring
dashboards.

**Pull request merged**
