### PR TITLE
improvement(ruff): enable `F821` and `F823` rules

### PR DESCRIPTION
**Pull request by vponomaryov**
Enable following rules:
- F821, `undefined-name` -> `Undefined name {name}. {tip}`
- F823, `undefined-local` -> `Local variable {name} referenced before assignment`

### Testing

- [ ]

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by vponomaryov** [comment]
I wasted some time catching missing imports in runtime instead of the pre-commit checks.

Probably we want to add more, but let's add these first.

**Comment by fruch** [comment]
> I wasted some time catching missing imports in runtime instead of the pre-commit checks.
> 
> Probably we want to add more, but let's add these first.

I had a list of one it might worth enabling, let's list this there:
https://github.com/scylladb/scylla-cluster-tests/issues/7860

**Comment by vponomaryov** [comment]
> > I wasted some time catching missing imports in runtime instead of the pre-commit checks.
> > Probably we want to add more, but let's add these first.
> 
> I had a list of one it might worth enabling, let's list this there: #7860

Added.

**Review by soyacz — APPROVED** [review]
LGTM

**Comment by soyacz** [comment]
I wonder if we shouldn't use git feature that can ignore specific commits in git blame: https://graphite.dev/guides/git-blame-ignore-revs
WDYT?

**Review by fruch — APPROVED** [review]
LGTM

**Comment by vponomaryov** [comment]
> I wonder if we shouldn't use git feature that can ignore specific commits in git blame: https://graphite.dev/guides/git-blame-ignore-revs WDYT?

How is this related to this change?

**Comment by soyacz** [comment]
generally, introducing changes just to make linting happy is hiding more important history from git blame. I think we could benefit from it with these kind of PR's.

**Comment by fruch** [comment]
> > I wonder if we shouldn't use git feature that can ignore specific commits in git blame: https://graphite.dev/guides/git-blame-ignore-revs WDYT?
> 
> How is this related to this change?

I think @soyacz suggests that we'll mark such a change that touches multiple places cause of linting as one that won't be shown in git blame,

I think we could experiment with it, it can ease a bit of investigation work around those touched places in the code.

It's nice to have, not more than that.

**Comment by fruch** [comment]
we got bit by not having this on v15, trying to backport

**Pull request merged**
