### PR TITLE
Added ICS longevity jenkinsfile and yaml

### PR DESCRIPTION
**Pull request by yarongilor**
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I gave variables/functions meaningful self-explanatory names
- [ ] I didn't leave commented-out/debugging code
- [ ] I didn't copy-paste code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
@yarongilor please add the rest of the jobs and change the path pf the pipelines to be flat as others.
Then, put urgent lable

**Comment by roydahan** [comment]
overall it's ok for now.
We will need to refactor the stress-cmd one day and make more robust for cases like these.
I added a task for it.

@yarongilor what about MV/SI? we need to test it as well with ICS.
Please send another PR for the MV/SI job.

**Comment by roydahan** [comment]
@bentsi we need to merge this and backport to 2019.1 and 2019.1.4

**Comment by yarongilor** [comment]
i just added a commit for mv/si after PR was already merged.

**Comment by fruch** [comment]
@yarongilor open a new PR

**Comment by yarongilor** [comment]
> @yarongilor open a new PR
@fruch , as commented above:
> opened a new PR: #1577

**Pull request merged**
