### PR TITLE
improvement(perf latency with nemesis): increase steady state

### PR DESCRIPTION
**Pull request by fgelcer**
as requested by @roydahan increasing the steady state.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
@roydahan , if you still think we need to increase it to 60 min.

**Comment by fgelcer** [comment]
there is another PR (#3101) that is increasing the c-s times, and i'm not taking it into consideration here

**Comment by roydahan** [comment]
I don't understand.
There are 2 PRs that both change the same thing.
If you extend it to 60 minutes, is it enough for the c-s?

**Comment by fgelcer** [comment]
> I don't understand.
> There are 2 PRs that both change the same thing.
> If you extend it to 60 minutes, is it enough for the c-s?

i thought the other PR was already merged, hence i increased it here too.
can you please merge and backport #3101 ?

**Comment by fgelcer** [comment]
> I don't understand.
> There are 2 PRs that both change the same thing.
> If you extend it to 60 minutes, is it enough for the c-s?

now, if you decide that you want still to increase the steady state, here is the PR, and it will also add time to the test and c-s commands.

**Pull request closed without merging**
