### PR TITLE
fix(upgrade_test): copy to /etc/scylla dir require sudo

### PR DESCRIPTION
**Pull request by aleksbykov**
Copy to /etc/scylla dir require root previligies.
Change to sudo.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] ~New configuration option are added and documented (in `sdcm/sct_config.py`)~
- [ ] ~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~
- [ ] ~All new and existing unit tests passed (CI)~
- [ ] ~I have updated the Readme/doc folder accordingly (if needed)~

### CODE REVIEW

**Review by vponomaryov — APPROVED** [review]
LGTM

**Comment by aleksbykov** [comment]
@vponomaryov Could set backport labels, if backport is required

**Comment by vponomaryov** [comment]
> @vponomaryov Could set backport labels, if backport is required

It is not required for k8s backends. So, if we talk about all other branches then I don't have enough info about it.

**Review by amoskong — APPROVED** [review]
Looks good.

**Review by bentsi — APPROVED** [review]

**Pull request merged**
