### PR TITLE
fix(artifacts offline install): remove oel76 nonroot

### PR DESCRIPTION
**Pull request by yarongilor**
oel76 nonroot is not supported.
	https://github.com/scylladb/scylla/issues/10574

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fgelcer — CHANGES_REQUESTED** [review]
please, also remove `test-cases/artifacts/oel76.yaml`

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by fgelcer** [comment]
@yarongilor , once this is merged, and the trigger is removed, we need to remove the Jenkins job as well...

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fgelcer** [comment]
@fruch , need to backport

**Pull request merged**
