### PR TITLE
Collect more details in perf regression tests

### PR DESCRIPTION
**Pull request by amoskong**

### CODE REVIEW

**Comment by roydahan** [comment]
Please update on all performance tests conf=True.

**Comment by amoskong** [comment]
I had updated the PR to collect the info for all sub perf tests.

Collected info in log:
```
  u'test_details': { u'cassandra-stress': { u'cl': u'QUORUM',
                     u'cpuset_conf': u'# DO NO EDIT\n# This file should be automatically configure by scylla_cpuset_setup\n#\n# CPUSET="--cpuset 0 --smp 1"',
                     u'io_conf': u'SEASTAR_IO="--max-io-requests=123"',
                     u'scylla_args': u'SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network
-stack posix"',
```

**Comment by amoskong** [comment]
@roydahan Let's review, merge and backport it to branch-perf-v2.

**Comment by amoskong** [comment]
I had backported the PR to branch-perf-v2

**Pull request merged**
