### PR TITLE
fix(mgmt_cli_test): properly read the persistent manager snapshot yaml

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
Following the addition of the restore nemesis, the structure of defaults/manager_persistent_snapshots.yaml has changed drastically, but the mgmt_cli_test file wasn't adjusted to the new structure. I modified mgmt_cli_test to read the yaml properly.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
@ShlomiBalalis please check what are the failing check failures.

**Comment by ShlomiBalalis** [comment]
> @ShlomiBalalis please check what are the failing check failures.

It's the failure from https://github.com/scylladb/scylla-cluster-tests/pull/6519

**Comment by ShlomiBalalis** [comment]
Also, the test run have passed: https://jenkins.scylladb.com/job/scylla-staging/job/Shlomo/job/sct-feature-test-restore-multiple-snapshot-restoring/3/

**Review by roydahan — APPROVED** [review]

**Comment by roydahan** [comment]
backported.

**Pull request merged**
