### PR TITLE
Backport reactor stall counter

### PR DESCRIPTION
**Pull request by aleksbykov**
Backport new feature event counters presented by this PR; https://github.com/scylladb/scylla-cluster-tests/pull/6302 from master to perf-v14

Backport of original PR was not clear due to missing some prs from master branch in perf-v14 which are not affect perf tests

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@aleksbykov should we first fix the issue found on master with this implementation ?

**Comment by fruch** [comment]
> @fruch this feature nicely work with perf tests on master, also i run longevity and it also passed. As i understood, the only problem happened with artifact tests.

yes it was affecting artifacts tests, but still I would recommend that this would be backported with the fix for it: 
https://github.com/scylladb/scylla-cluster-tests/pull/6348

**Comment by aleksbykov** [comment]
@fruch your fix is merged and backported, could this pr also be backported to perf-v14?

**Comment by fruch** [comment]
> @fruch your fix is merged and backported, could this pr also be backported to perf-v14?

It's there already, I've forgot to mark the PR

**Pull request merged**
