### PR TITLE
Perf with ops rework reduce email report

### PR DESCRIPTION
**Pull request by fgelcer**
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
it will be not easy to backport to perf branches, as @roydahan has removed part of these commits manually from these branches...
i'm running it right now [in here](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/perf_with_nemesis_reduce_report_size/job/perf-regression-latency-with-nemesis-smaller-report/19/) and hope to see the report being sent in few hours from now

**Comment by fgelcer** [comment]
@roydahan , also, i'm running this job above with my changes, based on master... and we should create a new branch for the perf jobs, as there are many good improvements for it (like in master it is running using SCT Runner), hurray!!!

**Comment by fruch** [comment]
> @roydahan , also, i'm running this job above with my changes, based on master... and we should create a new branch for the perf jobs, as there are many good improvements for it (like in master it is running using SCT Runner), hurray!!!

v13 has most of the goodies (the SCT runner for sure)

**Comment by fgelcer** [comment]
closing it for now, as the report in the `branch-perf-v12` seems to be working fine now

**Pull request closed without merging**
