### PR TITLE
improvement(k8s): make `check Scylla cleanups` K8S func test save logs

### PR DESCRIPTION
**Pull request by vponomaryov**
The `test_add_new_node_and_check_old_nodes_are_cleaned_up` K8S functional test
creates additional DB pod and cleans it up in the end of itself in any case.

So, make it save logs in case of failure for ease of debugging.
Also, stop `ParallelObject` threads which may run till the end of the test run, which is not expected thing to happen.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by vponomaryov** [comment]
Developed in conjunction with the fix for the configuration problem which gets fixed here: https://github.com/scylladb/scylla-cluster-tests/pull/6749

**Comment by vponomaryov** [comment]
Tested here: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-functional-eks/38/consoleFull

**Review by soyacz — APPROVED** [review]
LGTM

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
