### PR TITLE
fix(FullScanAggregatesOperation): fixing forward_request validation 

### PR DESCRIPTION
**Pull request by temichus**
in case of no ""Dispatching forward_request to \d* endpoints"" in query_trace events
event severity will be WARNING instead of ERROR

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fgelcer — COMMENTED** [review]
what is the root cause of it?
we found out that it doesn't happen on `5.2.0-rc1` but it does happen on `2023.1.0-rc1`

i think we can merge this change, but we need to understand clearly the reason, and the impact of it.

**Comment by fgelcer** [comment]
@temichus , checks are failing, please check why

**Review by vponomaryov — APPROVED** [review]
LGTM

**Review by fruch — APPROVED** [review]

**Comment by vponomaryov** [comment]
> > @temichus , checks are failing, please check why
> 
> linting fails ValueError: AMIs for oracle_scylla_version='4.6.9' not found in eu-west-1
> 
> @fruch , @fgelcer can I update it on 4.6.11 or later version? because it should fail for everyone now.
> 
> Going to run './sct.py list-images -c AWS -v 4.6'... Obtaining QA SSH keys... QA SSH keys obtained. install-bash-completion current path: /home/artsiom/codebase/scylla-cluster-tests New directory created: /home/artsiom/sct-results/20230223-121826-600915-list-images +-----------------------------------------------------------------------------------------------+ | AWS Machine Images by Version in region eu-west-1 | +---------+-----------------+-----------------------+--------------------------+----------------+ | Backend | Name | ImageId | CreationDate | NameTag | +---------+-----------------+-----------------------+--------------------------+----------------+ | AWS | ScyllaDB 4.6.11 | ami-030d958508f559ae9 | 2022-12-01T13:54:16.000Z | Packer Builder | +---------+-----------------+-----------------------+--------------------------+----------------+

https://github.com/scylladb/scylla-cluster-tests/pull/5850

**Review by fgelcer — DISMISSED** [review]
LGTM

**Comment by vponomaryov** [comment]
@temichus

Rebase it please to make the unit tests fix be applied here.

**Review by vponomaryov — APPROVED** [review]

**Review by fruch — APPROVED** [review]

**Comment by vponomaryov** [comment]
@fgelcer @fruch what about backports? 2023.1?

**Comment by fruch** [comment]
> @fgelcer @fruch what about backports? 2023.1?

5.2/2023.1

But we need to pay attention when we are going to stop FF those branches

**Comment by fgelcer** [comment]
@temichus , it should hit 2023.1 and 5.2, right?

@fruch , i think we stopped FF'ing

**Comment by fgelcer** [comment]
@roydahan , please approve backport

**Pull request merged**
