### PR TITLE
fix(disrupt_decommission_streaming_err): skip failure log

### PR DESCRIPTION
**Pull request by fruch**
Since RBNO is enabled, this nemesis is generating those logs:
```
scylla[5576]:  [shard  0] storage_service - decommission[aa9a834d-99b1-4af8-9267-cec699bb5140]:
Operation failed, sync_nodes={10.4.0.45, 10.4.3.213, 10.4.3.145, 10.4.1.131, 10.4.2.77,
10.4.2.119}: std::runtime_error ({shard 0: std::runtime_error (Failed to repair for
keyspace=alternator_usertable, cf=usertable, range=(-7819559552726985616, -7814482230290657926]),
 shard 1: std::runtime_error (Failed to repair for keyspace=alternator_usertable, cf=usertable,
 range=(-8277937157109075297, -8260575255900646513]), shard 2: std::runtime_error (Failed to
 repair for keyspace=alternator_usertable, cf=usertable, range=(-7814091121065622595,
 -7810918921443784702]), shard 3: std::runtime_error (Failed to repair for
 keyspace=alternator_usertable, cf=usertable, range=(-7920656420086354667, -7913393766828895675]),
 shard 4: std::runtime_error (Failed to repair for keyspace=alternator_usertable, cf=usertable,
 range=(-8217905152047068797, -8180520229346198706]), shard 5: std::runtime_error (Failed to
repair for keyspace=alternator_usertable, cf=usertable, range=(-8217905152047068797,
-8180520229346198706]), shard 6: std::runtime_error (Failed to repair for
keyspace=alternator_usertable, cf=usertable, range=(-8053837487533107823, -8014098015270410936]),
...
```

This error is expected, since we are delebritly failing the operation

Fixes: #5926

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by fgelcer** [comment]
is it needed backported to 5.2 and 2023.1?

**Comment by fruch** [comment]
> is it needed backported to 5.2 and 2023.1?

I'm not sure, I think RBNO on all action was enabled only on master. but I'm not sure.

**Comment by fgelcer** [comment]
> > is it needed backported to 5.2 and 2023.1?
> 
> I'm not sure, I think RBNO on all action was enabled only on master. but I'm not sure.

IIRC you are right, and RBNO is only enabled by default on master for all operations, but if there is a test that will enable RBNO on 5.2 or 2023.1, we will need this fix in there too, no? because AFAICT it doesn't disturb if RBNO is disabled anyway...

**Comment by fruch** [comment]
It wouldn't do any harm if backported.

But for now I see no point of backporting

**Review by soyacz — APPROVED** [review]

**Pull request merged**
