### PR TITLE
rolling upgrade instance_provision: 'on_demand'

### PR DESCRIPTION
**Pull request by yarongilor**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
it's not good enough...
Does it take the configuration from the job or not?
There should be defaults configured and the job should be able to configure it.

**Comment by bentsi** [comment]
I think we can keep master jobs on preemptible instances

**Comment by fruch** [comment]
this is the pipeline parameter:
https://github.com/scylladb/scylla-cluster-tests/blob/master/vars/rollingUpgradePipeline.groovy#L21

the 4 pipeline need to be change like this if you want them to default to `on_demend`:

(this is the centos7 as an example)
```groovy
#!groovy

// trick from https://github.com/jenkinsci/workflow-cps-global-lib-plugin/pull/43
def lib = library identifier: 'sct@snapshot', retriever: legacySCM(scm)

rollingUpgradePipeline(
    params: params,

    backend: 'gce',
    base_versions: ['2019.1', '3.2'],
    linux_distro: 'centos',
    gce_image_db: 'https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7',

    test_name: 'upgrade_test.UpgradeTest.test_rolling_upgrade',
    test_config: 'test-cases/upgrades/rolling-upgrade.yaml',
    workaround_kernel_bug_for_iotune: true,

    timeout: [time: 360, unit: 'MINUTES'],
    provision_type: 'on_demand'
)
```

even that from the comment here, seem like there is a disagreement if that's should be the default at all...

**Comment by roydahan** [comment]
Yaron sent this PR because he said that when he changed the parameter manually in the job it didn't work.
In my last commit to this pipeline that changes the post behaviour, I added missing "" to this paramter.
Maybe it solves the issue.

**Comment by yarongilor** [comment]
please advise if this change is sufficient and if and how we want to differentiate this not to apply on master but only on branch-3.3

**Comment by roydahan** [comment]
The default will remain spot.
If it fails we will running it manually as on_demand.

Now that it can be set from the job correctly as a parameter it should work.

**Comment by yarongilor** [comment]
got spot termination on 3.3 centos rolling upgrade #20. rerunning manually with on_demand.

**Pull request closed without merging**
