### PR TITLE
Branch 4.6 disable error limit

### PR DESCRIPTION
**Pull request by roydahan**
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
@fgelcer please use this for reproducer.

**Comment by roydahan** [comment]
@fgelcer / @yarongilor did we need this change eventually with 4.6?

**Comment by fgelcer** [comment]
> @fgelcer / @yarongilor did we need this change eventually with 4.6?

i don't remember what it is about... what was the problem we were trying to solve in here?

**Comment by fruch** [comment]
No one remembers what this is for...

**Pull request closed without merging**
