### PR TITLE
Calls to cql_connection_patient*(), session are being closed

### LINKED ISSUE #959: make sure any use of the python-cassandra-driver is being closed/cleaned
not closing those session create lots of unneeded logs:
```
< t:2019-05-08 15:13:50,169 f:thread.py       l:63   c:cassandra.pool       p:WARNING > Error attempting to reconnect to 52.211.79.50, scheduling retry in 4.0 seconds: 
< t:2019-05-08 15:13:50,170 f:thread.py       l:63   c:cassandra.pool       p:DEBUG > Reconnection error details < t:2019-05-08 15:13:50,170 f:thread.py       l:63   c:
< t:2019-05-08 15:13:50,170 f:thread.py       l:63   c:cassandra.pool       p:DEBUG > Traceback (most recent call last):
< t:2019-05-08 15:13:50,170 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >   File "cassandra/pool.py", line 208, in cassandra.pool._ReconnectionHandler.run
< t:2019-05-08 15:13:50,170 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >     conn = self.try_reconnect()
< t:2019-05-08 15:13:50,170 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >   File "cassandra/pool.py", line 279, in cassandra.pool._HostReconnectionHandler.t
< t:2019-05-08 15:13:50,170 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >     return self.connection_factory()
< t:2019-05-08 15:13:50,170 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >   File "cassandra/connection.py", line 332, in cassandra.connection.Connection.fac
< t:2019-05-08 15:13:50,170 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >     conn = cls(host, *args, **kwargs)
< t:2019-05-08 15:13:50,170 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >   File "/home/fruch/Projects/scylla-cluster-tests/.venv/local/lib/python2.7/site-p
< t:2019-05-08 15:13:50,170 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >     self._connect_socket()
< t:2019-05-08 15:13:50,170 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >   File "cassandra/connection.py", line 371, in cassandra.connection.Connection._co
< t:2019-05-08 15:13:50,170 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >     raise socket.error(sockerr.errno, "Tried connecting to %s. Last error: %s" % (
< t:2019-05-08 15:13:50,170 f:thread.py       l:63   c:cassandra.pool       p:DEBUG > error: [Errno None] Tried connecting to [('52.211.79.50', 9042)]. Last error: time
< t:2019-05-08 15:13:54,122 f:thread.py       l:63   c:cassandra.pool       p:WARNING > Error attempting to reconnect to 52.211.79.50, scheduling retry in 4.0 seconds: 
< t:2019-05-08 15:13:54,122 f:thread.py       l:63   c:cassandra.pool       p:DEBUG > Reconnection error details < t:2019-05-08 15:13:54,122 f:thread.py       l:63   c:
< t:2019-05-08 15:13:54,122 f:thread.py       l:63   c:cassandra.pool       p:DEBUG > Traceback (most recent call last):
< t:2019-05-08 15:13:54,122 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >   File "cassandra/pool.py", line 208, in cassandra.pool._ReconnectionHandler.run
< t:2019-05-08 15:13:54,122 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >     conn = self.try_reconnect()
< t:2019-05-08 15:13:54,122 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >   File "cassandra/pool.py", line 279, in cassandra.pool._HostReconnectionHandler.t
< t:2019-05-08 15:13:54,122 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >     return self.connection_factory()
< t:2019-05-08 15:13:54,122 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >   File "cassandra/connection.py", line 332, in cassandra.connection.Connection.fac
< t:2019-05-08 15:13:54,122 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >     conn = cls(host, *args, **kwargs)
< t:2019-05-08 15:13:54,122 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >   File "/home/fruch/Projects/scylla-cluster-tests/.venv/local/lib/python2.7/site-p
< t:2019-05-08 15:13:54,122 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >     self._connect_socket()
< t:2019-05-08 15:13:54,122 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >   File "cassandra/connection.py", line 371, in cassandra.connection.Connection._co
< t:2019-05-08 15:13:54,122 f:thread.py       l:63   c:cassandra.pool       p:DEBUG >     raise socket.error(sockerr.errno, "Tried connecting to %s. Last error: %s" % (
< t:2019-05-08 15:13:54,122 f:thread.py       l:63   c:cassandra.pool       p:DEBUG > error: [Errno None] Tried connecting to [('52.211.79.50', 9042)]. Last error: time
< t:2019-05-08 15:13:54,123 f:thread.py       l:63   c:cassandra.cluster    p:DEBUG > Ignoring scheduled task after shutdown: (<bound method _HostReconnectionHandler.ru
< t:2019-05-08 15:13:54,176 f:atexit.py       l:24   c:cassandra.cluster    p:DEBUG > Shutting down Cluster Scheduler
< t:2019-05-08 15:13:54,234 f:atexit.py       l:24   c:cassandra.cluster    p:DEBUG > Shutting down control connection
````

### PR DESCRIPTION
**Pull request by fruch**
example:

```python
with self.cql_connection_patient(node) as session:
    session.execute("DROP KEYSPACE keyspace1;")
    session.execute("DROP KEYSPACE ks_no_range_ghost_test;")
```
Fixes #959 

thanks to @ShlomiBalalis for helping to pinpoint the reason of this one

### CODE REVIEW

**Comment by fruch** [comment]
**Note:** 
this is isn't cause any issue, just clutter the logs with errors, cause the connections are still open.
this confuses people, when debugging other error and issues.

**Comment by fruch** [comment]
seem like all this doesn't really makes much difference,  since the background asyncore loop still tries to reconnect once the nodes are down...

**Comment by bentsi** [comment]
this is since we need to call `shutdown` method on `ClusterDriver` object (that is not stored any where)

**Comment by fruch** [comment]
@bentsi I've also tried that, and it doesn't seem to make much difference. the pool seem to be cleanup only at exit.

**Comment by bentsi** [comment]
look on the `cassandra.cluster.Cluster#shutdown` method:
```python

    def shutdown(self):
        """
        Closes all sessions and connection associated with this Cluster.
        To ensure all connections are properly closed, **you should always
        call shutdown() on a Cluster instance when you are done with it**.

        Once shutdown, a Cluster should not be used for any purpose.
        """
        with self._lock:
            if self.is_shutdown:
                return
            else:
                self.is_shutdown = True

        if self._idle_heartbeat:
            self._idle_heartbeat.stop()

        self.scheduler.shutdown()

        self.control_connection.shutdown()

        for session in tuple(self.sessions):
            session.shutdown()

        self.executor.shutdown()

        _discard_cluster_shutdown(self)
```
it should close the heartbeat thread among other things, so the solution here is to close all sessions and cluster object

**Pull request merged**
