### PR TITLE
improvement(sct_events.py): Creating one place for  all SCT events

### PR DESCRIPTION
**Pull request by Orenef11**
* Trello - https://trello.com/c/V3Ca21uD
   Trello description:
   Same filterd events are used for common actions.
   Need to find a way to group them in one file under the same Object
   Example:
   ```
     with DbEventsFilter(type='DATABASE_ERROR', line="repair's stream failed: streaming::stream_exception",
                    node=self.target_node), \
        DbEventsFilter(type='RUNTIME_ERROR', line='Can not find stream_manager', node=self.target_node), \
        DbEventsFilter(type='RUNTIME_ERROR', line='is aborted', node=self.target_node), \
        DbEventsFilter(type='RUNTIME_ERROR', line='Failed to repair', node=self.target_node):
   ```
* BasicSeverityEvent - Create DummyEvent namedtuple for tests
* SeverityEvent - Create SeverityEvent namedtuple for events with severity
* DbEventType - Create one place with all Database events type
* DbEvent - Create enum for each Cassandra event
* DbEventsFilter - Improvement DbEventsFilter class to support all events
* DummyEventsFilter - Create enum for each dummy event (event_class and regex) for tests
* SeverityEvents - Create enum for each severity (include Alternator) events
* EventsFilter - Improvement EventsFilter class to supported all Scylla events. Create 3 events types.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [x] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [x] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by Orenef11** [comment]
What is the best way to test the changes I have made?

**Comment by roydahan** [comment]
please add the description of the ticket from trello and the motivation to here and to the commit message.
It's not clear to whoever reads it.

**Comment by Orenef11** [comment]
> please add the description of the ticket from trello and the motivation to here and to the commit message.
> It's not clear to whoever reads it.

Done.
Unfortunately, there are many failures, due I change the status to draft.

> please add the description of the ticket from trello and the motivation to here and to the commit message.
> It's not clear to whoever reads it.

Done.
Unfortunately, there are many failures, due I change the status to draft.

**Comment by Orenef11** [comment]
> You are missing the whole point here, it wasn't to put the name and regexs in one place,
> It was to put the whole logic as in `ignore_alternator_client_errors` for the places that are reusing same group of filters.
> here you re-write the whole filtering class, without adding nothing to readability (maybe even lowering readability, with hiding the names and regex somewhere else.)

Yes, you are right.
But now it's much more regulated and all events are under one class.
This change was made due we can change any event (message and type) in one place.
I merged the classes and now it is much more orderly, understandable and there is no need for the other departments that were.

**Pull request closed without merging**
