### PR TITLE
Remove libvirt and openstack support from SCT

### PR DESCRIPTION
**Pull request by fruch**
Since both of those backends are not being used anymore,
we remove them from the code.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I gave variables/functions meaningful self-explanatory names
- [ ] I didn't leave commented-out/debugging code
- [ ] I didn't copy-paste code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
waiting for @roydahan and @bentsi  to take a decision on this one.

**Comment by bentsi** [comment]
@roydahan this code is completely broken, if we would like to support OpenStack and libvirt in future we will need to rewrite it. So let's remove it

**Comment by roydahan** [comment]
Ok

**Comment by fruch** [comment]
waiting for a PR that would fix `test-provision` tag to check this

**Pull request merged**
