### PR TITLE
fix(jepsen): run commit_log_check_thread in jepsen

### PR DESCRIPTION
**Pull request by temichus**
fix(jepsen): run commit_log_check_thread in jepsen
to run commit_log_check_thread
in jepsen pipleine need to perform
seastar-cpu-map.sh via sudo
### Testing

- [ ] https://jenkins.scylladb.com/job/scylla-staging/job/artsiom_mishuta/job/jepsen-test-all/11/
- [ ] https://jenkins.scylladb.com/job/scylla-staging/job/artsiom_mishuta/job/longevity-10gb-3h-test/56/

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevent to this change (if needed)

### CODE REVIEW

**Review by soyacz — APPROVED** [review]
LGTM

**Comment by temichus** [comment]
looks like sudo should also work. testing now

**Comment by fruch** [comment]
> it looks like sudo should also work. testing now (at least it works via manual SSH on Jepsen node and "test_custom_time" cluster )

looks from the run it did solved the issue.
can you update the PR title and description ?

**Comment by temichus** [comment]
> > it looks like sudo should also work. testing now (at least it works via manual SSH on Jepsen node and "test_custom_time" cluster )
> 
> looks from the run it did solved the issue. can you update the PR title and description ?

updated

**Pull request merged**
