### PR TITLE
fix (install_scylla): adjust the dependency repos for debian10

### PR DESCRIPTION
**Pull request by amoskong**
There is 3rdparty repositorie for Debian 10, the installation doesn't
require it. The openjdk-8-jre dependency can be solved by adoptopenjdk
repositorie.

This patch removed invalid 3rdparty repositorie for Debian 10, and added
adoptopenjdk repositorie.

Signed-off-by: Amos Kong <amos@scylladb.com>

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by amoskong** [comment]
Testing this PR by : https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-debian10-clone/1/

**Comment by amoskong** [comment]
The test passed.
- https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-debian10-clone/1/

**Comment by amoskong** [comment]
Pylint failed

```
21:58:57  pylint...................................................................Failed
21:58:57  hookid: pylint
21:58:57  
21:58:57  ************* Module sdcm.rsyslog_daemon
21:58:57  sdcm/rsyslog_daemon.py:1:0: R0801: Similar lines in 2 files
21:58:57  ==unit_tests.test_prometheus:128
21:58:57  ==unit_tests.test_send_email:15
21:58:57      temp_dir = None
21:58:57  
21:58:57      @classmethod
21:58:57      def setUpClass(cls):
21:58:57          cls.temp_dir = tempfile.mkdtemp()
21:58:57  
21:58:57      @classmethod
21:58:57      def tearDownClass(cls):
21:58:57          # stop_events_device()
21:58:57          shutil.rmtree(cls.temp_dir)
21:58:57   (duplicate-code)
21:58:57  
21:58:57  --------------------------------------------------------------------
21:58:57  Your code has been rated at 10.00/10 (previous run: 10.00/10, -0.00)
```

**Comment by fruch** [comment]
@amoskong  is there third party repo is going to be what's written in our docs too ?

**Comment by amoskong** [comment]
> @amoskong is there third party repo is going to be what's written in our docs too ?

Yes,  `https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/` will be added to get started documentation of debian 10

@tzach @syuu1228

**Comment by amoskong** [comment]
Hi @bentsi @fruch ,  After backported https://github.com/scylladb/scylla-cluster-tests/pull/1778,  this PR also need to be backported to 3.3

**Pull request merged**
