### PR TITLE
test(many-clients): add authenticator

### PR DESCRIPTION
**Pull request by soyacz**
We want to test many-clients scenario with authentication enabled to see the impact on the performance (and other possible aspects).

Added auth to c-s load for it.
Also increased number of connections, reaching 100k connections per db instance.

### Testing

- [x] - https://argus.scylladb.com/test/06f4ed0f-f137-4779-8169-d8cfad14103d/runs?additionalRuns[]=4c6880aa-ab60-497f-af20-d322ac2b8cc7

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevent to this change (if needed)

### CODE REVIEW

**Review by fruch — APPROVED** [review]
LGTM

**Comment by roydahan** [comment]
Screenshot 2024-01-03 at 3 12 23

Nice.
What was the request? 
100K connections per instance?
How many do we have per shard?

**Comment by soyacz** [comment]
> Screenshot 2024-01-03 at 3 12 23
> 
> Nice. What was the request? 100K connections per instance? How many do we have per shard?

request was about that number 100k, it is 16k/shard IIRC

**Review by roydahan — APPROVED** [review]

**Comment by roydahan** [comment]
@fruch / @soyacz please backport.

**Comment by soyacz** [comment]
backported

**Pull request merged**
