### PR TITLE
fix(es-upload): reduce amount of data in docs we uplaod to ES

### PR DESCRIPTION
**Pull request by vponomaryov**
Running performance tests we write lots of data to ElasticSearch
and pretty often get following error which fails test runs:

    elasticsearch.exceptions.RequestError: RequestError(
        400,
        'illegal_argument_exception',
        'Limit of total fields [1000] has been exceeded')

It happens because in some cases when we gather sysctl configs from
DB nodes we get hundreds of records for each node.
And in summary it exceeds 1000 of keys in the data we write.
So, update the code where we gather sysctls removing some huge sets
of data which are unlikely to be used by us.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by vponomaryov** [comment]
Code was tested and workable.

**Comment by fruch** [comment]
I think that @roydahan @fgelcer are the main user of this, they should say what params they actually used

**Comment by fgelcer** [comment]
> I think that @roydahan @fgelcer are the main user of this, they should say what params they actually used

this data of `sysctl` was added recently to be collected, and i have never looked into it, but it seems fair what was excluded in this PR, and it will allow us to "ignore" even more things in the future, if we find the information collected is useless.

**Comment by fgelcer** [comment]
@vponomaryov , in any case, if this is related to perf jobs, it must be backported to `branch-perf-v12` and `branch-perf-v13`

**Comment by vponomaryov** [comment]
> @vponomaryov , in any case, if this is related to perf jobs, it must be backported to `branch-perf-v12` and `branch-perf-v13`

Yes, it is related to perf jobs, because we enable writing to ES there. Updated labels as requested.

**Pull request merged**
