### PR TITLE
fix(BaseNode): change directory for startup script upload from /tmp to $HOME.

### PR DESCRIPTION
**Pull request by mikliapko**
Fix changes directory for startup script upload from /tmp to $HOME. 
The change is required for DB nodes deployed in Cloud where /tmp dir is mounted with noexec option what makes script 
execution impossible there.

### Testing

- [x] siren-sct-integration [test](https://jenkins.scylladb.com/job/scylla-staging/job/mikita/job/siren-tests/job/siren-sct-integration/123)

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### CODE REVIEW

**Comment by fruch** [comment]
@mikliapko what's the implementation in cloud ? using the `$HOME` ?

**Comment by mikliapko** [comment]
> @mikliapko what's the implementation in cloud ? using the `$HOME` ?
> 
> maybe we can just switch to it ?, there's nothing holy in /tmp for SCT, we just need to run the script.

Yes, the plan is to use $HOME in cloud nodes.
If the directory doesn't matter for SCT as you mentioned above, I will just switch to $HOME in SCT without introducing new attributes.

**Comment by fruch** [comment]
> > @mikliapko what's the implementation in cloud ? using the `$HOME` ?
> > maybe we can just switch to it ?, there's nothing holy in /tmp for SCT, we just need to run the script.
> 
> Yes, the plan is to use $HOME in cloud nodes. If the directory doesn't matter for SCT as you mentioned above, I will just switch to $HOME in SCT without introducing new attributes.

I think it would be better, the defining yet another "API" like that between the two parts

**Comment by mikliapko** [comment]
> I think it would be better, the defining yet another "API" like that between the two parts

Changed to $HOME, testing [here](https://jenkins.scylladb.com/job/scylla-staging/job/mikita/job/siren-tests/job/siren-sct-integration/123/).

@fruch 
Which SCT may I run to validate changes don't lead to any regression?

**Comment by fruch** [comment]
> > I think it would be better, the defining yet another "API" like that between the two parts
> 
> Changed to $HOME, testing [here](https://jenkins.scylladb.com/job/scylla-staging/job/mikita/job/siren-tests/job/siren-sct-integration/123/).
> 
> @fruch 
> Which SCT may I run to validate changes don't lead to any regression?

Running CI with AWS provision test, I think that should suffice

**Review by vponomaryov — APPROVED** [review]
LGTM

**Review by fruch — APPROVED** [review]
LGTM 

The provision test is failing on nemesis, unrelated to this change

**Pull request merged**
