### PR TITLE
fix(docker): switch to scylla-driver==3.25.4

### PR DESCRIPTION
**Pull request by fruch**
Cause of issues with creation connection while scylla is
loaded trying to use this version with this fix:
https://github.com/scylladb/python-driver/pull/140

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
it didn't solve the issue we thought would be related to it, but it did improve the performance of the overall test...
i don't know if we want to do it, but i will be happy to see `branch-4.5` using Scylla driver.
@roydahan , WDYT?

**Comment by fruch** [comment]
> it didn't solve the issue we thought would be related to it, but it did improve the performance of the overall test... i don't know if we want to do it, but i will be happy to see `branch-4.5` using Scylla driver. @roydahan , WDYT?

My 2 cents, there not point skewing the results in that branch and we i'm not sure how it would effect other use cases, like longevity and such. 
Also once 5.0 will be out, it would become obsolete. (I think that should be in the next week or so)

**Comment by roydahan** [comment]
We will not backport this.
Maybe in later phase for 2022.1, but not for now.

**Comment by fgelcer** [comment]
verified that it didn't fix the issue by itself, and it was decided that it won't be backported, hence closing it.

**Pull request closed without merging**
