### PR TITLE
Manager 2.3 suspend and resume tests

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by ShlomiBalalis** [comment]
https://jenkins.scylladb.com/job/manager-master/job/staging/job/centos-sanity-test-staging/

**Comment by ShlomiBalalis** [comment]
At the end of the day, the test did not require a large amount of data like I thought (at least the backup one, the repair one is running atm).
As such, I think this can be a part of the sanity

**Comment by fruch** [comment]
@ShlomiBalalis I think you can do better with the title of this PR :)

**Comment by fruch** [comment]
> At the end of the day, the test did not require a large amount of data like I thought (at least the backup one, the repair one is running atm).
> As such, I think this can be a part of the sanity

that's good, we would be able to split it in half, if needed. i.e. the backend can be part of sanity, and the repair not.
but let leave it open until you have a information you can do decisions base on

**Comment by ShlomiBalalis** [comment]
> @ShlomiBalalis I think you can do better with the title of this PR :)
> 

@fruch It's because the pr includes two commits. After I'll be done with it they title will be fixed.

> also stick to the names which are part of the feature, i.e. not suspension, but pause/resume. it would become confusing for other to understand.

The name of the feature is suspend/resume, so suspension is the correct term

**Comment by ShlomiBalalis** [comment]
@fruch test_id of the successful run: 0d79e465-d200-47d2-8df8-441d03fc1668

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
