### PR TITLE
test_default.yaml set monitoring branch to 4.4

### PR DESCRIPTION
**Pull request by amnonh**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x ] I didn't leave commented-out/debugging code
- [x ] I added the relevant `backport` labels
- [x ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ x] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ x] All new and existing unit tests passed (CI)
- [x ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by roydahan — APPROVED** [review]

**Comment by roydahan** [comment]
@amnonh what version does it support?
Shall we backport to 5.2 and 2023.1?

**Comment by amnonh** [comment]
> @amnonh what version does it support? Shall we backport to 5.2 and 2023.1?

Supported versions: 5.0,5.1,5.2,5.3,2020.1,2021.1,2022.1,2022.2,2023.1,master

Definitely backport to 5.2 and 2023.1

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by fruch — CHANGES_REQUESTED** [review]
SCT fails to create screnshots, we should investigate further before merging this

we can find some elements we expect to be visible before taking snapshots

**Comment by mykaul** [comment]
Who's looking at the screenshot breakage?

**Comment by roydahan** [comment]
@k0machi since @aleksbykov our screenshots expert is out, can you please take a look at this and fix it ?
(you can include this small change together in a new PR).

**Comment by k0machi** [comment]
> @k0machi since @aleksbykov our screenshots expert is out, can you please take a look at this and fix it ? (you can include this small change together in a new PR).

I'll take a look

**Comment by k0machi** [comment]
New version of grafana in branch-4.4 has different page structure, locators for dashboards need to be fixed for screenshots to work again. Will see if it can be done quickly, opening a task.

**Comment by roydahan** [comment]
The question is if they changed again also in branch-4.5 - @amnonh ?

**Pull request closed without merging**
