### PR TITLE
feature(k8s): support direct usage of the `PodIP` addresses for DB pods

### PR DESCRIPTION
**Pull request by vponomaryov**
In the `v1.11.0*` scylla-operator was added possibility to use PodIPs for node-to-node and node-to-client connectivity.

So, add it's support and define following new SCT config options:
- `k8s_db_node_service_type` - defines the type of the K8S `Service` objects type used for ScyllaDB pods.
  Allowed values are `""` (do not set), `"ClusterIP"`, `"Headless"` ('service' object won't have IP address), `"LoadBalancer"`.
- `k8s_db_node_to_node_broadcast_ip_type` - defines the source of the IP address to be used for the `broadcast_address` config option in the 'scylla.yaml' files. Allowed values are `""` (do not set), `"ServiceClusterIP"`, `"PodIP"` and `"ServiceLoadBalancerIngress"`.
- `k8s_db_node_to_client_broadcast_ip_type` - defines the source of the IP address to be used for the `broadcast_rpc_address` config option in the 'scylla.yaml' files. Allowed values are the same as above in the 'node-to-node' case.

To use only `PodIP`s define above options as following:
- `k8s_db_node_service_type='Headless'`
- `k8s_db_node_to_node_broadcast_ip_type='PodIP'`
- `k8s_db_node_to_client_broadcast_ip_type='PodIP'`

Or having `ServiceIP` be around but not used:
- `k8s_db_node_service_type='ClusterIP' or k8s_db_node_service_type=''`
- `k8s_db_node_to_node_broadcast_ip_type='PodIP'`
- `k8s_db_node_to_client_broadcast_ip_type='PodIP'`

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [x] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Review by fruch — APPROVED** [review]
LGTM

**Review by soyacz — COMMENTED** [review]
please update docs also

**Comment by vponomaryov** [comment]
> please update docs also

Done

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
