### PR TITLE
fix(tls-ssl-1dis-2nondis-nemesis longevity): pre create schema

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
Because of the multiple schema changes happening at the same time, this scenario can fail right after the prepare stage. As such, I amended the scenario's yaml config to pre create the schema.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by ShlomiBalalis** [comment]
The run that ran into the error initially failed roughly 8 hours in: https://jenkins.scylladb.com/job/enterprise-2022.2/job/longevity/job/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis-test/3/
I ran the fix on thursday, and the run lasted for over 30 hours, eventually only failing due to spot termination: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis-test_pre-create-schema/3/
I think we're safe to merge

@fruch @fgelcer thoughts?

**Comment by fruch** [comment]
> The run that ran into the error initially failed roughly 8 hours in: https://jenkins.scylladb.com/job/enterprise-2022.2/job/longevity/job/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis-test/3/ I ran the fix on thursday, and the run lasted for over 30 hours, eventually only failing due to spot termination: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis-test_pre-create-schema/3/ I think we're safe to merge
> 
> @fruch @fgelcer thoughts?

Looks o.k. to me...

**Review by fgelcer — APPROVED** [review]
> The run that ran into the error initially failed roughly 8 hours in: https://jenkins.scylladb.com/job/enterprise-2022.2/job/longevity/job/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis-test/3/ I ran the fix on thursday, and the run lasted for over 30 hours, eventually only failing due to spot termination: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis-test_pre-create-schema/3/ I think we're safe to merge
> 
> @fruch @fgelcer thoughts?

looks OK for me as well, but few points:
1. @roydahan , do you think that might be any relevance here to check if these schema changes are happening in the cluster under load?
2. any job that is longer than 1 day should run as `on_demand`

other than that, LGTM

**Review by fruch — APPROVED** [review]
LGTM

**Comment by ShlomiBalalis** [comment]
> 2. any job that is longer than 1 day should run as `on_demand`

This was just for my staging run to see the fix is working. Didn't want to waste money on it.

**Pull request merged**
