### PR TITLE
Add daemon-reload to rollback procedure for all distros

### PR DESCRIPTION
**Pull request by roydahan**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [x] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [x] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
@amoskong, need to update the procedure for all distros, not only centos (they are updated on enterprise 2019 upgrade)

https://docs.scylladb.com/upgrade/upgrade-opensource/upgrade-guide-from-3.1-to-3.2/upgrade-guide-from-3.1-to-3.2-rpm/

https://docs.scylladb.com/upgrade/upgrade-opensource/upgrade-guide-from-3.1-to-3.2/upgrade-guide-from-3.1-to-3.2-ubuntu-16-04/

....

**Comment by roydahan** [comment]
I tested this fix manually on failed rolling-upgrade cluster where scylla-jmx failed to start because it looks for the previous file location of (3.2)

**Comment by amoskong** [comment]
> I tested this fix manually on failed rolling-upgrade cluster where scylla-jmx failed to start because it looks for the previous file location of (3.2)

There is an issue:
- https://github.com/scylladb/scylla/issues/5522

We expect scylla both old and new scylla can reload the systemd file of scylla-server & scylla-jmx automatically.

If the config of scylla-jmx can't be loaded automatically, then it's bug of old release.
This PR is good to workaround the issue.

Hi @syuu1228 do we need to fix the old release?

**Comment by fruch** [comment]
@syuu1228 @amoskong
Why not do that for prosperity ?

https://stackoverflow.com/a/56982975

**Comment by syuu1228** [comment]
@fruch This is not about rpm build system does not automatically do reload, it actually have macros to handle everything correctly.
But since we cross-build CentOS7 .rpm on Fedora 31, the macro does not works correctly.
Because Fedora 31 macro supposed to use new rpm features, witch does not exist on CentOS7.

See https://github.com/scylladb/scylla-jmx/pull/92#discussion_r363678653 and https://github.com/scylladb/scylla-jmx/issues/94, also new pull-req https://github.com/scylladb/scylla-jmx/pull/95

**Comment by syuu1228** [comment]
@amoskong The issue caused because we build CentOS rpm on Fedora, we started it since we merged relocated packaging.
So it affects 3.1 and 3.2, but not for older versions. Not for enterprise releases, either.

**Comment by amoskong** [comment]
> @amoskong The issue caused because we build CentOS rpm on Fedora, we started it since we merged relocated packaging.
> So it affects 3.1 and 3.2, but not for older versions. Not for enterprise releases, either.

So we need to reload the systemd config in rollback to 3.1 from 3.2.
Will you fix the problem in 3.1?   you already fixed the issue in 3.2, the config can be reloaded automatically.

Currently we are using this PR in upgrade test to reload the systemd configuration, otherwise the rollback will fail. It seems we need to write this into the upgrade guide.

**Comment by syuu1228** [comment]
The fix should merge to both 3.2 and 3.1 (currently only merged to next)

**Pull request merged**
