### PR TITLE
Fetch and decode reactor stalls from job database logs or journalctl logs

### PR DESCRIPTION
**Pull request by juliayakovlev**
These scripts search in the job log or journalctl logs all stalles, find unique stalles and decode them

### CODE REVIEW

**Comment by bentsi** [comment]
@juliayakovlev 
- add **Tools** section in the **readme**
- write a short explanation of the tools 
- add run examples (I mean how to run it, not the example output)

**Comment by juliayakovlev** [comment]
@bentsi 
>> write a short explanation of the tools
>> add run examples (I mean how to run it, not the example output)
It's written in the beginning of every script

**Comment by bentsi** [comment]
@juliayakovlev as mentioned in the comment, please add the info to the **SCT Readme** so people
will be aware of the tools

**Comment by juliayakovlev** [comment]
> @juliayakovlev as mentioned in the comment, please add the info to the **SCT Readme** so people
> will be aware of the tools

@bentsi  Added

**Comment by amoskong** [comment]
@bentsi ping

**Comment by bentsi** [comment]
@juliayakovlev I meant *short* explanation, not copy pasting the documentation from the script.
Example:
```
1) utils/fetch_and_decode_stalls_from_job_database_logs.sh

     This script searches in the log all reactor stalles, find unique stalles and decode them.
    The script analyzes the database.logs that are located under avocado/job-results/<job-folder>/<test-folder>/<cluster-folder>. The script is going through nodes folders and analyze database.log for every node.
```

**Comment by bentsi** [comment]
@juliayakovlev it should look like this:

```
1) utils/fetch_and_decode_stalls_from_job_database_logs.sh

    This script searches in the log all reactor stalles, find unique stalles and decode them.
    The script analyzes the database.logs that are located under avocado/job-results/<job-folder>/<test-folder>/<cluster-folder>. The script is going through nodes folders and analyze database.log for every node.

 2) utils/fetch_and_decode_stalls_from_journalctl_logs_all_nodes.sh

    This script searches in the journalctl all reactor stalles, find unique stalles and decode them.
    Save the journalctl from every node to the database.log and move to the folders by node. Organize all folders in one folder, like:
            logs
        |            |
    node1          node2
    database.log   database.log

 3) utils/fetch_and_decode_stalls_from_one_journalctl_log.sh

    This script searches in the journalctl all reactor stalles, find unique stalles and decode them.
    Save the journalctl to the database.log and move to the folder
```

**Comment by juliayakovlev** [comment]
> @juliayakovlev it should look like this:
> 
> ```
> 1) utils/fetch_and_decode_stalls_from_job_database_logs.sh
> 
>     This script searches in the log all reactor stalles, find unique stalles and decode them.
>     The script analyzes the database.logs that are located under avocado/job-results/<job-folder>/<test-folder>/<cluster-folder>. The script is going through nodes folders and analyze database.log for every node.
> 
>  2) utils/fetch_and_decode_stalls_from_journalctl_logs_all_nodes.sh
> 
>     This script searches in the journalctl all reactor stalles, find unique stalles and decode them.
>     Save the journalctl from every node to the database.log and move to the folders by node. Organize all folders in one folder, like:
>             logs
>         |            |
>     node1          node2
>     database.log   database.log
> 
>  3) utils/fetch_and_decode_stalls_from_one_journalctl_log.sh
> 
>     This script searches in the journalctl all reactor stalles, find unique stalles and decode them.
>     Save the journalctl to the database.log and move to the folder
> ```

@bentsi  Done

**Pull request merged**
