### PR TITLE
Start rsyslog in background to bring logs

### PR DESCRIPTION
**Pull request by fruch**
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I gave variables/functions meaningful self-explanatory names
- [ ] I didn't leave commented-out/debugging code
- [ ] I didn't copy-paste code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (`hydra unit-tests`)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
oops, meant to create that as draft...

**Comment by fruch** [comment]
it's far from finish
the /etc/rsyslog.conf that needs to be changed:
```
action(type="omfwd" Target="0.tcp.ngrok.io" Port="19016" Protocol="tcp")
```

**Comment by bentsi** [comment]
I've made some progress on the weekend. Please continue from `get-db-log-with-rsyslog` on my fork https://github.com/bentsi/scylla-cluster-tests/tree/get-db-log-with-rsyslog

**Comment by fruch** [comment]
closing cause of #1153

**Pull request closed without merging**
