### PR TITLE
sdcm.cluster: Improve update_db_binary with --stop-services ami option

### PR DESCRIPTION
**Pull request by lmr**
If we're passing update_db_binary to the configuration,
let's pass --stop-services to the nodes. This is a rebased
and updated version of a previous patch by Asias He asias@scylladb.com.

Signed-off-by: Lucas Meneghel Rodrigues lmr@scylladb.com

### CODE REVIEW

**Comment by asias** [comment]
The test fails:

```
016-08-11 06:16:26,237 remote           L0832 DEBUG| Remote [centos@52.87.191.79]: Running 'sudo systemctl status scylla-io-setup.service'
2016-08-11 06:16:26,237 remote           L0094 INFO | [52.87.191.79] Running '/bin/ssh -a -x  -o ControlPath=/var/tmp/ssh-masterpV4ygx/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmp6NwsS1 -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/asias-test-long-longevity-test-9aa511ed.pem 52.87.191.79 "sudo systemctl status scylla-io-setup.service"'
2016-08-11 06:16:26,245 remote           L0832 DEBUG| Remote [centos@52.87.240.158]: Running 'sudo systemctl status scylla-io-setup.service'
2016-08-11 06:16:26,246 remote           L0094 INFO | [52.87.240.158] Running '/bin/ssh -a -x  -o ControlPath=/var/tmp/ssh-masterp70rFt/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpYaqL8u -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/asias-test-long-longevity-test-9aa511ed.pem 52.87.240.158 "sudo systemctl status scylla-io-setup.service"'
2016-08-11 06:16:26,538 remote           L0194 DEBUG| [52.90.94.54] [stdout] ● scylla-io-setup.service
2016-08-11 06:16:26,538 remote           L0194 DEBUG| [52.90.94.54] [stdout]    Loaded: not-found (Reason: No such file or directory)
2016-08-11 06:16:26,538 remote           L0194 DEBUG| [52.90.94.54] [stdout]    Active: inactive (dead)
2016-08-11 06:16:26,559 output           L0632 DEBUG| Exception in thread Thread-12:
2016-08-11 06:16:26,559 output           L0632 DEBUG| Traceback (most recent call last):
2016-08-11 06:16:26,559 output           L0632 DEBUG|   File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
2016-08-11 06:16:26,559 output           L0632 DEBUG|     self.run()
2016-08-11 06:16:26,559 output           L0632 DEBUG|   File "/usr/lib64/python2.7/threading.py", line 757, in run
2016-08-11 06:16:26,559 output           L0632 DEBUG|     self.__target(*self.__args, **self.__kwargs)
2016-08-11 06:16:26,559 output           L0632 DEBUG|   File "sdcm/cluster.py", line 1807, in node_setup
2016-08-11 06:16:26,560 output           L0632 DEBUG|     node.update_db_binary(new_scylla_bin)
2016-08-11 06:16:26,560 output           L0632 DEBUG|   File "sdcm/cluster.py", line 695, in update_db_binary
2016-08-11 06:16:26,560 output           L0632 DEBUG|     self.wait_service_status('scylla-io-setup.service', 0)
2016-08-11 06:16:26,560 output           L0632 DEBUG|   File "sdcm/cluster.py", line 685, in wait_service_status
2016-08-11 06:16:26,560 output           L0632 DEBUG|     wait.wait_for(service_status, step=5)
2016-08-11 06:16:26,560 output           L0632 DEBUG|   File "sdcm/wait.py", line 40, in wait_for
2016-08-11 06:16:26,560 output           L0632 DEBUG|     ok = func(*args, **kwargs)
2016-08-11 06:16:26,561 output           L0632 DEBUG|   File "sdcm/cluster.py", line 683, in service_status
2016-08-11 06:16:26,561 output           L0632 DEBUG|     result = self.remoter.run('sudo systemctl status %s' % service_name)
2016-08-11 06:16:26,561 output           L0632 DEBUG|   File "sdcm/remote.py", line 843, in run
2016-08-11 06:16:26,561 output           L0632 DEBUG|     watch_stdout_pattern=watch_stdout_pattern)
2016-08-11 06:16:26,561 output           L0632 DEBUG|   File "sdcm/remote.py", line 808, in _run
2016-08-11 06:16:26,561 output           L0632 DEBUG|     watch_stdout_pattern=watch_stdout_pattern)
2016-08-11 06:16:26,561 output           L0632 DEBUG|   File "sdcm/remote.py", line 215, in ssh_run
2016-08-11 06:16:26,562 output           L0632 DEBUG|     raise process.CmdError(cmd, sp.result)
2016-08-11 06:16:26,562 output           L0632 DEBUG| CmdError: Command '/bin/ssh -a -x  -o ControlPath=/var/tmp/ssh-mastera3uvDR/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpAgmdwf -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/asias-test-long-longevity-test-9aa511ed.pem 52.90.94.54 "sudo systemctl status scylla-io-setup.service"' failed (rc=3)
2016-08-11 06:16:26,562 output           L0632 DEBUG|
2016-08-11 06:16:26,632 remote           L0194 DEBUG| [52.87.191.79] [stdout] ● scylla-io-setup.service
2016-08-11 06:16:26,632 remote           L0194 DEBUG| [52.87.191.79] [stdout]    Loaded: not-found (Reason: No such file or directory)
2016-08-11 06:16:26,632 remote           L0194 DEBUG| [52.87.191.79] [stdout]    Active: inactive (dead)
2016-08-11 06:16:26,634 output           L0632 DEBUG| Exception in thread Thread-13:
2016-08-11 06:16:26,634 output           L0632 DEBUG| Traceback (most recent call last):
2016-08-11 06:16:26,634 output           L0632 DEBUG|   File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
2016-08-11 06:16:26,634 output           L0632 DEBUG|     self.run()
2016-08-11 06:16:26,634 output           L0632 DEBUG|   File "/usr/lib64/python2.7/threading.py", line 757, in run
2016-08-11 06:16:26,634 output           L0632 DEBUG|     self.__target(*self.__args, **self.__kwargs)
2016-08-11 06:16:26,634 output           L0632 DEBUG|   File "sdcm/cluster.py", line 1807, in node_setup
2016-08-11 06:16:26,635 output           L0632 DEBUG|     node.update_db_binary(new_scylla_bin)
2016-08-11 06:16:26,635 output           L0632 DEBUG|   File "sdcm/cluster.py", line 695, in update_db_binary
2016-08-11 06:16:26,635 output           L0632 DEBUG|     self.wait_service_status('scylla-io-setup.service', 0)
2016-08-11 06:16:26,635 output           L0632 DEBUG|   File "sdcm/cluster.py", line 685, in wait_service_status
2016-08-11 06:16:26,635 output           L0632 DEBUG|     wait.wait_for(service_status, step=5)
2016-08-11 06:16:26,635 output           L0632 DEBUG|   File "sdcm/wait.py", line 40, in wait_for
2016-08-11 06:16:26,635 output           L0632 DEBUG|     ok = func(*args, **kwargs)
2016-08-11 06:16:26,636 output           L0632 DEBUG|   File "sdcm/cluster.py", line 683, in service_status
2016-08-11 06:16:26,636 output           L0632 DEBUG|     result = self.remoter.run('sudo systemctl status %s' % service_name)
2016-08-11 06:16:26,636 output           L0632 DEBUG|   File "sdcm/remote.py", line 843, in run
2016-08-11 06:16:26,636 output           L0632 DEBUG|     watch_stdout_pattern=watch_stdout_pattern)
2016-08-11 06:16:26,636 output           L0632 DEBUG|   File "sdcm/remote.py", line 808, in _run
2016-08-11 06:16:26,636 output           L0632 DEBUG|     watch_stdout_pattern=watch_stdout_pattern)
2016-08-11 06:16:26,636 output           L0632 DEBUG|   File "sdcm/remote.py", line 215, in ssh_run
2016-08-11 06:16:26,637 output           L0632 DEBUG|     raise process.CmdError(cmd, sp.result)
2016-08-11 06:16:26,637 output           L0632 DEBUG| CmdError: Command '/bin/ssh -a -x  -o ControlPath=/var/tmp/ssh-masterpV4ygx/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmp6NwsS1 -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/asias-test-long-longevity-test-9aa511ed.pem 52.87.191.79 "sudo systemctl status scylla-io-setup.service"' failed (rc=3)
2016-08-11 06:16:26,637 output           L0632 DEBUG|
2016-08-11 06:16:26,640 remote           L0194 DEBUG| [52.87.240.158] [stdout] ● scylla-io-setup.service
2016-08-11 06:16:26,640 remote           L0194 DEBUG| [52.87.240.158] [stdout]    Loaded: not-found (Reason: No such file or directory)
2016-08-11 06:16:26,640 remote           L0194 DEBUG| [52.87.240.158] [stdout]    Active: inactive (dead)
2016-08-11 06:16:26,641 output           L0632 DEBUG| Exception in thread Thread-14:
2016-08-11 06:16:26,642 output           L0632 DEBUG| Traceback (most recent call last):
2016-08-11 06:16:26,642 output           L0632 DEBUG|   File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
2016-08-11 06:16:26,642 output           L0632 DEBUG|     self.run()
2016-08-11 06:16:26,642 output           L0632 DEBUG|   File "/usr/lib64/python2.7/threading.py", line 757, in run
2016-08-11 06:16:26,642 output           L0632 DEBUG|     self.__target(*self.__args, **self.__kwargs)
2016-08-11 06:16:26,642 output           L0632 DEBUG|   File "sdcm/cluster.py", line 1807, in node_setup
2016-08-11 06:16:26,642 output           L0632 DEBUG|     node.update_db_binary(new_scylla_bin)
2016-08-11 06:16:26,643 output           L0632 DEBUG|   File "sdcm/cluster.py", line 695, in update_db_binary
2016-08-11 06:16:26,643 output           L0632 DEBUG|     self.wait_service_status('scylla-io-setup.service', 0)
2016-08-11 06:16:26,643 output           L0632 DEBUG|   File "sdcm/cluster.py", line 685, in wait_service_status
2016-08-11 06:16:26,643 output           L0632 DEBUG|     wait.wait_for(service_status, step=5)
2016-08-11 06:16:26,643 output           L0632 DEBUG|   File "sdcm/wait.py", line 40, in wait_for
2016-08-11 06:16:26,643 output           L0632 DEBUG|     ok = func(*args, **kwargs)
2016-08-11 06:16:26,643 output           L0632 DEBUG|   File "sdcm/cluster.py", line 683, in service_status
2016-08-11 06:16:26,643 output           L0632 DEBUG|     result = self.remoter.run('sudo systemctl status %s' % service_name)
2016-08-11 06:16:26,644 output           L0632 DEBUG|   File "sdcm/remote.py", line 843, in run
2016-08-11 06:16:26,644 output           L0632 DEBUG|     watch_stdout_pattern=watch_stdout_pattern)
2016-08-11 06:16:26,644 output           L0632 DEBUG|   File "sdcm/remote.py", line 808, in _run
2016-08-11 06:16:26,644 output           L0632 DEBUG|     watch_stdout_pattern=watch_stdout_pattern)
2016-08-11 06:16:26,644 output           L0632 DEBUG|   File "sdcm/remote.py", line 215, in ssh_run
2016-08-11 06:16:26,644 output           L0632 DEBUG|     raise process.CmdError(cmd, sp.result)
2016-08-11 06:16:26,644 output           L0632 DEBUG| CmdError: Command '/bin/ssh -a -x  -o ControlPath=/var/tmp/ssh-masterp70rFt/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpYaqL8u -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/asias-test-long-longevity-test-9aa511ed.pem 52.87.240.158 "sudo systemctl status scylla-io-setup.service"' failed (rc=3)
2016-08-11 06:16:26,645 output           L0632 DEBUG|
```

**Comment by lmr** [comment]
Oh, I forgot to add ignore_status to the run calls. OK, will fix, thanks.

**Comment by lmr** [comment]
@asias, now that I have recompiled scylla, my problem is that restarting scylla-server is not working. I tested with the patch applied and without it. I still didn't investigate it further.

**Comment by roydahan** [comment]
Why haven't we merged this pull request?

I bump into an issue with the update_db_binary code, but this PR won't solve it as well.
Seems like when adding a node during the test, it will stop/restart services for all nodes and not only the new node... this cause the c-s I/O to the cluster to die.
For example, when running Longevity with new db binary (my case).

**Pull request closed without merging**
