### PR TITLE
defaults/test_default.yaml: update Manager default to use 3.3.0

### PR DESCRIPTION
**Pull request by mykaul**
### Testing

- [ ] None.

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by mykaul** [comment]
It's unclear to me what failed... 
18:01:02  ========= 921 passed, 17 skipped, 131 deselected in 550.44s (0:09:10) ========

**Comment by mykaul** [comment]
image

**Comment by vponomaryov** [comment]
@mykaul 

```
17:51:27  Check Yaml...........................................(no files to check)Skipped
17:51:27  Check for added large files..............................................Passed
17:51:27  Check JSON...........................................(no files to check)Skipped
17:51:28  Detect AWS Credentials...................................................Passed
17:51:28  Detect Private Key.......................................................Passed
17:51:28  autopep8.............................................(no files to check)Skipped
17:51:28  ruff.................................................(no files to check)Skipped
17:51:28  commitlint...............................................................Failed
17:51:28  - hook id: commitlint
17:51:28  - exit code: 1
17:51:28  
17:51:28  ⧗   input: defaults/test_default.yaml: update Manager default to use 3.3.0
17:51:28  
17:51:28  Signed-off-by: Yaniv Kaul <yaniv.kaul@scylladb.com>
17:51:28  ✖   subject may not be empty [subject-empty]
17:51:28  ✖   type may not be empty [type-empty]
17:51:28  ✖   scope may not be empty [scope-empty]
17:51:28  
17:51:28  ✖   found 3 problems, 0 warnings
17:51:28  ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

SCT has rules for the commit topic structure.

Need to change it to be something like the following:

```
ci(defaults): update Manager default to use 3.3.0 
```

Also, need to update like 11: `manager_version: '3.2'` -> `manager_version: '3.3'`

**Review by vponomaryov — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@mikliapko 

please first test this first, 
I'm not changing defaults, before some proof of this change working.

**Comment by mikliapko** [comment]
> @mikliapko
> 
> please first test this first, I'm not changing defaults, before some proof of this change working.

Tested it here - PASSED:
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/mikita/job/manager-master/view/Installation/job/ubuntu22-installation-test/4

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
