### PR TITLE
Fix for: the scylla_create_devices has been moved to the '/opt/scylladb' folder in the master branch

### PR DESCRIPTION
**Pull request by juliayakovlev**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [x] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by juliayakovlev** [comment]
> Can you add an else clause to the for loop ? so we'll raise an exception if we didn't found any of those files ?

Done

**Comment by fruch** [comment]
@juliayakovlev FYI, I was talking about:
https://book.pythontips.com/en/latest/for_-_else.html#else-clause

can save a few lines, and defining a variable.
keep it in mind next time you have a loop with break

**Comment by fruch** [comment]
@roydahan Are you o.k. with back porting this one ? I think it's safe enough, or we can assume the branches won't get this change in scylla-ami ?

**Comment by juliayakovlev** [comment]
> @juliayakovlev FYI, I was talking about:
> https://book.pythontips.com/en/latest/for_-_else.html#else-clause
> 
> can save a few lines, and defining a variable.
> keep it in mind next time you have a loop with break

@fruch 
Done. Thanks

**Comment by roydahan** [comment]
I don't think we need to backport it.
wait with the merge few minutes, Shlomi ask to check why the location has changed.

**Comment by roydahan** [comment]
removed the backports for now.
We hit it only in master.

**Pull request merged**
