### PR TITLE
improvement(ruff): add f-string logs check

### PR DESCRIPTION
**Pull request by soyacz**
We miss f-string log checks in ruff and cause issues with backporting (and anyway we want to keep it).

Fixed along issues with it in most of cases.

### Testing

- [ ]

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
I'm, not completely sure we want to keep (for example for dtest we don't enforce it)
the speed up from it isn't that great (or relevant to SCT), and the usability vs. f-string , kind of sucks..

we could disable it on the branches... 

I'm not sure

**Comment by soyacz** [comment]
> I'm, not completely sure we want to keep (for example for dtest we don't enforce it) the speed up from it isn't that great (or relevant to SCT), and the usability vs. f-string , kind of sucks..
> 
> we could disable it on the branches...
> 
> I'm not sure

I wasn't taking decision to enable it, so I conformed.
I agree this is not relevant to SCT as anyway we always run with debug logs (and we don't use trace logs).

Let's other maintainers take the side

**Comment by roydahan** [comment]
I like f-strings and hate this stupid lint check to replace it.

**Comment by fruch** [comment]
> I like f-strings and hate this stupid lint check to replace it.

ruff is even **nicer**, he know to replace it automatically, not just to warn you about it.

**Review by vponomaryov — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@soyacz remember to close this, and disable this check on releases pylint

**Comment by soyacz** [comment]
closing in favor of https://github.com/scylladb/scylla-cluster-tests/pull/7957

**Pull request closed without merging**
