### PR TITLE
fix(cluster_init): Add recommended cluster initialization with bootst…

### PR DESCRIPTION
**Pull request by aleksbykov**
…rap enabled

According to scylla doc next schema of cluster initializtion should be used:
1. choose one node as seed.
2. update scylla.yaml on all other node with seed ip(only one)
3. start scylla on node as seed with auto bootstrap enabled
4. start next node with autobootstrap enabled.
5. wait node is UN
6. Repeat 4, 5 for all other node.
7. update scylla.yaml with required number of seeds ips. Reboot not required

docs:
https://docs.scylladb.com/operating-scylla/procedures/cluster-management/create_cluster/

Also was added code from commit:
https://github.com/scylladb/scylla-cluster-tests/pull/2856/

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [x] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by aleksbykov** [comment]
Only to branch-perf-v8

**Comment by fruch** [comment]
@aleksbykov have you tested this already ? and it's proven working ?

**Review by fruch — APPROVED** [review]
LGTM, 
even that I think we should kill this branch already.
What's holding us back from doing that ?

**Review by roydahan — APPROVED** [review]

**Comment by fruch** [comment]
@aleksbykov 
I've tried to run this one:
https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-aws-test-throughput/67/

seem to failing:
```
15:14:19  < t:2020-11-24 13:14:04,448 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > 2020-11-24 13:14:04.436: (TestFrameworkEvent Severity.CRITICAL), source=PerformanceRegressionTest.SetUp()message=None
15:14:19  < t:2020-11-24 13:14:04,448 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > exception=Traceback (most recent call last):
15:14:19  < t:2020-11-24 13:14:04,448 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/tester.py", line 277, in setUp
15:14:19  < t:2020-11-24 13:14:04,448 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     self.init_nodes(db_cluster=self.db_cluster)
15:14:19  < t:2020-11-24 13:14:04,448 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/tester.py", line 244, in init_nodes
15:14:19  < t:2020-11-24 13:14:04,448 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     db_cluster.wait_for_init(node_list=db_cluster.nodes)
15:14:19  < t:2020-11-24 13:14:04,448 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/cluster.py", line 2906, in wrapper
15:14:19  < t:2020-11-24 13:14:04,448 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     verify_node_setup(start_time)
15:14:19  < t:2020-11-24 13:14:04,448 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/cluster.py", line 2886, in verify_node_setup
15:14:19  < t:2020-11-24 13:14:04,448 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     raise NodeSetupFailed(node=node, error_msg=setup_exception[0], traceback_str=setup_exception[1])
15:14:19  < t:2020-11-24 13:14:04,448 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > TypeError: NodeSetupFailed does not take keyword arguments
```

**Pull request merged**
