### PR TITLE
feature(k8s-serverless): deploy ingress (sni_proxy)

### PR DESCRIPTION
**Pull request by fruch**
base on the examples from:
https://github.com/scylladb/scylla-operator/pull/1076

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by vponomaryov** [comment]
Working variant is here: https://github.com/scylladb/scylla-cluster-tests/pull/5393
Just need to wait for the following things:
- Merge of the https://github.com/scylladb/gocql/pull/106
- Adoption of it in the `scylla-operator`

**Comment by fruch** [comment]
> Working variant is here: #5393 Just need to wait for the following things:
> 
> * Merge of the [Use ConnectionConfig values when establishing session to initial contact point gocql#106](https://github.com/scylladb/gocql/pull/106)
> * Adoption of it in the `scylla-operator`

why do need this fix ? operator is doing CQL ? can you elaborate a bit ?

I'm also waiting for this and a few other things to get fixed:
https://github.com/scylladb/qa-tasks/issues/8#issuecomment-1308320719

**Comment by fruch** [comment]
Anyone closing this one

**Comment by vponomaryov** [comment]
> > Working variant is here: #5393 Just need to wait for the following things:
> > 
> > * Merge of the [Use ConnectionConfig values when establishing session to initial contact point gocql#106](https://github.com/scylladb/gocql/pull/106)
> > * Adoption of it in the `scylla-operator`
> 
> why do need this fix ? operator is doing CQL ? can you elaborate a bit ?
> 
> I'm also waiting for this and a few other things to get fixed: [scylladb/qa-tasks#8 (comment)](https://github.com/scylladb/qa-tasks/issues/8#issuecomment-1308320719)

Good question, looks like it is needed only for the operator's e2e tests and not operator itself.
Then even better for us.

**Pull request closed without merging**
