### PR TITLE
fix(azure): add more timeout for hard reboots

### PR DESCRIPTION
**Pull request by fruch**
since Azure can schedule the restart up to 15-18min into the
future, we need to wait more time for it to finish.
Fix: #5608

## Testing

- [x] - https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity-10gb-3h-azure-test/15/

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by soyacz — APPROVED** [review]

**Comment by roydahan** [comment]
@fruch I think this PR is wrong.
It shouldn't take so long to reboot a node and something is off and need to be reported if this is the case as you mentioned above.

In a run I'm looking at, I see that a boot takes 6 minutes (which still sounds a lot to me):
```
Mar 23 18:06:45 longevity-10gb-3h-2023-1-db-node-eastus-8 systemd[1]: scylla-image-setup.service: Consumed 14.818s CPU time.
-- Boot 17f33b6a12f34833915e651c6b79a865 --
Mar 23 18:12:20 longevity-10gb-3h-2023-1-db-node-eastus-8 systemd[1]: Starting Scylla Cloud Image Setup service...
...
...
Mar 23 18:12:50 longevity-10gb-3h-2023-1-db-node-eastus-8 scylla[904]:  [shard 0] init - Scylla version 2023.1.0~rc3-0.20230321.80de75947b7a initialization completed.

```

This is a [run](https://argus.scylladb.com/test/495648b9-1123-4547-a33b-eef73457c1db/runs?additionalRuns[]=302e60f7-0150-4882-9525-5ba9253ebb18) without your fix and it should have passed even without your fix (1200 timeout was good enough).

However, it looks like the actual issue is something wrong (by parallel_object?), we rebooted the host twice although the nemesis didn't planned to do it and it's not clear if the watcher missed the first boot of the node or not.
Check out the logs of node-8.
It had boot in 17:46:56 and another one in 18:06.

**Comment by fruch** [comment]
> @fruch I think this PR is wrong.
> It shouldn't take so long to reboot a node and something is off and need to be reported if this is the case as you mentioned above.
> 
> In a run I'm looking at, I see that a boot takes 6 minutes (which still sounds a lot to me):
> ```
> Mar 23 18:06:45 longevity-10gb-3h-2023-1-db-node-eastus-8 systemd[1]: scylla-image-setup.service: Consumed 14.818s CPU time.
> -- Boot 17f33b6a12f34833915e651c6b79a865 --
> Mar 23 18:12:20 longevity-10gb-3h-2023-1-db-node-eastus-8 systemd[1]: Starting Scylla Cloud Image Setup service...
> ...
> ...
> Mar 23 18:12:50 longevity-10gb-3h-2023-1-db-node-eastus-8 scylla[904]:  [shard 0] init - Scylla version 2023.1.0~rc3-0.20230321.80de75947b7a initialization completed.
> 
> ```
> 
> This is a [run](https://argus.scylladb.com/test/495648b9-1123-4547-a33b-eef73457c1db/runs?additionalRuns[]=302e60f7-0150-4882-9525-5ba9253ebb18) without your fix and it should have passed even without your fix (1200 timeout was good enough).
> 
> However, it looks like the actual issue is something wrong (by parallel_object?), we rebooted the host twice although the nemesis didn't planned to do it and it's not clear if the watcher missed the first boot of the node or not.
> Check out the logs of node-8.
> It had boot in 17:46:56 and another one in 18:06.
> 
> 
> 

It nothing todo with parallel, we've seen it multiple times, azure doesn't gurrentee reboot would be immediate, and they even write it down that the operation is scheduled to a later time.

Now that our account is "real", maybe we can open a support ticket. But until then, this change is the best we can do.

**Comment by roydahan** [comment]
Do they guarantee soft reboot?
Is so, we can do that instead for Azure.
I still don't understand what caused the reboot at 17:46.

**Comment by fruch** [comment]
> Do they guarantee soft reboot?
> Is so, we can do that instead for Azure.
> I still don't understand what caused the reboot at 17:46.

They don't guarantee anything, it's not written anywhere that I could find, it's just an observation of how the APIs behave.

If it's soft reboot vs. timeout of 10 more minutes, I don't think it's a big difference for us.

I didn't into the specific case, I would assume you are seeing the next nemesis in action, there's no retries that I know of in that sequence (it's not an ssh command, it's an API call, and parallel object doesn't have retries)

**Comment by fruch** [comment]
I suggest we let it run for a while and see, if there are more issues with this fix or if it's enough

**Pull request merged**
