### PR TITLE
Set destroy as a default post behaviour for Cloud Longevity tests

### PR DESCRIPTION
**Pull request by bentsi**

### CODE REVIEW

**Comment by slivne** [comment]
please set a time limit in hours for the tests ....

how long should this tests run ?

do we mark them with keep:alive.

if they run for 3 hours - they should not be marked with keep:alive

**Comment by roydahan** [comment]
They are running for 48 hours.

**Comment by bentsi** [comment]
@slivne the test run for 48 hours. We have a task in a pipeline to limit the time to the test run + K hours

**Comment by fruch** [comment]
> please set a time limit in hours for the tests ....
> 
> how long should this tests run ?
> 
> do we mark them with keep:alive.
> 
> if they run for 3 hours - they should not be marked with keep:alive

@slivne those the same cleanup script run on the cloud ? that support the new `keep:[duration]` format ?

**Comment by fruch** [comment]
@bentsi I don't think this should be enough of a change, since the pipeline would overwrite it:

https://github.com/scylladb/scylla-cluster-tests/blob/master/vars/scyllaCloudLongevityPipeline.groovy#L27

**Comment by slivne** [comment]
yes all of them have the same script

**Pull request merged**
