### PR TITLE
improvement(GCE create_instance): Create GCE lables for instances

### PR DESCRIPTION
**Pull request by roydahan**
Creating the tags we have in AWS also as labels in GCE.
Till now we created them only as metadata for instances, but this
information can't be use in other places like billing.

The reason we did not create them as labels is that the label format
is very restricting, allowing only lower case, numbers, dash and
underscore. Hence, the labels aren't going to replace the metadata
and are going to be opportunistic. It means that only if the values
match the format, the labels will be created. Otherwise there is a
warning but the test continues.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
@amnonh FYI for what you need.

**Comment by roydahan** [comment]
Positive test I ran: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/roy/job/test_gce_labels/7/console

**Review by fruch — APPROVED** [review]
LGTM

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by dkropachev — APPROVED** [review]

**Pull request merged**
