### PR TITLE
Performance tests run using pipeline

### PR DESCRIPTION
**Pull request by aleksbykov**
- Performance tests rebased on branch-3.2
- Prepare pipeline for performancetests
- Changed query for ES to search results for old runs and new one
- fixed minor issues

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I gave variables/functions meaningful self-explanatory names
- [ ] I didn't leave commented-out/debugging code
- [ ] I didn't copy-paste code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
Why this commit isn't to master ?

@aleksbykov can you add a link to a working Jenkins job ?

**Comment by aleksbykov** [comment]
@fruch problem is that it is based on branch-3.2 and not on master.
Job links: 
https://jenkins.scylladb.com/view/Performance/job/Perf-Regression/job/scylla-release-perf-regression-aws-test-latency/5/
https://jenkins.scylladb.com/view/Performance/job/Perf-Regression/job/scylla-release-perf-regression-aws-test-throughput/

**Comment by fruch** [comment]
> @fruch problem is that it is based on branch-3.2 and not on master.
> Job links:
> https://jenkins.scylladb.com/view/Performance/job/Perf-Regression/job/scylla-release-perf-regression-aws-test-latency/5/
> https://jenkins.scylladb.com/view/Performance/job/Perf-Regression/job/scylla-release-perf-regression-aws-test-throughput/

I understand it, but my question is why ? don't we also want this in master ?
i.e. why this is different from any other feature, that goes first to master, and then backported to any branch isn't needed it ?

**Comment by roydahan** [comment]
I think that how @bentsi phrased the task is a bit confusing.

@bentsi did you mean that the jobs should be configured like latest jobs (which at the point you opened it were 3.2)?

**Comment by bentsi** [comment]
1. @aleksbykov where is the link to the task?
2. @roydahan the task was called so since back then (`Nov 28, 2019 at 2:43 PM`) we wanted just to run the performance tests using the latest stable that was `branch-3.2` due to avocado/other issues and not to develop new features or fix something. So I wanted to check if perf jobs work correctly on 3.2 branch. 
When Alex started working on it, there were new requirements added, like moving it to pipeline and more. If so we certainly need this code to be in master!

**Comment by aleksbykov** [comment]
Adding new PR with rebasing on master
https://github.com/scylladb/scylla-cluster-tests/pull/1765

**Comment by fruch** [comment]
> Adding new PR with rebasing on master
> #1765

Also I need this merge, for working on alternator perf test

**Comment by fruch** [comment]
Also seems like there's a pylint error, can you add a commit to fix it ? (Even that it's not this change making it ?

**Comment by fruch** [comment]
@aleksbykov is this PR needed ? since there a PR open for master ?

**Comment by aleksbykov** [comment]
I think no.

**Comment by bentsi** [comment]
So I am closing this

**Pull request closed without merging**
