### PR TITLE
change default monitor branch to 2.4

### PR DESCRIPTION
**Pull request by roydahan**
Not sure why we have 2 defaults but changes them both.

### CODE REVIEW

**Comment by fruch** [comment]
@roydahan we have two defaults since we still support running with accovado style configuration, we should remove them once removing avocado.

**Comment by fruch** [comment]
@roydahan did you run it with this vesrion already ?

**Comment by roydahan** [comment]
No, I prefer to have surprises :)

**Comment by fruch** [comment]
@roydahan living on the edge... closest to extreme sport for me :)

**Comment by bentsi** [comment]
@roydahan Why to hurry? somebody needs to check this.
possible failures:
- monitoring stack won't start
- prometheus configuration failures
- dashboards/links broken
- snapshot feature won't work

**Comment by roydahan** [comment]
so if we merge it someone will be forced to test it :)

**Pull request merged**
