### PR TITLE
test(longevity): remove longevity-large-partition-200k-pks-2days-aws-i4i

### PR DESCRIPTION
**Pull request by juliayakovlev**
By Roy's request:
https://github.com/scylladb/scylla-cluster-tests/pull/6418/files#r1279706134 remove large partition i4i longevity

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by juliayakovlev** [comment]
@roydahan there are 7 jobs with this yaml. Do disable them or delete?

**Comment by fgelcer** [comment]
> @roydahan there are 7 jobs with this yaml. Do disable them or delete?

they are jobs on different branches... and i'm not sure the change to `i4i` instances was backported, but to all branches it was backported, then the job should be disabled

**Comment by fruch** [comment]
> @roydahan there are 7 jobs with this yaml. Do disable them or delete?

It should be deleted from master and enterprise, after this would be merged.

No need to backport this PR.

On release as @fgelcer mentioned we should disable (anyhow none of those are triggered right ?)

**Comment by fgelcer** [comment]
> none of those are triggered right ?

they should not

**Comment by juliayakovlev** [comment]
@fruch @roydahan @fgelcer 
Can you merge if it ok?

**Comment by juliayakovlev** [comment]
unit tests failed with:
```
16:13:14  FAILED unit_tests/test_scan_operation_thread.py::test_scan_positive[aggregate] - AssertionError: Subscriber <EventsFileLogger name='EventsFileLogger-107' pid=2901 parent=10 started daemon> didn't receive 2 events in 10 seconds
16:13:14  ===== 1 failed, 881 passed, 21 skipped, 53 deselected in 672.61s (0:11:12) =====
```

that is not due to this commit

**Comment by fgelcer** [comment]
> @fruch @roydahan @fgelcer Can you merge if it ok?

i don't have the privilege to merge it as is...

**Comment by juliayakovlev** [comment]
> > @roydahan there are 7 jobs with this yaml. Do disable them or delete?
> 
> It should be deleted from master and enterprise, after this would be merged.
> 
> No need to backport this PR.
> 
> On release as @fgelcer mentioned we should disable (anyhow none of those are triggered right ?)

@fruch 
I am going to delete:
https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-large-partition-200k-pks-2days-aws-i4i-test/
https://jenkins.scylladb.com/job/scylla-enterprise/job/longevity/job/longevity-large-partition-200k-pks-2days-aws-i4i-test/
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/longevity/job/longevity-large-partition-200k-pks-2days-aws-i4i-test/

Any objections?

**Comment by juliayakovlev** [comment]
> > @roydahan there are 7 jobs with this yaml. Do disable them or delete?
> 
> they are jobs on different branches... and i'm not sure the change to `i4i` instances was backported, but to all branches it was backported, then the job should be disabled

@fruch @fgelcer 

The jobs are disabled on releases: 5.3, 5.3 releng, 2023.1

**Pull request merged**
