### PR TITLE
test(upgrade): run upgrade test with SLA [branch 2022.2]

### PR DESCRIPTION
**Pull request by juliayakovlev**
This test was added by https://github.com/scylladb/scylla-cluster-tests/pull/5421 But it's not compatible with branch-2022.2.
Create separate commit

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by juliayakovlev** [comment]
The rolling upgrade test finished with error `Too many in flight hints`, but it's not connected to this commit.
https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/rolling-upgrade-with-sla/22/

I'll run longevity_sla test

**Comment by juliayakovlev** [comment]
Test https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/staging-sla-100gb-4h/59/ runs cassandra-stress with SLA successfully

**Review by fruch — APPROVED** [review]
LGTM

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
