### PR TITLE
improvement(k8s): remove redundant config options for K8S backends

### PR DESCRIPTION
**Pull request by vponomaryov**
Remove the `k8s_scylla_datacenter` and the `k8s_scylla_rack` config options as redundant.
Use real region name instead of the value of the `k8s_scylla_datacenter` in EKS and GKE clusters.
Use automatically defined one for the local K8S as `local-dc-1`.

Then, use only automatically defined value `rack-1` instead of the `k8s_scylla_rack` config option's value.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by vponomaryov** [comment]
This is one of many planned improvement PRs before the multiDC feature support addition.

**Review by fruch — COMMENTED** [review]
Lgtm

**Comment by vponomaryov** [comment]
> Lgtm

The `approve` button has been used.

**Review by soyacz — APPROVED** [review]
LGTM

**Comment by vponomaryov** [comment]
@fruch , @soyacz the follow-up PR with fix for the GKE is here: https://github.com/scylladb/scylla-cluster-tests/pull/6739

**Pull request merged**
