### PR TITLE
fix(ubuntu22 artifacts): workaround - remove manager

### PR DESCRIPTION
**Pull request by fgelcer**
manager doesn't yet support ubuntu 22.04.
artifacts are failing, because we do install
manager agent along with Scylla, and because
manager doesn't yet support it, test are currently
failing.

Refs: #4924

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by yaronkaikov — APPROVED** [review]

**Comment by fgelcer** [comment]
> @fgelcer what are you stating manager doesn't support it ? the debian package is unified and it should be working:
> 
> http://downloads.scylladb.com.s3.amazonaws.com/deb/debian/scylladb-manager-3.0.list
> 
> see the rest of the debian based list files, are identical

i heard from @ShlomiBalalis , and @yaronkaikov can confirm, that it is not supported, so there is no proper support for it now

**Comment by fruch** [comment]
> > @fgelcer what are you stating manager doesn't support it ? the debian package is unified and it should be working:
> > http://downloads.scylladb.com.s3.amazonaws.com/deb/debian/scylladb-manager-3.0.list
> > see the rest of the debian based list files, are identical
> 
> i heard from @ShlomiBalalis , and @yaronkaikov can confirm, that it is not supported, so there is no proper support for it now

I've just installed the manager agent just fine on 22.04, from straight out of `http://downloads.scylladb.com.s3.amazonaws.com/deb/debian/scylladb-manager-3.0.list`:
```
❯ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
```

who exactly is going say which version is supported, if not us after it's tested ?

**Comment by yaronkaikov** [comment]
@fruch in general ubuntu:22.04 is supported starting from 5.0 and 2022.1 (Ref: https://docs.scylladb.com/getting-started/os-support/) 

@tzach any page regarding manager?

**Comment by fgelcer** [comment]
the issue with the manager, is that it depends on a backend that supports that OS, so, support to Ubuntu 22.04 on manager is most likely set when we have a released Scylla version that supports that OS (2022.1)

**Comment by fruch** [comment]
> the issue with the manager, is that it depends on a backend that supports that OS, so, support to Ubuntu 22.04 on manager is most likely set when we have a released Scylla version that supports that OS (2022.1)

That's maybe true for the manager-server (even that I don't see the real value of pinning it to an enterprise version, for no technical reason), the agent need to be installed regardless, and in those artifacts test we are installing only the agent, and not the server.

adding this limitation artificially is just shooting our-self in the leg, waiting a whole year until testing new distro releases with the manager.

**Comment by fgelcer** [comment]
i will add "support" for it, and try to run it in a staging, but if it doesn't work, i will remove it (using this PR)

**Comment by fgelcer** [comment]
replaced this PR with #4928

**Pull request closed without merging**
