### PR TITLE
feature(k8s-eks): update k8s to verison 1.24

### PR DESCRIPTION
**Pull request by fruch**
Since we want to test operator 1.8 with latest versions of k8s, we are switch to use 1.24 which is the latest available in EKS

## Testing
- [x] functional - https://jenkins.scylladb.com/job/scylla-operator/job/operator-1.8/job/upgrade/job/upgrade-platform-k8s-eks/4/
- [x] longevity - https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity-scylla-operator-3h-eks/25/

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
seems that the minio is failing to install:
```
23:23:35  >               raise DockerException(f"{self._helm_container}: {res.output.decode('utf-8')}")
23:23:35  E               docker.errors.DockerException: <20bcd312af functional-k8s-eks--localhost-f7ba457e-d597-4288-b569-6a75a34f2557-helm>: install.go:178: [debug] Original chart version: ""
23:23:35  E               install.go:195: [debug] CHART PATH: /home/ubuntu/scylla-cluster-tests/sdcm/k8s_configs/minio
23:23:35  E               
23:23:35  E               client.go:128: [debug] creating 6 resource(s)
23:23:35  E               client.go:299: [debug] Starting delete for "minio-make-bucket-job" Job
23:23:35  E               client.go:328: [debug] jobs.batch "minio-make-bucket-job" not found
23:23:35  E               client.go:128: [debug] creating 1 resource(s)
23:23:35  E               client.go:529: [debug] Watching for changes to Job minio-make-bucket-job with timeout of 5m0s
23:23:35  E               client.go:557: [debug] Add/Modify event for minio-make-bucket-job: ADDED
23:23:35  E               client.go:596: [debug] minio-make-bucket-job: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
23:23:35  E               client.go:557: [debug] Add/Modify event for minio-make-bucket-job: MODIFIED
23:23:35  E               client.go:596: [debug] minio-make-bucket-job: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
23:23:35  E               client.go:557: [debug] Add/Modify event for minio-make-bucket-job: MODIFIED
23:23:35  E               client.go:596: [debug] minio-make-bucket-job: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
23:23:35  E               client.go:557: [debug] Add/Modify event for minio-make-bucket-job: MODIFIED
23:23:35  E               client.go:596: [debug] minio-make-bucket-job: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
23:23:35  E               client.go:557: [debug] Add/Modify event for minio-make-bucket-job: MODIFIED
23:23:35  E               client.go:596: [debug] minio-make-bucket-job: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
23:23:35  E               Error: INSTALLATION FAILED: failed post-install: timed out waiting for the condition
23:23:35  E               helm.go:84: [debug] failed post-install: timed out waiting for the condition
23:23:35  E               INSTALLATION FAILED
23:23:35  E               main.newInstallCmd.func2
23:23:35  E               	helm.sh/helm/v3/cmd/helm/install.go:127
23:23:35  E               github.com/spf13/cobra.(*Command).execute
23:23:35  E               	github.com/spf13/cobra@v1.3.0/command.go:856
23:23:35  E               github.com/spf13/cobra.(*Command).ExecuteC
23:23:35  E               	github.com/spf13/cobra@v1.3.0/command.go:974
23:23:35  E               github.com/spf13/cobra.(*Command).Execute
23:23:35  E               	github.com/spf13/cobra@v1.3.0/command.go:902
23:23:35  E               main.main
23:23:35  E               	helm.sh/helm/v3/cmd/helm/helm.go:83
23:23:35  E               runtime.main
23:23:35  E               	runtime/proc.go:255
23:23:35  E               runtime.goexit
23:23:35  E               	runtime/asm_amd64.s:1581
```

**Comment by fruch** [comment]
> seems that the minio is failing to install:
> 
> ```
> 23:23:35  >               raise DockerException(f"{self._helm_container}: {res.output.decode('utf-8')}")
> 23:23:35  E               docker.errors.DockerException: <20bcd312af functional-k8s-eks--localhost-f7ba457e-d597-4288-b569-6a75a34f2557-helm>: install.go:178: [debug] Original chart version: ""
> 23:23:35  E               install.go:195: [debug] CHART PATH: /home/ubuntu/scylla-cluster-tests/sdcm/k8s_configs/minio
> 23:23:35  E               
> 23:23:35  E               client.go:128: [debug] creating 6 resource(s)
> 23:23:35  E               client.go:299: [debug] Starting delete for "minio-make-bucket-job" Job
> 23:23:35  E               client.go:328: [debug] jobs.batch "minio-make-bucket-job" not found
> 23:23:35  E               client.go:128: [debug] creating 1 resource(s)
> 23:23:35  E               client.go:529: [debug] Watching for changes to Job minio-make-bucket-job with timeout of 5m0s
> 23:23:35  E               client.go:557: [debug] Add/Modify event for minio-make-bucket-job: ADDED
> 23:23:35  E               client.go:596: [debug] minio-make-bucket-job: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
> 23:23:35  E               client.go:557: [debug] Add/Modify event for minio-make-bucket-job: MODIFIED
> 23:23:35  E               client.go:596: [debug] minio-make-bucket-job: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
> 23:23:35  E               client.go:557: [debug] Add/Modify event for minio-make-bucket-job: MODIFIED
> 23:23:35  E               client.go:596: [debug] minio-make-bucket-job: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
> 23:23:35  E               client.go:557: [debug] Add/Modify event for minio-make-bucket-job: MODIFIED
> 23:23:35  E               client.go:596: [debug] minio-make-bucket-job: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
> 23:23:35  E               client.go:557: [debug] Add/Modify event for minio-make-bucket-job: MODIFIED
> 23:23:35  E               client.go:596: [debug] minio-make-bucket-job: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
> 23:23:35  E               Error: INSTALLATION FAILED: failed post-install: timed out waiting for the condition
> 23:23:35  E               helm.go:84: [debug] failed post-install: timed out waiting for the condition
> 23:23:35  E               INSTALLATION FAILED
> 23:23:35  E               main.newInstallCmd.func2
> 23:23:35  E               	helm.sh/helm/v3/cmd/helm/install.go:127
> 23:23:35  E               github.com/spf13/cobra.(*Command).execute
> 23:23:35  E               	github.com/spf13/cobra@v1.3.0/command.go:856
> 23:23:35  E               github.com/spf13/cobra.(*Command).ExecuteC
> 23:23:35  E               	github.com/spf13/cobra@v1.3.0/command.go:974
> 23:23:35  E               github.com/spf13/cobra.(*Command).Execute
> 23:23:35  E               	github.com/spf13/cobra@v1.3.0/command.go:902
> 23:23:35  E               main.main
> 23:23:35  E               	helm.sh/helm/v3/cmd/helm/helm.go:83
> 23:23:35  E               runtime.main
> 23:23:35  E               	runtime/proc.go:255
> 23:23:35  E               runtime.goexit
> 23:23:35  E               	runtime/asm_amd64.s:1581
> ```

After looking it up seems like since k8s 1.23, we need ebs-csi-driver to be install so we can use EBS.
https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi-migration-faq.html

setting to roles and permission for it, is a bit trick, so it's blocking us. (or we need to disable minio)

**Comment by soyacz** [comment]
> setting to roles and permission for it, is a bit trick, so it's blocking us. (or we need to disable minio)

I cannot find the reason why we use minio for Scylla Manager instead of s3. @fruch @vponomaryov do you know why we need it?

**Comment by fruch** [comment]
> > setting to roles and permission for it, is a bit trick, so it's blocking us. (or we need to disable minio)
> 
> I cannot find the reason why we use minio for Scylla Manager instead of s3. @fruch @vponomaryov do you know why we need it?

Most of the reasoning seems to be documented here:
https://github.com/scylladb/qa-tasks/issues/205

I've open this today, so we could track it, and actually fix it:
https://github.com/scylladb/qa-tasks/issues/949

**Comment by soyacz** [comment]
> > > setting to roles and permission for it, is a bit trick, so it's blocking us. (or we need to disable minio)
> > 
> > 
> > I cannot find the reason why we use minio for Scylla Manager instead of s3. @fruch @vponomaryov do you know why we need it?
> 
> Most of the reasoning seems to be documented here: [scylladb/qa-tasks#205](https://github.com/scylladb/qa-tasks/issues/205)

thanks
> 
> I've open this today, so we could track it, and actually fix it: [scylladb/qa-tasks#949](https://github.com/scylladb/qa-tasks/issues/949)

I'd opt for this solution instead fixing minio to work with ebs on new version of k8s (I believe issue is only for EKS).
E.g. when I think of scale test, minio disk space reservation would be very big (and actually unknown).

**Comment by fruch** [comment]
> > > > setting to roles and permission for it, is a bit trick, so it's blocking us. (or we need to disable minio)
> > > 
> > > 
> > > I cannot find the reason why we use minio for Scylla Manager instead of s3. @fruch @vponomaryov do you know why we need it?
> > 
> > 
> > Most of the reasoning seems to be documented here: [scylladb/qa-tasks#205](https://github.com/scylladb/qa-tasks/issues/205)
> 
> thanks
> 
> > I've open this today, so we could track it, and actually fix it: [scylladb/qa-tasks#949](https://github.com/scylladb/qa-tasks/issues/949)
> 
> I'd opt for this solution instead fixing minio to work with ebs on new version of k8s (I believe issue is only for EKS). E.g. when I think of scale test, minio disk space reservation would be very big (and actually unknown).

the issue is that the solution for them both is very similar, it's granting permission to a specific cluster.
once we have that solved and working, it should be relatively easy to solve them both.

**Pull request merged**
