### PR TITLE
fix(k8s): skip empty rack deletion test and nemesis for broken versions

### PR DESCRIPTION
**Pull request by vponomaryov**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by soyacz** [comment]
what is `empty rack`?

**Comment by vponomaryov** [comment]
> what is `empty rack`?

Scylla-operator allows to create Scylla clusters using 1+ `rack`s. And when we delete a pod which is last in a rack it becomes empty.

**Comment by vponomaryov** [comment]
@soyacz 
With this PR the functional tests now work: https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-cluster-tests/job/PR-6503/3/execution/node/115/log/?consoleFull
The bug https://github.com/scylladb/scylla-enterprise/issues/3211 doesn't affect it because the target test now gets skipped conditionally.

**Comment by vponomaryov** [comment]
@soyacz 
Since @fruch is on vacation this and next week, this one is waiting only for you.
Also, note, that it is needed to workaround the following bug: https://github.com/scylladb/scylla-enterprise/issues/3211
This bug we catch in lots of K8S test runs.

**Review by soyacz — APPROVED** [review]
LGTM

**Comment by soyacz** [comment]
@vponomaryov still we need another approve to merge it (unless you have this ability with one review)

**Comment by vponomaryov** [comment]
@scylladb/qa-maintainers Please, review it and merge. We will need it in the upcoming scylla-operator release testing.

**Review by temichus — APPROVED** [review]

**Pull request merged**
