### PR TITLE
fix(sles artifacts): removing usupported manager options

### LINKED ISSUE #4016: Disable scylla-manager test on SLES15
The [artifacts-sles15-test](https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-sles15-test/) is trying to test scylla-manager on SLES15 which isn't supported (which of course causes the test to fail),
The sles15 config should be updated accordingly (at least until it will be supported).

```
[2021-10-07T03:11:38.799Z] < t:2021-10-07 03:11:38,032 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     self.params = init_and_verify_sct_config()
[2021-10-07T03:11:38.800Z] < t:2021-10-07 03:11:38,032 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/jenkins/slave/workspace/scylla-master/artifacts/artifacts-sles15-test/scylla-cluster-tests/sdcm/sct_config.py", line 1860, in init_and_verify_sct_config
[2021-10-07T03:11:38.800Z] < t:2021-10-07 03:11:38,032 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     sct_config.verify_configuration()
[2021-10-07T03:11:38.800Z] < t:2021-10-07 03:11:38,032 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/jenkins/slave/workspace/scylla-master/artifacts/artifacts-sles15-test/scylla-cluster-tests/sdcm/sct_config.py", line 1643, in verify_configuration
[2021-10-07T03:11:38.800Z] < t:2021-10-07 03:11:38,032 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     self._check_unexpected_sct_variables()
[2021-10-07T03:11:38.800Z] < t:2021-10-07 03:11:38,032 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/jenkins/slave/workspace/scylla-master/artifacts/artifacts-sles15-test/scylla-cluster-tests/sdcm/sct_config.py", line 1681, in _check_unexpected_sct_variables
[2021-10-07T03:11:38.800Z] < t:2021-10-07 03:11:38,032 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     raise ValueError(res)
[2021-10-07T03:11:38.800Z] < t:2021-10-07 03:11:38,032 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > ValueError: Unsupported config option/s found:
[2021-10-07T03:11:38.800Z] < t:2021-10-07 03:11:38,032 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > 	 * 'scylla_mgmt_agent_repo: http://downloads.scylladb.com.s3.amazonaws.com/manager/rpm/unstable/centos/master/latest/scylla-manager.repo'
```

### PR DESCRIPTION
**Pull request by fgelcer**
right now it is failing because of artifacts test
for SLES 15 is trying to install manager (and manager
agent), and they are not supported.
Fixes #4016

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
while running [here](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/sles15-artifacts/) the jobs are failing when they find conflict with `zypper` package manager already in use... we worked around similar issue with `apt-get` introducing a retry mechanism... it most likely should be done here as well...

**Comment by fgelcer** [comment]
this is currently blocked by https://github.com/scylladb/scylla/issues/9458

IMHO we can merge this PR, as it solved the previous issue with scylla-manager installation

**Comment by fgelcer** [comment]
@roydahan @dkropachev @enaydanov @benipeled

**Comment by benipeled** [comment]
> IMHO we can merge this PR, as it solved the previous issue with scylla-manager installation

Yes, since it's all about configurations (disable manager test),
LGTM.

**Comment by roydahan** [comment]
If manager isn’t supported on SLES, we need an issue for that on manager.
We can’t release it without manager supporting it.

**Pull request closed without merging**
