### PR TITLE
fix(get_any_ks_cf_list): wrong usage of parameter 'session'

### PR DESCRIPTION
**Pull request by yarongilor**
the correct parameter to use in execute_cmd() should be: 'cql_session'.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by yarongilor** [comment]
Tested in: https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/longevity-twcs-48h-test-cql-timeout/4/

**Comment by fgelcer** [comment]
> Tested in: https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/longevity-twcs-48h-test-cql-timeout/4/
> 
> Testing if issue [scylladb/scylladb#12268](https://github.com/scylladb/scylladb/issues/12268) is not reproduced with this fix.

@denesb FYI

@yarongilor , please report test's progress

**Comment by fruch** [comment]
@yarongilor @fgelcer I don't see any reason how this would change any behavior what so ever... 
It would need a it more explaining on why someone things this is the root cause of the problem.

**Comment by juliayakovlev** [comment]
> @yarongilor @fgelcer I don't see any reason how this would change any behavior what so ever... It would need a it more explaining on why someone things this is the root cause of the problem.

I agree. The parameter `cql_session` in inner function `execute_cmd`, but `session` object exists in the `get_any_ks_cf_list` and actually the cql is run with `session`. And `cql_session` is unnessessary here.

The error "Tombstones processed by unpaged query exceeds limit" shows that query was run and this error is not connected to the parameter name

**Comment by fgelcer** [comment]
AFAICT we are doing some settings for `session`, but when we execute the query, we use `cql_session`, so it may not have the required settings in place... or what we missed is to set correctly the query that failed

**Comment by fgelcer** [comment]
or maybe we needed to set up better the `cql_session` with the parameter we did for `session`, or use `session` instead of `cql_session` in the following line:
```
stmt = SimpleStatement(f"SELECT * FROM {table_name}", fetch_size=10)
has_data = bool(cql_session.execute(stmt).one())
```

**Comment by juliayakovlev** [comment]
> AFAICT we are doing some settings for `session`, but when we execute the query, we use `cql_session`, so it may not have the required settings in place... or what we missed is to set correctly the query that failed

We change settings for `session` and run the query with `session`. Or I miss something?

**Comment by yarongilor** [comment]
> > AFAICT we are doing some settings for `session`, but when we execute the query, we use `cql_session`, so it may not have the required settings in place... or what we missed is to set correctly the query that failed
> 
> We change settings for `session` and run the query with `session`. Or I miss something?

The problem is previously it ran both `session.execute_async(cmd)` and `cql_session.execute(stmt)` and that makes less sense.

**Comment by juliayakovlev** [comment]
> > > AFAICT we are doing some settings for `session`, but when we execute the query, we use `cql_session`, so it may not have the required settings in place... or what we missed is to set correctly the query that failed
> > 
> > 
> > We change settings for `session` and run the query with `session`. Or I miss something?
> 
> The problem is previously it ran both `session.execute_async(cmd)` and `cql_session.execute(stmt)` and that makes less sense.

Yes, you are right, it confuses and need be changed. 
But it does not explain (and not causes) the error.

**Comment by yarongilor** [comment]
The issue is not reproduced with this fix (+5606):
```
< t:2023-01-09 21:08:57,103 f:nemesis.py      l:1052 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Set current_disruption -> ShowToppartitions Node longevity-twcs-48h-missing--db-node-305f2ced-3 [34.205.203.229 | 10.12.1.121] (seed: False)
< t:2023-01-09 21:09:01,918 f:common.py       l:1551 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test", consistency=Not Set>' ...
< t:2023-01-09 21:09:01,918 f:common.py       l:1559 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test", consistency=Not Set>' ...
< t:2023-01-09 21:09:03,744 f:common.py       l:1551 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test", consistency=Not Set>' ...
< t:2023-01-09 21:09:03,744 f:common.py       l:1559 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test", consistency=Not Set>' ...
< t:2023-01-09 21:09:04,194 f:common.py       l:1551 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test", consistency=Not Set>' ...
< t:2023-01-09 21:09:04,194 f:common.py       l:1559 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test", consistency=Not Set>' ...
< t:2023-01-09 21:09:04,849 f:common.py       l:1551 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test_counters", consistency=Not Set>' ...
< t:2023-01-09 21:09:04,850 f:common.py       l:1559 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test_counters", consistency=Not Set>' ...
< t:2023-01-09 21:09:04,942 f:common.py       l:1551 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test_counters", consistency=Not Set>' ...
< t:2023-01-09 21:09:04,942 f:common.py       l:1559 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test_counters", consistency=Not Set>' ...
< t:2023-01-09 21:09:04,994 f:common.py       l:1551 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test_counters", consistency=Not Set>' ...
< t:2023-01-09 21:09:04,994 f:common.py       l:1559 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test_counters", consistency=Not Set>' ...
< t:2023-01-09 21:09:05,057 f:common.py       l:1551 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test_counters", consistency=Not Set>' ...
< t:2023-01-09 21:09:05,057 f:common.py       l:1559 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test_counters", consistency=Not Set>' ...
< t:2023-01-09 21:09:05,112 f:common.py       l:1551 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test_counters", consistency=Not Set>' ...
< t:2023-01-09 21:09:05,112 f:common.py       l:1559 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test_counters", consistency=Not Set>' ...
< t:2023-01-09 21:09:05,183 f:common.py       l:1551 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test_counters", consistency=Not Set>' ...
< t:2023-01-09 21:09:05,184 f:common.py       l:1559 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test_counters", consistency=Not Set>' ...
< t:2023-01-09 21:09:05,265 f:common.py       l:1551 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test_counters", consistency=Not Set>' ...
< t:2023-01-09 21:09:05,265 f:common.py       l:1559 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="SELECT * FROM scylla_bench.test_counters", consistency=Not Set>' ...
ubuntu@ip-10-12-3-132:~/sct-results/latest$ egrep 'query_tombstone_page_limit|unpaged' sct.log 
ubuntu@ip-10-12-3-132:~/sct-results/latest$ 
```

**Comment by yarongilor** [comment]
> @yarongilor so we can close this one ?
> 
> or at least update the description and title of this one ? since it's a change we should be doing, but i's not fixing any bug.

updated the description. i guess we better merge this one to avoid future confusions and align it to be consistent.

**Pull request merged**
