### PR TITLE
fix(manager-gce): removed gsutil dependencies installation

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
As of late, the db node's comes with the gsutil dependencies pre-installed,
so I removed the installation from the test flow

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@ShlomiBalalis what happens if we do try to install ? doesn't it fail/break ?

where the installation is coming from, from scylla-machine-image ? i.e. if we won't use our image it can be missing..

**Comment by ShlomiBalalis** [comment]
> @ShlomiBalalis what happens if we do try to install ? doesn't it fail/break ?
> 
> where the installation is coming from, from scylla-machine-image ? i.e. if we won't use our image it can be missing...
> 
> I would rather check if it's installed before installing, and that's it.

This is the failure:
```
2022-05-11 14:07:07.841: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=5b42e96f-4e11-4b1d-abce-876e0e44186a, source=MgmtCliTest.test_backup_feature (mgmt_cli_test.MgmtCliTest) [Test Backup Rate Limit]() message=Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 471, in test_backup_feature
    self.test_backup_rate_limit()
  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 550, in test_backup_rate_limit
    self.verify_backup_success(mgr_cluster=mgr_cluster, backup_task=backup_task)
  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 179, in verify_backup_success
    self.restore_backup_from_backup_task(mgr_cluster=mgr_cluster, backup_task=backup_task,
  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 166, in restore_backup_from_backup_task
    self.restore_backup(mgr_cluster=mgr_cluster, snapshot_tag=snapshot_tag,
  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 151, in restore_backup
    install_dependencies(node=node)
  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 90, in install_gsutil_dependencies
    self._run_cmd_with_retry(executor=node.remoter.run, cmd=shell_script_cmd("""\
  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 66, in _run_cmd_with_retry
    executor(cmd)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'bash -cxe "curl https://sdk.cloud.google.com > install.sh\nbash install.sh --disable-prompts\n"'

Exit code: 1

Stdout:

Downloading Google Cloud SDK install script: https://dl.google.com/dl/cloudsdk/channels/rapid/install_google_cloud_sdk.bash
Running install script from: /tmp/tmp.eyVaiu7HCl/install_google_cloud_sdk.bash


Stderr:

+ bash install.sh --disable-prompts

######################################################################## 100.0%
which curl
curl -# -f https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz

######################################################################## 100.0%
mkdir -p /home/scylla-test
"/home/scylla-test/google-cloud-sdk" already exists and may contain out of date files.
Remove /home/scylla-test/google-cloud-sdk or select a new installation directory, then run again.
```

**Comment by fgelcer** [comment]
does it happen to GCE images only?

**Comment by ShlomiBalalis** [comment]
> does it happen to GCE images only?

We only ever try to install the sdk in gce images (since this is the only test that uses gcp as a backup location), so I can only confirm about gce images

**Comment by fruch** [comment]
> > does it happen to GCE images only?
> 
> We only ever try to install the sdk in gce images (since this is the only test that uses gcp as a backup location), so I can only confirm about gce images

so check for the existence of /home/scylla-test/google-cloud-sdk before installing. 

since if for some reason we will run without formal gcp images, it would be missing. we shouldn't be assuming things are installed, we should verify it.

**Comment by ShlomiBalalis** [comment]
> curl -# -f https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz

Done

**Comment by ShlomiBalalis** [comment]
> > > does it happen to GCE images only?
> > 
> > 
> > We only ever try to install the sdk in gce images (since this is the only test that uses gcp as a backup location), so I can only confirm about gce images
> 
> so check for the existence of /home/scylla-test/google-cloud-sdk before installing.
> 
> since if for some reason we will run without formal gcp images, it would be missing. we shouldn't be assuming things are installed, we should verify it.

Done

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
