### PR TITLE
RFC: still use private ip for prometheus in multiple DCs case

### PR DESCRIPTION
**Pull request by amoskong**
Base on current firewall rule, it's fine to access instances by private ips
across regions in GCE. But we have to add new rule to allow accessing by
public ip.

### CODE REVIEW

**Comment by amoskong** [comment]
I will test with multiple-dc before merge this PR, thanks for review.

**Comment by amoskong** [comment]
Wrote a doc about connections:
https://github.com/scylladb/scylla-cluster-tests/wiki/SCT-connections

image

**Comment by amoskong** [comment]
Tested with multiple dc, works well.
In GCE, we can still use private IP across the dc.

**Comment by roydahan** [comment]
This PR has an issue.
PR #461 is fixing it.

**Pull request merged**
