### PR TITLE
fix(configuration): unify region_name across backends

### PR DESCRIPTION
**Pull request by soyacz**
We used to have different region parameter for each backend. This
creates additional, unnecessary complexity and code duplication.

This commit unifies configuration by renaming `gce_datacenter` and
`azure_region_name` to `region_name` (AWS nomenclature).

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@soyacz this change is going to be painful:
1) it would be very hard to backport test-cases into release branches.
2) this change need to be sync with `siren-tests`, since I'm quite sure they are using those parameters in their longevity pipelines

**Comment by soyacz** [comment]
> @soyacz this change is going to be painful:
> 
> 1. it would be very hard to backport test-cases into release branches.

how often we do it?

> 2. this change need to be sync with `siren-tests`, since I'm quite sure they are using those parameters in their longevity pipelines

Thanks, good to know.
If we want this unification, will postponing it bring any benefit?

**Comment by soyacz** [comment]
@fruch can you answer my questions? We can have a call to discuss it if you prefer.

**Comment by vponomaryov** [comment]
> @soyacz this change is going to be painful:
> 
> 1. it would be very hard to backport test-cases into release branches.
> 2. this change need to be sync with `siren-tests`, since I'm quite sure they are using those parameters in their longevity pipelines

1) Exactly this change won't be hard, it is only rename of options. It is not hard at all. Just possible mislooks and need to do additional PRs with fixed. Don't consider it as show-stopper for the planned `unified provisioning` feature.
2) Siren-tests sync SCT code only when compatibility job passes. So, they will have time to fix their option names in their plugin code without any problems to running CI jobs.

As a result, if we want unified provisioning then we merge this PR.

**Review by vponomaryov — APPROVED** [review]
LGTM

**Review by fgelcer — APPROVED** [review]
LGTM

2 things:
1st --> worth to send a heads up to the whole team, as if someone is developing a new test , he/she won't know that something is broken until merging, or until rebasing, and re-running the test
2nd --> confirm that no new jobs were introduced with the old format, as i saw few new tests being added lately...

**Comment by fgelcer** [comment]
> @fruch can you answer my questions? We can have a call to discuss it if you prefer.

ping @fruch

**Comment by fruch** [comment]
> > @soyacz this change is going to be painful:
> > 
> > 1. it would be very hard to backport test-cases into release branches.
> 
> how often we do it?

we backport things quite often, to pref branches and to release branches, to manager branches

> 
> > 2. this change need to be sync with `siren-tests`, since I'm quite sure they are using those parameters in their longevity pipelines
> 
> Thanks, good to know. If we want this unification, will postponing it bring any benefit?

postponed until we know we don't break users of SCT, like siren-test and scylla-pkg

**Comment by fruch** [comment]
notice #5143 that did changes using `gce_datacenter` regarding GKE usage, that needs to be taken into account.

**Comment by soyacz** [comment]
Not working on it currently. Reopen when we get back to it.

**Pull request closed without merging**
