### PR TITLE
fix(sct_config): 4.6.3 AMIs were removed

### PR DESCRIPTION
**Pull request by fruch**
yet again older AMI were removed, and those tests are failing, also move this test to be an integration test so it would be annoying us that often.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
is it the same failure we saw on `branch-perf-v14`? if yes, we should backport it there too

**Review by fgelcer — COMMENTED** [review]
there is another failure
```
19:23:48  =================================== FAILURES ===================================
19:23:48  ________________ ConfigurationTests.test_12_scylla_version_ami _________________
19:23:48  
19:23:48  self = <unit_tests.test_config.ConfigurationTests testMethod=test_12_scylla_version_ami>
19:23:48  
19:23:48      @pytest.mark.integration
19:23:48      def test_12_scylla_version_ami(self):
19:23:48          os.environ.pop('SCT_AMI_ID_DB_SCYLLA', None)
19:23:48          os.environ['SCT_CLUSTER_BACKEND'] = 'aws'
19:23:48          os.environ['SCT_SCYLLA_VERSION'] = '5.1.8'
19:23:48      
19:23:48          os.environ['SCT_CONFIG_FILES'] = 'internal_test_data/multi_region_dc_test_case.yaml'
19:23:48          conf = sct_config.SCTConfiguration()
19:23:48          conf.verify_configuration()
19:23:48      
19:23:48  >       self.assertEqual(conf.get('ami_id_db_scylla'), 'ami-0e8a0f4016294654a ami-0554f19f2ba89f446')
19:23:48  E       AssertionError: 'ami-053e8113c01b576e4 ami-0554f19f2ba89f446' != 'ami-0e8a0f4016294654a ami-0554f19f2ba89f446'
19:23:48  E       - ami-053e8113c01b576e4 ami-0554f19f2ba89f446
19:23:48  E       ?      --  ^^^^  ^ ---
19:23:48  E       + ami-0e8a0f4016294654a ami-0554f19f2ba89f446
19:23:48  E       ?        ^^^^  ^^^^^  +
19:23:48  
19:23:48  unit_tests/test_config.py:187: AssertionError
```

**Comment by soyacz** [comment]
In this way, when running integration tests we'll get annoying error and these tests take more time (and anyway whole pipeline must be rerun).
How about transforming this test to this:
1. get list of ami's
2. assert  >x images were found
3. pick the last (or the first) and use it for SCT_ORACLE_SCYLLA_VERSION
4. assert found image matches the one from the list of ami's

**Comment by fruch** [comment]
> there is another failure
> 
> ```
> 19:23:48  =================================== FAILURES ===================================
> 19:23:48  ________________ ConfigurationTests.test_12_scylla_version_ami _________________
> 19:23:48  
> 19:23:48  self = <unit_tests.test_config.ConfigurationTests testMethod=test_12_scylla_version_ami>
> 19:23:48  
> 19:23:48      @pytest.mark.integration
> 19:23:48      def test_12_scylla_version_ami(self):
> 19:23:48          os.environ.pop('SCT_AMI_ID_DB_SCYLLA', None)
> 19:23:48          os.environ['SCT_CLUSTER_BACKEND'] = 'aws'
> 19:23:48          os.environ['SCT_SCYLLA_VERSION'] = '5.1.8'
> 19:23:48      
> 19:23:48          os.environ['SCT_CONFIG_FILES'] = 'internal_test_data/multi_region_dc_test_case.yaml'
> 19:23:48          conf = sct_config.SCTConfiguration()
> 19:23:48          conf.verify_configuration()
> 19:23:48      
> 19:23:48  >       self.assertEqual(conf.get('ami_id_db_scylla'), 'ami-0e8a0f4016294654a ami-0554f19f2ba89f446')
> 19:23:48  E       AssertionError: 'ami-053e8113c01b576e4 ami-0554f19f2ba89f446' != 'ami-0e8a0f4016294654a ami-0554f19f2ba89f446'
> 19:23:48  E       - ami-053e8113c01b576e4 ami-0554f19f2ba89f446
> 19:23:48  E       ?      --  ^^^^  ^ ---
> 19:23:48  E       + ami-0e8a0f4016294654a ami-0554f19f2ba89f446
> 19:23:48  E       ?        ^^^^  ^^^^^  +
> 19:23:48  
> 19:23:48  unit_tests/test_config.py:187: AssertionError
> ```

seems like the caching for on of the calls was wrong, and causing a mismatch , and not just deleted AMIs

**Review by fgelcer — APPROVED** [review]
LGTM

**Pull request merged**
