### PR TITLE
improvement(byo): make CI jobs fail fast if BYO fails

### PR DESCRIPTION
**Pull request by vponomaryov**
Fixes: #7884

### Testing

- https://jenkins.scylladb.com/job/scylla-staging/job/valerii/job/vp-longevity-10gb-3h-test/110

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@vponomaryov what about the rolling upgrade ?

**Comment by vponomaryov** [comment]
> @vponomaryov what about the rolling upgrade ?

Current pipeline structure for rolling upgrade is different and the same logic cannot be used:

```
java.lang.NoSuchMethodError: No such DSL method 'steps' found among steps [...]
```

If moving BYO above, then Argus test run start should be moved, but we should have Argus test run per unique upgrade combination.

**Comment by fruch** [comment]
> > @vponomaryov what about the rolling upgrade ?
> 
> Current pipeline structure for rolling upgrade is different and the same logic cannot be used:
> 
> ```
> java.lang.NoSuchMethodError: No such DSL method 'steps' found among steps [...]
> ```
> 
> If moving BYO above, then Argus test run start should be moved, but we should have Argus test run per unique upgrade combination.

so a fix for rolling-update would be on a separate PR ?

**Comment by fruch** [comment]
@vponomaryov  wait a minute, on the rolling upgrade case, we build each split it's own BYO ?

that's something we missed, we should build it before we split in parallel run, i.e. the whole idea there is to upgrade into same version in of the splits...

**Comment by vponomaryov** [comment]
> @vponomaryov wait a minute, on the rolling upgrade case, we build each split it's own BYO ?

As of now - yes.

> that's something we missed, we should build it before we split in parallel run, i.e. the whole idea there is to upgrade into same version in of the splits...

Then I will need to move it out of the Argus test run precedence.

**Review by fruch — APPROVED** [review]

**Comment by fruch** [comment]
> > so a fix for rolling-update would be on a separate PR ?
> 
> Probably, will add it here.
> 
> > @vponomaryov wait a minute, on the rolling upgrade case, we build each split it's own BYO ?
> 
> As of now - yes.
> 
> > that's something we missed, we should build it before we split in parallel run, i.e. the whole idea there is to upgrade into same version in of the splits...
> 
> Then I will need to move it out of the Argus test run precedence.

Let's raise as an issue so we don't forget it.

But building 3 times in one job is going to be quite excessive (i.e we only implemented the target version, not the base)

**Comment by vponomaryov** [comment]
@fruch 

As I wrote above I planned to update this PR.
Since, this one is merged already, created another PR for the upgrade part:
- https://github.com/scylladb/scylla-cluster-tests/pull/7939

**Pull request merged**
