### PR TITLE
improvement(artifacts test): improve email report

### PR DESCRIPTION
**Pull request by enaydanov**
Trello: https://trello.com/c/GKMTNYYr/1703-improve-artifacts-email-report

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by amoskong** [comment]
@enaydanov It seems this PR isn't necessary for branch-3.3, right?

**Comment by enaydanov** [comment]
> @enaydanov It seems this PR isn't necessary for branch-3.3, right?

Yes, because we don't backport artifacts tests to 3.3

**Comment by amoskong** [comment]
> > @enaydanov It seems this PR isn't necessary for branch-3.3, right?
> 
> Yes, because we don't backport artifacts tests to 3.3

Now, we want to backport artifact-tests to 3.3, currently only for supporting test of debian10 & centos8.

This PR improved the email report, it's not a serious issue. So we don't need to backport it, right?

**Comment by enaydanov** [comment]
> Now, we want to backport artifact-tests to 3.3, currently only for supporting test of debian10 & centos8.
> 
> This PR improved the email report, it's not a serious issue. So we don't need to backport it, right?

In this case it's better to backport it. Thanks for taking care about it.

**Comment by bentsi** [comment]
please create a backport PR for this

**Pull request merged**
