### PR TITLE
feature(cluster.py): support new directory structure of unified package

### PR DESCRIPTION
**Pull request by syuu1228**
On https://github.com/scylladb/scylladb/pull/8867, we changed directory structure of unified package, and increment it's
relocatable_package_version to 3.0.

We need to support it on SCT to run offline tests.

### CODE REVIEW

**Comment by syuu1228** [comment]
Tested on: https://jenkins.scylladb.com/job/scylla-staging/job/takuya/job/artifacts-offline-install/

**Review by fruch — DISMISSED** [review]
LGTM

**Comment by fruch** [comment]
@syuu1228 can you fix the precommit issues ? mainly wrong import order ?

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
