### PR TITLE
fix(manager debian 10): update ami id

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
Since the previous ami was deprecated, I've replaced it with a newer, supported image

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by ShlomiBalalis** [comment]
Running: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/debian10-sanity-test/

**Comment by fgelcer** [comment]
> Running: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/debian10-sanity-test/

@ShlomiBalalis , it failed with an issue master, that was reverted... please rebase and re-run

**Review by fgelcer — COMMENTED** [review]
please re-run the job that failed because an unrelated issue on SCT master (was reverted, and a fix is queued), so we can get it merged once we are sure it works

**Review by fruch — APPROVED** [review]
LGTM

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by ShlomiBalalis** [comment]
@scylladb/qa-maintainers If you may

**Review by roydahan — APPROVED** [review]

**Comment by ShlomiBalalis** [comment]
@roydahan Can you please backport?

**Comment by ShlomiBalalis** [comment]
@scylladb/qa-maintainers Can anyone backport?

**Comment by roydahan** [comment]
backported by Valerii

**Pull request merged**
