### PR TITLE
improvement(gemini tests):gemini tests to run with all nemesis

### PR DESCRIPTION
**Pull request by aleksbykov**
Added new gemini test config and jenkins job files to execute gemini
test with all nemesis (disruptive and non disruptive) in regular way

 - test with gemini basic cql-features ( only table)
 - test with gemini normal cql-features ( table, MV, SI)
Trello: https://trello.com/c/1b6HfHmI

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I gave variables/functions meaningful self-explanatory names
- [ ] I didn't leave commented-out/debugging code
- [ ] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by bentsi** [comment]
@aleksbykov `test-cases/gemini/gemini-3h-with-nemesis.yaml → test-cases/gemini/gemini-3h-with-nemesis-basic-cql-feature.yaml` - does the change of the file affect any pipeline?

**Comment by aleksbykov** [comment]
@bentsi , no it will not affect on current any pipeline.

**Comment by bentsi** [comment]
please create jobs in Jenkins master

**Comment by aleksbykov** [comment]
2 new jobs created:
https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-3h-chaos-nemesis-basic-cql-feature/
https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-3h-chaos-nemesis-normal-cql-feature/

**Comment by roydahan** [comment]
I don't understand why we need two more new jobs.
Why not adding the disruptive to the current one with non-disruptive?
Also, why separating the jobs for features?
Do they both should pass with the current state of Gemini?

**Comment by aleksbykov** [comment]
first job run disruptive and non disruptive nemesises over schema with only basic table
second job run disruptive and non disruptive nemesses over schema with table and MV and SI. For this job to avoid false positives in gemini added gemini parameter increase timeout of waiting for MV/SI are updated.
Both jobs should passed. But Gemini periodically failed. Issue for gemini was opened https://github.com/scylladb/gemini/issues/217.

**Comment by roydahan** [comment]
Do not merge it please.
I don't want too many Gemini jobs.

If Gemini already supporting nemesis and shouldn't fail, the Gemini job we already have for nemesis should be changed to support both disruptive and non-disruptive.

If the MV/SI feature works, I don't want to split it either and run it on the same job.

Moreover, if the Gemini-with-nemesis job become stable, I want to remove the old job that is basic and doesn't run nemesis.

**Comment by aleksbykov** [comment]
A bit blocked with gemini issue: https://github.com/scylladb/gemini/issues/220

**Comment by aleksbykov** [comment]
@roydahan 
Gemini issue  scylladb/gemini#220 fixed. 
Gemini tests was updated
new job added: https://jenkins.scylladb.com/view/master/job/scylla-master/job/gemini-/job/gemini-3h-with-nemesis/
These jobs removed:
https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-3h-chaos-nemesis-basic-cql-feature/
https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-3h-chaos-nemesis-normal-cql-feature/

Added PR to scylla-pkg, for automating run of job 

I suggest to leave for a short period the gemini-3h basic job without nemesis as a marker for gemini stability.

**Comment by aleksbykov** [comment]
Job is passed: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/gemini-staging-test/job/gemini--clone/job/gemini-3h-chaos-nemesis/

**Comment by bentsi** [comment]
@roydahan can we merge this?

**Comment by aleksbykov** [comment]
@bentsi could you merge?

**Pull request merged**
