### PR TITLE
test(ldap authorization): add new test

### PR DESCRIPTION
**Pull request by fgelcer**
will run longevity-50gb-3days test with
LDAP authorization enabled.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
@roydahan , job is ready, waiting for code to reach branch-2020.1:
https://jenkins.scylladb.com/job/enterprise-2020.1/job/SCT_Enterprise_Features/job/LDAP_authorization/job/longevity-50gb-3days/

**Comment by roydahan** [comment]
waiting for PR to change the c-s user.

**Comment by fgelcer** [comment]
> waiting for PR to change the c-s user.

should not have waited with it, then i could rebase the code in latest master (or branch-2020.1) and start testing something...

the PR with c-s user is #3263

**Review by roydahan — APPROVED** [review]

**Comment by fgelcer** [comment]
@roydahan need to be backported

**Comment by fgelcer** [comment]
> @roydahan need to be backported

ping @roydahan

**Comment by roydahan** [comment]
It was already backported.

**Pull request merged**
