### PR TITLE
fix(k8s): make 'stop' close K8sClientLogger's log stream fast

### PR DESCRIPTION
**Pull request by vponomaryov**
For the moment when SCT calls 'stop' method of the `K8sClientLogger` class instance used for getting DB pod logs it may hang up to the `read timeout` which is `20m` now.
The same happens for each DB pod because they get processed serially. And it is very easy to get this stream hanging just because DB pod logs may not have any new data.

So, use `socket` python library to close the 'read' and 'write' channels then close stream's file descriptor.

Statistics:
In case of EKS it saves us about `20m` from max possible 60m (20m * 3 pods). 
In case of KinD (local K8S) it saves us about `40m`.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by vponomaryov** [comment]
Example of the bug: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-3h-eks/52/consoleFull
```
18:25:31  < t:2023-05-12 15:25:30,768 f:remote_logger.py l:346  c:K8sClientLogger      p:INFO  > Stopping logger for pod sct-cluster-us-east1-b-us-east1-0
18:26:19  < t:2023-05-12 15:26:16,624 f:cluster.py      l:1089 c:sdcm.cluster         p:INFO  > Node sct-cluster-us-east1-b-us-east1-1 [10.0.0.210 | 10.0.1.124] (seed: False): Set termination_event
18:26:19  < t:2023-05-12 15:26:16,655 f:remote_logger.py l:346  c:K8sClientLogger      p:INFO  > Stopping logger for pod sct-cluster-us-east1-b-us-east1-1
18:45:16  < t:2023-05-12 15:45:15,555 f:cluster.py      l:1089 c:sdcm.cluster         p:INFO  > Node sct-cluster-us-east1-b-us-east1-2 [10.0.2.238 | 10.0.1.42] (seed: False): Set termination_event
18:45:16  < t:2023-05-12 15:45:15,571 f:remote_logger.py l:346  c:K8sClientLogger      p:INFO  > Stopping logger for pod sct-cluster-us-east1-b-us-east1-2
18:46:25  < t:2023-05-12 15:46:15,771 f:remote_logger.py l:346  c:K8sClientLogger      p:INFO  > Stopping logger for pod sct-cluster-us-east1-b-us-east1-0
18:46:25  < t:2023-05-12 15:46:16,773 f:remote_logger.py l:346  c:K8sClientLogger      p:INFO  > Stopping logger for pod sct-cluster-us-east1-b-us-east1-1
18:46:25  < t:2023-05-12 15:46:17,774 f:remote_logger.py l:346  c:K8sClientLogger      p:INFO  > Stopping logger for pod sct-cluster-us-east1-b-us-east1-2
18:46:25  < t:2023-05-12 15:46:17,775 f:cluster.py      l:1089 c:sdcm.cluster         p:INFO  > Set termination_event
18:46:25  < t:2023-05-12 15:46:17,775 f:cluster.py      l:1089 c:sdcm.cluster         p:INFO  > Set termination_event
18:46:25  < t:2023-05-12 15:46:17,776 f:cluster.py      l:1089 c:sdcm.cluster_aws     p:INFO  > Node longevity-scylla-operator-3h-dev-monitor-node-1c7ec125-1 [16.171.62.121 | 10.0.1.242] (seed: False): Set termination_event
18:46:25  < t:2023-05-12 15:46:22,781 f:__init__.py     l:1508 c:sdcm.cluster_k8s     p:INFO  > K8S-LOGS: starting logs gathering
```
`~19m`

**Review by soyacz — DISMISSED** [review]
LGTM

**Review by fruch — APPROVED** [review]
LGTM

Can we run a few short EKS longevity to show it solved the issues with logs ?

**Comment by vponomaryov** [comment]
> LGTM
> 
> Can we run a few short EKS longevity to show it solved the issues with logs ?

https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-provision-eks-cluster/132/consoleFull :

```
14:51:57  < t:2023-05-18 11:51:45,706 f:cluster.py      l:1089 c:sdcm.cluster         p:INFO  > Node sct-cluster-us-east1-b-us-east1-0 [10.0.6.64 | 10.0.7.35] (seed: False): Set termination_event
14:51:57  < t:2023-05-18 11:51:45,708 f:remote_logger.py l:350  c:K8sClientLogger      p:INFO  > Stopping logger for pod sct-cluster-us-east1-b-us-east1-0
14:51:57  < t:2023-05-18 11:51:45,710 f:cluster.py      l:1089 c:sdcm.cluster         p:INFO  > Node sct-cluster-us-east1-b-us-east1-1 [10.0.5.187 | 10.0.4.119] (seed: False): Set termination_event
14:51:57  < t:2023-05-18 11:51:45,714 f:remote_logger.py l:350  c:K8sClientLogger      p:INFO  > Stopping logger for pod sct-cluster-us-east1-b-us-east1-1
14:51:57  < t:2023-05-18 11:51:45,715 f:cluster.py      l:1089 c:sdcm.cluster         p:INFO  > Node sct-cluster-us-east1-b-us-east1-2 [10.0.6.92 | 10.0.4.48] (seed: False): Set termination_event
14:51:57  < t:2023-05-18 11:51:45,728 f:remote_logger.py l:350  c:K8sClientLogger      p:INFO  > Stopping logger for pod sct-cluster-us-east1-b-us-east1-2
14:51:57  < t:2023-05-18 11:51:47,733 f:remote_logger.py l:348  c:K8sClientLogger      p:INFO  > Logger for pod sct-cluster-us-east1-b-us-east1-0 is already stopped. Ignoring.
14:51:57  < t:2023-05-18 11:51:47,733 f:remote_logger.py l:348  c:K8sClientLogger      p:INFO  > Logger for pod sct-cluster-us-east1-b-us-east1-1 is already stopped. Ignoring.
14:51:57  < t:2023-05-18 11:51:47,734 f:remote_logger.py l:348  c:K8sClientLogger      p:INFO  > Logger for pod sct-cluster-us-east1-b-us-east1-2 is already stopped. Ignoring.
14:51:57  < t:2023-05-18 11:51:47,734 f:cluster.py      l:1089 c:sdcm.cluster         p:INFO  > Set termination_event
14:51:57  < t:2023-05-18 11:51:47,735 f:cluster.py      l:1089 c:sdcm.cluster_aws     p:INFO  > Node sct-test-dev-monitor-node-1d7d7e46-1 [13.48.30.209 | 10.0.7.10] (seed: False): Set termination_event
14:51:57  < t:2023-05-18 11:51:51,741 f:__init__.py     l:1422 c:sdcm.cluster_k8s     p:INFO  > K8S-LOGS: starting logs gathering
```

**Pull request merged**
