### PR TITLE
GCE: use qa-vpc network for longevity

### PR DESCRIPTION
**Pull request by amoskong**
The qa-vpc reduces the effect from public network.

### CODE REVIEW

**Comment by roydahan** [comment]
Can you please rebase with master just to be sure.
I pushed something right before your PR.

**Comment by amoskong** [comment]
Github is green for `Merging can be performed automatically.`
However, I just rebased it to latest master.

**Comment by amoskong** [comment]
Backported this to branch-2.1

```
commit d4d40ac4e51f045c5e3acaaafbb92826b46de42b
Author: Amos Kong <amos@scylladb.com>
Date:   Thu Nov 23 23:04:01 2017 +0800

    GCE: use qa-vpc network for longevity
    
    The qa-vpc reduces the effect from public network.
    
    Signed-off-by: Amos Kong <amos@scylladb.com>
    (cherry picked from commit 8d755653b5a18ec526fb0846beb24569490d54d8)
```

**Comment by amoskong** [comment]
Backported this to branch-2.0

```
commit dc545c19492717d430e627553e5d5875995f223e (HEAD -> branch-2.0, origin/branch-2.0)
Author: Amos Kong <amos@scylladb.com>
Date:   Thu Nov 23 23:04:01 2017 +0800

    GCE: use qa-vpc network for longevity
    
    The qa-vpc reduces the effect from public network.
    
    Signed-off-by: Amos Kong <amos@scylladb.com>
    (cherry picked from commit 8d755653b5a18ec526fb0846beb24569490d54d8)
```

**Pull request merged**
