### PR TITLE
fix(node_setup): update repo cache for db nodes

### PR DESCRIPTION
**Pull request by amoskong**
It will fail to install package by apt when Ubuntu AMI is ready. This
patch changed to update repo cache at the beginning stage.

Signed-off-by: Amos Kong <amos@scylladb.com>

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by juliayakovlev** [comment]
According to https://snapcraft.io/install/stress-ng/ubuntu, on Ubuntu 16.4 and later, snap is already installed and ready. So we don't need the `apt` and don't need to update it. Snap it's part of Ubuntu. 
Run `sudo snap install stress-ng` is enough

**Comment by amoskong** [comment]
> According to https://snapcraft.io/install/stress-ng/ubuntu, on Ubuntu 16.4 and later, snap is already installed and ready. So we don't need the `apt` and don't need to update it. Snap it's part of Ubuntu.
> Run `sudo snap install stress-ng` is enough

We also have other apt install commands are effected, not sure if we can switch all to `snap`.

**Comment by juliayakovlev** [comment]
> > According to https://snapcraft.io/install/stress-ng/ubuntu, on Ubuntu 16.4 and later, snap is already installed and ready. So we don't need the `apt` and don't need to update it. Snap it's part of Ubuntu.
> > Run `sudo snap install stress-ng` is enough
> 
> We also have other apt install commands are effected, not sure if we can switch all to `snap`.

I don't mean switch all to snap, just this nemesis

**Review by roydahan — APPROVED** [review]

**Comment by amoskong** [comment]
> > > According to https://snapcraft.io/install/stress-ng/ubuntu, on Ubuntu 16.4 and later, snap is already installed and ready. So we don't need the `apt` and don't need to update it. Snap it's part of Ubuntu.
> > > Run `sudo snap install stress-ng` is enough
> > 
> > 
> > We also have other apt install commands are effected, not sure if we can switch all to `snap`.
> 
> I don't mean switch all to snap, just this nemesis

I agree your PR (https://github.com/scylladb/scylla-cluster-tests/pull/3514) will solve (avoid) the stress-ng install problem.
But the root problem is https://github.com/scylladb/scylla-enterprise/issues/1754, which only exists with Ubuntu AMI (2021.1).
It's not enough to just fix stress-ng.

If the this PR (merged & backported) solved the stress-ng problem, it's not necessary to replace apt to snap in install stress-ng.

**Comment by roydahan** [comment]
I'm fine to do both.

**Comment by roydahan** [comment]
and ubuntu AMI is not only 2021, it's also master and 4.5

**Pull request merged**
