### PR TITLE
fix(null query support,rolling upgrade test), scylla supports "WHERE k=null"

### PR DESCRIPTION
**Pull request by shoshan**
scylla supports "WHERE k=null" test fix following https://github.com/scylladb/scylla/commit/4bb11076525df443d155e45331c82a3f34e2e649

test error was: AssertionError: query SELECT * FROM null_support_test WHERE k = null is not valid

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [ ] ~~All new and existing unit tests passed (CI)~~
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by fruch** [comment]
@shoshan can you have a more descriptive title for this PR/commit ?

**Review by amoskong — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@shoshan 
please fix the autopep issue:
https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-cluster-tests/job/PR-3079/1/execution/node/23/log/

also can you mention in the headline it's a fix for rolling upgrade ?

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by fgelcer** [comment]
> also can you mention in the headline it's a fix for rolling upgrade ?

@shoshan , can you?

**Comment by shoshan** [comment]
@fruch elaborated PR and commit messages, fixed autopep.

**Comment by shoshan** [comment]
@fruch can this PR merged?

**Pull request merged**
