### PR TITLE
make full scan stop when test completed

### PR DESCRIPTION
**Pull request by dkropachev**
FIxes https://github.com/scylladb/scylla-cluster-tests/issues/3851

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by dkropachev** [comment]
Test is running here - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/dmitry/job/dmitry-byo-longevity/484/

**Comment by dkropachev** [comment]
Tested here - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/dmitry/job/dmitry-byo-longevity/488/execution/node/117
Run ffiled because i killed id. look at the logs:
``
< t:2021-08-07 21:33:44,852 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-08-07 21:33:44.850: (FullScanEvent Severity.NORMAL) period_type=not-set event_id=37f79601-0229-4d75-a817-7f28341baa9d: type=start select_from=keyspace1.standard1 on db_node=10.0.0.208
< t:2021-08-08 04:58:48,557 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-08-08 04:58:48.555: (FullScanEvent Severity.NORMAL) period_type=not-set event_id=768adc73-25e8-4807-98ef-66f33fbc0f3e: type=finish select_from=keyspace1.standard1 on db_node=10.0.0.208 message=terminated
```

**Comment by dkropachev** [comment]
@bentsi , I'am not sure about backporting it, could you please take a look at set proper labels

**Review by roydahan — DISMISSED** [review]
LGTM

**Review by bentsi — DISMISSED** [review]

**Comment by bentsi** [comment]
fix the pre commit
```
15:18:31  ************* Module sdcm.tester
15:18:31  sdcm/tester.py:22:0: W0611: Unused import random (unused-import)
15:18:31  sdcm/tester.py:39:0: W0611: Unused SimpleStatement imported from cassandra.query (unused-import)
15:18:31  sdcm/tester.py:71:0: W0611: Unused FullScanEvent imported from sdcm.sct_events.database (unused-import)

```

**Comment by dkropachev** [comment]
> fix the pre commit
> 
> ```
> 15:18:31  ************* Module sdcm.tester
> 15:18:31  sdcm/tester.py:22:0: W0611: Unused import random (unused-import)
> 15:18:31  sdcm/tester.py:39:0: W0611: Unused SimpleStatement imported from cassandra.query (unused-import)
> 15:18:31  sdcm/tester.py:71:0: W0611: Unused FullScanEvent imported from sdcm.sct_events.database (unused-import)
> ```

done

**Comment by bentsi** [comment]
let's wait till this code will work on master and then backport

**Pull request merged**
