### PR TITLE
fix(multinetwork): remove second network interface configuration

### PR DESCRIPTION
**Pull request by juliayakovlev**
After multiple hard reboots a node eventually loses connection to all other nodes in the cluster. After node reboot, 2nd interface isn't functioning. Found that our `sdcm.provision.aws.utils.configure_eth1_script` re-configure the second network interface and it causes to lost connection.
Actually with using existing and configured network interface we do not need this eth1 configuration script any more.

Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8553

### Testing

- [x] [disrupt_multiple_hard_reboot_node](https://argus.scylladb.com/test/b08fa1c7-ae96-4a5b-be2d-98db30813a00/runs?additionalRuns[]=eb113145-1c10-479e-b1db-8dc788cfac94)
- [x] [all nemeses](https://argus.scylladb.com/tests/scylla-cluster-tests/61a71bd6-177f-40e6-9d9d-0c8b74a8c03d)

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@juliayakovlev 

Can you link to the testing job validated it's working?

**Review by fruch — APPROVED** [review]

**Comment by fruch** [comment]
@juliayakovlev 

any reason this is still draft ? only cause waiting for test results ?

**Comment by juliayakovlev** [comment]
> @juliayakovlev
> 
> any reason this is still draft ? only cause waiting for test results ?

@fruch it is because there are few failures in the job with all nemeses. I need to validate that the failures are not connected to the change

**Comment by fruch** [comment]
> > @juliayakovlev
> > any reason this is still draft ? only cause waiting for test results ?
> 
> @fruch it is because there are few failures in the job with all nemeses. I need to validate that the failures are not connected to the change

can we take it out of draft ? and get it merged ?

**Comment by juliayakovlev** [comment]
> > > @juliayakovlev
> > > any reason this is still draft ? only cause waiting for test results ?
> > 
> > 
> > @fruch it is because there are few failures in the job with all nemeses. I need to validate that the failures are not connected to the change
> 
> can we take it out of draft ? and get it merged ?

We need this commit is rebased with https://github.com/scylladb/scylla-cluster-tests/pull/8925

**Comment by fruch** [comment]
> > > > @juliayakovlev
> > > > any reason this is still draft ? only cause waiting for test results ?
> > > 
> > > 
> > > @fruch it is because there are few failures in the job with all nemeses. I need to validate that the failures are not connected to the change
> > 
> > can we take it out of draft ? and get it merged ?
> 
> We need this commit is rebased with https://github.com/scylladb/scylla-cluster-tests/pull/8925

I'm not sure it depends on each other.

Let's get this merged

**Comment by juliayakovlev** [comment]
> > > > > @juliayakovlev
> > > > > any reason this is still draft ? only cause waiting for test results ?
> > > > 
> > > > 
> > > > @fruch it is because there are few failures in the job with all nemeses. I need to validate that the failures are not connected to the change
> > > 
> > > 
> > > can we take it out of draft ? and get it merged ?
> > 
> > 
> > We need this commit is rebased with #8925
> 
> I'm not sure it depends on each other.
> 
> Let's get this merged

The commit is rebased and test passed

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
