### PR TITLE
fix(ami user data): change `user_data_format_version` default to 2

### PR DESCRIPTION
**Pull request by fruch**
since the formal AMIs are not tagged for now by scylla-pkg,
we'll default the master to `user_data_format_version: '2'`

also backport to branch-4.0

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I gave variables/functions meaningful self-explanatory names
- [ ] I didn't leave commented-out/debugging code
- [ ] I didn't copy-paste code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
should we add this is a workaround to the commit message?
as master will not be able to work from now with the un-tagged versions

**Comment by bentsi** [comment]
@fgelcer after discussion with Roy, we will support the old format in "old" version branches only.

**Comment by bentsi** [comment]
@fruch So we can remove the old code in future

**Comment by fgelcer** [comment]
> @fgelcer after discussion with Roy, we will support the old format in "old" version branches only.

so, no more need to tag AMIs?

**Comment by bentsi** [comment]
@fgelcer We will need to tag with versions since the user-data format can change

**Pull request merged**
