### PR TITLE
fix(yaml): set correct c-s commands parameters

### PR DESCRIPTION
**Pull request by aleksbykov**
Fix syntax errors in profile and c-s command parameters

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fgelcer — APPROVED** [review]
@aleksbykov , a bit more of context on why this change is required, would be good to undertstand the changes proposed...
why do we need `no-warmup`?

**Review by juliayakovlev — APPROVED** [review]

**Comment by fgelcer** [comment]
@scylladb/qa-maintainers backport needed... @aleksbykov FYI

**Comment by fgelcer** [comment]
ping backport @scylladb/qa-maintainers

**Comment by soyacz** [comment]
Was already backported, added labels

**Comment by fgelcer** [comment]
@aleksbykov , is this PR related to #5398 in any way?

**Pull request merged**
