### PR TITLE
test(operator): cover only 2 latest manager versions in functional tests

### PR DESCRIPTION
**Pull request by vponomaryov**
Trello: https://trello.com/c/uwlkJuDf/4985-create-scylla-operator-compatability-job-for-20221-50

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@vponomaryov you really need those backports ? i.e. you are running operator functional tests using those branches ?

**Comment by vponomaryov** [comment]
> @vponomaryov you really need those backports ? i.e. you are running operator functional tests using those branches ?

It is planned to be so to cover case of compatibility of operator and Scylla releases. It will be needed not only to release first GA version but also any further minor versions too.

**Comment by fruch** [comment]
@vponomaryov 4.6 doesn't have the test that support parameterize, you'll need to backport that first.
2021.1 doesn't have this file at all.

if you need this on both of those branch, please open PRs and collect all the needed commits.

**Comment by vponomaryov** [comment]
> @vponomaryov 4.6 doesn't have the test that support parameterize, you'll need to backport that first. 2021.1 doesn't have this file at all.
> 
> if you need this on both of those branch, please open PRs and collect all the needed commits.

Oh, I didn't think those branches are that ancient. Ok, then no need to backport it there.

**Pull request merged**
