### PR TITLE
fix(requirements.in): update to `ssh2-python==1.0.0`

### PR DESCRIPTION
**Pull request by fruch**
up until now we were using our own fork, with some memory leaks fixes, lets try it out a bit with the latest version. (and apply the fixes, again if proven needed)

Fix: #5386

- [x] test all provisioning tests
- [x] test short longevity - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/longevity/job/longevity-100gb-4h-test/11/
- [x] test 48h longevity - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/longevity-200gb-48h/3/
- [x] test 5000 tables / or scaling test - https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/scale-5000-tables-test/9/

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
Why to rock the boat?

**Comment by fruch** [comment]
> Why to rock the boat?

It's interfering with connecting to newer openssl versions. and in the way of running anything local with ssh 
for example 
 * docker backend, 
 * anything that needs SSH that you run locally
 * I needed to add docker loader for k8s functional tests, and it would fail whom ever gonna run any of the tests 

I had to change back to fabric in order to make things work, and it's gonna waste time for whom gonna face this

**Review by enaydanov — APPROVED** [review]

**Comment by enaydanov** [comment]
Imo, the fix for double free is already here but implemented in another way.  We definitely need to update this library.

**Review by roydahan — DISMISSED** [review]

**Comment by roydahan** [comment]
Good luck :)

**Comment by fruch** [comment]
All testing didn't showed any issue with related to ssh, rebuild the docker image and merging

**Review by enaydanov — APPROVED** [review]

**Comment by ShlomiBalalis** [comment]
@scylladb/qa-maintainers Can we try to backport it to 2022.1?

**Comment by fruch** [comment]
> @scylladb/qa-maintainers Can we try to backport it to 2022.1?

backported

**Pull request merged**
