### PR TITLE
fix(nemesis): disable unstable streaming err nemesises

### PR DESCRIPTION
**Pull request by amoskong**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@amoskong any reason this is a draft ? since this can be merged, but please tag the backports needed

**Comment by amoskong** [comment]
> @amoskong any reason this is a draft ? since this can be merged, but please tag the backports needed

Just change it to 'ready', and add backport label (only 4.1)

**Comment by fgelcer** [comment]
i think we should backport it to 4.0 too

**Comment by amoskong** [comment]
> i think we should backport it to 4.0 too

Streaming Err nemesises don't exist in SCT branch-4.0, we didn't backport them in the past.

**Pull request merged**
