### PR TITLE
fix(gemini): Update Oracle version

### PR DESCRIPTION
**Pull request by yarongilor**
Former version AMI's were deleted. Have to set an updated version.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by yarongilor** [comment]
Tested in: https://jenkins.scylladb.com/view/nexts/job/enterprise-2021.1/job/Reproducer/job/gemini-3h-with-nemesis-test-update-oracle-version/2/

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by fgelcer** [comment]
@fruch @roydahan please merge ASAP

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
