### PR TITLE
Fix writting to logs files

### PR DESCRIPTION
**Pull request by aleksbykov**

### CODE REVIEW

**Comment by aleksbykov** [comment]
@fruch adding the StreamWatcher. This allow to simplify code.

**Comment by aleksbykov** [comment]
i will investigate this, 
but i think, it not critical, because streams stores anyway, and not depend on Watchers.
```
                Stdout and stderr are always captured and stored in the
                ``Result`` object, regardless of ``hide``'s value.
```
if i correctly understood, stream watchs work with stored result in Result object, and it always store it.
So it could be out of memory anyway.

**Comment by fruch** [comment]
Looking now into Invoke code, you are correct that data is buffered anyhow, with no way to disabled it.
I'll try asking Jeff (the owner of Invoke) about is, but we need to keep that in mind, 
I think if we'll have 500 nodes for a few days, we'll be in a problem and might run out memory.

**Comment by bentsi** [comment]
@fruch did Jeff answer your question?

**Comment by fruch** [comment]
he's a bit busy right now, I need to ping him in a week or so

**Comment by roydahan** [comment]
label? backports?

**Comment by fruch** [comment]
@bentsi I've had a friendly chat with Jeff, and there's a milestone to address it in Invoke:

https://github.com/pyinvoke/invoke/issues/344#issuecomment-487443742

maybe one  of us is brave enough to try tackling it there, and help Jeff ?

**Comment by bentsi** [comment]
currently decided that we will find other solution to improve our log fetching process (See `SCT efficient logging` task)

**Pull request merged**
