### PR TITLE
Refactor stop compaction feature tests

### PR DESCRIPTION
**Pull request by KnifeyMoloko**
This PR introduces a few changes to the `StopCompaction` test:

- new REST API command for stopping a compaction on a given ks / cf is added
- new tests are added to cover the above API changes (mirroring the previous tests for stopping compaction)
- email reporter is switched to `FunctionalTestReporter`
- a decorator is added to collect subtest results for the functional tests template
- previously created tests are also decorated with the new decorator

Trello task: https://trello.com/c/onlJj6Nm
Jenkins runs:
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-longevity/job/mc-byo-new-test/265
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-longevity/job/mc-byo-new-test/266

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by KnifeyMoloko** [comment]
> LGTM

@fgelcer ping :)

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by soyacz** [comment]
@KnifeyMoloko are these features available in both 5.0/2022.1?

**Comment by KnifeyMoloko** [comment]
> @KnifeyMoloko are these features available in both 5.0/2022.1?

Yes, I see the original scylla commit merged both in scylla/branch-5.0 and scylla-enterpise/branch-2022.1.

**Comment by soyacz** [comment]
@roydahan do you approve backport?

**Comment by roydahan** [comment]
Not sure...
I think it needs more time in master, then we should backport to 2022.1 only.

**Comment by roydahan** [comment]
And of course to run the tests on master.

**Comment by soyacz** [comment]
We rarely run feature tests on master - time will not help us - only runs. 
Maybe run from master job with 2022.1 version too?

**Comment by roydahan** [comment]
For now I decided not to backport.
It's not cleanly backporting to 2022.1 and I don't think we will need it.

**Pull request merged**
