### PR TITLE
Use streaming instead of RBNO for a few longevity tests

### PR DESCRIPTION
**Pull request by pehala**
### Overview
* Use streaming for one tier1 (`longevity-mv-si-4days`) and one tier2 (`longevity-cdc-8h-multi-dc-topology-changes`) longevity tests
    
### Testing

- [x] Run `longevity-mv-si-4days` in jenkins
- [ ] Run `longevity-cdc-8h-multi-dc-topology-changes` in jenkins

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Questions
* Are those two tests enough? Should I add more tests from different categories?
    * Are those even right tests? 
* How can I verify that it uses streaming?
* For how long do I need to run tests to verify correctness of this PR?

Fixes https://github.com/scylladb/scylla-cluster-tests/issues/8289

### CODE REVIEW

**Comment by roydahan** [comment]
I'm not in favor of the renaming, it helps to have the history in one place.
If we do that renaming to make it clear that this one uses streaming, maybe it would be better to duplicate these and just replace the ones we have in in tier1 with them.
(i.e. move the originals to "longevity" and put the new ones in tier1, tier2).

**Comment by fruch** [comment]
> I'm not in favor of the renaming, it helps to have the history in one place. If we do that renaming to make it clear that this one uses streaming, maybe it would be better to duplicate these and just replace the ones we have in in tier1 with them. (i.e. move the originals to "longevity" and put the new ones in tier1, tier2).

also we should add the new jobs into the tier1/teir2 triggers while we add them

**Comment by pehala** [comment]
* Move old tests to `longevity`
* Change triggers to use new tests

**Review by roydahan — APPROVED** [review]
LGTM

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@pehala 

A general comment, if you run any Jenkins jobs, please supply link to them or to Argus, so whom need would be able to cross check what was running

**Comment by fruch** [comment]
@roydahan @pehala 

Do we want to change the triggers for release 2024.1 as well ?

**Comment by roydahan** [comment]
Preferably yes, assuming we tested them.

**Pull request merged**
