### PR TITLE
feature(upgrade): support to upgrade with AMI

### PR DESCRIPTION
**Pull request by amoskong**
base_version list will be converted to scylla_repo (gce backend) or ami_id for
AWS backend.

Signed-off-by: Amos Kong <amos@scylladb.com>

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by amoskong** [comment]
test job: https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/rolling-upgrade-centos-clone/6/console

**Comment by amoskong** [comment]
Another test job PASSed :-)

- https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/rolling-upgrade-centos-clone/7/console

**Comment by amoskong** [comment]
@roydahan will we share the original upgrade jobs?  or creating jenkins pipleline/jobs for AMI upgrade?

**Review by roydahan — APPROVED** [review]

**Comment by roydahan** [comment]
@amoskong please move the job from staging to master and 4.3.

In 4.3, the Ami-test should trigger the job and pass the ami-Id (PR to Scylla-pkg).
In master, the weekly trigger should trigger the job and use latest Ami id in master (parameter inside the weekly trigger job)

**Comment by amoskong** [comment]
> @amoskong please move the job from staging to master and 4.3.
> 
> In 4.3, the Ami-test should trigger the job and pass the ami-Id (PR to Scylla-pkg).
> In master, the weekly trigger should trigger the job and use latest Ami id in master (parameter inside the weekly trigger job)

If we set ami-id, the new AMI will be used to create the base cluster, what should we assigned for new_scylla_repo? (the upgraded version)

The upgrade job will still be trigger like original upgrade job. The new unstable scylla will be installed from scylla repo.
base_version is from jenkins pipeline, eg: [4.2]

##### Old upgrade job:
- backend: gce
- new_scylla_repo:

##### New upgrade jobs:
- backend: aws
- new_scylla_repo:

**Comment by roydahan** [comment]
> > @amoskong please move the job from staging to master and 4.3.
> > In 4.3, the Ami-test should trigger the job and pass the ami-Id (PR to Scylla-pkg).
> > In master, the weekly trigger should trigger the job and use latest Ami id in master (parameter inside the weekly trigger job)
> 
> If we set ami-id, the new AMI will be used to create the base cluster, what should we assigned for new_scylla_repo? (the upgraded version)
> 
Yes, sorry my confusion.
The AMI-id is the base version and should be fixed.
The repo is like all other rolling upgrade jobbs.


> The upgrade job will still be trigger like original upgrade job. The new unstable scylla will be installed from scylla repo.
> base_version is from jenkins pipeline, eg: [4.2]
> 
> ##### Old upgrade job:
> * backend: gce
> * new_scylla_repo:
> 
> ##### New upgrade jobs:
> * backend: aws
> * new_scylla_repo:

**Comment by amoskong** [comment]
@roydahan @bentsi can you help to backport this RP to 4.3?

**Pull request merged**
