### PR TITLE
improvement(log-collector): add ms precision to scylla logs

### PR DESCRIPTION
**Pull request by soyacz**
It was requested from dev team to support ms precision in db logs.

Adding `-o short-precise` to collection command that does the job.

fixes: #6682
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@soyacz reference to a job that this was working on ?

**Comment by soyacz** [comment]
> @soyacz reference to a job that this was working on ?

No, I just tested on some db instance manually

**Comment by soyacz** [comment]
testing here: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/artifacts-azure-image-test/17/

**Comment by kbr-scylla** [comment]
> fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6682

Why? #6682 is more than just ms precision in Scylla logs, it's about fixing the contents of `messages.log` file so we don't lose messages and we use original timestamps.

**Review by kbr-scylla — APPROVED** [review]

**Comment by soyacz** [comment]
> > fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6682
> 
> Why? #6682 is more than just ms precision in Scylla logs, it's about fixing the contents of `messages.log` file so we don't lose messages and we use original timestamps.

ok, this one is not fixing the issue - just giving proper time resolution to system.log.

If it get's closed I'll/please reopen it.

**Pull request merged**
