### PR TITLE
Branch 3.3 backup nemesis

### PR DESCRIPTION
**Pull request by fgelcer**
this is the backport of the commits needed for backup nemesis

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I gave variables/functions meaningful self-explanatory names
- [ ] I didn't leave commented-out/debugging code
- [ ] I didn't copy-paste code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
note that this PR is against branch-3.3

**Comment by roydahan** [comment]
Did you cherry-picked or did new commits?
If cherry-pick didn't you use "-x" ?

Lastly, does it work?

**Comment by fgelcer** [comment]
> Did you cherry-picked or did new commits?
yes
> If cherry-pick didn't you use "-x" ?
no
> 
> Lastly, does it work?
yes

**Comment by roydahan** [comment]
You should have used "-x" so we can see these commits were backported.
Anyway, I know you had issues with timeouts, were they solved? how? which commit solve them?

**Comment by fgelcer** [comment]
> You should have used "-x" so we can see these commits were backported.
> Anyway, I know you had issues with timeouts, were they solved? how? which commit solve them?

next time i will use -x (only if you insist, than i will redo the whole cherry-pick again)

about timeouts, https://github.com/scylladb/mermaid/issues/1794 is the ticket related to it

**Comment by fgelcer** [comment]
@roydahan  ping

**Comment by fgelcer** [comment]
@roydahan ping

**Pull request merged**
