### PR TITLE
Hydra: bumping up libvirt-python version to support CentOS 7.6

### PR DESCRIPTION
**Pull request by bentsi**

### CODE REVIEW

**Comment by bentsi** [comment]
backported to `branch-perf-v3`, `branch-3.0`

**Comment by roydahan** [comment]
@bentsi we are in branch-perf-v5.
(maybe worth deleting old branches)

**Comment by bentsi** [comment]
@roydahan why do we have `v5` branch and not continue with `v3`?
And why do you think we need to delete old branches?

**Comment by roydahan** [comment]
Because we had many changes on master and in the Jenkins jobs, so I decided to create new branches instead of trying to backport all.

We may want to remove all branches because we threw away all results.

**Pull request merged**
