### PR TITLE
fix(db_log_reader): remove parsing of multi line backtrace

### PR DESCRIPTION
**Pull request by fruch**
parsing of those is slowing us down complicated how read log files.

it was decided to stop supporting it, and support only one-liner backtraces

Ref: https://github.com/scylladb/scylladb/issues/16922

### Testing

- [ ]

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevent to this change (if needed)

### CODE REVIEW

**Review by soyacz — DISMISSED** [review]
IIRC multiline backtraces are prepended by "backtrace: " line, so we could detect that and parse next lines with this complex BACKTREACE_RE until it doesn't match.

But this requires testing and effort which I'm not sure we want to put, or do it in followup task.

So, LGTM

**Comment by roydahan** [comment]
This should wait for a scylla issue if we know backtraces that are still multi-line.
Also, all backports cannot happen until (probably never) the change will reach the old branches.

**Comment by fruch** [comment]
> IIRC multiline backtraces are prepended by "backtrace: " line, so we could detect that and parse next lines with this complex BACKTREACE_RE until it doesn't match.
> 
> But this requires testing and effort which I'm not sure we want to put, or do it in followup task.
> 
> So, LGTM

you are describing what this code that is going to be remove, is doing.
and it's not always working correctly, or how one might expect.
also there are case backtrace can be interleved (coming from diffrent shards)

**Comment by fruch** [comment]
> This should wait for a scylla issue if we know backtraces that are still multi-line. Also, all backports cannot happen until (probably never) the change will reach the old branches.

I think it can only help in release branches, less callstack we'll identify the better, isn't it ? :)

**Comment by fruch** [comment]
> > @roydahan
> > I've raised [scylladb/scylladb#16922](https://github.com/scylladb/scylladb/issues/16922)
> > and even a PR to suggest addressing it, in the same way reactor stalls were addressed
> 
> @roydahan
> 
> [scylladb/scylladb#16922](https://github.com/scylladb/scylladb/issues/16922) now is assigned to me 😕
> 
> and [scylladb/seastar#2052](https://github.com/scylladb/seastar/pull/2052) doesn't seems to go anywhere, i.e. where was that card we can pull on issues which are important to us ?

Nothing change since then...

**Comment by roydahan** [comment]
You can send the PR to SCT to remove the mulit-line support.
The only problem is that we won't be able to use newer version of SCT to test an older scylla and detecting multi-line backtrace.
Unless, you adda backward compatibility.

**Comment by fruch** [comment]
the change on seastar is moving, for now closing this.

for quite some time we don't have too many issue with the multiline, and we found the root cause of the slowdowns we have (long lines)

**Comment by roydahan** [comment]
Moving or not moving?

**Pull request closed without merging**
