### PR TITLE
disable upgrade from 2.3 to 3.1

### PR DESCRIPTION
**Pull request by amoskong**
Signed-off-by: Amos Kong <amos@scylladb.com>

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by amoskong** [comment]
Depends on https://github.com/scylladb/scylla/issues/4959#issuecomment-528641838

**Comment by fruch** [comment]
@amos why no backports ? Should 3.1 update ? And what about 2019.1 ?

**Comment by bentsi** [comment]
@amoskong do we need to backport this? to 3.1, 2019.1?

**Comment by amoskong** [comment]
> @Amos why no backports ? Should 3.1 update ? And what about 2019.1 ?

> @amoskong do we need to backport this? to 3.1, 2019.1?

The PR is prepared for 3.1. It disabled smooth upgrade from the version before last release (eg: 2.3 -> 3.1, 2017.1 -> 2019.1).

For 2019.1, there is no upgrade test from 2017.1 to 2019.1, so backport isn't needed.

We should support upgrade from 2.3 to 2019.1, we won't force 2.3 users to upgrade from 2.3 to 3.0, then upgrade to 2019.1. Backport isn't needed unless someone asked to disable upgrade test from 2.3 to 2019.1

/CC @roydahan @slivne

**Pull request merged**
