### PR TITLE
Fix js script for created shared snapshots of grafana dashboards

### PR DESCRIPTION
**Pull request by aleksbykov**

### CODE REVIEW

**Comment by bentsi** [comment]
@aleksbykov why did you change the script? please add the reason in the description of the PR

**Comment by aleksbykov** [comment]
Changes required, because the latest update of grafana change interfaces and need to update selectors.
Also, fix some js errors.
Before changes, the scripts failed to create shared snapshot
```
avocado.test: LocalCmdRunner [abykov@SCT-CONTAINER]: Command "cd phantomjs-2.1.1-linux-x86_64 && bin/phantomjs ../data_dir/share_snapshot.js "http://54.166.214.235:3000/dashboard/db/scylla-per-server-metrics-nemesis-3-0?from=1558416104000&to=now"" finished with status 0
avocado.test: Cluster abykov-gemini-basic-abykov-monitor-set-9402e1ec (AMI: ['ami-02eac2c0129f6376b'] Type: t3.small): TypeError: undefined is not an object (evaluating 'l[0].parentElement')

  undefined:5
  :6
TypeError: undefined is not an object (evaluating 'l[1].dispatchEvent')

  undefined:5
  :6
TypeError: undefined is not an object (evaluating 'l[0].parentElement')

  undefined:3
  :4
```

**Comment by bentsi** [comment]
by saying latest changes to Grafana you mean by moving to `branch-2.3` of the Scylla monitoring stack?

**Comment by bentsi** [comment]
@aleksbykov ?

**Comment by aleksbykov** [comment]
@bentsi it is related to grafana version in docker. It is not looks different in both branches 2.2 and 2.3

**Pull request merged**
