### PR TITLE
fix(cdcrepl_pipeline): Use correct functions in cdcrepl pipeline

### PR DESCRIPTION
**Pull request by aleksbykov**
Switch in cdcreplication pipeline to use the proper function from vars/
instead of longevityPipeline obj and sct-runner

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@aleksbykov 

we are maintaining this pipeline for one parameter ?

```
            string(defaultValue: "${pipelineParams.get('oracle_scylla_version', '')}",
                   description: "",
                   name: "oracle_scylla_version")
```

**Comment by aleksbykov** [comment]
@fruch 
For that moment yes.
But @kbr- could request additional parameters.

**Comment by fruch** [comment]
> @fruch
> For that moment yes.
> But @kbr- could request additional parameters.

I think that's a waste of our time, and we should strive to not create additional pipeline, as long there isn't a very big difference between them. (for example the artifacts ones, or the rolling upgrade, that run in parallel)

**Comment by bentsi** [comment]
@fruch agree

**Pull request merged**
