### PR TITLE
Add support for selecting branch AMIs by tags

### PR DESCRIPTION
**Pull request by fruch**
Now we support things like selecting ami based on branch version:
```bash
# specific version build-id / job-id
export SCT_SCYLLA_VERSION branch-3.1:60
# lastest
export SCT_SCYLLA_VERSION branch-3.1:latest
```

and new command line:

```bash
  0 fruch@fruch-syclla-laptop ~/ $ ./sct.py list-ami-branch branch-3.1:all
+----------------------------------------------------------------------------------------------------+
|                                     Scylla AMI branch versions                                     |
+---------------------------------------+-----------------------+--------------------------+---------+
| Name                                  | ImageId               | CreationDate             | BuildId |
+---------------------------------------+-----------------------+--------------------------+---------+
| jenkins-scylla-3.1-ami-test-label-60  | ami-0fd79a6f4ca83b0d6 | 2019-07-14T00:57:22.000Z | 60      |
| jenkins-scylla-3.1-ami-test-label-58  | ami-0db4cbf5a7970abc6 | 2019-07-12T00:34:59.000Z | 58      |
| jenkins-scylla-3.1-ami-test-label-57  | ami-0d5a423ede1415b21 | 2019-07-11T00:46:08.000Z | 57      |
| jenkins-scylla-3.1-ami-test-label-56  | ami-00f24e41fa9f416dd | 2019-07-10T01:12:01.000Z | 56      |
| jenkins-scylla-3.1-ami-test-label-55  | ami-0714b3c5e1fbba84b | 2019-07-09T06:08:57.000Z | 55      |
| jenkins-scylla-3.1-ami-test-label-54  | ami-063c015bf0b0ff1e3 | 2019-07-08T23:06:46.000Z | 54      |
| jenkins-scylla-3.1-ami-test-label-47  | ami-0f1ea365632fab3b6 | 2019-07-02T06:45:12.000Z | 47      |
| jenkins-scylla-3.1-ami-tests-label-40 | ami-0fa09aae5cdbe5d6f | 2019-06-26T07:30:10.000Z | 40      |
| jenkins-scylla-3.1-ami-tests-label-39 | ami-0e126224ddd01f170 | 2019-06-25T12:33:25.000Z | 39      |
| jenkins-scylla-3.1-ami-tests-label-38 | ami-0ac07c9630d9e4eea | 2019-06-25T00:30:59.000Z | 38      |

```
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [x] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [x] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [x] All new and existing unit tests passed (`hydra unit-tests`)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by bentsi** [comment]
COOL :) @roydahan please review

**Comment by bentsi** [comment]
resolve conflicts

**Comment by roydahan** [comment]
Looks good.
Do you want to add this option to all the pipeline jobs?

**Comment by fruch** [comment]
It would be available in the pipeline, I.e. SCT_SCYLLA_VERSION is already available. the syntax of what's possible to select with it just get extended

**Comment by fruch** [comment]
@roydahan waiting for you vote to merge this one...

**Pull request merged**
