### PR TITLE
modify the Backup feature gce scenario to use a multidc cluster

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fgelcer — COMMENTED** [review]
have you run it?

**Comment by ShlomiBalalis** [comment]
There was a small fix needed, the job now passed:
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/sct-feature-test-backup-gce-multidc/
(the Clean resrouces and Send email stages failed due to https://github.com/scylladb/scylla-cluster-tests/issues/5082)

**Review by fgelcer — DISMISSED** [review]
LGTM

**Review by rayakurl — DISMISSED** [review]
approved, just remove the first "also" from the commit message since it's confusing

**Comment by fruch** [comment]
> There was a small fix needed, the job now passed: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/sct-feature-test-backup-gce-multidc/ (the Clean resrouces and Send email stages failed due to #5082)

It wasn't #5082, it was a different bug that @vponomaryov just fixed, https://github.com/scylladb/scylla-cluster-tests/pull/5152

**Review by rayakurl — APPROVED** [review]

**Comment by rayakurl** [comment]
@ShlomiBalalis - what is pending?

**Review by fruch — DISMISSED** [review]
LGTM

**Review by fgelcer — DISMISSED** [review]
LGTM

**Comment by ShlomiBalalis** [comment]
> @ShlomiBalalis seems like the changes here are breaking the test case linter (yet again)
> 
> ```
> 14:30:29  Traceback (most recent call last):
> 14:30:29    File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-5072/./sct.py", line 686, in _run_yaml_test
> 14:30:29      config.verify_configuration()
> 14:30:29    File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-5072/sdcm/sct_config.py", line 1768, in verify_configuration
> 14:30:29      self._check_multi_region_params(backend)
> 14:30:29    File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-5072/sdcm/sct_config.py", line 1835, in _check_multi_region_params
> 14:30:29      raise ValueError("not all multi region values are equal: \n\t{}".format(region_count))
> 14:30:29  ValueError: not all multi region values are equal: 
> 14:30:29  	{'gce_datacenter': 1, 'n_db_nodes': 2}
> ```

Yeah, just noticed that. Looing at it.

**Comment by ShlomiBalalis** [comment]
Hurray!

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by rayakurl — APPROVED** [review]
Approved

**Pull request merged**
