### PR TITLE
Fix to make AddDropColumn nemesis to ignore scylla-bench tables

### PR DESCRIPTION
**Pull request by dkropachev**
https://github.com/scylladb/scylla-cluster-tests/issues/1651
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by roydahan** [comment]
I think the problem is more general, I commented about it in the original PR.
If we use this code as is, I think it won't do anything.
Does the default c-s schema use COMPACT STORAGE?
If so, it won't run on the table I want it to run.

**Comment by fruch** [comment]
@roydahan can you explain further ? cause I didn't understood what you mean in your comment...

**Comment by dkropachev** [comment]
> I think the problem is more general, I commented about it in the original PR.
> If we use this code as is, I think it won't do anything.
> Does the default c-s schema use COMPACT STORAGE?
> If so, it won't run on the table I want it to run.

I believe that we can overcome this problem by enforcing a 'special' way of treating scylla-bench tables, for instance if we will add column and drop column right away impact on scylla-bench will be minimized and we will still affect schema as we wanted.
I will try this approach tomorrow.

**Comment by roydahan** [comment]
No need to try it, testing it in a small environment doesn’t mean it will work and it probably won’t work when using bigger cluster and overloaded ones.
Each operation like that is a schema change, it won’t be immediate and it’s a risk for the workload.

My earlier comment was about missing parts of the original PR and it was implemented not as I asked.

At the moment all the longevities are using Default c-s with almost none of them doing pre-create schema.
It means that all these tables will be “with COMPACT STORAGE”.
That means we won’t have a table to run this nemesis on, IIRC in that case we just create a table and this nemesis on it and this is not what I wanted.

Anyway, I looking on an option to change the default c-s to be without compact storage and send PR to Scylla-tools-Java.

**Comment by dkropachev** [comment]
> No need to try it, testing it in a small environment doesn’t mean it will work and it probably won’t work when using bigger cluster and overloaded ones.
> Each operation like that is a schema change, it won’t be immediate and it’s a risk for the workload.
> 
> My earlier comment was about missing parts of the original PR and it was implemented not as I asked.
> 
> At the moment all the longevities are using Default c-s with almost none of them doing pre-create schema.
> It means that all these tables will be “with COMPACT STORAGE”.
> That means we won’t have a table to run this nemesis on, IIRC in that case we just create a table and this nemesis on it and this is not what I wanted.
> 
> Anyway, I looking on an option to change the default c-s to be without compact storage and send PR to Scylla-tools-Java.

I've tried approach i described, it did not work - scylla-bench sticks to the sending error message forever even if extra row is not there anymore.
Having that, there is two ways to overcome this issue:
- Unconditionally skip scylla-bench tables.
- Provide interface to mark tables (from the test, add special parameter) that are not supposed to be touched by nemesises like this one

**Comment by dkropachev** [comment]
I've done one more testing on scylla-bench that is run with no such option "-validate-data" and got same results.
So we have only one option here - to skip scylla-bench tables from table modifications.
And that is exactly what was done.

Which is unfortunate.

**Pull request merged**
