### PR TITLE
fix(elastic): store additional CPU info in elastic

### PR DESCRIPTION
**Pull request by temichus**
store in elastic  cpu MHz and cache size in addition to cpu_model

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by temichus** [comment]
@roydahan @fruch @fgelcer 
please check https://github.com/scylladb/qa-tasks/issues/1159 before reviewing. maybe we don't need this pr as it does now work for AWS

**Comment by fruch** [comment]
> @roydahan @fruch @fgelcer please check [scylladb/qa-tasks#1159](https://github.com/scylladb/qa-tasks/issues/1159) before reviewing. maybe we don't need this pr as it does now work for AWS

is there any perf job we run on GCE ? otherwise why would we add this ?

**Review by roydahan — APPROVED** [review]

**Comment by roydahan** [comment]
> > @roydahan @fruch @fgelcer please check [scylladb/qa-tasks#1159](https://github.com/scylladb/qa-tasks/issues/1159) before reviewing. maybe we don't need this pr as it does now work for AWS
> 
> is there any perf job we run on GCE ? otherwise why would we add this ?

Because we're trying to add this.

**Comment by fruch** [comment]
> > > @roydahan @fruch @fgelcer please check [scylladb/qa-tasks#1159](https://github.com/scylladb/qa-tasks/issues/1159) before reviewing. maybe we don't need this pr as it does now work for AWS
> > 
> > 
> > is there any perf job we run on GCE ? otherwise why would we add this ?
> 
> Because we're trying to add this.

add a GCP perf test ? since @temichus is saying this change doesn't work for AWS...

**Comment by roydahan** [comment]
Yes

**Comment by aleksbykov** [comment]
@temichus , i also suggest to add line: `flags: ...` Especially for gce, it could help to get eact cpu model, exp icelake or cascadelake

**Comment by temichus** [comment]
> @temichus , i also suggest to add line: `flags: ...` 

this one? 

(run on n2-highmem-8)
```
artsiom_mishuta@instance-1:~$ awk -F: '/^flags/{print $2; exit}' /proc/cpuinfo
 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm avx512f avx512dq rdseed adx smap clflushop
```


cant see "exp icelake or cascadelake"

```
artsiom_mishuta@instance-1:~$ cat /proc/cpuinfo| grep "lake"
artsiom_mishuta@instance-1:~$ 
```

**Comment by temichus** [comment]
> > this one?
> > (run on n2-highmem-8)
> > ```
> > artsiom_mishuta@instance-1:~$ awk -F: '/^flags/{print $2; exit}' /proc/cpuinfo
> >  fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm avx512f avx512dq rdseed adx smap clflushop
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > cant see "exp icelake or cascadelake"
> > ```
> > artsiom_mishuta@instance-1:~$ cat /proc/cpuinfo| grep "lake"
> > artsiom_mishuta@instance-1:~$ 
> > ```
> 
> yes this ones. you will not see exactly the model, but by set of cpu flags(features/instruction) it will be easily detect what type of processor. Ex IceLake and Casscade lake differs only on one flag : avx512_vnni. It present for Casscade lake but no in IceLake
> 
> * https://en.wikichip.org/wiki/intel/microarchitectures/cascade_lake
> * https://en.wikichip.org/wiki/intel/microarchitectures/ice_lake_(client)
> 
> You can see in New Instructions

@aleksbykov, updated

**Review by roydahan — APPROVED** [review]

**Review by aleksbykov — APPROVED** [review]
LGTM

**Pull request merged**
