### PR TITLE
test(artifact): add a t3.micro artifact test

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
Since scylla can't start on t3.micro without developer mode activated, I added a check in scylla_setup to activate developer mode when the instance type is t3.micro

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@ShlomiBalalis is there some context to this change ? why do we want to run micro ?

please add it to the commit description

What about other micro ? i4i.micro (if such a thing exists) ?

**Review by roydahan — APPROVED** [review]

**Comment by ShlomiBalalis** [comment]
> @ShlomiBalalis is there some context to this change ? why do we want to run micro ?
> 
> please add it to the commit description
> 
> What about other micro ? i4i.micro (if such a thing exists) ?

This is since t3.micro is the instance type used in the free tier, so we want to run the artifact test using it.

**Review by fgelcer — APPROVED** [review]
if it works, LGTM

**Comment by ShlomiBalalis** [comment]
> if it works, LGTM

@fgelcer Again, there's this issue:

> 2. After adding the ebs volume, the test MOSTLY passes, except the `verify_xfs_online_discard_enabled` check:
> 
> ```
> 2023-09-04 14:05:13.471: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=2a9c77fa-8fe9-4789-aa3a-ba1b25f0b3b2, source=ArtifactsTest.test_scylla_service (artifacts_test.ArtifactsTest) [verify XFS online discard enabled]() message=Traceback (most recent call last):
> File "/tmp/jenkins/workspace/scylla-staging/Shlomo/artifacts-ami-t3-test/scylla-cluster-tests/artifacts_test.py", line 327, in test_scylla_service
>     self.verify_xfs_online_discard_enabled()
> File "/tmp/jenkins/workspace/scylla-staging/Shlomo/artifacts-ami-t3-test/scylla-cluster-tests/artifacts_test.py", line 271, in verify_xfs_online_discard_enabled
>     self.assertIn("discard", mount_options)
> AssertionError: 'discard' not found in ['rw', 'noatime', 'attr2', 'inode64', 'logbufs=8', 'logbsize=32k', 'sunit=8', 'swidth=8', 'noquota']
> ```
> 
> [job link](https://jenkins.scylladb.com/job/scylla-staging/job/Shlomo/job/artifacts-ami-t3-test/) The thing is, I'm not sure this check is very relevant to this scenario. online discard is meant to ["improve SSD performance"](https://github.com/scylladb/scylla-cluster-tests/pull/4649), and I doubt it's really relevant to ebs volumes. @roydahan @fgelcer How can I confirm this?

**Comment by fgelcer** [comment]
> > if it works, LGTM
> 
> @fgelcer Again, there's this issue:
> 
> > 2. After adding the ebs volume, the test MOSTLY passes, except the `verify_xfs_online_discard_enabled` check:
> > 
> > ```
> > 2023-09-04 14:05:13.471: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=2a9c77fa-8fe9-4789-aa3a-ba1b25f0b3b2, source=ArtifactsTest.test_scylla_service (artifacts_test.ArtifactsTest) [verify XFS online discard enabled]() message=Traceback (most recent call last):
> > File "/tmp/jenkins/workspace/scylla-staging/Shlomo/artifacts-ami-t3-test/scylla-cluster-tests/artifacts_test.py", line 327, in test_scylla_service
> >     self.verify_xfs_online_discard_enabled()
> > File "/tmp/jenkins/workspace/scylla-staging/Shlomo/artifacts-ami-t3-test/scylla-cluster-tests/artifacts_test.py", line 271, in verify_xfs_online_discard_enabled
> >     self.assertIn("discard", mount_options)
> > AssertionError: 'discard' not found in ['rw', 'noatime', 'attr2', 'inode64', 'logbufs=8', 'logbsize=32k', 'sunit=8', 'swidth=8', 'noquota']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [job link](https://jenkins.scylladb.com/job/scylla-staging/job/Shlomo/job/artifacts-ami-t3-test/) The thing is, I'm not sure this check is very relevant to this scenario. online discard is meant to ["improve SSD performance"](https://github.com/scylladb/scylla-cluster-tests/pull/4649), and I doubt it's really relevant to ebs volumes. @roydahan @fgelcer How can I confirm this?

so, you should ignore this check in case we are running on such tiny instance type

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fgelcer** [comment]
ping backport

**Comment by roydahan** [comment]
When requesting backport, it's not enough to put a label because it doesn't send a notification!

**Comment by roydahan** [comment]
Backported.
please make sure we have the jobs created as needed.

**Comment by ShlomiBalalis** [comment]
@roydahan you only backported the second commit...

**Comment by roydahan** [comment]
Now with both commits.

**Pull request merged**
