### PR TITLE
feature(defaults/aws_config): increase root disk size of aws instance

### PR DESCRIPTION
**Pull request by amoskong**
Scylla_setup added support of swap setup, the maximum swap is 16G.
Current default root disk isn't enough.

The default disk size of GCE is 50G, and we don't use large GCE instance
in our test. So current value is fine.

Signed-off-by: Amos Kong <amos@scylladb.com>

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
This should be set as part of Scylla-machine-image not here, together with the swap configuration.

**Comment by fruch** [comment]
> This should be set as part of Scylla-machine-image not here, together with the swap configuration.

@roydahan this can't be part of the AMI, the setup of the swap yes, but the user will always be able to set size of the root disk on it's own... to bigger or small then what we'll need.

**Comment by amoskong** [comment]
> This should be set as part of Scylla-machine-image not here, together with the swap configuration.



> > This should be set as part of Scylla-machine-image not here, together with the swap configuration.

This PR only changed the root disk size of our testing (AWS) instances.



> @roydahan this can't be part of the AMI, the setup of the swap yes, but the user will always be able to set size of the root disk on it's own... to bigger or small then what we'll need.

For enable swap, we should change scylla-machine-image, the swap will be really set when new instance is created by the AMI. We don't set swap in the AMI.

**Comment by roydahan** [comment]
> > This should be set as part of Scylla-machine-image not here, together with the swap configuration.
> 
> @roydahan this can't be part of the AMI, the setup of the swap yes, but the user will always be able to set size of the root disk on it's own... to bigger or small then what we'll need.

The default root disk size of the AMI should be 30GB.
If the user decrease it, it's not our problem.
We can't expect him to know he should increase it though.

**Comment by amoskong** [comment]
> > > This should be set as part of Scylla-machine-image not here, together with the swap configuration.
> > 
> > 
> > @roydahan this can't be part of the AMI, the setup of the swap yes, but the user will always be able to set size of the root disk on it's own... to bigger or small then what we'll need.
 
> The default root disk size of the AMI should be 30GB.

Unless how much it is, sct config will overwrite it.

> If the user decrease it, it's not our problem.
> We can't expect him to know he should increase it though.

Here the 'user' is us (SCT user, we are also the AMI user), so it's our problem ;-)
The number I changed in this PR will overwrite the default root disk size in AMI itself.

**Comment by fruch** [comment]
> 30GB

if we set the AMI to 30GB, user can't make it smaller... 
why can we document that if swap is needed, a user need to enlarge the root disk ?

**Comment by amoskong** [comment]
> > 30GB
> 
> if we set the AMI to 30GB, user can't make it smaller...

Ok. Is it fine (safe) to change the default root disk size of AMI from 10G to 30G?
I just sent a PR:  https://github.com/scylladb/scylla-machine-image/pull/47

> why can we document that if swap is needed, a user need to enlarge the root disk ?

If the swap is always helpful, and recommended for scylla user.  We don't need to make it configurable, and just enable it all the time.

**Comment by roydahan** [comment]
> > 30GB
> 
> if we set the AMI to 30GB, user can't make it smaller...
> why can we document that if swap is needed, a user need to enlarge the root disk ?

Because it'll probably will be too late for him...
Swap becomes the default now also as part of the AMI, so in any case the user needs to enlarge the disk.

**Comment by amoskong** [comment]
@bentsi can you process the backport?

**Pull request merged**
