### PR TITLE
fix(k8s-eks): make S3 access really work on multi-tenant setups

### PR DESCRIPTION
**Pull request by vponomaryov**
Create separate unique AWS IAM role for each of the K8S service accounts used by Scylla clusters we create.
It will enable the possibility to use scylla manager in each of the Scylla tenants.

### Testing

- [ ]

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevent to this change (if needed)

### CODE REVIEW

**Comment by vponomaryov** [comment]
Being tested here: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-3h-multitenant-eks/67/consoleFull
Already see that location check work.
Just backuping is very slow having small load on tenants.

@fruch from above observations I can say that probably we may want to provide scylla-manager service more resources.

**Comment by vponomaryov** [comment]
Mgmt backups passed on both tenants after reducing the data size: https://argus.scylladb.com/test/626c2bab-1e46-4353-b92a-c7d8714e2495/runs?additionalRuns[]=40c5eac8-97ab-4615-a3e6-4753bd6b6657

So, this change really makes the S3 access working for our EKS deployments.

**Comment by vponomaryov** [comment]
@fruch , @soyacz 

Any objections?

**Comment by soyacz** [comment]
> @fruch , @soyacz
> 
> Any objections?

Is this only for multitenant setup?

**Comment by vponomaryov** [comment]
> > @fruch , @soyacz
> > Any objections?
> 
> Is this only for multitenant setup?

It is for all EKS setups.
Just original issue was related only to multitenant setups.
With further `fixes` I broke even single-tenant setups.
This change is what should have been done originally with enablement of S3 service for EKS.

**Review by fruch — APPROVED** [review]
LGTM

**Review by soyacz — APPROVED** [review]
LGTM

**Pull request closed without merging**
