### PR TITLE
refactor(nemesis.py): Filter out paxos operation timeout on node restart

### PR DESCRIPTION
**Pull request by yarongilor**
An 4.3.x workaround for issue:
	https://github.com/scylladb/scylla/issues/6155
	filtering out this message:
	"Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE."

       + fix previous backported commit compatibility issue: (db_event=DatabaseLogEvent.RUNTIME_ERROR)

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by bentsi** [comment]
which commit are you backporting?

**Review by roydahan — APPROVED** [review]

**Comment by roydahan** [comment]
It's not a backport commit, but "workaround" PR for patch release.

**Comment by aleksbykov** [comment]
@roydahan @bentsi Could be this PR also merged to 4.4 branch?

**Comment by roydahan** [comment]
please send a new PR directly to 4.4.
We don't backport the PRs from older to newer branches + it's not natively backport (there are conflicts need to be handled).

**Pull request merged**
