### PR TITLE
fix(k8s-gke): skip flush and reshard nemesis due to the bug

### PR DESCRIPTION
**Pull request by vponomaryov**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by vponomaryov** [comment]
Failed job with enabled nemesis is here: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-3h-gke/12/consoleFull
Passed job with the skipped nemesis is here: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-3h-gke/15/consoleFull

**Review by fruch — APPROVED** [review]

**Comment by fgelcer** [comment]
@vponomaryov , good practice is to give `the bug` a number, so we can track backwards, once `the bug` will be fixed

**Comment by fruch** [comment]
> @vponomaryov , good practice is to give `the bug` a number, so we can track backwards, once `the bug` will be fixed

it's written in the code:
https://github.com/scylladb/scylla-operator/issues/1077

**Comment by vponomaryov** [comment]
> @vponomaryov , good practice is to give `the bug` a number, so we can track backwards, once `the bug` will be fixed

As @fruch has already mentioned, the bug is referenced in the code change. So, good practice has been applied here from the start.

**Comment by fruch** [comment]
Having it also int the commit message and PR description could be even better, i.e. getting it linked to the bug.

**Pull request merged**
