### PR TITLE
[Draft][Stablizing]:feature(nemesis): Parallel topology operations

### PR DESCRIPTION
**Pull request by aleksbykov**
Add new nemesis for running parallel topology operations

### Testing

- [ ]

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by kbr-scylla** [comment]
> Do we support also first cluster initialization in parallel?
> If so, Is there a new procedure for it or just start all of them in parallel? (maybe 1 and then all).

Starting all nodes in parallel should work.

>  Do we have new documentation for all the above?

https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/index.html

> @kbr-scylla you feedback is also required.

You mean I should review the code (but note I'm not that familiar in SCT, last time I looked at it was ~4 years ago, so not sure if my review is valuable) or do you have some specific questions?

**Comment by roydahan** [comment]
> You mean I should review the code (but note I'm not that familiar in SCT, last time I looked at it was ~4 years ago, so not sure if my review is valuable) or do you have some specific questions?

At least the things this PR intends to test and if they are supported and fully covering what's needed.


@aleksbykov with @soyacz PR for actual parallel operations, most of these aren't relevant and/or need to be adjusted.

**Review by soyacz — COMMENTED** [review]
I don't see the need to create separate nemesis for this.
My proposal is to control nemesis behavior based on test config, e.g. enabling parallel operations and setting nemesis_add_node_cnt param (which is used in a few tests already).
see https://github.com/scylladb/scylla-cluster-tests/pull/7702

**Comment by roydahan** [comment]
I agree with @soyacz

**Comment by aleksbykov** [comment]
Close this PR. Bootstrap/Decommission was implemented. New issue was created to rest parts: https://github.com/scylladb/scylla-cluster-tests/issues/7826

**Pull request closed without merging**
