### PR TITLE
fix(tables): remove COMPACT STORAGE from code

### PR DESCRIPTION
**Pull request by juliayakovlev**
If a table is created with COMPACT STORAGE option, two 'ghost' columns 'column1' and 'value' are added to the columns' list in the system_schema.columns table. Issue: https://github.com/scylladb/scylladb/issues/16309

COMPACT STORAGE option will be deprecated: https://github.com/scylladb/scylladb/issues/12263

So it was decided that we should test COMPACT STORAGE in system tests, only functional tests. We should also deprecate it in new tables, and think about a migration path.

Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6680

## Test
- [x] Rolling upgrade - passed (https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/rolling-upgrade-ami-test/12/)
- [x] Longevity with pre-create schema - passed (https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/staging-longevity-100gb-4h/95/)

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by juliayakovlev** [comment]
Running the tests

**Comment by juliayakovlev** [comment]
@fruch @aleksbykov please, review

**Review by aleksbykov — APPROVED** [review]
LGTM

**Review by fruch — APPROVED** [review]
LGTM

**Comment by juliayakovlev** [comment]
@fruch we need to backport it. 100g longevity continues to fail

**Comment by fruch** [comment]
> @fruch we need to backport it. 100g longevity continues to fail

yeah, saw it failing, regardless we gonna replace that branch soon.

**Pull request merged**
