### PR TITLE
Latency with nemesis new index

### PR DESCRIPTION
**Pull request by fgelcer**
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
on [this run](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/perf-with-nemesis-new-index/job/latency_during_ops_new_index/2/), while trying to write to the new index we got:
```
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Limit of total fields [1000] has been exceeded')
```

**Comment by fgelcer** [comment]
> on [this run](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/perf-with-nemesis-new-index/job/latency_during_ops_new_index/2/), while trying to write to the new index we got:
> 
> ```
> elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Limit of total fields [1000] has been exceeded')
> ```

@roydahan , although i see this failure, i do see that the new run's data was saved into the ES new index... shall we create the other 2 indexes and run a test with all the 3 new indexes?

**Comment by fgelcer** [comment]
@roydahan @aleksbykov ,

all 3 jobs failed with the same error as before:
```
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Limit of total fields [1000] has been exceeded')
```
as you can see at [this job](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/perf-with-nemesis-new-index/job/latency_during_ops_new_index/3/)

but the date (at least for read, that has the index and mapping created) were saved

**Comment by fgelcer** [comment]
> @roydahan @aleksbykov ,
> 
> all 3 jobs failed with the same error as before:
> 
> ```
> elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Limit of total fields [1000] has been exceeded')
> ```
> 
> as you can see at [this job](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/perf-with-nemesis-new-index/job/latency_during_ops_new_index/3/)
> 
> but the date (at least for read, that has the index and mapping created) were saved

@roydahan , the indexes (mixed and write) were created ([see here](https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/app/management/data/index_management/indices))

what should be done now to have them working?

**Review by roydahan — APPROVED** [review]

**Comment by roydahan** [comment]
https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/app/discover#/view/6db226a0-3a96-11ec-82e2-5720a4e10573

Index looks good.

**Pull request merged**
