### PR TITLE
fix(_destroy_data_and_restart_scylla): not fail the nemesis if at least one file was destroyed

### PR DESCRIPTION
**Pull request by juliayakovlev**
5 data files should be destroyed by this function . But if < 5 files were destroyed and for some
of the ks.cf got exception - the nemesis fails with NoFilesFoundToDestroy.
Continue the nemesis if at leaset one file was destroyed.

[Task](https://trello.com/c/3E1slwgg/2192-fix-destroydataandrestartscylla-function-not-fail-the-nemesis-if-at-least-one-file-was-destroyed)

Example of how it worked before - despite 3 files from 5 were destroyed, nemesis failed :
```
sdcm.nemesis.ChaosMonkey: Files /var/lib/scylla/data/keyspace1/standard1-780ef140d26011ea9658000000000001/mc-6-* were destroyed
sdcm.nemesis.ChaosMonkey: Files /var/lib/scylla/data/keyspace1/standard1-780ef140d26011ea9658000000000001/mc-8-* were destroyed
sdcm.nemesis.ChaosMonkey: Files /var/lib/scylla/data/keyspace1/standard1-780ef140d26011ea9658000000000001/mc-3-* were destroyed
'_choose_file_for_destroy': failed with 'NoFilesFoundToDestroy('Data file for destroy is not found in keyspace1/standard1')', retrying [#0]
'_choose_file_for_destroy': failed with 'NoFilesFoundToDestroy('Data file for destroy is not found in keyspace1/standard1')', retrying [#1]
'_choose_file_for_destroy': failed with 'NoFilesFoundToDestroy('Data file for destroy is not found in keyspace1/standard1')', retrying [#2]
'_choose_file_for_destroy': failed with 'NoFilesFoundToDestroy('Data file for destroy is not found in keyspace1/standard1')', retrying [#3]
'_choose_file_for_destroy': failed with 'NoFilesFoundToDestroy('Data file for destroy is not found in keyspace1/standard1')', retrying [#4]
'_choose_file_for_destroy': failed with 'NoFilesFoundToDestroy('Data file for destroy is not found in keyspace1/standard1')', retrying [#5]
'_choose_file_for_destroy': failed with 'NoFilesFoundToDestroy('Data file for destroy is not found in keyspace1/standard1')', retrying [#6]
'_choose_file_for_destroy': failed with 'NoFilesFoundToDestroy('Data file for destroy is not found in keyspace1/standard1')', retrying [#7]
'_choose_file_for_destroy': failed with 'NoFilesFoundToDestroy('Data file for destroy is not found in keyspace1/standard1')', retrying [#8]
'_choose_file_for_destroy': failed with 'NoFilesFoundToDestroy('Data file for destroy is not found in keyspace1/standard1')', retrying [#9]
sdcm.nemesis.ChaosMonkey: ('Exception in random_disrupt_method %s: %s', 'destroy_data_then_rebuild', NoFilesFoundToDestroy('Data file for destroy is not found in keyspace1/standard1'))
```

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
In which case/s you had less than 5 data files?

**Comment by juliayakovlev** [comment]
> In which case/s you had less than 5 data files?

In case when there are no enough data files in the folder or remoter.run returned error

**Comment by roydahan** [comment]
:)
Yes, I understand that, but where did you face such an issue?
It's really weird not having at least 5 files.

**Comment by juliayakovlev** [comment]
> :)
> Yes, I understand that, but where did you face such an issue?
> It's really weird not having at least 5 files.

For example, in features-scale-180-200-cluster-test

**Comment by roydahan** [comment]
So it means we need to use higher load there.

**Comment by juliayakovlev** [comment]
> So it means we need to use higher load there.

@roydahan You don't want this change?

**Comment by roydahan** [comment]
Not sure, still considering.
What I’m trying to figure out is if we face such issue, we need to solve the root cause.

**Comment by roydahan** [comment]
Closing for now.
Wherever you face such an issue we need to increase the load.
(IOW, should be followed up with increasing the load for the scale test)

**Pull request closed without merging**
