### PR TITLE
improvement(latte): use newer version with tablets supports

### PR DESCRIPTION
**Pull request by vponomaryov**
### Testing

- [ ]

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by vponomaryov** [comment]
Release: https://github.com/scylladb/latte/releases/tag/0.25.2-scylladb
Docker image: https://hub.docker.com/r/scylladb/hydra-loaders/tags?page=1&name=latte

**Review by roydahan — APPROVED** [review]

**Review by soyacz — APPROVED** [review]
LGTM

**Comment by soyacz** [comment]
@vponomaryov did you run it somewhere?

**Comment by vponomaryov** [comment]
> @vponomaryov did you run it somewhere?

Yes, works ok. [scylla-staging/valerii/vp-longevity-gce-custom-d1-workload2-hybrid-raid#27](https://argus.scylladb.com/test/7a8a0e29-e8e2-45c4-9271-ec040095e4a7/runs?additionalRuns[]=05b21b44-752f-493e-ba5d-5635763cbfe0)

**Pull request merged**
