### PR TITLE
fix(monitoring_prereqs): specifing python3.6 in installation

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
Fixes: #3174 

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by ShlomiBalalis** [comment]
jenkins job - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/ubuntu1604-sanity-test-monitor-fix/

**Comment by ShlomiBalalis** [comment]
Fixes #3174

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
> Fixes #3174

this should go in the PR description or inside the commit description

**Pull request merged**
