### PR TITLE
fix(rolling-upgrade-with-null-inserts): add missing params

### PR DESCRIPTION
**Pull request by fgelcer**
jenkinsfile of this test was missing some of
the required parameters, that are being added
to be able to run the test (job doesn't exist
on master, so for now will run on 4.6).

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
@roydahan , here i also set the auto mode to all tests in this same PR, but in a different commit.

**Review by dkropachev — APPROVED** [review]

**Comment by roydahan** [comment]
@fgelcer i think this one was running with AMI as base version.

**Comment by fgelcer** [comment]
> @fgelcer i think this one was running with AMI as base version.

@roydahan , it is possible, but i didn't find even a job for it in master...
the failure i got in the tests for 4.6 is that it is missing the `linux_distro` parameter... it could be that, when using an AMI instead, it is not needed, but then it should have a default (like a version, or something like this)

**Comment by roydahan** [comment]
should be the same as rolling-upgrade-ami.

**Review by enaydanov — APPROVED** [review]

**Comment by fgelcer** [comment]
> @fgelcer i think this one was running with AMI as base version.

it doesn't seem to be the case, as in the pipeline itself, it sets `backend: 'gce'`

**Comment by fgelcer** [comment]
back port to branch-4.6 is still needed

**Pull request merged**
