### PR TITLE
fix(node-setup): disable daily triggered services for Ubuntu

### PR DESCRIPTION
**Pull request by bentsi**
The code was part of _scylla_install method that was
called only when Scylla is installed but we need to disable
the daily triggered services in any case (when we use
Scylla image like AMI or GCE Image Scylla is preinstalled)

```
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo bash -cxe "\napt-get install -y scylla-manager-agent\nsed -i \'s/# auth_token:.*$/auth_token: 4ea94ed9-708e-4317-8789-01306a70a611/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nscyllamgr_ssl_cert_gen\nsed -i \'s/#tls_cert_file/tls_cert_file/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsed -i \'s/#tls_key_file/tls_key_file/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsed -i \'s/#prometheus: .*/prometheus: :5090/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsystemctl restart scylla-manager-agent\nsystemctl enable scylla-manager-agent\n"'
Exit code: 100
Stdout:
Stderr:
+ apt-get install -y scylla-manager-agent
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 14408 (unattended-upgr)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

```

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [ ] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Review by juliayakovlev — APPROVED** [review]

**Comment by bentsi** [comment]
no need to backport since it is relevant to Ubuntu based image

**Comment by roydahan** [comment]
Why do we need to disable these?
And if we do, why don't we disable them in SMI?

**Comment by bentsi** [comment]
`apt-daily`, `apt-daily-upgrade` are "built-in" services in Ubuntu that are used to update apt cache and check for upgrades on daily basis. I don't think we need to disable them in SMI since they are part of the Ubuntu installation and possible customers will need them.
In regular Ubuntu installation there are "copule" of the automatically triggered services:
image

we are disabling them since we can run in the condition (as mentioned in the description) that daily automatic apt-daily-upgrade service checks for new updates and holds the general apt lock (via /var/lib/dpkg/lock-frontend lock file) and at the same time we try to install scylla manager. This causes the apt command to fail.

**Comment by roydahan** [comment]
**So this fix is not the correct way to go.**
We should wrap our install with try, except for this lock issue and retry.
If users has this running, we should have it running and deal with its consequences.

Avoiding it only in artifacts tests would be something to consider, but in longevities we must have it enabled as we ship the AMI.

**Comment by amoskong** [comment]
> **So this fix is not the correct way to go.**
> We should wrap our install with try, except for this lock issue and retry.

Good idea, that's close to human operations.

But it's a system wide problem, some apt commands are wrapped inside scylla_setup scripts.
When scylla_setup failed for apt lock in one step, we have to disable the succeeded parts and rerun the scylla_setup.

```
[amos@fedora scylla]$ git grep apt_install
dist/common/scripts/scylla_coredump_setup:            apt_install('systemd-coredump')
dist/common/scripts/scylla_cpuscaling_setup:            apt_install('cpufrequtils')
dist/common/scripts/scylla_ntp_setup:            apt_install('ntp ntpdate')
dist/common/scripts/scylla_util.py:def apt_install(pkg):
dist/common/scripts/scylla_util.py:        return apt_install(pkg)
```

> If users has this running, we should have it running and deal with its consequences.
> 
> Avoiding it only in artifacts tests would be something to consider, but in longevities we must have it enabled as we ship the AMI.

We always use latest GCE Ubuntu images for testing, so the daily update/upgrade won't take too much time.
If the update/upgrade tasks are huge, it's difficult to evaluate the execution time.

Right now, we only upgrade system in upgrade test.

```
$ git grep upgrade_system
sdcm/cluster.py:    def upgrade_system(self):
upgrade_test.py:        node.upgrade_system()
```

**Comment by roydahan** [comment]
> > **So this fix is not the correct way to go.**
> > We should wrap our install with try, except for this lock issue and retry.
> 
> Good idea, that's close to human operations.
> 
> But it's a system wide problem, some apt commands are wrapped inside scylla_setup scripts.
> When scylla_setup failed for apt lock in one step, we have to disable the succeeded parts and rerun the scylla_setup.
> 
> ```
> [amos@fedora scylla]$ git grep apt_install
> dist/common/scripts/scylla_coredump_setup:            apt_install('systemd-coredump')
> dist/common/scripts/scylla_cpuscaling_setup:            apt_install('cpufrequtils')
> dist/common/scripts/scylla_ntp_setup:            apt_install('ntp ntpdate')
> dist/common/scripts/scylla_util.py:def apt_install(pkg):
> dist/common/scripts/scylla_util.py:        return apt_install(pkg)
> ```
> 

In this case, it may be good to open a bug for scylla and possibly add the "try:except" in scylla_setup as well.
@bentsi let's have a trello task to fix this.
@amoskong if you think we can do the same also for scylla_setup let's send a PR / issue.

**Comment by amoskong** [comment]
> > > **So this fix is not the correct way to go.**
> > > We should wrap our install with try, except for this lock issue and retry.
> > 
> > 
> > Good idea, that's close to human operations.
> > But it's a system wide problem, some apt commands are wrapped inside scylla_setup scripts.
> > When scylla_setup failed for apt lock in one step, we have to disable the succeeded parts and rerun the scylla_setup.
> > ```
> > [amos@fedora scylla]$ git grep apt_install
> > dist/common/scripts/scylla_coredump_setup:            apt_install('systemd-coredump')
> > dist/common/scripts/scylla_cpuscaling_setup:            apt_install('cpufrequtils')
> > dist/common/scripts/scylla_ntp_setup:            apt_install('ntp ntpdate')
> > dist/common/scripts/scylla_util.py:def apt_install(pkg):
> > dist/common/scripts/scylla_util.py:        return apt_install(pkg)
> > ```
> 
> In this case, it may be good to open a bug for scylla and possibly add the "try:except" in scylla_setup as well.

I opened an issue long time ago for the retry suggestion: https://github.com/scylladb/scylla/issues/4059
- need retry for all yum/apt-get install commands in setup scripts [#4059](https://github.com/scylladb/scylla/issues/4059)

> @bentsi let's have a trello task to fix this.
> @amoskong if you think we can do the same also for scylla_setup let's send a PR / issue.

Replied https://github.com/scylladb/scylla/issues/4059#issuecomment-822088803

**Comment by roydahan** [comment]
@bentsi can you please send PR for 2021.1 backport?
I can't cherry-pick it cleanly and it should be pretty simple.

**Pull request merged**
