### PR TITLE
fix(saslauthd nemesis): use remote scylla yaml object

### PR DESCRIPTION
**Pull request by bentsi**
instead of grepping the scylla YAML use the
remote_scylla_yaml() infra method

Fixing:
```
2021-04-24 21:15:14.492: (DisruptionEvent Severity.ERROR): type=SwitchBetweenPasswordAuthAndSaslauthdAuth subtype=end target_node=Node longevity-100gb-4h-master-db-node-36102894-7 [13.49.21.163 | 10.0.0.28] (seed: False) duration=0 error=Encountered a bad command exit code!
Command: "grep -o '^authenticator: .*' /etc/scylla/scylla.yaml"
Exit code: 1
Stdout:
Stderr:
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2960, in wrapper
result = method(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3255, in disrupt
self.call_random_disrupt_method()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1119, in call_random_disrupt_method
self.execute_disrupt_method(disrupt_method)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1126, in execute_disrupt_method
disrupt_method()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 490, in disrupt_switch_between_PasswordAuthenticator_and_SaslauthdAuthenticator_and_back
result = self.target_node.remoter.run("grep -o '^authenticator: .*' /etc/scylla/scylla.yaml")
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "<decorator-gen-3>", line 2, in run
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
return method(self, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
return self._run(self._remote_runner(), command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
return runner.run(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
return self._run_body(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: "grep -o '^authenticator: .*' /etc/scylla/scylla.yaml"
Exit code: 1
Stdout:
Stderr:
```

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [ ] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Review by fgelcer — APPROVED** [review]
LGTM
it relates to #3445

**Comment by fgelcer** [comment]
@amoskong will know, do we need this to be back ported to `branch-2021.1`?

**Review by roydahan — APPROVED** [review]

**Comment by bentsi** [comment]
dup of #3445 , closing

**Comment by amoskong** [comment]
> @amoskong will know, do we need this to be back ported to `branch-2021.1`?

It's needed, https://github.com/scylladb/scylla-cluster-tests/pull/3445 had been backported to 2021.1

**Pull request closed without merging**
