### PR TITLE
config_setup: support to append scylla args

### PR DESCRIPTION
**Pull request by amoskong**
update /ets/sysconfig/scylla-server file.

TODO:
- update existing scylla arg

### CODE REVIEW

**Comment by roydahan** [comment]
@harelassayag please test the "reactor stall with 1s" with this branch.
If it works for you, we will merge it.

**Comment by harelassayag** [comment]
ok

**Comment by amoskong** [comment]
In my test, I have a space in the end of append_scylla_scylla_args parameter.

```
append_scylla_scylla_args: '--blocked-reactor-notify-ms 1000 '
```

I will update the PR to always add a space, thanks for the testing.

**Comment by harelassayag** [comment]
@roydahan I tested again after @amoskong updated the PR. works fine!

**Pull request merged**
