### PR TITLE
upgrade_test: only support to upgrade from latest release

### PR DESCRIPTION
**Pull request by amoskong**
Branches: master, branch-3.2

For example:
- upgrade from 3.1 to 3.2: supported
- upgrade from 3.0 to 3.2: not supported

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by amoskong** [comment]
> LGTM, even that i don't know where the problem with GCE came from exactly, i.e. which change broke this

The problem was introduced by commit c7f16dcf4f40232b9b78130800d18f5206aa3e9f

```
@@ -144,17 +144,18 @@ class GCENode(cluster.BaseNode):
         return ''
 
 
-class GCECluster(cluster.BaseCluster):
+class GCECluster(cluster.BaseCluster):  # pylint: disable=too-many-instance-attributes,abstract-method
 
     """
     Cluster of Node objects, started on GCE (Google Compute Engine).
     """
 
-    def __init__(self, gce_image, gce_image_type, gce_image_size, gce_network, services, credentials,
-                 cluster_uuid=None, gce_instance_type='n1-standard-1', gce_region_names=['us-east1-b'],
+    def __init__(self, gce_image, gce_image_type, gce_image_size, gce_network, services, credentials,  # pylint: disable=too-many-arguments
+                 cluster_uuid=None, gce_instance_type='n1-standard-1', gce_region_names=None,
                  gce_n_local_ssd=1, gce_image_username='root', cluster_prefix='cluster',
-                 node_prefix='node', n_nodes=[10], add_disks=None, params=None):
+                 node_prefix='node', n_nodes=3, add_disks=None, params=None):
 
+        # pylint: disable=too-many-locals
         self._gce_image = gce_image
         self._gce_image_type = gce_image_type
         self._gce_image_size = gce_image_size
@@ -168,6 +169,7 @@ class GCECluster(cluster.BaseCluster):
         self._add_disks = add_disks
         # the full node prefix will contain unique uuid, so use this for search of existing nodes
         self._node_prefix = node_prefix
+        gce_region_names = gce_region_names if gce_region_names else ['us-east1-b']
         super(GCECluster, self).__init__(cluster_uuid=cluster_uuid,
                                          cluster_prefix=cluster_prefix,
                                          node_prefix=node_prefix,
```

We use default 'us-east1-b' in __init__() of GCECluster for LoaderSetGCE, MonitorSetGCE before above commit. The above commit moved the default value assignment after self._gce_region_names assignment, so it's always None.

**Comment by fruch** [comment]
@amoskong c7f16dc was merge a very long time ago, since then we didn't use GCE on master ?

**Comment by fruch** [comment]
@amoskong please solve the conflict, and we'll merge this one

**Comment by amoskong** [comment]
> @amoskong [c7f16dc](https://github.com/scylladb/scylla-cluster-tests/commit/c7f16dcf4f40232b9b78130800d18f5206aa3e9f) was merge a very long time ago, since then we didn't use GCE on master ?

Yes.

**Comment by amoskong** [comment]
> @amoskong please solve the conflict, and we'll merge this one

Done.

**Comment by amoskong** [comment]
Unittest failed, but it's unrelated with this PR.

```
21:06:06  unit_tests/test_seed_selector.py::TestSeedSelector::test_first_2_seeds Exception: Error reading SSH protocol banner
21:06:06  PASSED [ 78%]
21:06:06  unit_tests/test_seed_selector.py::TestSeedSelector::test_random_2_seeds Traceback (most recent call last):
21:06:06  Traceback (most recent call last):
21:06:06  PASSED [ 79%]    buf += self._read_timeout(timeout)
21:06:06  
21:06:06  unit_tests/test_seed_selector.py::TestSeedSelector::test_reflector_node_not_exists Traceback (most recent call last):
21:06:06      buf += self._read_timeout(timeout)
21:06:06    File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 609, in _read_timeout
21:06:06      raise EOFError()
21:06:06  EOFError
21:06:06  
21:06:06  During handling of the above exception, another exception occurred:
21:06:06  
21:06:06  Traceback (most recent call last):
21:06:06    File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2039, in run
21:06:06      self._check_banner()
21:06:06  Exception: Error reading SSH protocol banner
21:06:06    File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2216, in _check_banner
21:06:06    File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 609, in _read_timeout
21:06:06    File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2211, in _check_banner
21:06:06  Traceback (most recent call last):
21:06:06      "Error reading SSH protocol banner" + str(e)
21:06:06  paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
21:06:06      buf = self.packetizer.readline(timeout)
21:06:06    File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 380, in readline
21:06:06      buf += self._read_timeout(timeout)
21:06:06    File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 609, in _read_timeout
21:06:06      raise EOFError()
21:06:06  EOFError
21:06:06  
21:06:06  During handling of the above exception, another exception occurred:
21:06:06  
21:06:06  Traceback (most recent call last):
21:06:06    File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2039, in run
21:06:06      self._check_banner()
21:06:06    File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2216, in _check_banner
21:06:06      "Error reading SSH protocol banner" + str(e)
21:06:06  paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
21:06:06  
21:06:06      raise EOFError()
21:06:06  EOFError
21:06:06  
21:06:06  During handling of the above exception, another exception occurred:
21:06:06  
21:06:06  Traceback (most recent call last):
21:06:06    File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2039, in run
21:06:06      self._check_banner()
21:06:06    File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2216, in _check_banner
21:06:06      "Error reading SSH protocol banner" + str(e)
21:06:06  paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
21:06:06  
21:06:06  
21:06:06  Connected (version 2.0, client OpenSSH_7.4)
21:06:06    File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2211, in _check_banner
21:06:06      buf = self.packetizer.readline(timeout)
21:06:06  PASSED [ 80%]  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 380, in readline
21:06:06      buf += self._read_timeout(timeout)
21:06:06    File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 609, in _read_timeout
21:06:06      raise EOFError()
21:06:06  EOFError
21:06:06  
21:06:06  During handling of the above exception, another exception occurred:
21:06:06  
21:06:06  Traceback (most recent call last):
21:06:06    File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2039, in run
21:06:06      self._check_banner()
21:06:06    File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2216, in _check_banner
21:06:06      "Error reading SSH protocol banner" + str(e)
21:06:06  paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

**Pull request merged**
