### PR TITLE
fix(hydra): switch docker base to 3.10.12-slim-bullseye

### PR DESCRIPTION
**Pull request by fruch**
looks like we are using a very early release of python 3.10 and we didn't got the revert that was done in python/cpython#98503 rebuilding image with latest release of python 3.10

Fixes: #6345
Ref: https://github.com/python/cpython/pull/98503

### Testing:

- [x] - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/artifacts-rocky9-test/22/
- [x] - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/artifacts-rocky9-test/23/
- [x] - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/artifacts-rocky9-test/24/
- [x] - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/artifacts-rocky9-test/25/
- [x] - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/artifacts-rocky9-test/26/

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by vponomaryov — COMMENTED** [review]
Was it tested?

**Comment by fruch** [comment]
> Was it tested?

just here on the PR.

as for the specific issue it should solve, we'll need to run a  bunch of artifacts tests at the same time. (but we don't have a specific reproducer)

**Review by vponomaryov — APPROVED** [review]
LGTM

**Review by soyacz — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
All artifacts tests passed

**Pull request merged**
