### PR TITLE
fix(aws_region) Enable DNS hostnames

### PR DESCRIPTION
**Pull request by igorsimb**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fruch — APPROVED** [review]
LGTM

**Review by vponomaryov — CHANGES_REQUESTED** [review]
Please add some description to the commit message about why it is done.

**Comment by fruch** [comment]
@igorsimb @enaydanov seem like this change is breaking the aws mock test:

I'm trying to address is in:
https://github.com/scylladb/aws_mock/pull/32

**Comment by enaydanov** [comment]
> 



> @igorsimb @enaydanov seem like this change is breaking the aws mock test:
> 
> I'm trying to address is in: [scylladb/aws_mock#32](https://github.com/scylladb/aws_mock/pull/32)

Thanks @fruch . I've merged your PR and pushed a new version of aws_mock to Docker Hub. Checks for this PR was restarted too.

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
