### PR TITLE
Perf with ops add more statistics

### PR DESCRIPTION
**Pull request by fgelcer**
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
running it in [here](https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/perf_with_nemesis_report_improvements/job/perf-new-metrics/2/), so we can see the report with the new metrics in it

**Comment by fgelcer** [comment]
here a screenshot with the result (STDEV and count of points above threshold per cycle):

Screenshot from 2022-08-13 22-41-11

**Comment by fgelcer** [comment]
ping @roydahan @aleksbykov

**Comment by roydahan** [comment]
Last thing I recall for this is that the email sent with these included wrong comparisons to the past.
@aleksbykov said he will check that.
Do we have a later run with this code?

**Comment by roydahan** [comment]
Ignore my last comment, it was a mistake with a different PR.

**Comment by fgelcer** [comment]
@fgelcer to squash commits

**Review by roydahan — DISMISSED** [review]

**Comment by roydahan** [comment]
LGTM, please squash the 2 first commits.

**Comment by fgelcer** [comment]
> LGTM, please squash the 2 first commits.

@roydahan , squashed

**Review by roydahan — APPROVED** [review]

**Comment by fgelcer** [comment]
@roydahan , it wasn't backported

**Comment by fgelcer** [comment]
@roydahan please backport so i can run the RBNO jobs

**Comment by roydahan** [comment]
The RBNO isn't related to this, please run it regardless of this PR.
The backport has conflicts, please send a PR to v12 and run a test with it on top of v12.

**Comment by fgelcer** [comment]
> The RBNO isn't related to this, please run it regardless of this PR. The backport has conflicts, please send a PR to v12 and run a test with it on top of v12.

i prefer wait a bit more, to have the commits from @aleksbykov backported first, so it will most likely minimize the conflicts, but if it won't work, i will backport it next week

**Comment by fgelcer** [comment]
as we are doing bigger changes to the test, this change will come along when we will create a new branch for it, so i'm removing the backport label

**Pull request merged**
