### PR TITLE
Set multi-dc jobs to use server encryption (internode_encryption)

### PR DESCRIPTION
**Pull request by roydahan**
Enabling internode_connection for multi-dc longevity jobs.

For now set to "all".
There is a trello task to support also other options "rack, dc".
Then, one should be change to "dc".

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
We may have a customer issue around this.

**Comment by roydahan** [comment]
@scylladb/qa-maintainers I need a review and quick merge here.

**Comment by roydahan** [comment]
don't merge yet, adding also client_encryption.

**Comment by fruch** [comment]
@roydahan what about the alternator multi dc ? you don't want it ?

**Review by bentsi — APPROVED** [review]

**Comment by bentsi** [comment]
@fruch I am merging this since Roy asked for quick merge

**Comment by roydahan** [comment]
Thanks.
Running a test using this change https://jenkins.scylladb.com/view/master/job/scylla-master/view/master-test/job/longevity/job/longevity-counters-6h-multidc-test/36/console

**Pull request merged**
