### PR TITLE
improvement(docker-backend): strip "_local" suffix from config file name

### PR DESCRIPTION
**Pull request by lersek**
Commit 9d9d98affbf8 introduced the "docker_backend_local.yaml" config file for running tests on the local workstation.

Commit fdef448af0cd enabled running the same docker tests in Jenkins / on AWS.

Therefore the "_local" suffix in the config file name is not valid anymore; the same config file can now be used for remote setups as well. Remove the suffix.

Fixes: fdef448af0cd

### Testing

- [ ]

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by lersek** [comment]
All checks have passed so I'm flipping the PR from "draft" to "ready for review">

**Review by dimakr — APPROVED** [review]
The change looks good to me.
But I don't understand the statement `Furthermore, the same commit restricted the longevity pipeline to the latter (i.e., remote) configuration only.`.
The referenced series of changes didn't restrict existing pipelines, but created a number of new jenkinsfiles to have dedicated pipelines for docker config. Maybe that statement is not necessary, to avoid confusion.

**Comment by lersek** [comment]
@dimakr thank you for the review, I'm going to push a v2 with the noted sentence removed.

**Comment by lersek** [comment]
v2: update both commit message and PR blurb per https://github.com/scylladb/scylla-cluster-tests/pull/8254#pullrequestreview-2220798202

**Pull request merged**
