### PR TITLE
fix(artifactsPipeline): use the right `region_name`

### PR DESCRIPTION
**Pull request by fgelcer**
since the last change, the `region_name` set to
the functions is not the correct for this branch.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by yaronkaikov — APPROVED** [review]
LGTM - Thanks

**Comment by fgelcer** [comment]
giving it a ride in [here](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/4.5/job/artifacts-ami-region-name-issue/2/)

**Comment by fgelcer** [comment]
@fruch , please merge

**Comment by fruch** [comment]
@fgelcer I've reverted all the changes to the artifacts pipeline that was introducing this

**Comment by fruch** [comment]
@fgelcer seem like the revert is solving the issue, we won't have the better timeout in this branch

https://jenkins.scylladb.com/job/scylla-4.5/job/artifacts/job/artifacts-ami-test/1668/

**Comment by fgelcer** [comment]
thank you @fruch

**Pull request closed without merging**
