### PR TITLE
Fix double email message sent by gemini job

### PR DESCRIPTION
**Pull request by aleksbykov**
Trello: https://trello.com/c/UAT64VdY

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by aleksbykov** [comment]
test-provision job was terminated

**Comment by fruch** [comment]
@aleksbykov seems like we hardcoded the test-provision only to one builder, and it's full now.
that's why it's timeout
anyhow for the changed you did here, this file won't cover it, i.e. you didn't did any change to `Jenkinsfile`

**Comment by fruch** [comment]
@aleksbykov please test it on a job in staging

**Comment by aleksbykov** [comment]
Ran job staging for gemini and for longevity, if email is set in *.jenkinsfile as parameter, it will be taken for email report sending, overwise the default qa@ will be used.

**Comment by aleksbykov** [comment]
One email only sent

**Pull request merged**
