### PR TITLE
fix(longevity-alternator-3h.yaml): Add timeout to ycsb

### PR DESCRIPTION
**Pull request by dkropachev**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [ ] ~~All new and existing unit tests passed (CI)~~
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by roydahan** [comment]
@fruch please review and if approving merge.

**Comment by fruch** [comment]
@dkropachev can you explain why adding this, cause technically there code adding this timeout during the run (based on `test_duration`).
can you explain why it's not enough ? or what's wrong with it ? that we need to add this ?

**Comment by dkropachev** [comment]
> @dkropachev can you explain why adding this, cause technically there code adding this timeout during the run (based on `test_duration`).
> can you explain why it's not enough ? or what's wrong with it ? that we need to add this ?

We should stop using test_duration as default timeout for stressthreads, it is time that will take whole test , including startup proceedures, up untill tearwdown is started.
This is exact reason why cdc longevity have no chance to complete in time:
https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h-test/111/
https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h-test/100/

Currently get_timeout for this test is set to 5h while test body should be completed in 3h, as result ycsb spinning till test timeout is reached and test is getting killed by timeout reason.

**Comment by fruch** [comment]
> > @dkropachev can you explain why adding this, cause technically there code adding this timeout during the run (based on `test_duration`).
> > can you explain why it's not enough ? or what's wrong with it ? that we need to add this ?
> 
> We should stop using test_duration as default timeout for stressthreads, it is time that will take whole test , including startup proceedures, up untill tearwdown is started.
> This is exact reason why cdc longevity have no chance to complete in time:
> https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h-test/111/
> https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h-test/100/
> 
> Currently get_timeout for this test is set to 5h while test body should be completed in 3h, as result ycsb spinning till test timeout is reached and test is getting killed by timeout reason.

I still rather handle it systematically then adding specific times in each stress command across the board.
I thought the all idea we'll have one parameter to control the length of test. and not multiple of those.

**Comment by dkropachev** [comment]
> > > @dkropachev can you explain why adding this, cause technically there code adding this timeout during the run (based on `test_duration`).
> > > can you explain why it's not enough ? or what's wrong with it ? that we need to add this ?
> > 
> > 
> > We should stop using test_duration as default timeout for stressthreads, it is time that will take whole test , including startup proceedures, up untill tearwdown is started.
> > This is exact reason why cdc longevity have no chance to complete in time:
> > https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h-test/111/
> > https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h-test/100/
> > Currently get_timeout for this test is set to 5h while test body should be completed in 3h, as result ycsb spinning till test timeout is reached and test is getting killed by timeout reason.
> 
> I still rather handle it systematically then adding specific times in each stress command across the board.
> I thought the all idea we'll have one parameter to control the length of test. and not multiple of those.

That is exactly why we do that, test_duration sets deadline for test to complete, there is no other way to control test execution time, because depending on test scenario you could either run 3 stress commands one by one, or do something in between the runs that could consume significant amount of time. 

We can have something like default stress execution time, but this is not purpose of this PR, this PR is to give the test chance to complete seccessfully.

**Review by bentsi — APPROVED** [review]

**Pull request merged**
