### PR TITLE
fix(backup nemesis): deleting all backup tasks before nemesis run

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
Since multiple backup nemesis cannot run at the same time, I
deleted all running backups and those that are about to run before
the backup task the nemesis creates starts

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by ShlomiBalalis** [comment]
Run has passed: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/cloud-longevity-small-data-set-1h-gcp/10/

**Comment by fruch** [comment]
@ShlomiBalalis is there code in SCT that make sure we don't run backup in parallel ? I.e. does parallel nemesis is aware of this ?

**Comment by ShlomiBalalis** [comment]
> @ShlomiBalalis is there code in SCT that make sure we don't run backup in parallel ? I.e. does parallel nemesis is aware of this ?

I don't believe we do, no

> @ShlomiBalalis - does it mean that you will delete all scheduled backups? no, right?

It will, as long as they didn't run before. Why?

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@ShlomiBalalis why this needs to be backported to 5.0 ? can you point to the issue happening there ?

**Comment by ShlomiBalalis** [comment]
> @ShlomiBalalis why this needs to be backported to 5.0 ? can you point to the issue happening there ?

It was more of a precaution, I didn't see it there. I suppose we can skip the backports.

**Review by rayakurl — APPROVED** [review]
Approved, after talking to Shlomo.

**Pull request merged**
