### PR TITLE
refactor(manager_pipeline): add sct-runner support

### PR DESCRIPTION
**Pull request by fruch**
* add support for using sct-runner
* add timeout support for each stage on it's own as
  in the `longevityPipeline.groovy`

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- ~~[ ] New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [x] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [x] All new and existing unit tests passed (CI)
- ~~[ ] I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by bentsi** [comment]
did you test this?

**Comment by fruch** [comment]
Still testing:

https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/manager-sanity/9/

But almost working

**Comment by fruch** [comment]
@bentsi this is ready for review.
It's working as expected from my POV

**Review by bentsi — APPROVED** [review]

**Comment by bentsi** [comment]
approved. Please backport this.

**Pull request merged**
