### PR TITLE
refactor(test config): change region for gemini jobs to us-east-1

### PR DESCRIPTION
**Pull request by aleksbykov**
Run gemini tests on us-east-1 region for regular manner.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I gave variables/functions meaningful self-explanatory names
- [ ] I didn't leave commented-out/debugging code
- [ ] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by bentsi** [comment]
@aleksbykov but what about pipelines?

**Comment by aleksbykov** [comment]
@bentsi , yep. fixed email and region

**Comment by fruch** [comment]
@aleksbykov this should be close if we merge #1784, right ?

**Comment by aleksbykov** [comment]
@fruch , yes this will not need any more

**Pull request closed without merging**
