### PR TITLE
use 3 keyspaces with different CompactionStrategy in longevity test

### PR DESCRIPTION
**Pull request by amoskong**
We want to cover three CompactionStrategy in longevity test.

- 'SizeTieredCompactionStrategy',
- 'DateTieredCompactionStrategy',
- 'LeveledCompactionStrategy'

### CODE REVIEW

**Comment by roydahan** [comment]
Looks good.
However, let's have a seperate branch with all these longevity enhancements, so we can test them all together.
(Including @larisau changes).

**Comment by larisau** [comment]
Because my last PR will be in conflict with this one, I'm waiting for the new branch to resolve the conflicts and re-sent my PR.

**Comment by amoskong** [comment]
@larisau I already merged this PR to https://github.com/scylladb/scylla-cluster-tests/commits/longevity , please rebase and send your PR

**Comment by amoskong** [comment]
We had reverted the patches from longevity branch.

**Pull request closed without merging**
