### PR TITLE
fix(remote_file): write inplace into the file

### PR DESCRIPTION
**Pull request by fruch**
since in some cases there's a process listing on changes
to this file, doing so with `mv` fails to continue the watch
on those files

### Testing
- [x] - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/longevity-5gb-1h-GrowShrinkClusterNemesis-aws-test/5/

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@soyacz @vponomaryov found the root cause of why there was no updates, the `mv` that `remote_file` was doing
caused prometheus to stop getting update on that file, and changing it in-place solve the issue 

here a dashboard showing the monitor node data is there in all of the test, while before it was gone after the first update
image

**Comment by soyacz** [comment]
> @soyacz @vponomaryov found the root cause of why there was no updates, the `mv` that `remote_file` was doing caused prometheus to stop getting update on that file, and changing it in-place solve the issue

nice catch,
the only left thing is to fix unit tests:
```
FAILED unit_tests/test_remoter.py::TestRemoteFile::test_remote_file - AssertionError: 'bash -cxe "cat \'temporary\' > \'/some/path/some.file\'\nrm \'temporary\'\n"' != "mv 'temporary' '/some/path/some.file'"
```

**Review by vponomaryov — CHANGES_REQUESTED** [review]
Good catch.
Left to fix unit tests.

**Review by soyacz — APPROVED** [review]
LGTM

**Pull request merged**
