### PR TITLE
fix(nemesis.py): Ignoring "got error in row level repair" error during repair

### PR DESCRIPTION
**Pull request by Orenef11**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- ~[] New configuration option are added and documented (in `sdcm/sct_config.py`)~
- ~[ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~
- [x] All new and existing unit tests passed (CI)
- ~[ ] I have updated the Readme/doc folder accordingly (if needed)~

### CODE REVIEW

**Comment by Orenef11** [comment]
Same commit for 4.6
https://github.com/scylladb/scylla-cluster-tests/pull/4335

**Comment by fgelcer** [comment]
> Same commit for 4.6 #4335

so you should change it to base version to be 4.6 (this is meant to be merged to master)

**Comment by Orenef11** [comment]
> > Same commit for 4.6 #4335
> 
> so you should change it to base version to be 4.6 (this is meant to be merged to master)

Done (thanks!)

**Comment by fgelcer** [comment]
commits to 4.6 are now FF from master, no special PR need to be sent to it

**Comment by fgelcer** [comment]
> > > Same commit for 4.6 #4335
> > 
> > 
> > so you should change it to base version to be 4.6 (this is meant to be merged to master)
> 
> Done (thanks!)

and BTW you didn't change the base version where you want it to be merged to

**Comment by Orenef11** [comment]
> and BTW you didn't change the base version where you want it to be merged to

I did it for #4335 
image

**Comment by fgelcer** [comment]
> > and BTW you didn't change the base version where you want it to be merged to
> 
> I did it for #4335 image

we don't need 2 PRs... move #4335 back to be merged to master, but explain why are you making this change... it doesn't make too much sense to me

**Pull request closed without merging**
