### PR TITLE
refactor(tester): add support for truncate timeout

### PR DESCRIPTION
**Pull request by KnifeyMoloko**
Truncate queries can now have an optional USING TIMEOUT parameter. This commit adds the timeout as an optional argument to the truncate_cf() method in our Tester class.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by fruch** [comment]
This on it's own seems harmless

But the code that is going to use it, needs to be aware of the version it's supported in (both OSS and enterprise), especially if it's going to be using as part of upgrade sequence, where we use older version by design.

**Comment by KnifeyMoloko** [comment]
> This on it's own seems harmless
> 
> But the code that is going to use it, needs to be aware of the version it's supported in (both OSS and enterprise), especially if it's going to be using as part of upgrade sequence, where we use older version by design.

I agree, but at the same time I don't think there's significant risk here. At the moment we're not using this method in rolling-upgrades (we run a bunch of pre-written queries as validation there, but not using this method) and if a future refactor includes it and runs with an older version, it will be an easy debug, since it's a CQL SyntaxError. 
This commit is more so that in the future anyone wanting to use truncate can be made aware of the timeout option via code.

**Review by fgelcer — APPROVED** [review]
LGTM

@KnifeyMoloko , did you try changing this on some calls to use this timeout and see what we get?

**Comment by fruch** [comment]
@fgelcer @KnifeyMoloko 

If there no immediate work going to be done ontop of it, from my POV it can way.

I rather no merge unused code (we have plenty of that already)

once someone is gonna need it, he could do the changes needed for his work. (or take this change as is)

**Comment by roydahan** [comment]
What I don't understand is what timeout do we use for it.
Also, What I want to see here is that a test that usually reproduce issue 6309 (Truncate timeout) doesn't reproduce it anymore when using large enough timeout.
And then, set large enough timeout as the default and hopefully even close 6309.

**Review by roydahan — APPROVED** [review]

**Comment by fgelcer** [comment]
> What I don't understand is what timeout do we use for it. Also, What I want to see here is that a test that usually reproduce issue 6309 (Truncate timeout) doesn't reproduce it anymore when using large enough timeout. And then, set large enough timeout as the default and hopefully even close 6309.

should we create a task from this comment?

**Pull request merged**
