### PR TITLE
sdcm/prometheus: reuse existing prometheus API server

### PR DESCRIPTION
**Pull request by amoskong**
Currently start_metrics_server() is only called once,
the whole testing uses the prometheus API server which
is started in monitor setup.

This patch supports to reuse available prometheus API server.

### CODE REVIEW

**Comment by amoskong** [comment]
Test:
```
>>> from sdcm.prometheus import start_metrics_server
>>> start_metrics_server(8001)
'10.240.0.49:8001'
>>> start_metrics_server(8001)
('Reuse existing prometheus API server on port: %s', 8001)
'10.240.0.49:8001'
```

**Comment by larisau** [comment]
from my ipython session:

```
In [35]: import prometheus_client

In [36]: prometheus_client.start_http_server(9389)

In [37]: prometheus_client.start_http_server(9389)

In [38]: Exception in thread Thread-1793:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/prometheus_client/exposition.py", line 103, in run
    httpd = HTTPServer((addr, port), MetricsHandler)
  File "/usr/lib64/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib64/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

```

**Comment by larisau** [comment]
Anyway trying to understand why do we need this patch.
1. Currently start_metrics_server() is only called once, so the curl command always fail - it's bad.
2. Instead of checking command status, command output is checked - not so good.
3. in curl hostname used instead of IP - it's wrong too

**Comment by amoskong** [comment]
Did you use the code (included this PR)?

**Comment by larisau** [comment]
No, you can ignore it.
Please read my comments above.

**Comment by amoskong** [comment]
So NACK this PR.

On Mon, Dec 18, 2017 at 6:00 PM, Larisa Ustalov <notifications@github.com>
wrote:

> Anyway trying to understand why do we need this patch.
>
>    1. Currently start_metrics_server() is only called once, so the curl
>    command always fail - it's bad.
>
> It will succeed if there are multiple SCT running in one builder. But we
should use multiple ports for this case.
Original code is fine, the PR introduced new problem.

>
>    1. Instead of checking command status, command output is checked - not
>    so good.
>
> Both command status and output should be checked.

>
>    1. in curl hostname used instead of IP - it's wrong too
>
>

**Pull request closed without merging**
