### PR TITLE
fix(schema-agreement): print proper error messages. v2

### PR DESCRIPTION
**Pull request by vponomaryov**
For the moment, if we fail to get the peers info for some reason, then we get 'Schema agreement is not reached' error running the 'ToggleTableIcs' nemesis.
So, detect specific problems and report correct messages not hiding valueable info.

Closes: https://github.com/scylladb/scylla-cluster-tests/issues/5265

P.S.
First version of this change was merged with 2 bugs in the [1]. And then reverted in the [2].

The problem with v1 was lots of redundant 'gossip' and 'peers' API calls with huge waiting intervals '2m14s' instead of '7s' for each of the DB nodes.

It was caused by the absence of the 'break' statement for the retry loop in case of success and reporting of a failure from previous iterations on the last succeeded, which caused the rerun of the function again.

The side effect of this redundancy is increase of spent time for a DB table creation in the 'upgrade_test.py' from '30s' to '537s'. 
Diff is 18 times in this case.
Multiplying it to the huge number of DB tables (90+) we were getting job timeouts.

So, fix 2 mentioned bugs and cover both cases in the unit tests.

[1] https://github.com/scylladb/scylla-cluster-tests/pull/5272 
[2] https://github.com/scylladb/scylla-cluster-tests/pull/5294

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [x] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by vponomaryov** [comment]
`precommit` failed on the unrelated module -> `sdcm/nemesis.py`

**Comment by fruch** [comment]
> `precommit` failed on the unrelated module -> `sdcm/nemesis.py`

Can you fix that on that issue ? it was introduced by the new operator functional test that copied some code out of the nemesis

Also let do a run of rolling upgrade with this PR, to verify it.

**Comment by vponomaryov** [comment]
> > `precommit` failed on the unrelated module -> `sdcm/nemesis.py`
> 
> Can you fix that on that issue ? it was introduced by the new operator functional test that copied some code out of the nemesis
> 
> Also let do a run of rolling upgrade with this PR, to verify it.

Tested here: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-rolling-upgrade-debian10-test-large-partitions/2/consoleFull
The timings for tables creations became normal, it failed on the `scylla-bench` command as written in the existing open bug: https://github.com/scylladb/scylladb/issues/11459

**Comment by fruch** [comment]
> > > `precommit` failed on the unrelated module -> `sdcm/nemesis.py`
> > 
> > 
> > Can you fix that on that issue ? it was introduced by the new operator functional test that copied some code out of the nemesis
> > Also let do a run of rolling upgrade with this PR, to verify it.
> 
> Tested here: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-rolling-upgrade-debian10-test-large-partitions/2/consoleFull The timings for tables creations became normal, it failed on the `scylla-bench` command as written in the existing open bug: [scylladb/scylladb#11459](https://github.com/scylladb/scylladb/issues/11459)

the error from the test doesn't look like: scylladb/scylladb#11459, there it's a repair failing on the keyspace, and in you case schema isn't agreed, and then truncate fails..

**Comment by vponomaryov** [comment]
@fruch 
I meant that the problem with the newly added call of the `scylla-bench`.
In current case, we call `scylla-bench` and get this agreement error not waiting or retrying.
So, I think, simple check for the agreement in SCT before calling `scylla-bench` must fix the problem.

Or in short, I see no relation of this PR to the failure of the job. Timings of table creations became normal.

**Comment by vponomaryov** [comment]
@fruch ?

**Review by fruch — APPROVED** [review]

**Pull request merged**
