### PR TITLE
improvement(hydra): Update hydra image to contain PyYAML==6.0.1

### PR DESCRIPTION
**Pull request by temichus**
build separate hydra image for branch-perf-v14 branch to apply changes
from https://github.com/scylladb/scylla-cluster-tests/pull/6404

also update argus-alm to latest version due to
incompatible versions in the resolved dependencies:
PyYAML<6.0.0,>=5.4.1 (from argus-alm==0.8.1->-r requirements.in (line 33))

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fgelcer — COMMENTED** [review]
if you are sure this fixes the issue for the perf branches, then LGTM

**Comment by temichus** [comment]
> if you are sure this fixes the issue for the perf branches, then LGTM

issue fixed by https://github.com/scylladb/scylla-cluster-tests/commit/89ed8c01fcb196b7ccb66b2db9d8c3512b8b3a77  

this PR is about proper backport and applying changes from https://github.com/scylladb/scylla-cluster-tests/pull/6404

**Review by soyacz — APPROVED** [review]
LGTM

**Review by fgelcer — CHANGES_REQUESTED** [review]
something is off then... because docker version is different from the PR you are taking its content from.. see https://github.com/k0machi/scylla-cluster-tests/blob/c7a12f997b6c405c337e3f1b9b7998b9cdf55e0e/docker/env/version#L1

**Comment by temichus** [comment]
> something is off then... because docker version is different from the PR you are taking its content from.. see https://github.com/k0machi/scylla-cluster-tests/blob/c7a12f997b6c405c337e3f1b9b7998b9cdf55e0e/docker/env/version#L1

Yes because I've built a new docker image, special for perf-14 : 1.37-pyyaml-awscli-fix-cython_pref-v14

**Comment by temichus** [comment]
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/simple_query_weekly_microbenchmark_test/
 perf-simple-query pipeline now passed

**Comment by fgelcer** [comment]
> > something is off then... because docker version is different from the PR you are taking its content from.. see https://github.com/k0machi/scylla-cluster-tests/blob/c7a12f997b6c405c337e3f1b9b7998b9cdf55e0e/docker/env/version#L1
> 
> Yes because I've built a new docker image, special for perf-14 : 1.37-pyyaml-awscli-fix-cython_pref-v14

this isn't explained in the commit msg

**Comment by fruch** [comment]
@temichus please update the title of the PR and the commit, the change itself is also changing argus, and it's not clear why

**Comment by temichus** [comment]
> @temichus please update the title of the PR and the commit, the change itself is also changing argus, and it's not clear why

uptaded

**Review by k0machi — APPROVED** [review]
LGTM

**Review by fgelcer — APPROVED** [review]
LGTM

**Pull request merged**
