### PR TITLE
fix(requirements.txt): Update requirements.txt (siren-stable)

### PR DESCRIPTION
**Pull request by k0machi**
This is a followup commit to add updated requirements.txt created from
https://github.com/scylladb/scylla-cluster-tests/pull/6168

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [x] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [x] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by soyacz** [comment]
@k0machi please add commit description

**Comment by fruch** [comment]
@k0machi what is this change ? why it's changing only `requriements.txt` and not `requirement.in` ?

**Comment by k0machi** [comment]
@fruch @soyacz Added the description, it's a quick followup to make sure requirements.in in #6168 stays in sync on this branch.

**Comment by fruch** [comment]
> @fruch @soyacz Added the description, it's a quick followup to make sure requirements.in in #6168 stays in sync on this branch.

Why are we doing PR into that branch ?

**Comment by fruch** [comment]
@k0machi is #6196 enough, so this can be closed ?

**Comment by k0machi** [comment]
> @k0machi is #6196 enough, so this can be closed ?

Yes, this can be closed

**Pull request closed without merging**
