### PR TITLE
fix(cordump_thread): get coredumpctl output in json format

### PR DESCRIPTION
**Pull request by fruch**
Switch to used json format when available, to avoid parsing the outout of coredumpctl which keep of changing

Fix: #5489

- [x] Testing known to be coredumping job:
https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity-large-partition-asymmetric-cluster-3h-test/12

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
we need it in perf branches also.

**Review by roydahan — APPROVED** [review]

**Comment by fruch** [comment]
> we need it in perf branches also.

branch-perf-v8 - doesn't even has those files I'm touching here, it's not a backport, we'll need to re-implement it.

**Comment by fruch** [comment]
> > we need it in perf branches also.
> 
> branch-pref-v8 - doesn't even has those files I'm touching here, it's not a backport, we'll need to re-implement it. 

implemented it for v8 in: https://github.com/scylladb/scylla-cluster-tests/pull/5498

> branch-perf-v12 - it's gonna be a clean backport

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@roydahan @fgelcer, you think we need this fix also for 5.1/2022.2 ? if there gonna backport the change for the AMIs for some reason ?

**Comment by fgelcer** [comment]
> @roydahan @fgelcer, you think we need this fix also for 5.1/2022.2 ? if there gonna backport the change for the AMIs for some reason ?

maybe later, for the release we are working now, i think there won't be any other changes to `systemd` in it

**Comment by fgelcer** [comment]
perhaps we may need it, depending on the `systemd` version included in the `5.1.0` images

**Comment by fruch** [comment]
> perhaps we may need it, depending on the `systemd` version included in the `5.1.0` images

it was part of moving to ubuntu 22.04, as far as I know.
but if @yaronkaikov would have have reason to backport those change to 5.1/2022.2 (or 2022.1)

then we'll need it.

**Comment by fgelcer** [comment]
> > perhaps we may need it, depending on the `systemd` version included in the `5.1.0` images
> 
> it was part of moving to ubuntu 22.04, as far as I know. but if @yaronkaikov would have have reason to backport those change to 5.1/2022.2 (or 2022.1)

then we won't need it

**Comment by yaronkaikov** [comment]
> > perhaps we may need it, depending on the `systemd` version included in the `5.1.0` images
> 
> it was part of moving to ubuntu 22.04, as far as I know. but if @yaronkaikov would have have reason to backport those change to 5.1/2022.2 (or 2022.1)
> 
> then we'll need it.

We will not change the OS for active releases

**Pull request merged**
