### PR TITLE
fix(unit-tests): fix CI checks

### PR DESCRIPTION
**Pull request by KnifeyMoloko**
This PR includes a few commits cherry-picked from master and a small fix to imports in order to fix the CI checks on branch-2022.1.

Part of the effort in: https://github.com/scylladb/qa-tasks/issues/813

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by fgelcer** [comment]
this test had 1 failure:
```
___________________ TestBaseVersion.test_2022_1_with_centos8 ___________________

self = <unit_tests.test_base_version.TestBaseVersion testMethod=test_2022_1_with_centos8>

    def test_2022_1_with_centos8(self):
        scylla_repo = self.url_base + \
            'unstable/scylla-enterprise/enterprise-2022.1/deb/unified/2022-06-03T00:22:55Z/scylladb-2022.1/scylla.list'
        linux_distro = 'centos-8'
        version_list = general_test(scylla_repo, linux_distro)
>       self.assertEqual(['5.0', '2021.1'], version_list)
E       AssertionError: Lists differ: ['5.0', '2021.1'] != ['5.0', '2021.1', '2022.1']
E       
E       Second list contains 1 additional elements.
E       First extra element 2:
E       '2022.1'
E       
E       - ['5.0', '2021.1']
E       + ['5.0', '2021.1', '2022.1']
E       ?                 ++++++++++

unit_tests/test_base_version.py:81: AssertionError
```

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by fgelcer** [comment]
need to backport this list of commits to `branch-5.0` and i expect it to fix all the checks as well

**Comment by roydahan** [comment]
I don't understand the list of commits in this PR.

**Comment by KnifeyMoloko** [comment]
> I don't understand the list of commits in this PR.

@roydahan Sorry for that, the description of the PR itself didn't help - I updated it. The commit were cherry-picked from master to fix our unit tests, plus some small changes to make the linter happy.

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
