### PR TITLE
fix(log_collector): stop compressing files remotely

### PR DESCRIPTION
**Pull request by fruch**
Since after we collect those files, we compress it yet again
into a tar.gz for the whole cluster/set, like db-cluster-**.tar.gz

Closes: #4793, #1820

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
looks like it's working o.k:
https://cloudius-jenkins-test.s3.amazonaws.com/0f83ad8b-482d-42ec-a8aa-c648ff39e09b/20220524_190341/db-cluster-0f83ad8b.tar.gz

**Review by roydahan — APPROVED** [review]

**Comment by fruch** [comment]
> LGTM, but have a question What if log on node is too large , will the change affect on download time?

from the run I've did, there wasn't any change (but I wouldn't expected an issue), especially we are using SCT-Runner all around.
there's no problem of space, cause we run only one test on it.

**Comment by enaydanov** [comment]
> LGTM, but have a question What if log on node is too large , will the change affect on download time?

Big files can be a problem. But for `rsync` we use `-z` option (which will compress data on a wire)
So, we can add the same for `scp` (`-C` option) and need to think about how we can solve it for k8s nodes.

**Comment by fruch** [comment]
> > LGTM, but have a question What if log on node is too large , will the change affect on download time?
> 
> Big files can be a problem. But for `rsync` we use `-z` option (which will compress data on a wire) So, we can add the same for `scp` (`-C` option) and need to think about how we can solve it for k8s nodes

aren't we reading the logs via kubectl commands ? straight into the test ?
can you explain why k8s is problematic in this case ?

**Comment by fruch** [comment]
as for the scp fallback, we should be using it. all of our tests are running inside hydra image, and should have rsync.

I think those fallback can be removed...

**Pull request merged**
