### PR TITLE
fix(argus): make it be compatible with K8S backends

### PR DESCRIPTION
**Pull request by vponomaryov**
Fix following exception:
```    
  File "%path%/sdcm/cluster.py", line 295, in
    provider=self.parent_cluster.cluster_backend,
  AttributeError: 'LocalKindCluster' object has no attribute 'cluster_backend'
```
    
By adding missing 'cluster_backend' attribute for K8S classes.
    
then, fix following exception:
```
  File "%path%/sdcm/cluster.py", line 294, in
    instance_details = CloudInstanceDetails(public_ip=self.public_ip_address,
  File "<string>", line 10, in __init__
  File "%path%/pydantic/dataclasses.py", line 99, in
    raise validation_error
  pydantic.error_wrappers.ValidationError: 1 validation error for CloudInstanceDetails
  region
    none is not an allowed value (type=type_error.none.not_allowed)
```

By making RemoteDocker and LocalNode provide non-empty strings as values
for the 'region' attribute instead of None which is not expected by Argus.
    
Finally fix following exception:
```    
  File "%path%/sdcm/cluster.py", line 294, in _init_argus_resource
    instance_details = CloudInstanceDetails(public_ip=self.public_ip_address, region=self.region,
  File "%path%/sdcm/cluster_k8s/__init__.py", line 1414, in region
    return self.parent_cluster.k8s_cluster.datacenter[0]
  IndexError: tuple index out of range
```

By properly getting datacenter value.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Review by k0machi — DISMISSED** [review]
Looks good to me

**Comment by vponomaryov** [comment]
Pre-commit failure looks unrealted. Pylint found code duplication in unchanged files.

**Review by bentsi — APPROVED** [review]

**Comment by bentsi** [comment]
pylint should pass, please fix the code dup issue

**Comment by bentsi** [comment]
merging since it is urgent, let's fix the code dups in separate PR

**Pull request merged**
