### PR TITLE
fix(docker): enable the ssh service back

### PR DESCRIPTION
**Pull request by fruch**
since scylladb/scylladb@7ce6962141dd4def9ce56837db691e2a8a983289 has removed the ssh service from it's code, we need to introduce it back on SCT end for docker backend to be workable

Fixes: #6887

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by yaronkaikov** [comment]
@fruch in 2022.2 it seems there is still an issue, https://jenkins.scylladb.com/job/enterprise-2022.2/job/artifacts/job/artifacts-docker-test/41/consoleFull Can you please have a look?

**Comment by fruch** [comment]
> @fruch in 2022.2 it seems there is still an issue, https://jenkins.scylladb.com/job/enterprise-2022.2/job/artifacts/job/artifacts-docker-test/41/consoleFull Can you please have a look?

seems like in this change I've broke the version check, fixing it in:
https://github.com/scylladb/scylla-cluster-tests/pull/6958

**Comment by mykaul** [comment]
@fruch - we use SSH since we do not have a 'docker exec' kind of way to get into the containers and run commands, I reckon?

**Comment by fruch** [comment]
> @fruch - we use SSH since we do not have a 'docker exec' kind of way to get into the containers and run commands, I reckon?

it use ssh, since it's much more simple, and match how we work with VMs

for k8s we are not using ssh, but for that we have to have a full implementation or the Remoter, that includes running command, and copying files, we might have such for docker as well, but it doesn't worth the effort

**Comment by fruch** [comment]
> > @fruch - we use SSH since we do not have a 'docker exec' kind of way to get into the containers and run commands, I reckon?
> 
> it use ssh, since it's much more simple, and match how we work with VMs
> 
> for k8s we are not using ssh, but for that we have to have a full implementation or the Remoter, that includes running command, and copying files, we might have such for docker as well, but it doesn't worth the effort

this check is relevant only to docker backend.
which we use for docker artifact test, and for local development only.

**Pull request merged**
