### PR TITLE
feature(argus): Update to 0.8.0

### PR DESCRIPTION
**Pull request by k0machi**
Added new scylla_version field, allowing to filter runs by specific
scylla version.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [x] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [x] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

[Trello](https://trello.com/c/FCR7csNH/5012-store-scylla-version-as-an-lsi-allow-dashboard-filtering-by-version)

### CODE REVIEW

**Comment by k0machi** [comment]
Running a staging job to verify changes [here](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/alexey/job/alexey-argus-testing/33/).

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by fruch — APPROVED** [review]
LGTM

**Comment by roydahan** [comment]
Are you backporting?

**Comment by roydahan** [comment]
Backported.

**Pull request merged**
