### PR TITLE
fix(c-s): update the docker image we use for c-s

### PR DESCRIPTION
**Pull request by fruch**
until we'll have an offical release of c-s seperate from scylla core we built this image, base on the version from scylla 6.0 this version should have tablets support (which 5.4.6 didn't had)

### Testing

- [ ]

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Review by soyacz — APPROVED** [review]
LGTM

**Comment by soyacz** [comment]
one more thing to consider is to update also loader ami's or... verify if we can drop them in favor of docker loaders.

**Comment by fruch** [comment]
> one more thing to consider is to update also loader ami's or... verify if we can drop them in favor of docker loaders.

the only reason we keep those, was for performance tests
we have a task for it: 
- https://github.com/scylladb/qa-tasks/issues/1715

**Review by vponomaryov — CHANGES_REQUESTED** [review]
Need also to update the `sdcm/remote/kubernetes_cmd_runner.py` module.
Specifically the `_get_docker_image` method in it:

https://github.com/scylladb/scylla-cluster-tests/blame/856af26dff1271ed87419751b0e3808784148d92/sdcm/remote/kubernetes_cmd_runner.py#L399

**Comment by fruch** [comment]
> Need also to update the `sdcm/remote/kubernetes_cmd_runner.py` module. Specifically the `_get_docker_image` method in it:
> 
> https://github.com/scylladb/scylla-cluster-tests/blame/856af26dff1271ed87419751b0e3808784148d92/sdcm/remote/kubernetes_cmd_runner.py#L399

updated both `_get_docker_image` functions, and remove the usage of scylla images

**Review by vponomaryov — APPROVED** [review]
LGTM

**Pull request merged**
