### PR TITLE
fix(nemesis.py): Disabling TruncateMonkeyLargePartition nemesis

### PR DESCRIPTION
**Pull request by Orenef11**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [ ] ~~All new and existing unit tests passed (CI)~~
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Review by roydahan — APPROVED** [review]

**Comment by yarongilor** [comment]
@roydahan , is there any reason it is not in 4.4? it fails there as well.

**Comment by Orenef11** [comment]
> @roydahan , is there any reason it is not in 4.4? it fails there as well.

It is failed for Scylla4.4?

**Comment by yarongilor** [comment]
> > @roydahan , is there any reason it is not in 4.4? it fails there as well.
> 
> Can you send the JOB URL?

https://jenkins.scylladb.com/job/scylla-4.4/job/longevity/job/longevity-2tb-4days-1Dis-2NonDis-Nemesises-test/4/

**Comment by roydahan** [comment]
I don't recall why we did it and specifically for branch-4.3.
Luckily the commit message is very informative so @Orenef11 can go back and explain you why we did it.

**Comment by Orenef11** [comment]
@roydahan @yarongilor 
I checked this nemesis for versions `4.4` and `4.5` (master). Thus, because I saw that nemesis failed for version `4.4`, and passed for version `4.5`, I assumed a problem started somewhere during version `4.4`.

**Pull request merged**
