### PR TITLE
test(tablets): disable tablets for unsupported features on 6.1

### PR DESCRIPTION
**Pull request by yarongilor**
Configure LWT/CDC pipelines with tablets-disabled,
	so it can be tested in 6.1, where tablets are enabled by default.

### Testing

- [ ]

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by yarongilor** [comment]
@roydahan , not sure why raised any need for a scylla-pkg PR as well. why not simply enabling existing jobs for 6.1 this way?

**Comment by yarongilor** [comment]
Are there additional applicable pipeline for this configuration? counters test?

**Review by roydahan — CHANGES_REQUESTED** [review]
I don't want to disable it in the original cases, but want to duplicate it to a "tablets disabled" or something similar folder.

Then, when you have the new tests, to have them triggered as part of master and 6.1.

**Comment by yarongilor** [comment]
addressed in https://github.com/scylladb/scylla-cluster-tests/pull/8207

**Pull request closed without merging**
