### PR TITLE
fix(provisioner): fix after multi-az

### PR DESCRIPTION
**Pull request by soyacz**
Recent merge of multi-az support broke provisioner.

Add basic support for this change in provisioner step.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@soyacz, can you test that this change can also work if we remove the hack in the pipeline ?

**Review by roydahan — APPROVED** [review]

**Comment by soyacz** [comment]
provision test failed, but unrelated: Failed to get spot instances: price-too-low
anyway, it is not testing provision jenkins step.
@fruch  can you merge?

**Comment by fruch** [comment]
> provision test failed, but unrelated: Failed to get spot instances: price-too-low anyway, it is not testing provision jenkins step. @fruch can you merge?

@soyacz did you ran the provision step anywhere on jenkins ?

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
