### PR TITLE
improvement(print_kernel_callstack): add new flag

### PR DESCRIPTION
**Pull request by fgelcer**
if flag will be set to `True`, then kernel callstack
will be printed in Scylla logs, otherwise (the default)
will be to NOT print it.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
this is still a draft, as i need to manually set it in every perf test it to be `True`, and to add the default value of it to be `False`

**Comment by fgelcer** [comment]
@roydahan , maybe we just don't want to backport it at all, so in master it will be disabled, but current behavior for performance branches will stay the same.
or eventually we will need to backport it, when we start to decode these kernel callstacks during test run.

**Review by soyacz — APPROVED** [review]
LGTM

**Review by roydahan — APPROVED** [review]
We will backport them so we can control it also for performance if needed

**Comment by soyacz** [comment]
Merge conflicts on perf branches - @fgelcer will you prepare commits for backports?

**Comment by fgelcer** [comment]
> Merge conflicts on perf branches - @fgelcer will you prepare commits for backports?

i have backported these commits myself, as part of them had many conflicts, so once i resolved them, i pushed to the right branch.

**Pull request merged**
