### PR TITLE
Scylla bench reversed queries

### PR DESCRIPTION
**Pull request by yarongilor**
improvement(reversed queries): Added reversed-queries to scylla-bench

        The new s-b parameter of select-order-by is added to v0.1.8
        So the new reversed-queries implementation of 5.0 can be tested this way.

Trello: https://trello.com/c/dDZ916oL
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by yarongilor** [comment]
Jobs are tseted in:
https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-twcs-48h-test-rq/3/
https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-large-partition-8h-test-rq/2/
https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-large-partition-4days-test-rq/2/
https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-large-partition-200k-pks-4days-test-rq/3/

**Comment by fgelcer** [comment]
@yarongilor , 4 days job, failed after 6 hours:
https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-large-partition-4days-test-rq/2/

8 hours job, failed after 9 hours:
https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-large-partition-8h-test-rq/2/

why did they fail?

**Comment by yarongilor** [comment]
> @yarongilor , 4 days job, failed after 6 hours: https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-large-partition-4days-test-rq/2/
> 
> 8 hours job, failed after 9 hours: https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-large-partition-8h-test-rq/2/
> 
> why did they fail?

The 8 hours test can be marked passed since only got an old known scylla-bench issue (quorum query timeout). The test with stress completed it's duration and no major differences in load. Only 1 node got a bit higher load of ~ 35%:

Screenshot from 2022-08-17 18-07-57
Screenshot from 2022-08-17 18-07-25

**Comment by yarongilor** [comment]
4-days test failed with a critical error of:
```
2022-08-15 19:23:13.931: (ScyllaBenchEvent Severity.CRITICAL) period_type=end event_id=278eb2b3-ad6a-4d78-afcf-51b86959b8d7 duration=3h47m21s: node=Node longevity-large-partitions-4d-scyll-loader-node-aa147e1b-2 [13.51.157.12 | 10.0.2.28] (seed: False)
stress_cmd=scylla-bench -workload=uniform -mode=read -select-order-by=desc,asc,none -replication-factor=3 -partition-count=60 -clustering-row-count=10000000 -clustering-row-size=2048 -rows-per-request=2000 -timeout=180s -concurrency=700 -max-rate=64000  -duration=5760m -connection-count 500 -error-at-row-limit 1000
errors:
Stress command completed with bad status 2: 2022/08/15 15:35:57 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=
```
@roydahan , in order to resolve this, it may be required to tune the s-b parameters of concurrency, connection-count, timeout.
Perhaps i'll try something like: concurrency=600, timeout=240s

**Comment by yarongilor** [comment]
200k-pk failed with a similar overloading issue, so probably has to be changed as well
```
21:21:55  2022-08-16 17:41:04.142: (ScyllaBenchEvent Severity.ERROR) period_type=end event_id=328c954c-f59f-46be-89ef-58ab9dcf1631 duration=1d1h46m9s: node=Node longevity-large-partitions-200k-pks-loader-node-769dca39-3 [16.171.54.146 | 10.0.1.24] (seed: False)
21:21:55  stress_cmd=scylla-bench -workload=sequential -mode=read  -select-order-by=desc,asc,none -replication-factor=3 -partition-count=1000 -clustering-row-count=100000 -clustering-row-size=uniform:3072..5120 -rows-per-request=10 -consistency-level=quorum -timeout=90s -concurrency=100 -connection-count=100 -iterations=0 -duration=6420m -error-at-row-limit 1000
21:21:55  errors:
21:21:55  Stress command completed with bad status -1: 2022/08/15 15:54:59 error: failed to connect to 10.0.2.61:9042 due to error: gocql: no response rece
```

**Comment by fgelcer** [comment]
how much was the CPU utilisation before you changed the parameters?

**Comment by yarongilor** [comment]
One SCT issue found during 8h run is: https://github.com/scylladb/scylla-cluster-tests/issues/5145

**Comment by roydahan** [comment]
Have you already started the runs of 4d and 200k with the new params?
If not, let's discuss before.

**Comment by fgelcer** [comment]
> > Have you already started the runs of 4d and 200k with the new params? If not, let's discuss before.
> 
> @roydahan , 4d is already running in https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-large-partition-4days-test-rq/

and failed after 2 hours

**Comment by fgelcer** [comment]
> One SCT issue found during 8h run is: #5145

have you fixed it?

**Comment by yarongilor** [comment]
> > One SCT issue found during 8h run is: #5145
> 
> have you fixed it?

I think we better first have a passing run, even without a nemesis at all.

**Comment by yarongilor** [comment]
Retested 4d with a single read stress in: https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-large-partition-4days-test-rq/5/
(Test was manually stopped after 6 hours).

@roydahan , the single read stress with reversed-queries did not failed but had a lot of timeout quorum errors, so it might be worst than the original configuration.

Right after the read started, there were about 2 erros per second, and a total of 1550 in ~ 5 hours:
```
yarongilor@yaron-pc:~/Downloads/logs/sct-runner-0f6a8159$ egrep "\-mode=read|ScyllaBenchLogEvent Severity.ERROR" sct.log | head -n 10
< t:2022-08-23 10:23:02,020 f:sct_config.py   l:1627 c:sdcm.sct_config      p:INFO  > - scylla-bench -workload=uniform -mode=read -select-order-by=desc,asc,none -replication-factor=3
< t:2022-08-23 11:15:20,765 f:longevity_test.py l:49   c:LargePartitionLongevityTest p:DEBUG > stress cmd: scylla-bench -workload=uniform -mode=read -select-order-by=desc,asc,none -replication-factor=3 -partition-count=6 -clustering-row-count=10000000 -clustering-row-size=2048 -rows-per-request=2000 -timeout=240s -concurrency=600 -max-rate=64000  -duration=5760m -connection-count 500
< t:2022-08-23 11:15:21,678 f:scylla_bench_thread.py l:172  c:sdcm.scylla_bench_thread p:DEBUG > Scylla bench command: scylla-bench -workload=uniform -mode=read -select-order-by=desc,asc,none -replication-factor=3 -partition-count=6 -clustering-row-count=10000000 -clustering-row-size=2048 -rows-per-request=2000 -timeout=240s -concurrency=600 -max-rate=64000  -duration=5760m -connection-count 500 -error-at-row-limit 1000
< t:2022-08-23 11:15:21,679 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/$HOME/go/bin/scylla-bench -workload=uniform -mode=read -select-order-by=desc,asc,none -replication-factor=3 -partition-count=6 -clustering-row-count=10000000 -clustering-row-size=2048 -rows-per-request=2000 -timeout=240s -concurrency=600 -max-rate=64000  -duration=5760m -connection-count 500 -error-at-row-limit 1000 -nodes 10.0.0.103,10.0.3.205,10.0.3.54,10.0.2.166"...
< t:2022-08-23 11:15:21,680 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > stress_cmd=scylla-bench -workload=uniform -mode=read -select-order-by=desc,asc,none -replication-factor=3 -partition-count=6 -clustering-row-count=10000000 -clustering-row-size=2048 -rows-per-request=2000 -timeout=240s -concurrency=600 -max-rate=64000  -duration=5760m -connection-count 500 -error-at-row-limit 1000
< t:2022-08-23 11:16:40,493 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2022-08-23 11:16:40.492 <2022-08-23 11:16:40.000>: (ScyllaBenchLogEvent Severity.ERROR) period_type=one-time event_id=50d5dbd9-9e41-4e6c-8033-a448ed6f30a2: type=ConsistencyError regex=received only line_number=29 node=Node reversed-queries-4d-scylla-b-loader-node-0f6a8159-1 [13.51.64.250 | 10.0.0.85] (seed: False)
< t:2022-08-23 11:16:40,995 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2022-08-23 11:16:40.993 <2022-08-23 11:16:40.000>: (ScyllaBenchLogEvent Severity.ERROR) period_type=one-time event_id=50d5dbd9-9e41-4e6c-8033-a448ed6f30a2: type=ConsistencyError regex=received only line_number=30 node=Node reversed-queries-4d-scylla-b-loader-node-0f6a8159-1 [13.51.64.250 | 10.0.0.85] (seed: False)
< t:2022-08-23 11:16:41,496 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2022-08-23 11:16:41.494 <2022-08-23 11:16:40.000>: (ScyllaBenchLogEvent Severity.ERROR) period_type=one-time event_id=50d5dbd9-9e41-4e6c-8033-a448ed6f30a2: type=ConsistencyError regex=received only line_number=31 node=Node reversed-queries-4d-scylla-b-loader-node-0f6a8159-1 [13.51.64.250 | 10.0.0.85] (seed: False)
< t:2022-08-23 11:16:41,997 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2022-08-23 11:16:41.996 <2022-08-23 11:16:40.000>: (ScyllaBenchLogEvent Severity.ERROR) period_type=one-time event_id=50d5dbd9-9e41-4e6c-8033-a448ed6f30a2: type=ConsistencyError regex=received only line_number=32 node=Node reversed-queries-4d-scylla-b-loader-node-0f6a8159-1 [13.51.64.250 | 10.0.0.85] (seed: False)
< t:2022-08-23 11:16:42,498 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2022-08-23 11:16:42.497 <2022-08-23 11:16:40.000>: (ScyllaBenchLogEvent Severity.ERROR) period_type=one-time event_id=50d5dbd9-9e41-4e6c-8033-a448ed6f30a2: type=ConsistencyError regex=received only line_number=33 node=Node reversed-queries-4d-scylla-b-loader-node-0f6a8159-1 [13.51.64.250 | 10.0.0.85] (seed: False)
yarongilor@yaron-pc:~/Downloads/logs/sct-runner-0f6a8159$ egrep "ScyllaBenchLogEvent Severity.ERROR" sct.log -c
1550

```
The error is in a form of
```
Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM
```

So i'm not sure if it is acceptible enough or it is too bad to continue testing more simultanious read stresses.

**Comment by yarongilor** [comment]
Retesting 4d with 3 read stress of different partition offset where onle one of them has reversed-queries in:
https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-large-partition-4days-test-rq/6/

https://argus.scylladb.com/test/2287346a-2617-4708-947d-ada5e24475cb/runs?additionalRuns[]=0f6a8159-2f9a-4b6a-8f95-a7f37bdd559b

**Comment by yarongilor** [comment]
200k-pk failed after running ~ 4 hours with a read stress without reversed-queries after a kill-scylla nemesis.
```
             "scylla-bench -workload=sequential -mode=read -replication-factor=3 -partition-count=42 -clustering-row-count=100000 -partition-offset=166 -clustering-row-size=uniform:3072..5120 -concurrency=100 -connection-count=100 -consistency-level=quorum -rows-per-request=10 -timeout=90s -iterations 10 -validate-data"
```
There was only a single other read stress that ran with reversed-queries.

**Comment by roydahan** [comment]
Here we decided the followings:
1. For now leave aside 200pk test.
2. For the 4days, let's see the result of the run with 3 read stress, but we want to make it even better and have 3 stress that 2 of them run read with only 10 rows per partition, 1 is ASC and 1 is DSC.

**Comment by roydahan** [comment]
@yarongilor what's the status of the runs we discussed on 4 days?

**Comment by fgelcer** [comment]
> Here we decided the followings:
> 
> 1. For now leave aside 200pk test.
> 2. For the 4days, let's see the result of the run with 3 read stress, but we want to make it even better and have 3 stress that 2 of them run read with only 10 rows per partition, 1 is ASC and 1 is DSC.

ping @yarongilor

**Comment by fgelcer** [comment]
@yarongilor , resolve conflicts, and move the PR to ready for review, once we confirm the test is not failing with previous issues we saw on loader crashing

**Comment by fgelcer** [comment]
is this PR still relevant?

**Comment by fgelcer** [comment]
@yarongilor , perhaps we will close this one in favor of #5335

**Comment by fgelcer** [comment]
> @yarongilor , perhaps we will close this one in favor of #5335

ping

**Pull request closed without merging**
