### PR TITLE
fix(sla test): fix SL batch name

### PR DESCRIPTION
**Pull request by juliayakovlev**
PR https://github.com/scylladb/scylla-cluster-tests/pull/6999 was not enough. Missed there a fix name in workload result

### Testing

- [x] https://argus.scylladb.com/test/2d1ed1fc-f581-431e-97bc-562de4bbcf3d/runs?additionalRuns[]=4bcbfe90-d050-43f1-9439-c485512e4d18. Test failed with relevant errors

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevent to this change (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@juliayakovlev is there a job you are running to validate this one ?

**Comment by juliayakovlev** [comment]
> @juliayakovlev is there a job you are running to validate this one ?

@fruch yes. https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/features-sla-workload-types-test/4/

**Comment by fruch** [comment]
@juliayakovlev 

this code change the status of the test, but without printing or telling the reason,
I would advice changing it to something more visible, like raising an assert, or using events  
```python
    def get_test_status(self) -> str:
        if self._comparison_results:
            try:
                if all((item["within_margin"] for item in self._comparison_results.values())):
                    return "SUCCESS"
                else:
                    return "FAILED"
            except KeyError as exc:
                self.log.error("Exception on attempting to check workload comparison results:\n%s", exc)
                return super().get_test_status()
        else:
            return super().get_test_status()
```

**Review by roydahan — APPROVED** [review]

**Comment by roydahan** [comment]
I agree with @fruch, your staging run failed and it's not clear why.
The check there in the end is just set Pass or failed.

TBH, I don't know why we merged this test and how.
The fix that Yulia did is very basic and I have no idea how the hell this test ever ran.

For now, let's try to raise error event with the comparison values and then decide what to do with this test.

**Comment by fruch** [comment]
> I agree with @fruch, your staging run failed and it's not clear why. The check there in the end is just set Pass or failed.
> 
> TBH, I don't know why we merged this test and how. The fix that Yulia did is very basic and I have no idea how the hell this test ever ran.
> 
> For now, let's try to raise error event with the comparison values and then decide what to do with this test.

this is a test which is part of https://github.com/scylladb/scylla-cluster-tests/pull/4605

this test wasn't run in 2023.1, so we didn't saw all those issues.
I think we should run all the other feature tests of SLA, not fixate on one we never did

**Comment by juliayakovlev** [comment]
@fruch @roydahan 
I added commit with result validation and event raising.
I used existing mechanism that allows deviation 10%.
It means: if expected result "2". but actuall "1.981" the test still will pass.
I do not familiar with this test and do not know if it is acceptable. 
I can ask @eliransin or we can merge it as is or we can fail every ran that "expected < actual"
Please, let your opinion

**Comment by roydahan** [comment]
What do get in your staging run?
Does it pass?

**Comment by juliayakovlev** [comment]
Errors in the test:

```
2023-12-27 14:07:50.449: (WorkloadPrioritisationEvent Severity.ERROR) period_type=one-time event_id=7f6fbda9-16a9-45e0-9dd9-745445d1eb39: type=RatioValidationEvent 
message=Validate workload ration for "op rate" item. . Actual ratio (0.9985532627731668) is not as expected (2.0)
```

```
2023-12-27 14:07:50.448: (WorkloadPrioritisationEvent Severity.ERROR) period_type=one-time event_id=43185387-af90-4be5-b195-4b58f8fa8374: type=RatioValidationEvent 
message=Validate workload ration for "latency 95th percentile" item. . Actual ratio (1.0) is not as expected (2.0)
```

```
2023-12-27 14:07:50.448: (WorkloadPrioritisationEvent Severity.ERROR) period_type=one-time event_id=63dce1b8-3345-4dfa-8fb9-11cd16f920b4: type=RatioValidationEvent 
message=Validate workload ration for "latency 99th percentile" item. . Actual ratio (1.017857142857143) is not as expected (2.0)
```

**Comment by juliayakovlev** [comment]
> What do get in your staging run? Does it pass?

@roydahan 
The fix works. Validation failed due to actual result is not as expected.
I asked Eliran to advice if expected result is still as we want

**Comment by eliransin** [comment]
The changes themselves LGTM (as far as I can tell with my limited understanding of SCT)
The ratio is something that we will need to work on (again :facepalm: ) but I don't think it is within the scope of this
PR.

**Comment by juliayakovlev** [comment]
> The changes themselves LGTM (as far as I can tell with my limited understanding of SCT) The ratio is something that we will need to work on (again 🤦 ) but I don't think it is within the scope of this PR.

@eliransin 
Yes, ratio is not part of this PR but the test failed and I want to know should we stop to run this test and fix an approach of the ratio

**Comment by juliayakovlev** [comment]
@fruch @roydahan 
The fix works. Test failed due to actual result not as expected.
This is answer of @eliransin about ratio problem: https://github.com/scylladb/scylla-cluster-tests/pull/7012#issuecomment-1870999296

We can merge and backport the commit and need to decide if we want to run this test

**Comment by juliayakovlev** [comment]
@roydahan @fruch ping

**Comment by fruch** [comment]
> @roydahan @fruch ping

@juliayakovlev 
we have an issue for the test failure ? 

also can you open an issue for SCT to change the way this test fail to be more visible ?

**Review by fruch — APPROVED** [review]
LGTM

**Comment by juliayakovlev** [comment]
> > @roydahan @fruch ping
> 
> @juliayakovlev we have an issue for the test failure ?

As Eliran wrote - this ratio should be re-checked and re-validated. So I will open SCT issue for that

**Pull request merged**
