### PR TITLE
Revert "feature(aws): add suport to multi az"

### PR DESCRIPTION
**Pull request by soyacz**
This reverts commit 798db4f8b3e68d7493e4ac76a5ee9c9f18773ad3.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
i understand what this PR is doing (reverting a PR that introduced an issue), but what was the issue?
where was it seen?

**Comment by soyacz** [comment]
fixed in https://github.com/scylladb/scylla-cluster-tests/pull/6010

**Comment by soyacz** [comment]
> i understand what this PR is doing (reverting a PR that introduced an issue), but what was the issue? where was it seen?

@fgelcer failing provisioning step due to error:
```
15:23:24  pydantic.error_wrappers.ValidationError: 1 validation error for AWSInstanceParams
15:23:24  NetworkInterfaces -> 0 -> SubnetId
15:23:24    str type expected (type=type_error.str)
```
See QA chat for more details.

**Comment by vponomaryov** [comment]
> > i understand what this PR is doing (reverting a PR that introduced an issue), but what was the issue? where was it seen?
> 
> @fgelcer failing provisioning step due to error:
> 
> ```
> 15:23:24  pydantic.error_wrappers.ValidationError: 1 validation error for AWSInstanceParams
> 15:23:24  NetworkInterfaces -> 0 -> SubnetId
> 15:23:24    str type expected (type=type_error.str)
> ```
> 
> See QA chat for more details.

Recent `Importance of Good Commit Messages & Best Practices` email says:

```
...
5. Clearly state the problem being solved or the opportunity being addressed.
...
```

And even not referring to email, it is always good to minimize dependencies on other tools.

**Comment by soyacz** [comment]
> > > i understand what this PR is doing (reverting a PR that introduced an issue), but what was the issue? where was it seen?
> > 
> > 
> > @fgelcer failing provisioning step due to error:
> > ```
> > 15:23:24  pydantic.error_wrappers.ValidationError: 1 validation error for AWSInstanceParams
> > 15:23:24  NetworkInterfaces -> 0 -> SubnetId
> > 15:23:24    str type expected (type=type_error.str)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > See QA chat for more details.
> 
> Recent `Importance of Good Commit Messages & Best Practices` email says:
> 
> ```
> ...
> 5. Clearly state the problem being solved or the opportunity being addressed.
> ...
> ```

I was in a hurry as issue was very severe, this was also 'revert', usually I write full descriptions. Sorry for that.

> 
> And even not referring to email, it is always good to minimize dependencies on other tools.

What you mean?

**Comment by vponomaryov** [comment]
> > And even not referring to email, it is always good to minimize dependencies on other tools.
> 
> What you mean?

I mean the general idea that keeping context in PR/commit messages is better than in other resources it may refer.

**Pull request closed without merging**
