### PR TITLE
fix(tester.py): Change cassandra-stress default timeout according to duration parameter

### PR DESCRIPTION
**Pull request by yarongilor**
in order for a cs stress not to get stuck for the whole test duration,
	blocking other test operation and batch stresses.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by yarongilor** [comment]
This change may be a bit risky, but can potenially save a lot of time, money and debugging efforts. not tested yet, pending feedback.

**Comment by roydahan** [comment]
@yarongilor I don't understand what the code try to do not from the code and not from the commit message.
Also, if it tries to be specific for batch runs, I don't see how it is specific.
If not specific, I need to see lot of testing!

**Comment by yarongilor** [comment]
> @yarongilor I don't understand what the code try to do not from the code and not from the commit message.
> Also, if it tries to be specific for batch runs, I don't see how it is specific.
> If not specific, I need to see lot of testing!

the problem is that CS is given a non optimal default timeout value to be completed. this default is the test duration. as a result, if a CS stress is stuck - it is stuck until test ends.

thus the suggested solution is changing this too-long-non-optimal timeout to be as the CS command 'duration' parameter (+ extra 10 minutes). in this way, if a CS stress is stuck - it will be limited to be stuck not for the whole test but rather for its specified duration. for example -  the 5000-tables stress has a 55-minutes duration. if it will get stuck, the new timeout for killing the thread will be 65 minutes, instead of (test-duration of) few days.

**Comment by yarongilor** [comment]
@roydahan i think an effective relevant way to test is by rerunning the 5000-tables test with it. can i try that on 4.4?

**Comment by roydahan** [comment]
Not yet.
I don’t want this fix, it’s too dangerous and I don’t know if you have
enough evidence or the test to check if the c-s got stuck.
Where did you see in the 5k tables that the stress got stuck?

**Comment by yarongilor** [comment]
> Not yet. I don’t want this fix, it’s too dangerous and I don’t know if you have enough evidence or the test to check if the c-s got stuck. Where did you see in the 5k tables that the stress got stuck?

ok. the duration default is now changed only for CS batch that uses "cs_duration" parameter.
so there should be no impact on all other test stresses.

An example for stuck stress in 5k tables test is:
```
< t:2021-02-23 22:59:44,423 f:remote_base.py  l:520  c:RemoteCmdRunner      p:DEBUG > Running command "echo TAG: loader_idx:0-cpu_idx:0-keyspace_idx:1; STRESS_TEST_MARKER=QYJDJGBMH3LG2KPYPIZX; cassandra-stress user profile=/tmp/templated_tables_mvzez87bvb.yaml cl=QUORUM 'ops(insert=1, read1=5)' duration=55m -rate threads=2 -errors skip-unsupported-columns ignore -node 10.0.3.100"...
< t:2021-02-24 18:35:04,654 f:base.py         l:144  c:RemoteCmdRunner      p:ERROR > Error executing command: "echo TAG: loader_idx:0-cpu_idx:0-keyspace_idx:1; STRESS_TEST_MARKER=QYJDJGBMH3LG2KPYPIZX; cassandra-stress user profile=/tmp/templated_tables_mvzez87bvb.yaml cl=QUORUM 'ops(insert=1, read1=5)' duration=55m -rate threads=2 -errors skip-unsupported-columns ignore -node 10.0.3.100"; Exit status: -1
```

**Comment by yarongilor** [comment]
running in https://jenkins.scylladb.com/view/scylla-4.4/job/scylla-4.4/job/longevity/job/longevity-5000-tables-test_yaron_dbg/3/

**Comment by yarongilor** [comment]
running on top of 2 PRs: a private base debug PR - loader_ami_5000_tables and the stress-fix PR: https://www.google.com/url?q=https://github.com/scylladb/scylla-cluster-tests/pull/3290&sa=D&source=editors&ust=1614954151155000&usg=AFQjCNGKNceDCUiYczKx40_kpk5BMeOqxA
Show less
Yaron Gilor
Yaron Gilor
12:15 PM Yesterday
looks like the timeout fix prevented test to get stuck with stress forever, but then something is not handled well in SCT following that.


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.4/job/longevity/job/longevity-5000-tables-test_yaron_dbg/5/)
Links:
Build URL
Download "Per server metrics nemesis" Grafana Screenshot
Download "Overview metrics" Grafana Screenshot

**Comment by roydahan** [comment]
@yarongilor IIRC, the timeout did the trick to kill the c-s but it didn't solve the issue we saw that the new batch doesn't start.
Am I correct?

**Comment by yarongilor** [comment]
> @yarongilor IIRC, the timeout did the trick to kill the c-s but it didn't solve the issue we saw that the new batch doesn't start.
> Am I correct?

yes, it killed the c-s as in expected shorter timeout, but following it, SCT encountered another masked problem and couldn't handle it right so it failed the test for it. so there was no chance for a new batch to start.

**Comment by enaydanov** [comment]
@yarongilor is this PR still relevant? Can you fix conflicts or close it?

@bentsi you asked for review, what we need to do here?

**Comment by yarongilor** [comment]
> @yarongilor is this PR still relevant? Can you fix conflicts or close it?
> 
> @bentsi you asked for review, what we need to do here?

It sounds relevant. i think, following the new issue found by testing, it should be addressed in an additional commit, then retested and reviewed. i'll create a task for it.

**Comment by bentsi** [comment]
@yarongilor  your idea is good in general! However, your implementation is too specific and requires manually setting `cs_duration` parameter. I think that the best implementation is to dynamically set the timeout for the stress command based on the CLI args that it ran with, for example c-s has `duration` argument, scylla-bench has `-duration`. We should parse it and use it as a timeout value for the command run. Let's close this PR and I will create a task for implementing the proposed logic.

**Pull request closed without merging**
