### PR TITLE
feature(integration-tests): enable the longer integration tests

### PR DESCRIPTION
**Pull request by fruch**
since we are not running those tests regulary, they tend to get broken, and also we might miss breakage espesily in our loader docker tests.

for now it's would be enable by using a label on the PR `test-integration`

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fgelcer — DISMISSED** [review]
LGTM

**Comment by fgelcer** [comment]
@fruch 1st, there is a conflict... 2nd, integration tests failed with:
```
18:52:23  Pull request #5468 event
18:52:23 18:52:23  Connecting to https://api.github.com/ using Github access key for QA unit tests (under scylladb-promoter user)
18:52:24  ERROR: Pull request 5468 : Not mergeable at a7a355d8e830b25f000731f15d142a7d5e8940d6+fb299af3f6c6eb33b734f9e866065fd201ca0601 (NOT_MERGEABLE)
18:52:24  Finished: FAILURE
```

it seems related somehow to the changes in this PR

**Comment by fruch** [comment]
> @fruch 1st, there is a conflict... 2nd, integration tests failed with:
> 
> ```
> 18:52:23  Pull request #5468 event
> 18:52:23 18:52:23  Connecting to https://api.github.com/ using Github access key for QA unit tests (under scylladb-promoter user)
> 18:52:24  ERROR: Pull request 5468 : Not mergeable at a7a355d8e830b25f000731f15d142a7d5e8940d6+fb299af3f6c6eb33b734f9e866065fd201ca0601 (NOT_MERGEABLE)
> 18:52:24  Finished: FAILURE
> ```
> 
> it seems related somehow to the changes in this PR

if there's a conflict the CI doesn't run, that's o.k.

**Review by fgelcer — APPROVED** [review]
LGTM

**Pull request merged**
