### PR TITLE
fix(gemini): update gemini version to 1.7.8

### PR DESCRIPTION
**Pull request by soyacz**
New fix for memory leak has been merged and new gemini version released. Let's use it.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by soyacz** [comment]
do we need test ride in some staging job? (I only tested `docker run <image> gemini --version` returns 1.7.8)

**Comment by fruch** [comment]
> do we need test ride in some staging job? (I only tested `docker run <image> gemini --version` returns 1.7.8)

I think we should at least try one short Gemini job, before merging

**Comment by fruch** [comment]
> > do we need test ride in some staging job? (I only tested `docker run <image> gemini --version` returns 1.7.8)
> 
> I think we should at least try one short Gemini job, before merging 

Also if integration tests relevant, I think, we should try them locally or on the PR

**Review by fgelcer — CHANGES_REQUESTED** [review]
it seems to break unittests

**Comment by soyacz** [comment]
> it seems to break unittests

fixed

**Comment by fgelcer** [comment]
> > it seems to break unittests
> 
> fixed

there is still 1 failure:
```
14:49:45  =================================== FAILURES ===================================
14:49:45  ___________________ ConfigurationTests.test_21_nested_values ___________________
14:49:45  
14:49:45  self = <unit_tests.test_config.ConfigurationTests testMethod=test_21_nested_values>
14:49:45  
14:49:45      def test_21_nested_values(self):
14:49:45          os.environ['SCT_CONFIG_FILES'] = ('["internal_test_data/minimal_test_case.yaml", '
14:49:45                                            '"unit_tests/test_data/stress_image_extra_config.yaml"]')
14:49:45          os.environ['SCT_CLUSTER_BACKEND'] = 'aws'
14:49:45          os.environ['SCT_AMI_ID_DB_SCYLLA'] = 'ami-1234'
14:49:45          os.environ["SCT_STRESS_READ_CMD.0"] = "cassandra_stress"
14:49:45          os.environ["SCT_STRESS_READ_CMD.1"] = "cassandra_stress"
14:49:45      
14:49:45          os.environ["SCT_STRESS_IMAGE"] = '{"ycsb": "scylladb/something_else"}'
14:49:45          os.environ["SCT_STRESS_IMAGE.cassandra-stress"] = "scylla-bench"
14:49:45          os.environ['SCT_STRESS_IMAGE.scylla-bench'] = "scylladb/something"
14:49:45      
14:49:45          conf = sct_config.SCTConfiguration()
14:49:45          conf.verify_configuration()
14:49:45          self.assertEqual(conf.get('stress_image'),
14:49:45                           {'alternator-dns': 'scylladb/hydra-loaders:alternator-dns-0.1',
14:49:45                            'cassandra-stress': 'scylla-bench',
14:49:45                            'cdc-stresser': 'scylladb/hydra-loaders:cdc-stresser-A',
14:49:45                            'gemini': 'scylladb/hydra-loaders:gemini-1.7.8',
14:49:45                            'ndbench': 'scylladb/hydra-loaders:ndbench-jdk8-A',
14:49:45                            'nosqlbench': 'scylladb/hydra-loaders:nosqlbench-A',
14:49:45                            'scylla-bench': 'scylladb/something',
14:49:45                            'ycsb': 'scylladb/something_else',
14:49:45                            'kcl': 'scylladb/hydra-loaders:kcl-jdk8-20210526-ShardSyncStrategyType-PERIODIC',
14:49:45                            'harry': 'scylladb/hydra-loaders:cassandra-harry-jdk11-20220816'})
14:49:45      
14:49:45  >       self.assertEqual(conf.get('stress_image.gemini'), 'scylladb/hydra-loaders:gemini-1.7.7')
14:49:45  E       AssertionError: 'scylladb/hydra-loaders:gemini-1.7.8' != 'scylladb/hydra-loaders:gemini-1.7.7'
14:49:45  E       - scylladb/hydra-loaders:gemini-1.7.8
14:49:45  E       ?                                   ^
14:49:45  E       + scylladb/hydra-loaders:gemini-1.7.7
14:49:45  E       ?                                   ^
14:49:45  
14:49:45  unit_tests/test_config.py:666: AssertionError
```

**Comment by soyacz** [comment]
I tested in staging: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/gemini-3h-with-nemesis-test/5/
but gemini failed with `Error response from daemon: No such exec instance: 90f7f85f468b46134be7b602a1a9d33287ad48994c7b229945574f26f1c5de43
`
I don't know what it means yet.

**Comment by fruch** [comment]
> I tested in staging: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/gemini-3h-with-nemesis-test/5/ but gemini failed with `Error response from daemon: No such exec instance: 90f7f85f468b46134be7b602a1a9d33287ad48994c7b229945574f26f1c5de43 ` I don't know what it means yet.

looks like dockerd crashed (from the loader set logs):

```
Feb 02 12:27:19 gemini-with-nemesis-3h-normal-updat-loader-node-08d92363-1 dockerd[1434]: fatal error: runtimer: bad p
Feb 02 12:27:19 gemini-with-nemesis-3h-normal-updat-loader-node-08d92363-1 dockerd[1434]: runtime stack:
Feb 02 12:27:19 gemini-with-nemesis-3h-normal-updat-loader-node-08d92363-1 dockerd[1434]: runtime.throw({0x55af4cce3332?, 0x0?})
Feb 02 12:27:19 gemini-with-nemesis-3h-normal-updat-loader-node-08d92363-1 dockerd[1434]: /usr/local/go/src/runtime/panic.go:992 +0x71
Feb 02 12:27:19 gemini-with-nemesis-3h-normal-updat-loader-node-08d92363-1 dockerd[1434]: runtime.runtimer(0xc00005a000, 0x735c7697a20)
Feb 02 12:27:19 gemini-with-nemesis-3h-normal-updat-loader-node-08d92363-1 dockerd[1434]: /usr/local/go/src/runtime/time.go:769 +0x285
Feb 02 12:27:19 gemini-with-nemesis-3h-normal-updat-loader-node-08d92363-1 dockerd[1434]: runtime.checkTimers(0xc00005a000, 0x0?)
```

it's not the first time we see it https://github.com/scylladb/scylla-cluster-tests/issues/5513, please add details of the run in there as well.

let's run it again

**Comment by soyacz** [comment]
> rerun: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/gemini-3h-with-nemesis-test/6/
spot termination
rerun in different region: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/gemini-3h-with-nemesis-test/7/

**Comment by soyacz** [comment]
@fruch I saw your [rerun](https://argus.scylladb.com/workspace?state=WyI1YjUwYzM0OS1jNDBjLTQ0MGMtYjcyNy1mNjljMmUwMGFjYjQiXQ), still something failed (but also this job is not stable on master). I investigated it:
collectd on loader dumped core:
```
Feb 02 21:34:27 gemini-with-nemesis-3h-normal-updat-loader-node-093f18c4-1 kernel: writer#0[1409]: segfault at 0 ip 00007fb6e124ca49 sp 00007fb6d7ffee90 error 6 in libpthread-2.17.so[7fb6e1241000+17000]
Feb 02 21:34:27 gemini-with-nemesis-3h-normal-updat-loader-node-093f18c4-1 kernel: Code: 74 14 83 f8 da 75 0f be 80 00 00 00 45 30 c0 b8 ca 00 00 00 0f 05 8b 3c 24 e8 63 2a 00 00 48 8b 7c 24 08 be 01 00 00 00 31 c0 <f0> 0f b1 37 0f 85 e0 00 00 00 8b 57 2c 48 8b 47 18 4c 8b 4f 10 3b
Feb 02 21:34:28 gemini-with-nemesis-3h-normal-updat-loader-node-093f18c4-1 systemd-coredump[10912]: Failed to create coredump file /var/lib/systemd/coredump/.#core.collectd.0.8ef35cd859964f5497c7993c9057319c.1372.16753736670000006521f12eb0531bfc: No such file or directory
Feb 02 21:34:28 gemini-with-nemesis-3h-normal-updat-loader-node-093f18c4-1 systemd-coredump[10912]: Process 1372 (collectd) of user 0 dumped core.
Feb 02 21:34:28 gemini-with-nemesis-3h-normal-updat-loader-node-093f18c4-1 systemd[1]: collectd.service: main process exited, code=killed, status=11/SEGV
Feb 02 21:34:28 gemini-with-nemesis-3h-normal-updat-loader-node-093f18c4-1 systemd[1]: Unit collectd.service entered failed state.
Feb 02 21:34:28 gemini-with-nemesis-3h-normal-updat-loader-node-093f18c4-1 systemd[1]: collectd.service failed.
Feb 02 21:34:28 gemini-with-nemesis-3h-normal-updat-loader-node-093f18c4-1 systemd[1]: collectd.service holdoff time over, scheduling restart.
```
Also around 21:30 I see from graphs we don't do much with the cluster - load is very small (but this happens also in [master](https://argus.scylladb.com/test/c05bf635-e29a-490c-a72f-9d4e42e6c7e7/runs?additionalRuns[]=31113eba-0899-45fd-a6c6-4862efd15992) ), maybe this gemini is not doing much, or it is failing silently.
as to `validation failed: unable to load check data from the oracle store: system failed: gocql: no response received from cassandra within timeout period` error, I don't see anything in oracle cluster logs - looks load was very small and there was nothing happening in its logs.

Do you think these errors are related to new version of gemini?

**Comment by fruch** [comment]
> @fruch I saw your [rerun](https://argus.scylladb.com/workspace?state=WyI1YjUwYzM0OS1jNDBjLTQ0MGMtYjcyNy1mNjljMmUwMGFjYjQiXQ), still something failed (but also this job is not stable on master). I investigated it:
> collectd on loader dumped core:
> ```
> Feb 02 21:34:27 gemini-with-nemesis-3h-normal-updat-loader-node-093f18c4-1 kernel: writer#0[1409]: segfault at 0 ip 00007fb6e124ca49 sp 00007fb6d7ffee90 error 6 in libpthread-2.17.so[7fb6e1241000+17000]
> Feb 02 21:34:27 gemini-with-nemesis-3h-normal-updat-loader-node-093f18c4-1 kernel: Code: 74 14 83 f8 da 75 0f be 80 00 00 00 45 30 c0 b8 ca 00 00 00 0f 05 8b 3c 24 e8 63 2a 00 00 48 8b 7c 24 08 be 01 00 00 00 31 c0 <f0> 0f b1 37 0f 85 e0 00 00 00 8b 57 2c 48 8b 47 18 4c 8b 4f 10 3b
> Feb 02 21:34:28 gemini-with-nemesis-3h-normal-updat-loader-node-093f18c4-1 systemd-coredump[10912]: Failed to create coredump file /var/lib/systemd/coredump/.#core.collectd.0.8ef35cd859964f5497c7993c9057319c.1372.16753736670000006521f12eb0531bfc: No such file or directory
> Feb 02 21:34:28 gemini-with-nemesis-3h-normal-updat-loader-node-093f18c4-1 systemd-coredump[10912]: Process 1372 (collectd) of user 0 dumped core.
> Feb 02 21:34:28 gemini-with-nemesis-3h-normal-updat-loader-node-093f18c4-1 systemd[1]: collectd.service: main process exited, code=killed, status=11/SEGV
> Feb 02 21:34:28 gemini-with-nemesis-3h-normal-updat-loader-node-093f18c4-1 systemd[1]: Unit collectd.service entered failed state.
> Feb 02 21:34:28 gemini-with-nemesis-3h-normal-updat-loader-node-093f18c4-1 systemd[1]: collectd.service failed.
> Feb 02 21:34:28 gemini-with-nemesis-3h-normal-updat-loader-node-093f18c4-1 systemd[1]: collectd.service holdoff time over, scheduling restart.
> ```
> Also around 21:30 I see from graphs we don't do much with the cluster - load is very small (but this happens also in [master](https://argus.scylladb.com/test/c05bf635-e29a-490c-a72f-9d4e42e6c7e7/runs?additionalRuns[]=31113eba-0899-45fd-a6c6-4862efd15992) ), maybe this gemini is not doing much, or it is failing silently.
> as to `validation failed: unable to load check data from the oracle store: system failed: gocql: no response received from cassandra within timeout period` error, I don't see anything in oracle cluster logs - looks load was very small and there was nothing happening in its logs.
> 
> Do you think these errors are related to new version of gemini?

I don't think it's Gemini, but we shouldn't run collectd anymore it's a leftover since we are using old loader image, we should also switch to ubuntu based images for the loaders

**Comment by soyacz** [comment]
anything else to test here?

**Comment by fruch** [comment]
> anything else to test here?

I think not, let's merge it

**Review by fruch — APPROVED** [review]

**Comment by roydahan** [comment]
@soyacz can you please backport this to 5.1?
We hit this issue when trying to release patch versions.

**Comment by soyacz** [comment]
@roydahan backported

**Comment by dkropachev** [comment]
@soyacz, @fruch , guys, can I please see memory consumption graph on run prior the fix and on run after the fix ?

**Comment by soyacz** [comment]
@fruch @dkropachev do we have these metrics collected? How to visualize them?

**Comment by fruch** [comment]
> @fruch @dkropachev do we have these metrics collected? How to visualize them?

recently we switch from collectd to node_exporter, so looking at the "OS" dashboard should show the loader memory usage

**Comment by soyacz** [comment]
@dkropachev we are not getting errors like `signal SIGSEGV: segmentation violation code=0x2...`, but still looks like memory is leaking:
image
Gemini stopped the load (should be 10h) but process itself finished on time and didn't report any error.

**Pull request merged**
