### PR TITLE
improvement(requirements.txt): start using `ssh2-python3`

### PR DESCRIPTION
**Pull request by fruch**
`ssh2-python` project is abandoned and didn't have a release in 2 years, in order to upgrade to newer python versions we are switching forks of that project

### Testing

- [x] 🟢 provision tests
- [x] 🟢 https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity-100gb-4h-test/89/
- [x] 🟢 https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity-10gb-3h-gce-test/57/
- [x] 🟢 https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity-10gb-3h-azure-test/47/

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@mikliapko did you managed to take this one for a ride with scylla-cloud ?

**Comment by mikliapko** [comment]
> @mikliapko did you managed to take this one for a ride with scylla-cloud ?

not yet, faced some issues with cluster deployment in Cloud on QA LAB env.
I will update you on any results from there.

**Comment by fruch** [comment]
provision test seem to be passing from my POV.

now trying a bit longer longevity

**Comment by soyacz** [comment]
in case @mikliapko have troubles anyway, what I remember I was setting `session.method_pref(LIBSSH2_METHOD_HOSTKEY, 'rsa-sha2-512,rsa-sha2-256,ssh-ed25519,ecdsa-sha2-nistp256')` before connecting - but I didn't verify if it works without it. 
leaving this comment just in case as I'll be on PTO till the end of next week.

**Comment by fruch** [comment]
> @fruch I see you force-pushed the commit an hour ago. Does it make sense to rerun with updated commit? Since I cherry-picked the initial commit yesterday and the SCT failed to connect to DB node all the same. https://jenkins.scylladb.com/job/scylla-staging/job/mikita/job/siren-tests/job/siren-sct-integration/72/

it was just a rebase, to get few unittest working

**Comment by mikliapko** [comment]
> @fruch I see you force-pushed the commit an hour ago. Does it make sense to rerun with updated commit? Since I cherry-picked the initial commit yesterday and the SCT failed to connect to DB node all the same. https://jenkins.scylladb.com/job/scylla-staging/job/mikita/job/siren-tests/job/siren-sct-integration/72/

alright, looks like my yesterday's attempt failed because of some missing permissions, rechecking once again

**Comment by mikliapko** [comment]
@fruch It works with Cloud nodes as well:
https://jenkins.scylladb.com/job/scylla-staging/job/mikita/job/siren-tests/job/siren-sct-integration/74/

**Review by vponomaryov — APPROVED** [review]
LGTM

**Pull request merged**
