### PR TITLE
fix(provision): remove deprecated spot duration minutes param

### PR DESCRIPTION
**Pull request by soyacz**
SpotDurationMinutes param has been deprecated and update of boto3 library revealed that. Now we get errors during provision: `BlockDurationMinutes is not a valid parameter`.

This commit removes this param to fix provision step for spot instances.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by soyacz** [comment]
test job: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/longevity-many-clients-4h-test/28/
I aborted it after provision step.

**Comment by roydahan** [comment]
So There is no spot_duration anymore??

**Review by fgelcer — DISMISSED** [review]
LGTM

**Comment by fruch** [comment]
> So There is no spot_duration anymore??

Seem like they deprecated is long ago, we didn't got the memo

Update July 2021 – Spot Instances with a defined duration (also known as Spot blocks) are no longer available to new customers as of July 1, 2021. For customers that have previously used the feature, we will continue to support Spot Instances with a defined duration until December 31, 2022. If your workload is interruption tolerant, we recommend that you use Spot Instances without setting a defined duration. If your workload is not interruption tolerant we recommend that you use On-Demand instances for the required duration of your workload. For the most up to date information please see our documentation here.

**Comment by soyacz** [comment]
> Update July 2021 – Spot Instances with a defined duration (also known as Spot blocks) are no longer available to new customers as of July 1, 2021. For customers that have previously used the feature, we will continue to support Spot Instances with a defined duration until December 31, 2022. 

So for us it was actually working till December 31, 2022

**Comment by soyacz** [comment]
I added commit that removes everything related to spot duration. Retested https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/longevity-many-clients-4h-test/29/
Looks working.

**Review by vponomaryov — APPROVED** [review]
LGTM

**Review by fruch — APPROVED** [review]

**Pull request merged**
