### PR TITLE
fix(test_case_lint): remove 4.6.9 from test configuration

### PR DESCRIPTION
**Pull request by vponomaryov**
`4.6.9` scylla version is not available anymore.
So, update the `oracle_scylla_version` config option with newer and existing scylla versions.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by soyacz — DISMISSED** [review]

**Comment by vponomaryov** [comment]
For some reason one of integration tests thinks that the new image version is absent;

```
13:54:17  unit_tests/test_scylla_yaml_builders.py::IntegrationTests::test_integration_node_3__tmp_jenkins_workspace_can_scylla_cluster_tests_PR_5850_unit_tests_test_data_test_scylla_yaml_builders_cdc_replication_longevity_yaml FAILED [ 52%]
...
13:57:11  =================================== FAILURES ===================================
13:57:11  _ IntegrationTests.test_integration_node_3__tmp_jenkins_workspace_can_scylla_cluster_tests_PR_5850_unit_tests_test_data_test_scylla_yaml_builders_cdc_replication_longevity_yaml _
13:57:11  
13:57:11  a = (<unit_tests.test_scylla_yaml_builders.IntegrationTests testMethod=test_integration_node_3__tmp_jenkins_workspace_can_scylla_cluster_tests_PR_5850_unit_tests_test_data_test_scylla_yaml_builders_cdc_replication_longevity_yaml>,)
13:57:11  
13:57:11      @wraps(func)
13:57:11      def standalone_func(*a):
13:57:11  >       return func(*(a + p.args), **p.kwargs)
13:57:11  
13:57:11  /usr/local/lib/python3.10/site-packages/parameterized/parameterized.py:533: 
13:57:11  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
13:57:11  unit_tests/test_scylla_yaml_builders.py:602: in test_integration_node
13:57:11      self._run_test(config_path, expected_node_config=expected_node_config)
13:57:11  unit_tests/test_scylla_yaml_builders.py:563: in _run_test
13:57:11      conf = SCTConfiguration()
13:57:11  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
13:57:11  
13:57:11  self = {'db_type': 'mixed_scylla', 'test_duration': 900, 'ip_ssh_connections': 'private', 'scylla_repo': '', 'manager_version...t_data/test_scylla_yaml_builders/cdc-replication-longevity.yaml'], 'cluster_backend': 'aws', 'prepare_saslauthd': True}
13:57:11  
13:57:11      def __init__(self):
13:57:11          # pylint: disable=too-many-locals,too-many-branches,too-many-statements
13:57:11          super().__init__()
13:57:11          self.log = logging.getLogger(__name__)
13:57:11          env = self._load_environment_variables()
13:57:11          config_files = env.get('config_files', [])
13:57:11          config_files = [sct_abs_path(f) for f in config_files]
13:57:11      
13:57:11          # prepend to the config list the defaults the config files
13:57:11          backend = env.get('cluster_backend')
13:57:11          backend_config_files = [sct_abs_path('defaults/test_default.yaml')]
13:57:11          if backend:
13:57:11              backend_config_files += self.defaults_config_files[str(backend)]
13:57:11          self.multi_region_params = self.per_provider_multi_region_params.get(str(backend), [])
13:57:11      
13:57:11          # 1) load the default backend config files
13:57:11          files = anyconfig.load(list(backend_config_files))
13:57:11          anyconfig.merge(self, files)
13:57:11      
13:57:11          # 2) load the config files
13:57:11          try:
13:57:11              files = anyconfig.load(list(config_files))
13:57:11              anyconfig.merge(self, files)
13:57:11          except ValueError:
13:57:11              self.log.warning("Failed to load configuration files: %s", config_files)
13:57:11      
13:57:11          regions_data = self.get('regions_data') or {}
13:57:11          if regions_data:
13:57:11              del self['regions_data']
13:57:11      
13:57:11          # 2.2) load the region data
13:57:11      
13:57:11          cluster_backend = self.get('cluster_backend')
13:57:11          cluster_backend = env.get('cluster_backend', cluster_backend)
13:57:11      
13:57:11          region_names = self.region_names
13:57:11      
13:57:11          if cluster_backend in ['aws', 'aws-siren', 'k8s-eks']:
13:57:11              if regions_data:
13:57:11                  for region in region_names:
13:57:11                      if region not in regions_data:
13:57:11                          raise ValueError(f"{region} isn't supported, use: {list(regions_data.keys())}")
13:57:11      
13:57:11                      for key, value in regions_data.get(region, {}).items():
13:57:11                          if key not in self.keys():
13:57:11                              self[key] = value
13:57:11                          elif len(self[key].split()) < len(region_names):
13:57:11                              self[key] += " {}".format(value)
13:57:11              else:
13:57:11                  for region in region_names:
13:57:11                      if region not in self.aws_supported_regions:
13:57:11                          raise ValueError(f"{region} isn't supported, use: {self.aws_supported_regions}")
13:57:11      
13:57:11          # 3) overwrite with environment variables
13:57:11          anyconfig.merge(self, env)
13:57:11      
13:57:11          # 4) update events max severities
13:57:11          add_severity_limit_rules(self.get("max_events_severities"))
13:57:11          print_critical_events()
13:57:11      
13:57:11          # 5) overwrite AMIs
13:57:11          for key in self.ami_id_params:
13:57:11              if param := self.get(key):
13:57:11                  self[key] = convert_name_to_ami_if_needed(param, self.region_names)
13:57:11      
13:57:11          # 6) handle scylla_version if exists
13:57:11          scylla_linux_distro = self.get('scylla_linux_distro')
13:57:11          dist_type = scylla_linux_distro.split('-')[0]
13:57:11          dist_version = scylla_linux_distro.split('-')[-1]
13:57:11      
13:57:11          if scylla_version := self.get('scylla_version'):  # pylint: disable=too-many-nested-blocks
13:57:11              if not self.get('docker_image'):
13:57:11                  self['docker_image'] = get_scylla_docker_repo_from_version(scylla_version)
13:57:11              if self.get("cluster_backend") in (
13:57:11                      "docker", "k8s-eks", "k8s-gke",
13:57:11                      "k8s-local-kind", "k8s-local-kind-aws", "k8s-local-kind-gce"):
13:57:11                  self.log.info("Assume that Scylla Docker image has repo file pre-installed.")
13:57:11                  self._replace_docker_image_latest_tag()
13:57:11              elif not self.get('ami_id_db_scylla') and self.get('cluster_backend') == 'aws':
13:57:11                  aws_arch = get_arch_from_instance_type(self.get('instance_type_db'))
13:57:11                  # ami.name format examples: ScyllaDB 4.4.0 or ScyllaDB Enterprise 2019.1.1
13:57:11                  scylla_version_substr = f" {scylla_version}"
13:57:11                  ami_list = []
13:57:11                  for region in region_names:
13:57:11                      if ':' in scylla_version:
13:57:11                          ami = get_branched_ami(scylla_version=scylla_version, region_name=region, arch=aws_arch)[0]
13:57:11                      else:
13:57:11                          for ami in get_scylla_ami_versions(region_name=region, arch=aws_arch):
13:57:11                              if scylla_version_substr in ami.name:
13:57:11                                  break
13:57:11                          else:
13:57:11                              raise ValueError(f"AMIs for {scylla_version=} not found in {region}")
13:57:11                      self.log.debug("Found AMI %s for scylla_version='%s' in %s", ami.image_id, scylla_version, region)
13:57:11                      ami_list.append(ami)
13:57:11                  self['ami_id_db_scylla'] = " ".join(ami.image_id for ami in ami_list)
13:57:11              elif not self.get("gce_image_db") and self.get("cluster_backend") == "gce":
13:57:11                  if ":" in scylla_version:
13:57:11                      gce_image = get_branched_gce_images(scylla_version=scylla_version)[0]
13:57:11                  else:
13:57:11                      # gce_image.name format examples: scylla-4-3-6 or scylla-enterprise-2021-1-2
13:57:11                      scylla_version_substr = f"scylla-{scylla_version.replace('.', '-')}"
13:57:11                      for gce_image in get_scylla_gce_images_versions():
13:57:11                          if gce_image.name.replace("-enterprise", "").startswith(scylla_version_substr):
13:57:11                              break
13:57:11                      else:
13:57:11                          raise ValueError(f"GCE images for {scylla_version=} not found")
13:57:11                  self.log.debug("Found GCE image %s for scylla_version='%s'", gce_image.name, scylla_version)
13:57:11                  self["gce_image_db"] = gce_image.extra["selfLink"]
13:57:11              elif not self.get("azure_image_db") and self.get("cluster_backend") == "azure":
13:57:11                  scylla_azure_images = []
13:57:11                  if isinstance(self.get('azure_region_name'), list):
13:57:11                      azure_region_names = self.get('azure_region_name')
13:57:11                  else:
13:57:11                      azure_region_names = [self.get('azure_region_name')]
13:57:11      
13:57:11                  for region in azure_region_names:
13:57:11                      azure_image = azure_utils.get_scylla_images(scylla_version, region)[0]
13:57:11                      self.log.debug("Found AMI %s for scylla_version='%s' in %s",
13:57:11                                     azure_image.name, scylla_version, region)
13:57:11                      scylla_azure_images.append(azure_image)
13:57:11                  self["azure_image_db"] = " ".join(image.id for image in scylla_azure_images)
13:57:11              elif not self.get('scylla_repo'):
13:57:11                  self['scylla_repo'] = find_scylla_repo(scylla_version, dist_type, dist_version)
13:57:11              else:
13:57:11                  raise ValueError("'scylla_version' can't used together with 'ami_id_db_scylla', 'gce_image_db' "
13:57:11                                   "or with 'scylla_repo'")
13:57:11      
13:57:11              if (
13:57:11                  self.get("n_loaders") and
13:57:11                  not self.get("bare_loaders") and
13:57:11                  not self.get("scylla_repo_loader") and
13:57:11                  self.get("cluster_backend") != "aws"
13:57:11              ):
13:57:11                  scylla_linux_distro_loader = self.get('scylla_linux_distro_loader')
13:57:11                  dist_type_loader = scylla_linux_distro_loader.split('-')[0]
13:57:11                  dist_version_loader = scylla_linux_distro_loader.split('-')[-1]
13:57:11      
13:57:11                  scylla_version_for_loader = "nightly" if scylla_version == "latest" else scylla_version
13:57:11      
13:57:11                  self['scylla_repo_loader'] = find_scylla_repo(scylla_version_for_loader,
13:57:11                                                                dist_type_loader,
13:57:11                                                                dist_version_loader)
13:57:11      
13:57:11          # 6.1) handle oracle_scylla_version if exists
13:57:11          if (oracle_scylla_version := self.get('oracle_scylla_version')) \
13:57:11             and self.get("db_type") == "mixed_scylla":  # pylint: disable=too-many-nested-blocks
13:57:11              suffix = f" {oracle_scylla_version}"  # ami.name format example: ScyllaDB 4.4.0
13:57:11              if not self.get('ami_id_db_oracle') and self.get('cluster_backend') == 'aws':
13:57:11                  aws_arch = get_arch_from_instance_type(self.get('instance_type_db'))
13:57:11                  ami_list = []
13:57:11                  for region in region_names:
13:57:11                      if ':' in oracle_scylla_version:
13:57:11                          ami = get_branched_ami(
13:57:11                              scylla_version=oracle_scylla_version, region_name=region, arch=aws_arch)[0]
13:57:11                      else:
13:57:11                          for ami in get_scylla_ami_versions(region_name=region, arch=aws_arch):
13:57:11                              if ami.name.endswith(suffix):
13:57:11                                  break
13:57:11                          else:
13:57:11  >                           raise ValueError(f"AMIs for {oracle_scylla_version=} not found in {region}")
13:57:11  E                           ValueError: AMIs for oracle_scylla_version='5.0.10' not found in eu-west-1
13:57:11  
13:57:11  sdcm/sct_config.py:1723: ValueError
```

But it is not true, it is there. Here is full list of the images in the `eu-west-1` region.

```
ScyllaDB 5.3.0-dev
ScyllaDB Enterprise 2023.1.0-rc1
ScyllaDB 5.2.0-rc1
ScyllaDB 5.1.5
ScyllaDB 5.0.10
ScyllaDB Enterprise 2023.1.0-rc0
ScyllaDB 5.1.4
ScyllaDB 5.2.0-rc0
ScyllaDB 5.0.9
ScyllaDB Enterprise 2022.2.0
ScyllaDB 5.1.3
ScyllaDB Enterprise 2022.1.5
ScyllaDB Enterprise 2022.1.4
ScyllaDB 5.1.2
ScyllaDB 5.0.8
ScyllaDB Enterprise 2021.1.17
ScyllaDB Enterprise 2021.1.17
ScyllaDB 5.2.0-dev
ScyllaDB 5.2.0-dev
ScyllaDB 5.2.0-dev
ScyllaDB 5.2.0-dev
ScyllaDB 5.2.0-dev
ScyllaDB 5.2.0-dev
ScyllaDB 5.2.0-dev
ScyllaDB 5.2.0-dev
ScyllaDB 5.0.7
ScyllaDB 5.1.1
ScyllaDB 4.6.11
ScyllaDB 5.0.6
ScyllaDB 5.1.0
ScyllaDB 5.2.0-dev
ScyllaDB 5.2.0-dev
ScyllaDB 5.2.0-dev
ScyllaDB Enterprise 2021.1.16
ScyllaDB 5.0.5
ScyllaDB Enterprise 2021.1.15
ScyllaDB Enterprise 2022.1.3
ScyllaDB 5.0.4
ScyllaDB Enterprise 2022.1.2
ScyllaDB 5.0.3
ScyllaDB Enterprise 2021.1.14
ScyllaDB 5.0.2
ScyllaDB Enterprise 2022.1.1
ScyllaDB Enterprise 2021.1.13
ScyllaDB Enterprise 2022.1.0
ScyllaDB 5.0.1
ScyllaDB 5.0.0
ScyllaDB Enterprise 2021.1.12
ScyllaDB Enterprise 2020.1.14
ScyllaDB Enterprise 2021.1.11
ScyllaDB Enterprise 2021.1.10
ScyllaDB Enterprise 2021.1.9
ScyllaDB Enterprise 2021.1.8
ScyllaDB Enterprise 2021.1.7
ScyllaDB Enterprise-2021.1.6
ScyllaDB Enterprise 2021.1.5
ScyllaDB Enterprise 2021.1.4
ScyllaDB Enterprise 2021.1.3
ScyllaDB Enterprise 2021.1.2
ScyllaDB Enterprise 2021.1.1
ScyllaDB Enterprise 2019.1.21
```

**Comment by vponomaryov** [comment]
Mocks, sweet mocks...

**Comment by soyacz** [comment]
you can run this test locally - it fails consistently.

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by fruch — APPROVED** [review]

**Comment by aleksbykov** [comment]
@frunch, @soyacz could you backport this to branch-5.2 and branch-5.1?

**Pull request merged**
