### PR TITLE
improvement(k8s-multitenancy): process all monitors in parallel

### PR DESCRIPTION
**Pull request by vponomaryov**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by vponomaryov** [comment]
Running 14 clients in K8S multitenant setup all monitors setup takes about 5,5minutes multiplied 14 times.

**Review by fruch — DISMISSED** [review]
LGTM

**Comment by fruch** [comment]
@vponomaryov after see the unittests failing, it was missing handling the case of no monitors. I've fixed it, and I'll merge once passing the unittests

**Comment by mykaul** [comment]
> Without this PR setup of all the monitors in 14 clients K8S multitenant setup takes about 5,5minutes multiplied 14 times.

Nice improvement!

**Pull request merged**
