### PR TITLE
improvement(speedup): skip java and scylla-tools install

### PR DESCRIPTION
**Pull request by soyacz**
When using docker based loaders we don't need to install java and scylla-tools.

Skipping it to save some preparation time.

refs: https://github.com/scylladb/qa-tasks/issues/1650

### Testing

- [x] - provision tests
- [x] - test [with `use_prepared_loaders: false`](https://argus.scylladb.com/test/5bd8d2cf-5760-405e-8c70-fa0fd2bad5f0/runs?additionalRuns%5B%5D=1ce4dc25-3523-4565-9200-ccd42be0d5bb)

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Review by fruch — CHANGES_REQUESTED** [review]
There is a misunderstanding here, my guess you are running with scylla AMI as loader, and not one of our prepared loaders, hence why you get all of the installation of things you don't expect to.


If it's Scylla AMI one should use the bare loaders to not install anything on them, not even docker.

**Comment by soyacz** [comment]
with this change loader setup time is ~75 seconds - less than db nodes.
[test](https://argus.scylladb.com/test/5bd8d2cf-5760-405e-8c70-fa0fd2bad5f0/runs?additionalRuns[]=1ce4dc25-3523-4565-9200-ccd42be0d5bb)

**Comment by soyacz** [comment]
but true - I'm confused as we have 2 settings: `bare_loaders` (`false` everywhere except jepsen tests) and `use_prepared_loaders` and in the code we verify if loader is prepared by `test -e ~/PREPARED-LOADER`
In my opinion we should remove one or even both by making it automatic based on `PREPARED-LOADER` file

**Comment by fruch** [comment]
> but true - I'm confused as we have 2 settings: `bare_loaders` (`false` everywhere except jepsen tests) and `use_prepared_loaders` and in the code we verify if loader is prepared by `test -e ~/PREPARED-LOADER`
> In my opinion we should remove one or even both by making it automatic based on `PREPARED-LOADER` file

Each one is for a different reason, one is when we identify it's our own created image, and one when it's based on images we didn't create.

Yes it might consolidate a bit, 
The idea in general was to have just docker based loaders, and ditch the rest of the installations and hacks.

It needs a bit more cleanup work, if we want to optimize it further for all of the use cases

**Comment by soyacz** [comment]
@fruch let's have a talk about it - something is not working correctly anyway and we need to define what it is.

**Comment by fruch** [comment]
> @fruch let's have a talk about it - something is not working correctly anyway and we need to define what it is.

We still need a talk ? Or I persuaded you it's not needed for now ?

**Comment by soyacz** [comment]
> > @fruch let's have a talk about it - something is not working correctly anyway and we need to define what it is.
> 
> We still need a talk ? Or I persuaded you it's not needed for now ?

This PR appeared for a reason - to speed up loader setup as it's still not optimal. Despite we use our AMI's for loaders it somehow still reaches e.g. java installation. Maybe we should use `bare_loaders` true as default?

**Comment by fruch** [comment]
> > > @fruch let's have a talk about it - something is not working correctly anyway and we need to define what it is.
> > 
> > We still need a talk ? Or I persuaded you it's not needed for now ?
> 
> This PR appeared for a reason - to speed up loader setup as it's still not optimal. Despite we use our AMI's for loaders it somehow still reaches e.g. java installation. Maybe we should use `bare_loaders` true as default?

The java installation was a work around to get HDR working, maybe it's not needed anymore. one would need to confirm that first.

why moving of docker installation is needed ?

**Comment by fruch** [comment]
Scylla tools installation is needed for GCP and Azure

Since they don't have preloaded images, we shouldn't remove it without handling that

**Pull request closed without merging**
