### PR TITLE
improvement(monitor_branch): Switch monitor to branch-4.1

### PR DESCRIPTION
**Pull request by roydahan**
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by amnonh** [comment]
LGTM

**Comment by fruch** [comment]
@roydahan I've put the provision tests labels, but it might need to rerun CI again for them to run

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
CI failed cause of #5499

**Pull request merged**
