### PR TITLE
Ics longevity of 1TB

### PR DESCRIPTION
**Pull request by yarongilor**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [ ] I didn't copy-paste code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@yarongilor any news with this one ? you need someone to review ?

**Comment by fruch** [comment]
@yarongilor ping me once you think this is ready for review

**Comment by yarongilor** [comment]
This PR may be covered by new PR of https://github.com/scylladb/scylla-cluster-tests/pull/1482
the delta missing code can be added later on top of the other PR code.

**Comment by fruch** [comment]
@yarongilor, so this PR can be closed ?

**Comment by fruch** [comment]
@yarongilor, still waiting for answer, if this PR can be closed or not ?

**Comment by yarongilor** [comment]
> @yarongilor, still waiting for answer, if this PR can be closed or not ?

copied the relevant parts to PR: https://github.com/scylladb/scylla-cluster-tests/pull/1544.
this PR can be closed.

**Pull request closed without merging**
