### PR TITLE
improvement(k8s): bump the K8S version

### PR DESCRIPTION
**Pull request by vponomaryov**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Review by soyacz — COMMENTED** [review]
It would be nice to have some sort of document what are the changes between 1.24->1.25 and how they are to Scylla/SCT.
Do we have such?

**Comment by vponomaryov** [comment]
> It would be nice to have some sort of document what are the changes between 1.24->1.25 and how they are to Scylla/SCT. Do we have such?

From the Scylla point of view it is kind of the same.
From operator point of view, with version `1.25` we start covering this change: https://github.com/scylladb/scylla-operator/pull/1005
And this bump was also requested from the operator dev team.

The `vpc_cni` version is set according to the docs: https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html

**Comment by fruch** [comment]
@vponomaryov please try GKE run once

**Review by fruch — APPROVED** [review]
LGTM

**Review by soyacz — APPROVED** [review]

**Comment by vponomaryov** [comment]
> @vponomaryov please try GKE run once

Works: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-3h-gke/24/console

**Pull request merged**
