### PR TITLE
feature(aws): add sct command for cleaning up old AWS KMS aliases

### PR DESCRIPTION
**Pull request by vponomaryov**
### Testing

- [ ]

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by vponomaryov** [comment]
```
py310: commands[3]> bash -c '/home/kiparis/projects/scylla-cluster-tests/sct.py clean-aws-kms-aliases -r eu-central-1'
logged in as arn:aws:iam::797456418907:user/qa
New directory created: /home/kiparis/sct-results/20240620-150826-424356-clean-aws-kms-aliases
KMS: Search for aliases older than '48' hours
KMS: [region 'eu-central-1'][key '40e793cb-9a53-4d79-97d3-4cba7f09892e'] read aliases
KMS: [region 'eu-central-1'][key '40e793cb-9a53-4d79-97d3-4cba7f09892e'] deleting old alias -> 'alias/testid-4a3166cf-cd4c-4809-a6c4-0380525bee5b' (2024-04-02 23:27:11.114000+03:00)
Deleting the 'alias/testid-4a3166cf-cd4c-4809-a6c4-0380525bee5b' alias in the KMS
KMS: [region 'eu-central-1'][key '40e793cb-9a53-4d79-97d3-4cba7f09892e'] deleting old alias -> 'alias/testid-d2ceaf31-56f1-4f2a-a17e-21e8d4a9b5c3' (2024-04-04 09:28:30.736000+03:00)
Deleting the 'alias/testid-d2ceaf31-56f1-4f2a-a17e-21e8d4a9b5c3' alias in the KMS
KMS: [region 'eu-central-1'][key '40e793cb-9a53-4d79-97d3-4cba7f09892e'] deleting old alias -> 'alias/testid-e07877a2-0f9d-46f7-a2dd-2b506499d7d5' (2024-04-04 13:57:15.474000+03:00)
Deleting the 'alias/testid-e07877a2-0f9d-46f7-a2dd-2b506499d7d5' alias in the KMS
KMS: [region 'eu-central-1'][key 'bc56ffa4-85f8-4869-821d-b5aa4e55e016'] read aliases
KMS: [region 'eu-central-1'][key 'bc56ffa4-85f8-4869-821d-b5aa4e55e016'] deleting old alias -> 'alias/testid-2792f6c5-22ce-4c4a-b6f2-ae9cab8ed99e' (2024-04-04 16:32:54.061000+03:00)
Deleting the 'alias/testid-2792f6c5-22ce-4c4a-b6f2-ae9cab8ed99e' alias in the KMS
KMS: [region 'eu-central-1'][key 'bc56ffa4-85f8-4869-821d-b5aa4e55e016'] deleting old alias -> 'alias/testid-8987dc4b-8699-49d9-a3bc-94d5619cbe8e' (2024-04-03 18:30:54.901000+03:00)
Deleting the 'alias/testid-8987dc4b-8699-49d9-a3bc-94d5619cbe8e' alias in the KMS
KMS: [region 'eu-central-1'][key 'bc56ffa4-85f8-4869-821d-b5aa4e55e016'] deleting old alias -> 'alias/testid-fc11a700-6345-48ab-bc48-397f9c075ebb' (2024-04-03 11:44:50.005000+03:00)
Deleting the 'alias/testid-fc11a700-6345-48ab-bc48-397f9c075ebb' alias in the KMS
KMS: [region 'eu-central-1'][key 'df4e99a9-eb9d-4fe8-85bf-8b1287a64138'] read aliases
KMS: [region 'eu-central-1'][key 'df4e99a9-eb9d-4fe8-85bf-8b1287a64138'] deleting old alias -> 'alias/testid-27de97f5-c933-4499-b7ff-dafae8b24ee3' (2024-04-03 20:52:32.444000+03:00)
Deleting the 'alias/testid-27de97f5-c933-4499-b7ff-dafae8b24ee3' alias in the KMS
KMS: [region 'eu-central-1'][key 'df4e99a9-eb9d-4fe8-85bf-8b1287a64138'] deleting old alias -> 'alias/testid-f9ea9846-0f77-4fc9-81e7-53a3a412e721' (2023-12-18 19:02:04.492000+02:00)
Deleting the 'alias/testid-f9ea9846-0f77-4fc9-81e7-53a3a412e721' alias in the KMS
KMS: finished cleaning up old aliases
KMS: finished cleaning up of old aliases

=============

py310: commands[3]> bash -c '/home/kiparis/projects/scylla-cluster-tests/sct.py clean-aws-kms-aliases -r eu-central-1 --dry-run'
logged in as arn:aws:iam::797456418907:user/qa
New directory created: /home/kiparis/sct-results/20240620-150903-693924-clean-aws-kms-aliases
KMS: Search for aliases older than '48' hours
KMS: [dry-run][region 'eu-central-1'][key '40e793cb-9a53-4d79-97d3-4cba7f09892e'] read aliases
KMS: [dry-run][region 'eu-central-1'][key 'bc56ffa4-85f8-4869-821d-b5aa4e55e016'] read aliases
KMS: [dry-run][region 'eu-central-1'][key 'df4e99a9-eb9d-4fe8-85bf-8b1287a64138'] read aliases
KMS: finished cleaning up old aliases
KMS: finished cleaning up of old aliases
```

Commands to use:
```
tox -e py310 -- `pwd`/sct.py clean-aws-kms-aliases
tox -e py310 -- `pwd`/sct.py clean-aws-kms-aliases --dry-run
tox -e py310 -- `pwd`/sct.py clean-aws-kms-aliases --time-delta-h=72 --dry-run
tox -e py310 -- `pwd`/sct.py clean-aws-kms-aliases --regions eu-west-2 --time-delta-h=47 --dry-run
tox -e py310 -- `pwd`/sct.py clean-aws-kms-aliases --regions eu-west-2 --regions eu-west-1 --time-delta-h=47 --dry-run
```

**Comment by vponomaryov** [comment]
I haven't cleaned up all the regions. Left it to anyone who wants to try it out.
The `tox -e py310 -- `pwd`/sct.py clean-aws-kms-aliases` command will cleanup all the old aliases.

**Comment by vponomaryov** [comment]
> is running with `tox` required? 

No =)

> Or it's just the way you do it?

Yes

After the `sct.py` is the common hydra command.

**Comment by fruch** [comment]
I miss the part of it being called periodically anywhere

I would suggest it would be added to the other cleanup pipelines

**Comment by vponomaryov** [comment]
> I miss the part of it being called periodically anywhere
> 
> I would suggest it would be added to the other cleanup pipelines
> 
> Here:
> 
> https://github.com/scylladb/scylla-cluster-tests/blob/master/jenkins-pipelines/qa/hydra-cleanup-cloud.jenkinsfile

Done

**Review by fruch — APPROVED** [review]
LGTM

**Comment by vponomaryov** [comment]
@Mergifyio refresh

**Pull request merged**
