### PR TITLE
fix(unit_tests/test_events.py): Fix pylint issue

### PR DESCRIPTION
**Pull request by dkropachev**
Addressing pylint duplicate code issue.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [ ] ~~All new and existing unit tests passed (CI)~~
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by bentsi** [comment]
I can't identify the difference except for changing the location of the method...

**Comment by dkropachev** [comment]
> I can't identify the difference except for changing the location of the method and moving arguments to one line... what is exactly duplicate here?

That is true, time to time (have no idea why it does not do that all the time) pylint throw duplicate-code error on these lines of code, if you reorganize it this way it does not do that.

**Comment by fruch** [comment]
@dkropachev there really a duplication ? or it's a false alarm ?

**Comment by dkropachev** [comment]
> @dkropachev there really a duplication ? or it's a false alarm ?

Real duplication, this code is partially duplicated from tester.py

**Comment by fruch** [comment]
> > @dkropachev there really a duplication ? or it's a false alarm ?
> 
> Real duplication, this code is partially duplicated from tester.py

so why not just solve the duplication ?
I know pylint has weird issues around it, i.e. no always finding the duplication

but if it did, maybe it better just to address it ?

**Comment by dkropachev** [comment]
> > > @dkropachev there really a duplication ? or it's a false alarm ?
> > 
> > 
> > Real duplication, this code is partially duplicated from tester.py
> 
> so why not just solve the duplication ?
> I know pylint has weird issues around it, i.e. no always finding the duplication
> 
> but if it did, maybe it better just to address it ?

There two ways to solve this duplication:
1. Make ClusterTester so that you could test it, but it is work for couple of PRs.
2. Create Base class before ClusterTester that will hold these two methods and solely purpose of which is being used in this particular test.

**Pull request merged**
