### PR TITLE
test(artifacts test): add ability to test Scylla Manager

### PR DESCRIPTION
**Pull request by enaydanov**
Trello: https://trello.com/c/dsfJI1Jw/1512-manager-agent-in-artifacts-tests-for-all-distros

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [x] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [x] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
i think it is missing another parameter, that is scylla_repo_m `Url to the repo of scylla version to install scylla from for managment tests`

**Comment by fgelcer** [comment]
> i think it is missing another parameter, that is scylla_repo_m `Url to the repo of scylla version to install scylla from for managment tests`

i see it is declared on `test_default.yaml`, in case artifact tests are using it too

**Comment by enaydanov** [comment]
> > i think it is missing another parameter, that is scylla_repo_m `Url to the repo of scylla version to install scylla from for managment tests`
> 
> i see it is declared on `test_default.yaml`, in case artifact tests are using it too

I just set it to `scylla_repo`:

```sh
export SCT_SCYLLA_REPO_M="${params.scylla_repo}"
```

**Comment by fgelcer** [comment]
> > > i think it is missing another parameter, that is scylla_repo_m `Url to the repo of scylla version to install scylla from for managment tests`
> > 
> > 
> > i see it is declared on `test_default.yaml`, in case artifact tests are using it too
> 
> I just set it to `scylla_repo`:
> 
> ```shell
> export SCT_SCYLLA_REPO_M="${params.scylla_repo}"
> ```

I see... missed it before, but, i think we want here to use last stable (either enterprise or OSS) version.
Although it shall work as it is, if version under test isn't broken.

**Comment by fruch** [comment]
Who is going to trigger those jobs with manager version ? it would be on every release of manager ?

**Comment by roydahan** [comment]
From the task description:

So I thought to start with something like that:
3.3 artifacts will install manager-2.0 agent
4.0 & 4.1 will install manager-2.1 agent
master will install manager-master agent.

If agent installations fails for some reason, it fails the entire test.
I know It can create a dependency that not necessarily exist, but I think it's acceptable from now.

**Comment by bentsi** [comment]
@enaydanov how are you going to set `scylla_mgmt_repo` according to what Roy proposed?
Those jobs are triggered automatically and I don't think Releng passes `scylla_mgmt_repo` param, so probably we will need to create PR's with defaults for each of the branches that Roy mentioned.

**Comment by enaydanov** [comment]
> @enaydanov how are you going to set `scylla_mgmt_repo` according to what Roy proposed?
> Those jobs are triggered automatically and I don't think Releng passes `scylla_mgmt_repo` param, so probably we will need to create PR's with defaults for each of the branches that Roy mentioned.

My initial idea was to ask RelEng to add this parameter to their jobs, but we can set them in `test-cases/artifacts/*.yaml` instead.

**Comment by fruch** [comment]
> > @enaydanov how are you going to set `scylla_mgmt_repo` according to what Roy proposed?
> > Those jobs are triggered automatically and I don't think Releng passes `scylla_mgmt_repo` param, so probably we will need to create PR's with defaults for each of the branches that Roy mentioned.
> 
> My initial idea was to ask RelEng to add this parameter to their jobs, but we can set them in `test-cases/artifacts/*.yaml` instead.
> 
> But in this case we should change these files on branch creation too. If we want to set `scylla_mgmt_repo` to `master` for master branch.

we already had defaults for those, we'll need to change the default in each branch.

Would be nice if we had a way to do a per version option, similar to how we treat per region defaults in AWS. but figure out the version/branch might be a bit tricky, since we need to do that before having a running server. 
since there are more place such thing might be needed, for example the default command line args for scylla

**Comment by bentsi** [comment]
Ok, let's not expose it as a param in the pipeline and use branches to set the correct repo.
Another thing with using branches is that the link to the repository is different for Debian like and RHEL like repos...

**Comment by bentsi** [comment]
I think better to set the `scylla_mgmt_repo` on each of the YAMLs:
```
.
├── amazon2.yaml
├── ami.yaml
├── centos7.yaml
├── centos8.yaml
├── debian10.yaml
├── debian9.yaml
├── docker.yaml
├── oel76.yaml
├── rhel7.yaml
├── rhel8.yaml
├── ubuntu1604.yaml
└── ubuntu1804.yaml

```

**Comment by enaydanov** [comment]
> I think better to set the `scylla_mgmt_repo` on each of the YAMLs:
> 
> ```
> .
> ├── amazon2.yaml
> ├── ami.yaml
> ├── centos7.yaml
> ├── centos8.yaml
> ├── debian10.yaml
> ├── debian9.yaml
> ├── docker.yaml
> ├── oel76.yaml
> ├── rhel7.yaml
> ├── rhel8.yaml
> ├── ubuntu1604.yaml
> └── ubuntu1804.yaml
> ```

Ok. But we need exclude `ami.yaml` and `docker.yaml`. Do I need to create another PR for master branch or make changes here?

**Comment by roydahan** [comment]
@bentsi is right (good catch).
No need to handle ami and docker.
you can push for master here and new PRs for the older branches.

**Comment by enaydanov** [comment]
Finally, I decided to define default values for `scylla_mgmt_repo` in `.jenkinsfile`'s. I split this PR into two commits, please do not smash them and backport the first one only.

**Comment by fgelcer** [comment]
shouldn't we be aiming to master:latest or either latest stable (including RCs)?

**Comment by enaydanov** [comment]
> shouldn't we be aiming to master:latest or either latest stable (including RCs)?
http://downloads.scylladb.com/manager/rpm/unstable/centos/master/latest/ is not updated from the middle of January. Don't know why.

**Comment by fgelcer** [comment]
> > shouldn't we be aiming to master:latest or either latest stable (including RCs)?
> 
> http://downloads.scylladb.com/manager/rpm/unstable/centos/master/latest/ is not updated from the middle of January. Don't know why.

i have seen errors like this before, and IIRC @yaronkaikov was the one who fixed them.

**Comment by bentsi** [comment]
@enaydanov please open an issue to fix the latest link in `scylla-pkg`, then we will need to update the YAMLs

**Comment by enaydanov** [comment]
> @enaydanov please open an issue to fix the latest link in `scylla-pkg`, then we will need to update the YAMLs

https://github.com/scylladb/scylla-pkg/issues/1358

**Comment by bentsi** [comment]
@roydahan do we need to backport to 2020.1?

**Comment by bentsi** [comment]
@enaydanov please backport.

**Pull request merged**
