### PR TITLE
store test details and statistics in DB(elasticsearch)

### PR DESCRIPTION
**Pull request by larisau**

### CODE REVIEW

**Comment by larisau** [comment]
Part of code was moved from performance regression to the tester to support all the tests. Added nemesis statistics, coredumps and errors info. Setup details are stored in DB when test starts, nemesis and stress command info stored each time it's running. Each test has its own index in ES DB (class name).
Currently tested with longevity and grow_cluster tests.

**Comment by roydahan** [comment]
@larisau, please verify that all data is in elasticsearch and merge your PR.

**Comment by larisau** [comment]
tested on performance regression with user profiles:
http://jenkins.cloudius-systems.com:8080/job/scylla-ami-perf-regression-user-profiles/31

**Comment by amoskong** [comment]
Hi @larisau 

I just touched following error, is it caused by that the data type?
After supported multi-dc, n_db_nodes might be string like this '6 6 6', 3 datacenters and each datacenter has 6 db nodes.

```
Traceback (most recent call last):
  File "/jenkins/slave/workspace/scylla-1.7-longevity-gce-multidc/label/gce2/sdcm/tester.py", line 129, in wrapper
    return method(*args, **kwargs)
  File "/jenkins/slave/workspace/scylla-1.7-longevity-gce-multidc/label/gce2/sdcm/tester.py", line 235, in setUp
    self.create_test_stats()
  File "/jenkins/slave/workspace/scylla-1.7-longevity-gce-multidc/label/gce2/sdcm/tester.py", line 1051, in create_test_stats
    db.create(self.test_index, self.test_type, self.test_id, self.stats)
  File "/jenkins/slave/workspace/scylla-1.7-longevity-gce-multidc/label/gce2/sdcm/es.py", line 29, in create
    self._es.create(index=index, doc_type=doc_type, id=doc_id, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 258, in create
    id, '_create'), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'mapper_parsing_exception', u'failed to parse [setup_details.n_db_nodes]')
```

SCT log: [parse_error_multi-dc-job.log.txt](https://github.com/scylladb/scylla-cluster-tests/files/1297959/parse_error_multi-dc-job.log.txt)

**Comment by larisau** [comment]
Yes, the problem is in the new format of n_db_nodes string that has blank symbols.
I sent the fix: https://github.com/scylladb/scylla-cluster-tests/pull/371

**Pull request merged**
