### PR TITLE
Multiple fixes to test_enospc_before_restore in mgmt_cli_test.py

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by ShlomiBalalis** [comment]
[Successful run](https://jenkins.scylladb.com/job/scylla-staging/job/Shlomo/job/sct-feature-test-backup/7/)

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by fgelcer** [comment]
@fruch , can you please help here reviewing and merging? there is a failing test in the patch release of 3.1.2

**Review by fruch — APPROVED** [review]

**Comment by fruch** [comment]
> @fruch , can you please help here reviewing and merging? there is a failing test in the patch release of 3.1.2

It's merged, backport would wait for someone to be in front of a keyboard

**Comment by fgelcer** [comment]
> > @fruch , can you please help here reviewing and merging? there is a failing test in the patch release of 3.1.2
> 
> It's merged, backport would wait for someone to be in front of a keyboard

backported

**Pull request merged**
