### PR TITLE
Revert "fix(upgrade_tests): write data for validation with CL=ALL"

### PR DESCRIPTION
**Pull request by fruch**
Reverts scylladb/scylla-cluster-tests#6452

Looks like the `stress_before_upgrade` is actually happing during upgrades and using cl=all breaks all rolling upgrades.

### CODE REVIEW

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by fgelcer** [comment]
@fruch , once you backport to 2023.1 and 5.2, LMK so i can re-trigger the rolling upgrade jobs that failed because of it

**Comment by fruch** [comment]
> @fruch , once you backport to 2023.1 and 5.2, LMK so i can re-trigger the rolling upgrade jobs that failed because of it

I have backported it, for triggering you might ask releng which job to trigger

**Comment by fgelcer** [comment]
> > @fruch , once you backport to 2023.1 and 5.2, LMK so i can re-trigger the rolling upgrade jobs that failed because of it
> 
> I have backported it, for triggering you might ask releng which job to trigger

i will trigger them, thank you

**Comment by mykaul** [comment]
I'm unsure that this is the right way to handle it. If I understand correctly, you can't use CL=ALL because some nodes are unavailable?

**Comment by fruch** [comment]
> I'm unsure that this is the right way to handle it. If I understand correctly, you can't use CL=ALL because some nodes are unavailable?

the initial assumption of the change I've did was that `stress_before_upgrade` is done while all node are up, so we can use ALL
but it wasn't true in all of the test using it, and in some the `stress_before_upgrade` was used while the 1st/2nd node are be upgrades, we can use ALL while nodes are down.

we'll need to align the test code that `stress_before_upgrade` would be use before the upgrade, and a different command with QURUM could be used during the upgrade.

**Pull request merged**
