### PR TITLE
refactor(azure config): Changed backup backend to azure instead of s3

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
Since in real azure clusters customers will most likely use azure as the backup backend
as well, our scenarios should match it.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by rayakurl — APPROVED** [review]
approved

**Comment by rayakurl** [comment]
@fgelcer - FYI

**Review by fgelcer — COMMENTED** [review]
do we have a successful backup to Azure backend?

**Comment by ShlomiBalalis** [comment]
> do we have a successful backup to Azure backend?

yes https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/longevity-10gb-3h-azure-test/9/

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by soyacz — APPROVED** [review]
Only if I knew it is so easy... :smiling_face_with_tear:

**Comment by soyacz** [comment]
@roydahan do we want this backported to 5.0/2022.1 branches? So we would have passing backup nemesis there too.

**Comment by roydahan** [comment]
If that's all what needed, sure.

**Pull request merged**
