### PR TITLE
Cassandra-stress jar file with fix of NoSuchElement issue

### PR DESCRIPTION
**Pull request by juliayakovlev**
This jar has been built from slivne_fix_cs_userdefined_retry branch and intended to prevent  NoSuchElementException during c-s running on schema with materialized views/secondary indexes

### CODE REVIEW

**Comment by amoskong** [comment]
Why don't you copy the file in loader setup (after installed scylla-tools-java package) in this PR?  

cover /usr/share/scylla/cassandra/stress.jar by the stress.jar in PR

**Comment by bentsi** [comment]
I don't understand, why do we need a binary file in the Git repository? and where in the SCT code is it used?

**Comment by amoskong** [comment]
I have same question as Bentsi.

What I do is uploading files to s3, replacing in loader setup by curl.
We can update new version if it is in s3 (not sct repo)

sdcm/cluster.py
@@ -2032,6 +2032,8 @@ def node_setup(self, node, verbose=False,
db_node_address=None, **kwargs):
            node.remoter.run('sudo apt-get update')
            node.remoter.run('sudo apt-get install -y -o
Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
--force-yes --allow-unauthenticated {}-tools'.format(node.scylla_pkg()))

 +        node.remoter.run('sudo curl -L
https://s3.amazonaws.com/scylla-qa-public/stress.jar -o
/usr/share/scylla/cassandra/stress.jar', verbose=True)
 +       node.remoter.run('sudo curl -L
https://s3.amazonaws.com/scylla-qa-public/cassandra-stress -o
/usr/bin/cassandra-stress', verbose=True)
        node.wait_cs_installed(verbose=verbose)
        if node.is_rhel_like():
            node.remoter.run('sudo yum install -y screen')



Bentsi <notifications@github.com> 于 2019年1月17日周四 上午12:28写道：

**Comment by roydahan** [comment]
This is a temporary solution.
When we will have Ami for loader that contains the updated c-s probably no one will need it.

Furthermore, it’s much more convenient and won’t require S3 access for those who need / want to replace c-s jar in their tests.

I don’t have general objection to store binaries that we commonly use in the repo.

**Comment by bentsi** [comment]
1) Git is not a place to store binary files and is not designed for this
2) AWS access is required anyway (Keystore and  Hydra for example) so it is not a problem

**Comment by bentsi** [comment]
Read here about the reasons why it is a  bad practice to store binaries in Git: https://robinwinslow.uk/2013/06/11/dont-ever-commit-binary-files-to-git/

**Comment by larisau** [comment]
Large(usually) binaries can significantly increase time of repo download

**Comment by roydahan** [comment]
It's 500KB.
Better than to clone entire scylla-tools-java and build c-s everytime (ask Yulia how painful it can be sometimes).
This is my opinion at least.

**Comment by bentsi** [comment]
Agree that compiling is not an option. Let's put it in S3.

**Comment by amoskong** [comment]
We already have loader AMI which contains shlomi's fixed C-S.

Let's close this PR.

**Pull request closed without merging**
