### PR TITLE
fix(performance_test): Wait compaction finalization before test

### PR DESCRIPTION
**Pull request by aleksbykov**
Add to test_read and test_mixed (throughput tests) the no compaction
running waiter after preload data is done and berfore read/mixed
stress

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~New configuration option are added and documented (in `sdcm/sct_config.py`)~
- [ ] ~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~
- [ ] ~All new and existing unit tests passed (CI)~
- [ ] ~I have updated the Readme/doc folder accordingly (if needed)~

### CODE REVIEW

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by fgelcer** [comment]
@aleksbykov , @roydahan has the right answer, but i think we should back port it to `branch-perf-v8` as well, Because the performance tests (but performace with nemesis ones) are running from it, and not from v10

**Comment by roydahan** [comment]
In theory it shouldn't affect the current tests we have because they were all served from cache.
However, we need to prove it and run it with branch-perf-v8 and see if we get the same results.

**Comment by roydahan** [comment]
This one can be closed.
I'm testing this + more changes in another PR.

**Pull request closed without merging**
