### PR TITLE
improvement(ScyllaLogCollector): Added scylla-manager-agent.yaml

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
Since sometimes the yaml is sometimes required for manager related investigations, I added it to the collected log entities of the scylla node log collector

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by ShlomiBalalis** [comment]
Tested and passed:
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/artifacts-ubuntu2204-test_collect-agent-yaml/
7b67b46c-11a4-45cc-9a19-628984232e1d

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by ShlomiBalalis** [comment]
Reran the job with manager disabled just to make sure it will not cause a failure with the log collection, and it did not
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/artifacts-ubuntu2204-test_collect-agent-yaml/3/
The content of the collected file was `cat: /etc/scylla-manager-agent/scylla-manager-agent.yaml: No such file or directory`, so clearly our log collector can handle that.

**Comment by fruch** [comment]
> Reran the job with manager disabled just to make sure it will not cause a failure with the log collection, and it did not
> https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/artifacts-ubuntu2204-test_collect-agent-yaml/3/
> The content of the collected file was `cat: /etc/scylla-manager-agent/scylla-manager-agent.yaml: No such file or directory`, so clearly our log collector can handle that.

That totaly cosmetic

**Comment by ShlomiBalalis** [comment]
> > Reran the job with manager disabled just to make sure it will not cause a failure with the log collection, and it did not
> > https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/artifacts-ubuntu2204-test_collect-agent-yaml/3/
> > The content of the collected file was `cat: /etc/scylla-manager-agent/scylla-manager-agent.yaml: No such file or directory`, so clearly our log collector can handle that.
> 
> That totaly cosmetic

Wdym?

**Comment by fruch** [comment]
> > > Reran the job with manager disabled just to make sure it will not cause a failure with the log collection, and it did not
> > > https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/artifacts-ubuntu2204-test_collect-agent-yaml/3/
> > > The content of the collected file was `cat: /etc/scylla-manager-agent/scylla-manager-agent.yaml: No such file or directory`, so clearly our log collector can handle that.
> > 
> > That totaly cosmetic
> 
> Wdym?

That I'm o.k. with having a file like that in case the manager agent isn't installed, it's a cosmetic issue.

**Comment by ShlomiBalalis** [comment]
So... do you approve @fruch?

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@vponomaryov or @soyacz would be able to merge and backport tomorrow

**Review by vponomaryov — APPROVED** [review]
LGTM

**Comment by vponomaryov** [comment]
Backported.
The `manager-3.0` had merge conflicts.

**Pull request merged**
