### PR TITLE
fix(GrafanaSnapshot): get snapshot even panel is not fully loaded

### PR DESCRIPTION
**Pull request by aleksbykov**
By default grafana dashboard reload data with 30s interval.
Sometimes it could bring that while panel has been loading
previous data, it starts load new version. The loadign element
continue to stay in Panel DOM structue and cause exception by timeout

1. Added ot dashboard url qs parameter &refresh=1d to avoid often
page refreshing
2. Added more panels to OververDashboard, to validate dashboard loading
3. Added additional exception by timeout, to get snapshot if some panel
don't have data loaded.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by bentsi** [comment]
did you test it?

**Comment by bentsi** [comment]
please fix pre-commit for the files that you touched

**Comment by aleksbykov** [comment]
> did you test it?

Yes. it works.

**Comment by aleksbykov** [comment]
> please fix pre-commit for the files that you touched

Why i didn't get pre-commits warning during commiting?

**Review by fgelcer — DISMISSED** [review]
LGTM

**Comment by fgelcer** [comment]
@aleksbykov , don't we want this on perf-v10 and perf-v11 as well?

**Comment by aleksbykov** [comment]
> @aleksbykov , don't we want this on perf-v10 and perf-v11 as well?

@fgelcer , i think no, it is related only for scylla-monitor-3.8

**Comment by aleksbykov** [comment]
@bentsi i fixed for files i modified, but precommit continue to fail with other files.

**Comment by fgelcer** [comment]
> @bentsi i fixed for files i modified, but precommit continue to fail with other files.

`sdcm/logcollector.py` still have 25 pylint failures

**Comment by aleksbykov** [comment]
> > @bentsi i fixed for files i modified, but precommit continue to fail with other files.
> 
> `sdcm/logcollector.py` still have 25 pylint failures

Fixed

**Review by bentsi — APPROVED** [review]

**Comment by bentsi** [comment]
@aleksbykov next time please fix pylint issues in separate commit

**Pull request merged**
