### PR TITLE
improvement(k8s-eks): cleanup OIDC providers

### PR DESCRIPTION
**Pull request by vponomaryov**
After merge of the https://github.com/scylladb/scylla-cluster-tests/pull/5658 we create OIDC providers running on EKS backend. 
And the problem with it is that we do not cleanup created OIDC providers. 
It doesn't get automatically deleted with an associated EKS cluster too.

So, delete it explicitly to avoid limits violations.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by vponomaryov** [comment]
Tested here: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-provision-eks-cluster/113/consoleFull

**Review by soyacz — APPROVED** [review]
In case destroy oidc provider fails or delete cluster fails after deletion, it will leave oidc provider until manual removal. I don't think it will be frequent issue, but if you know some nice&easy solution better to implement it right away.

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
> In case destroy oidc provider fails or delete cluster fails after deletion, it will leave oidc provider until manual removal. I don't think it will be frequent issue, but if you know some nice&easy solution better to implement it right away.

I think we need to add this to the task we have for cleanups for k8s resources.

**Comment by vponomaryov** [comment]
> In case destroy oidc provider fails or delete cluster fails after deletion, it will leave oidc provider until manual removal. I don't think it will be frequent issue, but if you know some nice&easy solution better to implement it right away.

All the preceding cleanups are in `try`-blocks. So, deletion of `OIDC provider`s is reachable in anyway. Even if EKS cluster deletion fails.
`oidc provider` may fail, in current case only, if AWS platform API is unavailable or something like this.
So, if it is platform problem, then you won't be able to delete anyway.

**Comment by soyacz** [comment]
> > In case destroy oidc provider fails or delete cluster fails after deletion, it will leave oidc provider until manual removal. I don't think it will be frequent issue, but if you know some nice&easy solution better to implement it right away.
> 
> All the preceding cleanups are in `try`-blocks. So, deletion of `OIDC provider`s is reachable in anyway. Even if EKS cluster deletion fails. `oidc provider` may fail, in current case only, if AWS platform API is unavailable or something like this. So, if it is platform problem, then you won't be able to delete it anyway.

Yes, that may be the case. So one idea could be to add creation_time and duration tags so we could filter not only by cluster-name and make decision even without it.

**Pull request merged**
