### PR TITLE
ci(deps): pin pycodestyle to 2.10.0

### PR DESCRIPTION
**Pull request by cezarmoise**
Pins pycodestyle(https://pypi.org/project/pycodestyle/) to 2.10.0 
More recent versions break autopep8 due to https://github.com/PyCQA/pycodestyle/issues/1191
Alternatively, there is a fix in autopep8>2.0.4  https://github.com/hhatto/autopep8/pull/704

---

#### Example

```diff
diff --git a/artifacts_test.py b/artifacts_test.py
index d3dac34c0..4d5f94537 100644
--- a/artifacts_test.py
+++ b/artifacts_test.py
@@ -44,7 +44,7 @@ BACKENDS = {
 
 
 class ArtifactsTest(ClusterTester):  # pylint: disable=too-many-public-methods
-    REPO_TABLE = "housekeeping.repo"
+    REPO_TABLE= "housekeeping.repo"
     CHECK_VERSION_TABLE = "housekeeping.checkversion"
 
     def setUp(self) -> None:
```

Results in

```
➜ pre-commit run -a
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...............................................................Passed
Check for added large files..............................................Passed
Check JSON...............................................................Passed
Detect AWS Credentials...................................................Passed
Detect Private Key.......................................................Passed
autopep8.................................................................Failed
- hook id: autopep8
- exit code: 1

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/cezar/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/cezar/.pyenv/versions/3.10.14/envs/sct-3.10.14/lib/python3.10/site-packages/autopep8.py", line 4363, in _fix_file
    return fix_file(*parameters)
  File "/home/cezar/.pyenv/versions/3.10.14/envs/sct-3.10.14/lib/python3.10/site-packages/autopep8.py", line 3584, in fix_file
    fixed_source = fix_lines(fixed_source, options, filename=filename)
  File "/home/cezar/.pyenv/versions/3.10.14/envs/sct-3.10.14/lib/python3.10/site-packages/autopep8.py", line 3564, in fix_lines
    fixed_source = fix.fix()
  File "/home/cezar/.pyenv/versions/3.10.14/envs/sct-3.10.14/lib/python3.10/site-packages/autopep8.py", line 627, in fix
    self._fix_source(filter_results(source=''.join(self.source),
  File "/home/cezar/.pyenv/versions/3.10.14/envs/sct-3.10.14/lib/python3.10/site-packages/autopep8.py", line 571, in _fix_source
    modified_lines = fix(result)
  File "/home/cezar/.pyenv/versions/3.10.14/envs/sct-3.10.14/lib/python3.10/site-packages/autopep8.py", line 770, in fix_e225
    pycodestyle.missing_whitespace_around_operator(fixed, ts))
AttributeError: module 'pycodestyle' has no attribute 'missing_whitespace_around_operator'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cezar/.pyenv/versions/sct-3.10.14/bin/autopep8", line 8, in <module>
    sys.exit(main())
  File "/home/cezar/.pyenv/versions/3.10.14/envs/sct-3.10.14/lib/python3.10/site-packages/autopep8.py", line 4498, in main
    results = fix_multiple_files(args.files, args, sys.stdout)
  File "/home/cezar/.pyenv/versions/3.10.14/envs/sct-3.10.14/lib/python3.10/site-packages/autopep8.py", line 4390, in fix_multiple_files
    results.extend([x.get() for x in rets if x is not None])
  File "/home/cezar/.pyenv/versions/3.10.14/envs/sct-3.10.14/lib/python3.10/site-packages/autopep8.py", line 4390, in <listcomp>
    results.extend([x.get() for x in rets if x is not None])
  File "/home/cezar/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
AttributeError: module 'pycodestyle' has no attribute 'missing_whitespace_around_operator'

ruff.....................................................................Passed
```

### CODE REVIEW

**Comment by fruch** [comment]
I would suggest always installing environment from `requirements.txt`, version listed there are the one proven to be working.

using any other variations could end up failing all bunch of things.

regarding backports, we'll consider which branches we would, it's not a needed fix for release branches.

**Comment by fruch** [comment]
@dimakr 

Can you take over and rebuild the docker image ?

**Comment by dimakr** [comment]
> @dimakr
> 
> Can you take over and rebuild the docker image ?

@fruch Updated the docker version to the latest number and pushed the image

**Comment by fruch** [comment]
> That fail in test_cassandra_stress_thread.py integration tests is something not related to this change, it is failing on the master as well.

please open an issue for it:
unit_tests/test_cassandra_stress_thread.py::test_01_cassandra_stress

it's not clear what's going on there.

**Review by fruch — APPROVED** [review]
LGTM

**Comment by dimakr** [comment]
> please open an issue for it:

Created https://github.com/scylladb/scylla-cluster-tests/issues/9542 for this problem

**Pull request merged**
