### PR TITLE
fix(manager): Added 'Aborted' task status

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@ShlomiBalalis what's the context of this PR ?

**Comment by ShlomiBalalis** [comment]
@fruch In one of the longevities of @fgelcer the repair task reached a status of `Aborted`, and since the status was not recognized by sct the wait function continued ad infinitum, until the longevity ended. This should remedy it.

**Comment by fgelcer** [comment]
> @fruch In one of the longevities of @fgelcer the repair task reached a status of `Aborted`, and since the status was not recognized by sct the wait function continued ad infinitum, until the longevity ended. This should remedy it.

it wasn't a longevity, it was a performance job with nemesis

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by fgelcer** [comment]
thank you @ShlomiBalalis

**Pull request merged**
