### PR TITLE
fix(curl failure square brackets): new curl version fails for ipv6

### PR DESCRIPTION
**Pull request by fgelcer**
square brackets

so there are 2 options, to escape the square brackets or to add the -g
paramater, that will switch off globbing parser.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
it worked for private IPs:
Screenshot from 2020-06-21 20-10-08

and for IPv6:
Screenshot from 2020-06-21 20-10-12

**Comment by bentsi** [comment]
@fgelcer check why `lint_test_cases` failed and ask @Orenef11 why `unit-tests` failed

**Comment by fgelcer** [comment]
> @fgelcer check why `lint_test_cases` failed and ask @Orenef11 why `unit-tests` failed

inside of the link, i see the lint_test_cases all green (only the provision test is grey, as it didn't run)

**Comment by fgelcer** [comment]
> @fgelcer check why `lint_test_cases` failed and ask @Orenef11 why `unit-tests` failed

checking with @Orenef11 , we see that the repo file is broken, hence it failed

**Comment by fgelcer** [comment]
@bentsi , it could be related to #2289

**Comment by fgelcer** [comment]
@bentsi , issues were fixed, and the CI checks passed

**Pull request merged**
