### PR TITLE
Add first Jenkins pipeline

### PR DESCRIPTION
**Pull request by fruch**
A few examples of pipelines for SCT

an example job running it:
http://jenkins.scylladb.com/view/staging/job/scylla-staging/job/longevity-pipeline-fruch

`jenkins-pipelines/longevity.jenkinsfile`:
a plain straight forward example of a specific pipeline

since we are going to use same pipeline as templates I've crate `vars/longevityPipeline.groovy` as an example of a template pipeline
 
`jenkins-pipelines/master-longevity.jenkinsfile` is an example of a usage of the template/module.
i.e. where you can have a fixed values for the `sct_repo` and `sct_branch` for example

we probably would want to have a directory per branch we maintain with it's pipeline jobs, giving us a good control which job runs where

### CODE REVIEW

**Comment by fruch** [comment]
@roydahan submit the review... I might see the question :)

**Comment by roydahan** [comment]
Weird, it didn’t save it.
My question was if it’s maybe worth to split the run SCT stage into two:
1. Setting test params
2. Run.

**Comment by fruch** [comment]
@roydahan 
I don't think so, maybe we could put all the configuration selection log into `environment {}` clause

**Comment by bentsi** [comment]
the code for the pipeline is the same for all SCT tests, the question is how we can easily create a job and configure it to use the test and test configuration

**Comment by bentsi** [comment]
another thing it should support selecting backend to run on (aws, gce)

**Comment by bentsi** [comment]
another thing, I think we should merge #817 before moving to Pipelines

**Comment by fruch** [comment]
rolling upgrade might look like this:
Screenshot from 2019-05-15 15-11-08

**Comment by fruch** [comment]
@bentsi 
I agree on the backend selection, even that it would complex some of the things like labeling on which workers to work, and so on...

As for waiting for avocado, that a chicken and a hen problem, part of pushing those pipeline now it's cause we need to create new jobs, after we are done, moving to the use the new `hydra unit-test` would be a few lines of change. 

This would step the ground work, switch to the new way of running would be quite seamless since all the job configuration would be inside the code.

**Comment by bentsi** [comment]
@fruch please use qa bot credentials

**Comment by roydahan** [comment]
Need to change the name of google-cloud-snitch yaml to gce-snitch-multi-dc.yaml

**Pull request merged**
