### PR TITLE
Update jepsen pipeline

### PR DESCRIPTION
**Pull request by temichus**
commit 1: update jepsen pipeline
cover Jensen pipeline by fail faster pipeline logic

commit 2: report to argus in post
added additional reporting to Argus in post pipeline section in case an Exception happened in the pipeline itself

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by temichus** [comment]
test runs: 
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/test_catch_failed_runs_earlier/30/
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/jepsen-test-all/4/

**Comment by temichus** [comment]
> > test runs: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/test_catch_failed_runs_earlier/30/ https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/jepsen-test-all/4/
> 
> both failed

I failed them by myself to check that "Argus test run finished." in any case

**Comment by fruch** [comment]
@temichus if you were already touch the jepsen pipeline, why not fixing the issue it has, while you are at it ?
```
12:38:06  install-bash-completion current path: /tmp/workspace/scylla-staging/artsiom_mishuta/jepsen-test-all/scylla-cluster-tests
12:38:06  Error: Option '--test-name' requires an argument.
```

**Review by fruch — APPROVED** [review]
LGTM

**Comment by temichus** [comment]
> This PR changes 2 pipelines, not only the `jePsen` one. So, what about updating all other pipelines which have similar situation?
> 
> * vars/artifactsPipeline.groovy
> * vars/rollingOperatorUpgradePipeline.groovy
> * vars/rollingUpgradePipeline.groovy
> 
> Also, please update the commit with the `jepsen` pipeline to have correct letters in the word `jepsen`. It is valuable for future search attempts in git commit history.

created separate task for this 

as it takes quite a long time to test changes in CI + mentioned pipelines currently have no issues with missed reports. set priority P3, size medium

cc @fruch @roydahan

**Comment by temichus** [comment]
> Also, please update the commit with the jepsen pipeline to have correct letters in the word jepsen. It is valuable for future search attempts in git commit history.
@vponomaryov 
Done

**Comment by temichus** [comment]
> @temichus if you were already touch the jepsen pipeline, why not fixing the issue it has, while you are at it ?
> 
> ```
> 12:38:06  install-bash-completion current path: /tmp/workspace/scylla-staging/artsiom_mishuta/jepsen-test-all/scylla-cluster-tests
> 12:38:06  Error: Option '--test-name' requires an argument.
> ```

have no idea what should be put in --test-name

**Comment by vponomaryov** [comment]
> > Also, please update the commit with the jepsen pipeline to have correct letters in the word jepsen. It is valuable for future search attempts in git commit history.
> > @vponomaryov
> > Done

Not done. The commit message still has typos. `Commit message` != `github PR message`

**Review by vponomaryov — APPROVED** [review]
LGTM

**Pull request merged**
