### PR TITLE
improvement(sdcm/sct_config.py): perform repo checks for proper backends

### PR DESCRIPTION
**Pull request by vponomaryov**
Do not verify config options values that are related to package repos
on the backends which do not use these options such as "K8S" and "siren"-based.
So, it will allow us to avoid false negative results of checks.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Review by enaydanov — COMMENTED** [review]
Do you think we need to skip verification of `scylla_repo_loader` link too? Looks like we still use it at least for `k8s-gce-minikube` backend.

**Comment by yarongilor** [comment]
> Do you think we need to skip verification of `scylla_repo_loader` link too? Looks like we still use it at least for `k8s-gce-minikube` backend.

@vponomaryov , the loader is needed in a similar case of cloud longevities as found here: https://github.com/scylladb/scylla-cluster-tests/pull/3918

would like me to add this PR there? or you prefer taking 3918 commit here?

**Comment by vponomaryov** [comment]
> Do you think we need to skip verification of `scylla_repo_loader` link too? Looks like we still use it at least for `k8s-gce-minikube` backend.

Thanks for pointing it out.
Actually, `scylla_repo_loader` is used not only in the "k8s-gce-minikube" backend but also in other "local K8S" ones.
So, that option must be kept too.

> > Do you think we need to skip verification of `scylla_repo_loader` link too? Looks like we still use it at least for `k8s-gce-minikube` backend.
> 
> @vponomaryov , the loader is needed in a similar case of cloud longevities as found here: #3918
> 
> would like me to add this PR there? or you prefer taking 3918 commit here?

I can implement both requirements in this change.If you don't mind.

**Review by yarongilor — APPROVED** [review]
LGTM

**Review by bentsi — APPROVED** [review]

**Pull request merged**
