### PR TITLE
fix(performance_regression_test): Wait no compactions after write

### PR DESCRIPTION
**Pull request by roydahan**
Since there are ongoing changes with compactions, there are cases
where compactions leftovers are still running after the prepare
workload and affecting the results of READ and MIXED workloads.

It was decided to fix it on the original branch and not advancing
to a new branch version despite the fact it may void some of the
previous results.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [x] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [x] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
This changes already exist in later branches, however, there are more changes (like shard aware loaders) that weren't approved yet.
When testing performance throughput of 5.0.rc5 we noticed that compactions are running through the entire test.
I'm opening an issue for that, but we decided to add this protection anyway on the original branch.

**Comment by roydahan** [comment]
Please do not merge yet.

**Comment by fruch** [comment]
@roydahan is this still needed ?

**Comment by roydahan** [comment]
Can be closed for now.

**Review by aleksbykov — APPROVED** [review]
LGTM

**Comment by fgelcer** [comment]
> Can be closed for now.
> 

closing for now

**Pull request closed without merging**
