### PR TITLE
improvement(cluster.py): add scylla_apt_keys parameter

### PR DESCRIPTION
**Pull request by enaydanov**
Trello: https://trello.com/c/Z9FoayPh/4441-use-relevant-gpg-keys-for-currently-installed-scylla-version

- Move add keys logic to `download_scylla_*repo()` functions
- Remove ScyllaDB PPA key completely because we don't use it anymore
- Use only recent APT key in artifact tests

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [x] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [x] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by bentsi — APPROVED** [review]

**Comment by roydahan** [comment]
I didn't understand how it works.
If now we have two different keys for 4.6 and for master, what would it pick for 4.6?
What happens in rolling upgrades from 4.6 to master?

**Comment by enaydanov** [comment]
> I didn't understand how it works. If now we have two different keys for 4.6 and for master, what would it pick for 4.6? What happens in rolling upgrades from 4.6 to master?

We have 3 keys:
  - 17723034C56D4B19  --  ScyllaDB Package Signing Key 2018
  - 5E08FBD8B5D6EC9C  --  ScyllaDB Package Signing Key 2020
  - D0A112E067426AB2  --  ScyllaDB Package Signing Key 2022

By default, all three keys added to the APT key ring, so, it'll accept all repos we made. 

For artifacts tests **only the last key** will be added to the APT key ring, so, we can verify that the repo we test is signed with the correct key.

**Review by fruch — APPROVED** [review]
LGTM

We need this, since all the manager sanity test are failing on this.

**Comment by yaronkaikov** [comment]
> > I didn't understand how it works. If now we have two different keys for 4.6 and for master, what would it pick for 4.6? What happens in rolling upgrades from 4.6 to master?
> 
> We have 3 keys:
> 
> * 17723034C56D4B19  --  ScyllaDB Package Signing Key 2018
> * 5E08FBD8B5D6EC9C  --  ScyllaDB Package Signing Key 2020
> * D0A112E067426AB2  --  ScyllaDB Package Signing Key 2022
> 
> By default, all three keys added to the APT key ring, so, it'll accept all repos we made.
> 
> For artifacts tests **only the last key** will be added to the APT key ring, so, we can verify that the repo we test is signed with the correct key.

@enaydanov So if i understand this change, you guys basically load all gpg keys. and it will use the relevant one. right?

**Comment by enaydanov** [comment]
@yaronkaikov, yes

**Comment by yaronkaikov** [comment]
> @yaronkaikov, yes

And this logic will be backport to all active releases ?

**Comment by enaydanov** [comment]
To 4.6 only, I think

**Comment by yaronkaikov** [comment]
> To 4.6 only, I think

@enaydanov Thanks. @roydahan Based on this logic, there is no point of doing the GPG revert from 4.6 #justSaying :-)

**Review by yaronkaikov — APPROVED** [review]
LGTM

**Review by roydahan — APPROVED** [review]

**Comment by roydahan** [comment]
In 4.6 they are going to revert to the old key, so we won't backport it.

**Comment by roydahan** [comment]
@bentsi this will be the end of the FF.

**Comment by bentsi** [comment]
@roydahan, I talked with @yaronkaikov and he said that they still didn't revert the commit with the new GPG in 4.6. So I am FF-ing 4.6 now, and when Yaron will revert this will be the end of FF era for 4.6

**Comment by yaronkaikov** [comment]
@bentsi just merged in into next-4.6...

**Pull request merged**
