### PR TITLE
feature(cluster.py): support new directory structure of unified package

### PR DESCRIPTION
**Pull request by syuu1228**
This is v2 of https://github.com/scylladb/scylla-cluster-tests/pull/5315, here is change list:
- Fix support of current unified package, which contains .relocatable_package_version on root, not sub-directory.

----

On https://github.com/scylladb/scylladb/pull/8867, we changed directory structure of unified package, and increment it's
relocatable_package_version to 3.0.

We need to support it on SCT to run offline tests.

### CODE REVIEW

**Comment by fruch** [comment]
@syuu1228, please run the artifact test with and without the change, and report the results back here.

**Comment by syuu1228** [comment]
@fruch Test passed on both current unified package and new unified package (https://github.com/scylladb/scylladb/pull/8867).

Current unified package: https://jenkins.scylladb.com/view/master/job/scylla-master/job/releng-testing/job/offline-installer/195/
New unified package: https://jenkins.scylladb.com/view/master/job/scylla-master/job/releng-testing/job/offline-installer/194/

Note that artifacts-offline-install jobs are modified version, since original one is hardcoded repository path and branch (it just changed the repo to syuu1228:unified_move_files_to_subdirectory_v2).

**Comment by fruch** [comment]
@syuu1228

please fix the pylint issues:
```
08:43:21  ************* Module sdcm.cluster
08:43:21  sdcm/cluster.py:2018:38: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
08:43:21  sdcm/cluster.py:2024:38: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
08:43:21  sdcm/cluster.py:32:0: C0411: standard import "from typing import List, Optional, Dict, Union, Set, Iterable, ContextManager" should be placed before "import packaging.version" (wrong-import-order)
08:43:21  sdcm/cluster.py:33:0: C0411: standard import "from datetime import datetime" should be placed before "import packaging.version" (wrong-import-order)
08:43:21  sdcm/cluster.py:34:0: C0411: standard import "from textwrap import dedent" should be placed before "import packaging.version" (wrong-import-order)
08:43:21  sdcm/cluster.py:35:0: C0411: standard import "from functools import cached_property, wraps" should be placed before "import packaging.version" (wrong-import-order)
08:43:21  sdcm/cluster.py:36:0: C0411: standard import "from collections import defaultdict" should be placed before "import packaging.version" (wrong-import-order)
08:43:21  sdcm/cluster.py:37:0: C0411: standard import "from collections.abc import Iterator" should be placed before "import packaging.version" (wrong-import-order)
08:43:21  sdcm/cluster.py:38:0: C0411: standard import "from dataclasses import dataclass" should be placed before "import packaging.version" (wrong-import-order)
```

**Comment by syuu1228** [comment]
> please fix the pylint issues:
> 
> ```
> 08:43:21  ************* Module sdcm.cluster
> 08:43:21  sdcm/cluster.py:2018:38: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
> 08:43:21  sdcm/cluster.py:2024:38: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
> 08:43:21  sdcm/cluster.py:32:0: C0411: standard import "from typing import List, Optional, Dict, Union, Set, Iterable, ContextManager" should be placed before "import packaging.version" (wrong-import-order)
> 08:43:21  sdcm/cluster.py:33:0: C0411: standard import "from datetime import datetime" should be placed before "import packaging.version" (wrong-import-order)
> 08:43:21  sdcm/cluster.py:34:0: C0411: standard import "from textwrap import dedent" should be placed before "import packaging.version" (wrong-import-order)
> 08:43:21  sdcm/cluster.py:35:0: C0411: standard import "from functools import cached_property, wraps" should be placed before "import packaging.version" (wrong-import-order)
> 08:43:21  sdcm/cluster.py:36:0: C0411: standard import "from collections import defaultdict" should be placed before "import packaging.version" (wrong-import-order)
> 08:43:21  sdcm/cluster.py:37:0: C0411: standard import "from collections.abc import Iterator" should be placed before "import packaging.version" (wrong-import-order)
> 08:43:21  sdcm/cluster.py:38:0: C0411: standard import "from dataclasses import dataclass" should be placed before "import packaging.version" (wrong-import-order)
> ```

Fixed them.

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fgelcer** [comment]
should we run offline artifacts test to test this one?

**Comment by fruch** [comment]
> should we run offline artifacts test to test this one?

@syuu1228 already run a few of them to test it.

it would be triggered tomorrow.

**Pull request merged**
