### PR TITLE
refactor(rolling-upgrades): Move back basic rolling upgrades

### PR DESCRIPTION
**Pull request by roydahan**
All the rolling upgrade tests regardless if they are "basic" or advanced should be under the "rolling-upgrades" test dir.

### Testing

- [ ]

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Review by fruch — DISMISSED** [review]
trigger file should be updated

**Review by dimakr — DISMISSED** [review]
LGTM

**Comment by dimakr** [comment]
> trigger file should be updated

@fruch
reverted the master weekly trigger to the state how it was before moving distro specific jobs out of 'rolling-upgrades' dir (with proper adjustments for new ubuntu jobs).

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
