### PR TITLE
Offline install fix

### PR DESCRIPTION
**Pull request by amoskong**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fruch — APPROVED** [review]
LGTM

**Comment by amoskong** [comment]
Test this PR by:
- root offline install: https://jenkins.scylladb.com/job/scylla-master/job/reproducers/job/byo-artifact-centos8-test/1/console
- nonroot offline install: https://jenkins.scylladb.com/job/scylla-master/job/reproducers/job/byo-artifact-centos7-test/2/console

**Review by roydahan — APPROVED** [review]

**Comment by roydahan** [comment]
@amoskong can you backport to 4.3?

**Comment by amoskong** [comment]
> @amoskong can you backport to 4.3?

Just sent a backport PR: https://github.com/scylladb/scylla-cluster-tests/pull/3061

**Pull request merged**
