### PR TITLE
improvement(oel support): Take the latest oel8 and oel9 from aws

### PR DESCRIPTION
**Pull request by roydahan**
Instead of fixing our OEL support to specific images and old versions,
this commit changes the image picking to search the offical oracle images
by owner id, for the latest OEL minor version per major version for 8 & 9.

With this change, the new images should also support newer instances
types like i4i (my original motivation behind this commit).

Ref: https://forums.oracle.com/ords/apexds/post/launch-an-oracle-linux-instance-in-aws-9462

### Testing

- [x] 🟢  https://jenkins.scylladb.com/job/scylla-master/job/reproducers/job/artifacts-oel8-test/3/ [Argus](https://argus.scylladb.com/test/c9ec58be-7258-4d57-a0de-7099a2412e15/runs?additionalRuns[]=ee569b16-c1b5-46de-98f4-37f30dd4340d)
- [x] 🟢  https://jenkins.scylladb.com/job/scylla-master/job/reproducers/job/artifacts-oel9-test/2

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
Still in draft because I haven't test these images.

**Comment by roydahan** [comment]
REMINDER TO SELF ---> change triggers for renamed pipelines in scylla-pkg

**Comment by roydahan** [comment]
Running here: https://argus.scylladb.com/test/c9ec58be-7258-4d57-a0de-7099a2412e15/runs?additionalRuns[]=66fd037e-5170-4549-bc7d-2b287da6e6a1

**Comment by fruch** [comment]
> REMINDER TO SELF ---> change triggers for renamed pipelines in scylla-pkg

At some point we should create trigger groups for each artifact type and list what to trigger in each one.

This game of syncing the trigger, and then across backports, is really getting old..

**Comment by roydahan** [comment]
BTW, the test failed.
It couldn't connect with SSH, I think these are called "hardened for a reason" :)

**Comment by fruch** [comment]
> BTW, the test failed. It couldn't connect with SSH, I think these are called "hardened for a reason" :)

based on this:
https://forums.oracle.com/ords/apexds/post/launch-an-oracle-linux-instance-in-aws-9462

I've switch it to using owner id, for lookup of the images.

and I was working for me both fro OEL8 and OEL9

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@roydahan now it works, and need to be align with the triggers

**Comment by roydahan** [comment]
scylla-pkg PR for triggers: https://github.com/scylladb/scylla-pkg/pull/4328

**Comment by roydahan** [comment]
@fruch should I run the job that creates the new jobs based on pipelines or it's scheduled somewhere?

**Comment by fruch** [comment]
> @fruch should I run the job that creates the new jobs based on pipelines or it's scheduled somewhere?

It's scheduled, but once a week.

You can retrigger it for master and enterprise

**Pull request merged**
