### PR TITLE
fix(cluster.py): skipping scylla bench installation

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by ShlomiBalalis** [comment]
@fgelcer Consider backporting

**Comment by fgelcer** [comment]
> i want to see it in the field...

[running here](https://jenkins.scylladb.com/view/enterprise-2019.1/job/enterprise-2019.1/job/rolling-upgrade/job/rolling-upgrade-centos7/28/)

**Comment by fgelcer** [comment]
test failed, but this part of the code now passed, hence merging

**Review by fgelcer — APPROVED** [review]
LGTM

**Pull request merged**
