### PR TITLE
Setting default nemesis interval to 5min

### PR DESCRIPTION
**Pull request by bentsi**

### CODE REVIEW

**Comment by roydahan** [comment]
Why 5 mins?
What was the default till now? shall we even have default?

**Comment by fruch** [comment]
There wasn't any default and the test would fail only after first nemesis run

**Comment by juliayakovlev** [comment]
> Why 5 mins?
> What was the default till now? shall we even have default?

We have nemesis_name default value but don't have default interval. Seems it's logical to have default for both. If interval doesn't defined in the yaml, thread fails

**Comment by bentsi** [comment]
There was no default. But all tests have it set. It failed the test when somebody forgot to set it (after the resources provisioned) so after this will be merged it won't fail the test.

**Pull request merged**
