### PR TITLE
fix(alternator): create role with ConsistencyLevel.ALL

### PR DESCRIPTION
**Pull request by fruch**
Since there are cases when we might start the YCSB stress before all nodes would be synced with the created role, and we might error like:
```
ERROR site.ycsb.db.DynamoDBClient
-com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException:
User not found: alternator (Service: AmazonDynamoDBv2; Status Code: 400;
Error Code: UnrecognizedClientException; Request ID: null; Proxy: null)
```

we now add the role with `ConsistencyLevel.ALL`, to avoid those races

Fix: #5805

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by soyacz — APPROVED** [review]
LGTM

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by fgelcer** [comment]
i'm running [here](https://jenkins.scylladb.com/view/scylla-5.2/job/scylla-5.2/job/SCT_Reproducers/job/upgrade-alternator-ycsb-failures/2/) to test it

**Comment by fgelcer** [comment]
> i'm running [here](https://jenkins.scylladb.com/view/scylla-5.2/job/scylla-5.2/job/SCT_Reproducers/job/upgrade-alternator-ycsb-failures/2/) to test it

@fruch @roydahan , test passed... please merge and backport (or FF), so we next runs on 5.2 and 2023.1 will not hit this issue

**Pull request merged**
