### PR TITLE
test(longevity-5000-tables): Add ChaosMonkey as nemesis to longevity …

### PR DESCRIPTION
**Pull request by roydahan**
…5k tables

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I gave variables/functions meaningful self-explanatory names
- [ ] I didn't leave commented-out/debugging code
- [ ] I didn't copy-paste code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@roydahan you are running it anywhere ? or it's anther let change it and assume it's working kind of PRs ? :stuck_out_tongue:

**Comment by roydahan** [comment]
@fruch easy merge

**Comment by fruch** [comment]
> @fruch easy merge

Someone would have nice surprise, next version we run it :)

**Comment by fruch** [comment]
@roy it was run for 3.3 already ? I wasn't tracking it...

**Pull request merged**
