### PR TITLE
feature(azure): block all external communication

### PR DESCRIPTION
**Pull request by fruch**
from now on, all resources created by SCT wouldn't be available by public network, only sct runners would be accessable, and would be used as jump server if nodes needs to be reached

### Testing

- [ ]

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevent to this change (if needed)

### CODE REVIEW

**Review by soyacz — COMMENTED** [review]
We could also try with not providing public ip at all in Azure 

also I'd rather see a field in `InstanceDefinition` instead changing `get_or_create_instances` args

**Comment by fruch** [comment]
> We could also try with not providing public ip at all in Azure 

That specific per instance

> 
> also I'd rather see a field in `InstanceDefinition` instead changing `get_or_create_instances` args 

But the NSG isn't per instance, that doesn't make any sense

Also the fact it's the same NSG for all of the test, made this change do nothing, cause the SCT runner create it, and others only get it.

**Comment by soyacz** [comment]
so could apply additional rule to block all with higher priority

**Comment by fruch** [comment]
> so could apply additional rule to block all with higher priority

that's not a new rule, that's a new NSG, that shouldn't be applied to runner

**Comment by soyacz** [comment]
> > so could apply additional rule to block all with higher priority
> 
> that's not a new rule, that's a new NSG, that shouldn't be applied to runner

I'd be opting for not giving public IP's to machines that are not meant to public

**Comment by fruch** [comment]
@soyacz already implemented this one 

closing

**Pull request closed without merging**
