### PR TITLE
improvement(latency.py): improved the collect_latency

### PR DESCRIPTION
**Pull request by fgelcer**
while we are seeing in some reports the avg being
bigger than the max of a sequence, we made few
changes to the collect_latency function, as few
things were changed around (SCT, Scylla core and others).

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
job running [here](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/add-build-id-to-report/job/perf-latency-regression-with-build-id/4/) to check PR's regression

**Review by bhalevy — APPROVED** [review]

**Comment by fgelcer** [comment]
@roydahan , [this job](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/fix_collect_latency_issues/job/perf-latency-regression-collect-latency-fix/3/) and hence this PR is ready to be merged.

**Comment by fgelcer** [comment]
@roydahan , this must reach `branch-perf-v10`

**Comment by roydahan** [comment]
I know.

**Comment by roydahan** [comment]
done.

**Comment by fgelcer** [comment]
> done.

thank you

**Pull request merged**
