### PR TITLE
feature(nemesis): introduce MemoryStressMonkey

### PR DESCRIPTION
**Pull request by amoskong**
The new nemesis tries to execute stress-ng to preemt scylla memory,
scylla lock memory is enabled by default, so scylla won't swap allocate
memroy.

Signed-off-by: Amos Kong <amos@scylladb.com>

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
is it tested on staging?
Do you have a monitor to share?

**Comment by amoskong** [comment]
> is it tested on staging?
> Do you have a monitor to share?

Test job: https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/byo-test/60/console
Monitor snapshot: https://snapshot.raintank.io/dashboard/snapshot/mLJvt8eMgqmUJXExtFRynJ33Or90gUMM

Stress-ng output: 
```
### first stress-ng executed 10 seconds.

the fail is normal, memory isn't enough.

2020-07-28 05:28:14,551 | Running command "stress-ng --vm-bytes $(awk '/MemAvailable/{printf "%d\n", $2 * 1.2;}' < /proc/meminfo)k --vm-keep -m 1 -t 100"...
2020-07-28 05:28:15,069 | stress-ng: info:  [16481] dispatching hogs: 1 vm
2020-07-28 05:28:21,017 | 2020-07-28T05:28:14+00:00  longevity-10gb-3h-master-db-node-9b6e3daf-6 !INFO    | stress-ng: invoked with 'stress-ng --vm-bytes 133284638k --vm-keep -m 1 -t 100' by user 1000
2020-07-28 05:28:21,017 | 2020-07-28T05:28:14+00:00  longevity-10gb-3h-master-db-node-9b6e3daf-6 !INFO    | stress-ng: system: 'longevity-10gb-3h-master-db-node-9b6e3daf-6' Linux 5.7.9-1.el7.elrepo.x86_64 #1 SMP Wed Jul 15 10:37:17 EDT 2020 x86_64
2020-07-28 05:28:21,017 | 2020-07-28T05:28:14+00:00  longevity-10gb-3h-master-db-node-9b6e3daf-6 !INFO    | stress-ng: memory (MB): total 122763.49, free 106143.52, shared 18.16, buffer 3.60, swap 0.00, free swap 0.00
2020-07-28 05:28:25,083 | stress-ng: error: [16493] stress-ng-vm: gave up trying to mmap, no available memory
2020-07-28 05:28:25,584 | stress-ng: info:  [16481] successful run completed in 10.03s
2020-07-28 05:28:25,585 | STDERR: stress-ng: info:  [16481] dispatching hogs: 1 vm
2020-07-28 05:28:25,585 | stress-ng: error: [16493] stress-ng-vm: gave up trying to mmap, no available memory
2020-07-28 05:28:25,585 | stress-ng: info:  [16481] successful run completed in 10.03s
2020-07-28 05:28:25,585 | Command "stress-ng --vm-bytes $(awk '/MemAvailable/{printf "%d\n", $2 * 1.2;}' < /proc/meminfo)k --vm-keep -m 1 -t 100" finished with status 0

### second stress-ng executed 109 seconds.

2020-07-28 05:28:25,586 | Running command "stress-ng --vm-bytes $(awk '/MemTotal/{printf "%d\n", $2 * 0.9;}' < /proc/meminfo)k --vm-keep -m 1 -t 100"...
2020-07-28 05:28:26,143 | stress-ng: info:  [16544] dispatching hogs: 1 vm
2020-07-28 05:28:36,019 | 020-07-28T05:28:25+00:00  longevity-10gb-3h-master-db-node-9b6e3daf-6 !INFO    | stress-ng: invoked with 'stress-ng --vm-bytes 113138830k --vm-keep -m 1 -t 100' by user 1000
2020-07-28 05:28:36,019 | 2020-07-28T05:28:25+00:00  longevity-10gb-3h-master-db-node-9b6e3daf-6 !INFO    | stress-ng: system: 'longevity-10gb-3h-master-db-node-9b6e3daf-6' Linux 5.7.9-1.el7.elrepo.x86_64 #1 SMP Wed Jul 15 10:37:17 EDT 2020 x86_64
2020-07-28 05:28:36,019 | 2020-07-28T05:28:25+00:00  longevity-10gb-3h-master-db-node-9b6e3daf-6 !INFO    | stress-ng: memory (MB): total 122763.49, free 106144.53, shared 18.16, buffer 3.60, swap 0.00, free swap 0.00
2020-07-28 05:30:15,287 | stress-ng: info:  [16544] successful run completed in 109.10s (1 min, 49.10 secs)
2020-07-28 05:30:15,288 | STDERR: stress-ng: info:  [16544] dispatching hogs: 1 vm
2020-07-28 05:30:15,288 | stress-ng: info:  [16544] successful run completed in 109.10s (1 min, 49.10 secs)
2020-07-28 05:30:15,288 | Command "stress-ng --vm-bytes $(awk '/MemTotal/{printf "%d\n", $2 * 0.9;}' < /proc/meminfo)k --vm-keep -m 1 -t 100" finished with status 0
```

**Comment by amoskong** [comment]
Currently we don't have swap for db nodes, but it will be enabled in another task.

- https://trello.com/c/oAk2GRsW/2172-scyllasetup-enable-swapfile

So it's acceptable that the first stress-ng only executed 10 seconds. Its return code is zero, it won't fail the nemesis.

```
[centos@longevity-10gb-3h-master-db-node-9b6e3daf-4 ~]$ free -g
              total        used        free      shared  buff/cache   available
Mem:            119          14          95           6          10          97
Swap:             0           0           0
```

**Comment by amoskong** [comment]
Just rebase the PR to latest master to solve the regular conflict.

**Comment by amoskong** [comment]
@bentsi can you process the backport? thanks

**Comment by amoskong** [comment]
I checked some of master jobs, the MemoryStress nemesis works well, so it's safe to backport it to 4.2

@roydahan do we want to backport it to 4.2 now?

**Pull request merged**
