### PR TITLE
Branch 2020.1 add ldap support

### PR DESCRIPTION
**Pull request by fgelcer**
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

following PR #2761 , this PR is to enable us to backport the LDAP authorization tests to branch-2020.1

### CODE REVIEW

**Comment by fgelcer** [comment]
@fruch , here the backport to branch-2020.1 of the LDAP tests, after it was merged, and we were not able to automatically backport it.
in the meanwhile, there is a job running to be sure nothing is broken after fixing all the conflicts [here](https://jenkins.scylladb.com/view/enterprise-2020.1/job/enterprise-2020.1/job/SCT_Enterprise_Features/job/LDAP_authorization/job/longevity-100gb-4h-with-ldap-authorization/2/)

**Comment by fgelcer** [comment]
> @fruch , here the backport to branch-2020.1 of the LDAP tests, after it was merged, and we were not able to automatically backport it.
> in the meanwhile, there is a job running to be sure nothing is broken after fixing all the conflicts [here](https://jenkins.scylladb.com/view/enterprise-2020.1/job/enterprise-2020.1/job/SCT_Enterprise_Features/job/LDAP_authorization/job/longevity-100gb-4h-with-ldap-authorization/3/)

@fruch , the job passed, hence it is ready to be merged.

**Comment by fgelcer** [comment]
ping @fruch

**Review by amoskong — APPROVED** [review]
LGTM

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
