### PR TITLE
Backport manager 3 support

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by ShlomiBalalis** [comment]
Checked with https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/longevity-100gb-4h-test-2022-3.0/. The run has passed.

**Comment by fgelcer** [comment]
> Checked with https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/longevity-100gb-4h-test-2022-3.0/. The run has passed.

this run is with a different branch than one in this PR... are you sure they have the same content?

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by fgelcer** [comment]
also, it doesn't seem related to your PR, but:
```
18:48:35  pylint...................................................................Failed
18:48:35  - hook id: pylint
18:48:35  - exit code: 8
18:48:35  
18:48:35  ************* Module artifacts_test
18:48:35  artifacts_test.py:264:4: R0912: Too many branches (14/12) (too-many-branches)
```

**Comment by ShlomiBalalis** [comment]
> > Checked with https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/longevity-100gb-4h-test-2022-3.0/. The run has passed.
> 
> this run is with a different branch than one in this PR... are you sure they have the same content?

Yes, only added this commit to test the code: https://github.com/ShlomiBalalis/scylla-cluster-tests/commit/412339af58151ab5983fe69b2a90af9d9fd4c2ae



> also, it doesn't seem related to your PR, but:
> 
> ```
> 18:48:35  pylint...................................................................Failed
> 18:48:35  - hook id: pylint
> 18:48:35  - exit code: 8
> 18:48:35  
> 18:48:35  ************* Module artifacts_test
> 18:48:35  artifacts_test.py:264:4: R0912: Too many branches (14/12) (too-many-branches)
> ```

Yes, already fixed in another pr: https://github.com/scylladb/scylla-cluster-tests/pull/4938

**Comment by roydahan** [comment]
For now, we hold the merge.
I don't know if it'll bring instabilities.

**Comment by rayakurl** [comment]
@roydahan - since 5.0 is promoted, can we merge and backport to 5.0 now?

**Comment by rayakurl** [comment]
@roydahan  - 5.0 is promoted for some time now, Can we merge this PR? thanks

**Comment by roydahan** [comment]
Approved for backport to 5.0 and 2022.1.

**Pull request merged**
