### PR TITLE
fix(ICS-1TB-5d): Decrease c-s duration to fit test duration

### PR DESCRIPTION
**Pull request by yarongilor**
The test duration is 7200, so c-s duration is decreased
	from 10080m to 6800m
[argus](https://argus.scylladb.com/test/d0b1d90e-dd6a-4a7c-96c3-3d31a43fc892/runs?additionalRuns[]=646aafe0-6665-4c33-8722-bbd2a90b2330)
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
@yarongilor , are you sure about all these backport labels?

**Review by fgelcer — APPROVED** [review]
other than the backport labels, LGTM

**Comment by yarongilor** [comment]
> @yarongilor , are you sure about all these backport labels?

@fgelcer , well, more precisely, the issue started from 2021.1, if it's relevant as well.

**Review by roydahan — APPROVED** [review]

**Comment by roydahan** [comment]
Backported.

**Pull request merged**
