### PR TITLE
fix(user-data): add support to Ubuntu22

### PR DESCRIPTION
**Pull request by fgelcer**
this old branch didn't have proper support to
Ubuntu22, and it is now the OS in the image created by Scylla, hence we are patching it (based on much more modern code in master branch) to have minimal support to run perf tests.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
relates to #5477

**Comment by fruch** [comment]
Again, what's stopping us from stop using this old branch ? and not spin a new one based on master ?

**Comment by fgelcer** [comment]
> Again, what's stopping us from stop using this old branch ? and not spin a new one based on master ?

at least part of the tests will be moving to newer branch soon, but for now, we need to continue getting results..
closing this one in favor of #5481

**Comment by fgelcer** [comment]
closing this one in favor of https://github.com/scylladb/scylla-cluster-tests/pull/5481

**Pull request closed without merging**
