### PR TITLE
fix(nemesis.py): ignore user-profile tables in add-drop column nemesis

### PR DESCRIPTION
**Pull request by yarongilor**
since CS cannot handles add-remove columns in user-profile mode,
	the MV / SI tables should be skipped on this nemesis

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
You are failing on pre-commit

**Comment by dkropachev** [comment]
@yarongilor 
> ```
> since CS cannot handles add-remove columns in user-profile mode,
> the MV / SI tables should be skipped on this nemesis

I have a guess that you hit this problem because you do not limit select or update to the colums defined in schema, basically you should avoid using * .

Can I have example run to look at ?

**Comment by dkropachev** [comment]
> @yarongilor
> 
> > ```
> > since CS cannot handles add-remove columns in user-profile mode,
> > the MV / SI tables should be skipped on this nemesis
> > ```
> 
> I have a guess that you hit this problem because you do not limit select or update to the colums defined in schema, basically you should avoid using * .
> 
> Can I have example run to look at ?
Run: https://jenkins.scylladb.com/job/scylla-3.3/job/longevity/job/longevity-mv-si-4days/5/
I see opotunity for easy c-s fix there, we need to only filter out schema columns by generator configuration

**Comment by roydahan** [comment]
@dkropachev what are your takes here?
Shall @yarongilor change the * to the specific table name?
He didn't test it, he tries to workaround the issue we have for mv-si longevity in 3.3

**Comment by dkropachev** [comment]
Here is 10 lines fix to solve this issue from other side - https://github.com/scylladb/scylla-tools-java/pull/144

**Comment by dkropachev** [comment]
> @dkropachev what are your takes here?
> Shall @yarongilor change the * to the specific table name?
> He didn't test it, he tries to workaround the issue we have for mv-si longevity in 3.3

I've sent email, with whole information on it.
We have to make decision, either we temprorary fix it in sct, or we pushing https://github.com/scylladb/scylla-tools-java/pull/144.

**Comment by dkropachev** [comment]
@yarongilor please fix precommit issue

**Comment by bentsi** [comment]
please fix PEP8 issue

**Pull request merged**
