### PR TITLE
fix(is_cluster_topology_consistent): Make sure non-voters don't remain in the group0.

### PR DESCRIPTION
**Pull request by aleksbykov**
Cluster topology consistent means that token ring and group0 doesn't have garbage host ids and host id as non-voter after topology operation done.
Add to check that non-voter nodes stay in cluster.

### Testing
- [Job passed with BootStreamingErr](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/longevity-100gb-4h/91/)

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by soyacz** [comment]
I'm bit confused: don't we verify non-voters are 'removed' from cluster?

**Comment by aleksbykov** [comment]
> I'm bit confused: don't we verify non-voters are 'removed' from cluster?

@soyacz 
i renamed so its name become more meaningful

**Review by soyacz — APPROVED** [review]
LGTM

**Review by vponomaryov — APPROVED** [review]
LGTM

**Comment by soyacz** [comment]
@aleksbykov please fix precommit:
```
16:11:23  ✖   header must not be longer than 72 characters, current length is 84 [header-max-length]
16:11:23  ✖   subject may not end with full stop [subject-full-stop]
```

**Comment by aleksbykov** [comment]
@soyacz , Fixed precommit

**Comment by soyacz** [comment]
@aleksbykov are backport labels right (missing 2024.1, and is this feature in 2023.1)?

**Comment by aleksbykov** [comment]
> @aleksbykov are backport labels right (missing 2024.1, and is this feature in 2023.1)?

fixed. looks, i missed on label last time

**Pull request merged**
