### PR TITLE
feature(monitoring): set monitoring branch to 4.7

### PR DESCRIPTION
**Pull request by amnonh**
- [x ] I didn't leave commented-out/debugging code

### CODE REVIEW

**Comment by fruch** [comment]
I've mark 2 provision test to run

we'll check their monitoring output, and if o.k., we can merged this one

**Comment by fruch** [comment]
@amnonh 

why we don't have images for this branch ? (i.e. in other PR i'm trying out the images, and I only see 4.6.2)

**Comment by fruch** [comment]
our dashboard becomes a bit more broken with this version:
image

for some reason the default view show only the metric name, and not the values (we'll need to fix that)

**Review by fruch — DISMISSED** [review]
LGTM

**Comment by roydahan** [comment]
I don’t want to merge it if it breaks our view

**Comment by soyacz** [comment]
os monitoring also doesn't work properly. I could see only one instance metrics. Tested on branch-perf-v14:
image

**Comment by roydahan** [comment]
@fruch please correct me if I'm wrong, but now that you moved to monitor images, it's not enough to just change the monitor branch.

**Comment by fruch** [comment]
> @fruch please correct me if I'm wrong, but now that you moved to monitor images, it's not enough to just change the monitor branch.
> 

We haven't yet merged it, but yes it changes a bit this flow of updating, hence why I've asked here where are the images

**Comment by soyacz** [comment]
@amnonh possibly problem I'm seeing is due missing backport of https://github.com/scylladb/scylla-cluster-tests/pull/6975 to branch-perf-v14

**Comment by fruch** [comment]
> our dashboard becomes a bit more broken with this version: image
> 
> for some reason the default view show only the metric name, and not the values (we'll need to fix that)

@amnonh can you help us figure this one ? its what holding us from merging this (and the fact we now need to specify also the images for 4.7)

**Comment by fruch** [comment]
@yaronkaikov 

can you clarify where the monitoring images should be found ? on which account ? 
and why aren't they public ?

**Comment by fruch** [comment]
I've check the latest runs of this PR, and the issue with the nemesis panel isn't there anymore:

image


once I'll find the right image for GCE, this is good to go

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
