### PR TITLE
fix(vars/perfRegressionParallelPipeline.groovy): fix provision_type to on_demand

### PR DESCRIPTION
**Pull request by dkropachev**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [ ] ~~All new and existing unit tests passed (CI)~~
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Review by bentsi — APPROVED** [review]

**Review by roydahan — COMMENTED** [review]
No need for this change here.
We can change it only in the weekly trigger, so once a week it will be triggered as on_demand.
I’ll try first with spot_duration.

**Comment by bentsi** [comment]
ooops, merged this

**Comment by bentsi** [comment]
reverting

**Comment by bentsi** [comment]
reverted

**Comment by roydahan** [comment]
I'll handle it for the weekly runs.

**Pull request merged**
