### PR TITLE
fix(skip nemesis before running part of it): when no prepare_saslauthd

### PR DESCRIPTION
**Pull request by fgelcer**
if prepare_saslauthd is not set, we should not even start the
nemesis, but to skip it with "UnsupportedNemesis".
The skip was already in there, but after few decisions were
taken, and few commands were run.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by amoskong** [comment]
Oops! I sent a similar PR: https://github.com/scylladb/scylla-cluster-tests/pull/3467
I didn't pirate your PR ;-)

**Review by amoskong — APPROVED** [review]

**Comment by amoskong** [comment]
I'm fine to rebase my PR (https://github.com/scylladb/scylla-cluster-tests/pull/3467/) after this PR is merged.

**Review by roydahan — APPROVED** [review]

**Comment by roydahan** [comment]
conflict to backport to branch-2021.1

**Comment by fgelcer** [comment]
well, after extra thinking about it, i think we don't need it on branch-2021.1 (@amoskong , fix me if i'm wrong)

**Pull request merged**
