### PR TITLE
fix(scylla_yaml): remove duplication of `listen_interface`

### PR DESCRIPTION
**Pull request by fruch**
by mistake `listen_interface` was duplicated, and ruff PIE check uncovered it.

this change remove the newly introduced definition

### Testing

- [x] no need for testing

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by soyacz** [comment]
but I don't see where it is duplicated...

**Review by dimakr — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
> but I don't see where it is duplicated...

see line 43 in that file...

**Comment by soyacz** [comment]
> > but I don't see where it is duplicated...
> 
> see line 43 in that file...

my mistake, was not rebased.

**Review by soyacz — APPROVED** [review]
LGTM

**Pull request merged**
