### PR TITLE
fix(ipv6 config): ubuntu 20.04 network

### PR DESCRIPTION
**Pull request by fgelcer**
since there was a workaround in place for
Amazon Linux2, and other code was prepared
for rhel like environment, here we are bypassing
the workaround, and skipping the rhel like
configuration.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
well, twice it failed during `Waiting for SSH to be up: timeout - 500 seconds - expired`

so i might be missing something... i will continue to debug it tomorrow

**Comment by fgelcer** [comment]
@juliayakovlev @roydahan , it seems now to be working in [this job](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/ipv6/job/longevity-10gb-3h-ipv6/9/console)

**Comment by fgelcer** [comment]
@roydahan , [this job](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/ipv6/job/longevity-10gb-3h-ipv6/19/) had few nodetool events error, but: 1) branch-2021.1 has no nodetool events yet; 2) we might need to add a filter to this event during `TerminateAndRemoveNodeMonkey` as the `nodetool repair` is expected to potentially fail during this nemesis.

**Comment by fgelcer** [comment]
@juliayakovlev we need your review here

**Review by juliayakovlev — APPROVED** [review]

**Review by roydahan — APPROVED** [review]

**Pull request merged**
