### PR TITLE
Changed scylla BE of manager to 2020, and added (disabled) config files for buster and focal

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
Also: alligned scylla_repo_m to be 2021.1 accross the board,
since there's no earlier version for focal

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
> @fruch A few important things to note:
> 
> * There are no manager 2.2 builds for Buster and Focal, so there's no version to upgrade from. Should we skip upgrade tests for those distributions? 

we shouldn't be backporting this change for 2.2

> * manager master still does not have focal build job - contacted Yaron about it

so what do we have in this url, the this PR is pointing to ?
`http://downloads.scylladb.com/manager/deb/unstable/focal/master/latest/scylla-manager-master/scylla-manager.list`

> * due to focal only having 2021 scylla build (for manager backend) I've updated scylla_repo_m for all distributions

This totally fine, it's something we should have done regardless (across all jobs)

**Comment by ShlomiBalalis** [comment]
> > @fruch A few important things to note:
> > 
> > * There are no manager 2.2 builds for Buster and Focal, so there's no version to upgrade from. Should we skip upgrade tests for those distributions?
> 
> we shouldn't be backporting this change for 2.2

What I meant was that, in upgrade tests of focal and buster, what will the base manager version be?
http://downloads.scylladb.com/deb/debian/scylladb-manager-2.2-buster.list was only a placeholder, it doesn't exist.

> > * manager master still does not have focal build job - contacted Yaron about it
> 
> so what do we have in this url, the this PR is pointing to ?
> `http://downloads.scylladb.com/manager/deb/unstable/focal/master/latest/scylla-manager-master/scylla-manager.list`

It was a place holder until the build was created, no it exists. I'm running the test in staging to check it

**Comment by fruch** [comment]
> > > @fruch A few important things to note:
> > > 
> > > * There are no manager 2.2 builds for Buster and Focal, so there's no version to upgrade from. Should we skip upgrade tests for those distributions?
> > 
> > 
> > we shouldn't be backporting this change for 2.2
> 
> What I meant was that, in upgrade tests of focal and buster, what will the base manager version be?
> http://downloads.scylladb.com/deb/debian/scylladb-manager-2.2-buster.list was only a placeholder, it doesn't exist.
> 
> > > * manager master still does not have focal build job - contacted Yaron about it
> > 
> > 
> > so what do we have in this url, the this PR is pointing to ?
> > `http://downloads.scylladb.com/manager/deb/unstable/focal/master/latest/scylla-manager-master/scylla-manager.list`
> 
> It was a place holder until the build was created, now it exists. I'm running the test in staging to check it

Don't leave placeholders, if something doesn't exist, it should be in the code. it would only cause confusion.
if some setups we can't do upgrade test we don't have installers for them in 2.2, that's o.k. but use specific faliure/comment in places, and not place holders, non existing paths in s3.

**Comment by fruch** [comment]
@ShlomiBalalis please add the jobs to master, and share a links of working jobs.

**Comment by ShlomiBalalis** [comment]
I ran all of the sanities with 2020.1 and they passed: https://jenkins.scylladb.com/view/scylla-manager/job/manager-master/job/staging/

**Comment by fruch** [comment]
@ShlomiBalalis can this be close ?

**Comment by fruch** [comment]
@ShlomiBalalis can you confirm this one is working on master ? I'm not sure we should to backport this to 2.3...

**Comment by ShlomiBalalis** [comment]
We already have a test that passed with 2020: https://jenkins.scylladb.com/view/scylla-manager/job/manager-master/job/centos-upgrade-test/158/
But I guess it's not really a must have for 2.3

**Pull request merged**
