### PR TITLE
improvement(sct.py): Collect argus events if they don't exist

### PR DESCRIPTION
**Pull request by k0machi**
This commit allows `collect-logs` command to check if argus run has
received events from `tester.py`, and if it hasn't, restarts the old
event device and registry and resubmits events from it.

Task: #7483

### Testing

- [x] [Argus](https://argus.scylladb.com/test/b0b22734-758e-47b4-b6ec-29e64d212d52/runs?additionalRuns[]=91f70677-988e-41b2-bedf-6fbb545f1c26)
- [x] [Jenkins](https://jenkins.scylladb.com/job/scylla-staging/job/alexey/job/alexey-argus-testing/97/)

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by k0machi** [comment]
Added what I think the PR should be backported to, feel free to remove uneeded ones.

**Comment by k0machi** [comment]
I've also ran the code locally and it seems to work:

image

**Review by fruch — APPROVED** [review]
LGTM

**Comment by soyacz** [comment]
> backports would be quite a pain

Why?
I'll be also updating Argus client and will require backporting too.

**Review by soyacz — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
> > backports would be quite a pain
> 
> Why?
> I'll be also updating Argus client and will require backporting too.

Building docker images

**Comment by soyacz** [comment]
> > > backports would be quite a pain
> > 
> > 
> > Why?
> > I'll be also updating Argus client and will require backporting too.
> 
> Building docker images per branch

I'm confused... why we need docker image per branch?

**Comment by fruch** [comment]
> > > > backports would be quite a pain
> > > 
> > > 
> > > Why?
> > > I'll be also updating Argus client and will require backporting too.
> > 
> > 
> > Building docker images per branch
> 
> I'm confused... why we need docker image per branch?

for older branches, like 2024.1

**Comment by soyacz** [comment]
> > > > > backports would be quite a pain
> > > > 
> > > > 
> > > > Why?
> > > > I'll be also updating Argus client and will require backporting too.
> > > 
> > > 
> > > Building docker images per branch
> > 
> > 
> > I'm confused... why we need docker image per branch?
> 
> for older branches, like 2024.1

I just saw it, it's very bad.

**Pull request merged**
