### PR TITLE
fix(manager default): scylla now uses Focal Fossa as default

### PR DESCRIPTION
**Pull request by fgelcer**
base image, hence need to update the default manager agent
to the correct repo.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by bentsi — APPROVED** [review]

**Comment by bentsi** [comment]
we can't backport  to perf-v8 since we use the branch for old releases that use CentOS...

**Comment by fgelcer** [comment]
> we can't backport to perf-v8 since we use the branch for old releases that use CentOS...

@bentsi , in fact that is the same for perf-v10 as well...
so, we might add another param in the jenkins job, to decide what to install, instead of having it hard coded like this?

**Comment by fgelcer** [comment]
> > we can't backport to perf-v8 since we use the branch for old releases that use CentOS...
> 
> @bentsi , in fact that is the same for perf-v10 as well...
> so, we might add another param in the jenkins job, to decide what to install, instead of having it hard coded like this?

@roydahan , what would you like to do for it?
perf-v8 doesn't need it, only perf-v10... should we create `branch-perf-v10-master` to support it?

**Comment by roydahan** [comment]
We need the backport only to branch-perf-v10.

**Comment by fgelcer** [comment]
> We need the backport only to branch-perf-v10.

so this branch might not work on releases, as they might not be based on rhel

**Comment by roydahan** [comment]
This fix is not good enough.
The fix should be as follow:
- agent_version: x.y
- mapping somewhere between the agent version to its packages location.
- Each platform installs the relevant packages based on the platform and version.

**Pull request merged**
