### PR TITLE
improvement(c-s): remove redundant jmx port specification in c-s CMDs

### PR DESCRIPTION
**Pull request by vponomaryov**
Remove `-port jmx=6868` part from all the C-S commands to avoid following error messages in loaders logs:

```
    Stress command completed with bad status 143: Failed to connect over JMX; not collecting these stats
```

Such error exists in all our loader logs because of the 2 reasons:
- JMX port is different than the configured one
- JMX port is opened only for localhost and closed for all other including loader ones

So, it has been trying all the time to connect to JMX service, timing out and only then starting the load.
So, just remove it.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
> The same may be done for all other dozens of test configuration files.

I think we never actually been using (at least since I've remember)

**Comment by roydahan** [comment]
Yes, this param is older than me and I don’t think anyone has tried removing it.
Let’s remove it from all of the configuration files. (In this PR)

**Comment by vponomaryov** [comment]
> Yes, this param is older than me and I don’t think anyone has tried removing it. Let’s remove it from all of the configuration files. (In this PR)

Done

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
