### PR TITLE
Add java for keytool

### PR DESCRIPTION
**Pull request by fruch**
### Testing

- [ ]

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@dimakr 

here are two options that can help you use keytool

I think I prefer the 2nd, i.e. to pull it as need, and not have it always available

**Review by dimakr — APPROVED** [review]
LGTM

**Comment by dimakr** [comment]
> I think I prefer the 2nd, i.e. to pull it as need, and not have it always available

Agree. Looks like exactly what we need to go on with keytool.

**Comment by fruch** [comment]
> LGTM

@dimakr 

pick one of the two commits, and you can take them to you own PR, to get it working and able to run on jenkins

**Comment by fruch** [comment]
no needed anymore, closing this PR

**Pull request closed without merging**
