### PR TITLE
improvement(test-defaults): decrease reactor stalls limit to 100ms

### PR DESCRIPTION
**Pull request by bentsi**
Per Shlomi's request https://github.com/scylladb/scylla/issues/8089#issuecomment-804225804

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [ ] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Comment by roydahan** [comment]
We can’t do it until we decide on the new severity of stalls events and the way to filter them from mail but keeping them in attachment.

**Comment by roydahan** [comment]
We merged few PRs to handle the stalls better.
Let's see how it looks now before we merge this.

**Comment by fgelcer** [comment]
same change was merged 2 or 3 days ago on 64e4813a4aa193006b31a45711a591e4f0d4002e

**Comment by fgelcer** [comment]
same change was merged 2 or 3 days ago on 64e4813a4aa193006b31a45711a591e4f0d4002e

**Pull request closed without merging**
