### PR TITLE
longevity: fixed write prepare verification

### PR DESCRIPTION
**Pull request by larisau**

### CODE REVIEW

**Comment by larisau** [comment]
otherwise test will stuck on waiting on an empty queue - forever as we know(need to be fixed too :))

**Comment by amoskong** [comment]
Thanks for the fix, introduced by me in merge.

**Comment by roydahan** [comment]
Needs backport to branch-2.1

**Comment by amoskong** [comment]
It's already backported to branch-2.1
```
commit 51cf6a625bfd7d5e1f130961ecc7ff0062c32aa3
Author: Larisa Ustalov <larisau@scylladb.com>
Date:   Sun Nov 19 11:03:42 2017 +0200

    longevity: fixed write prepare verification
    
    (cherry picked from commit dce508c1d0872bcd075944e97c8c902c5c050e47)

```

**Pull request merged**
