### PR TITLE
fix(rolling-upgrade): ignore RPC `unknown exception`

### PR DESCRIPTION
**Pull request by fruch**
ignoring those unsuppressed exceptions,
till both ends of the upgrade would have scylladb/scylladb#14681

Ref: scylladb/scylladb#14681
Ref: scylladb/scylladb#14882

### Testing
- [x] - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/rolling-upgrade-ubuntu20.04-test/11

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by soyacz — APPROVED** [review]
LGTM

**Review by fgelcer — APPROVED** [review]
LGTM

**Comment by roydahan** [comment]
If it's temporary, how shall we remember to remove it later?

**Comment by fruch** [comment]
> Is it only when upgrading from 5.2 to 5.4?
> If so, we can either merge and revert from master branch or send this PR only to branch-5.4.
> In master, the upgrades now should be from 5.4.rcx to 5.5.dev..

Master is currently hard coded to start from 5.2,  on @mykaul request, he also promised us to remind us when to remove it :)

I don't want to start backporting to 5.4 we are FF for now, cause of this.

It can be left on the master, until further notice (removing it, would affect reproducing of issues and such on master)

**Comment by roydahan** [comment]
Since we have 5.4.rc0, we should release master to pick it as the base version for upgrade.

**Comment by fgelcer** [comment]
> Since we have 5.4.rc0, we should release master to pick it as the base version for upgrade.

we already have `5.4.0-rc1` running

**Pull request merged**
