### PR TITLE
fix(sct_runner): don't call ssh_run_cmd during cleanup if there is no public IP

### PR DESCRIPTION
**Pull request by enaydanov**
In Scylla Cloud staging environment, for security's sake, we have an allocated pool of public IPs for the runners.  If we fail to get an IP due to an empty pool then the cleanup script used to fail since it tried to execute a command via SSH using a public IP.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [x] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [x] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by rayakurl — CHANGES_REQUESTED** [review]
approved,  but I would re-phrase the commit message to something a bit clearer:
"In scylla cloud staging environment, for security sake, we have an allocated pool of public IPs for the runners. If we fail to allocate an IP due to an empty pool - the cleanup script used to fail since it tried to execute a command via SSH using a public IP. This commit fixes it" 

WDYT?

**Comment by enaydanov** [comment]
The commit message has been reworded.

**Review by rayakurl — APPROVED** [review]
approved

**Review by fruch — APPROVED** [review]
LGTM

**Review by vponomaryov — APPROVED** [review]
LGTM

**Pull request merged**
