### PR TITLE
Scale test - reduce the load also during prepare

### PR DESCRIPTION
**Pull request by roydahan**
### Testing

- [ ]

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevent to this change (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
Tested here: https://argus.scylladb.com/test/282f3c8b-e819-4aee-85cb-88235028ca36/runs?additionalRuns[]=261969c0-cf9b-4212-9080-15a99bf83f85

**Comment by fruch** [comment]
@roydahan 

new nodes are being added, also during prepare ? cause the load in the attach run isn't that high.
it's just to remove all the noise of the killed by read semaphore part ?

**Comment by roydahan** [comment]
> @roydahan
> 
> new nodes are being added, also during prepare ? cause the load in the attach run isn't that high. it's just to remove all the noise of the killed by read semaphore part ?

Yes, the load is stressing the disks of these machines too much because these a large blobs (8kb) written to 16 columns.

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
