### PR TITLE
fix(fill_db_data): move to invalid queries with empty key

### PR DESCRIPTION
**Pull request by aleksbykov**
According to fix https://github.com/scylladb/scylla/commit/146f7b5421a2a8f5e7e7f531db78ca53c2cb4eec
some queries with empth primary and range keys become invalid
and cause rolling-upgrade tests to fail.

move failing query to invalid queries check

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by aleksbykov** [comment]
Need to be merged to branch-4.4 only.
Job with fix passed: https://jenkins.scylladb.com/job/scylla-4.4/job/rolling-upgrade/job/rolling-upgrade-ami-test/87

**Review by fgelcer — APPROVED** [review]
are those not "invalid" for master, 4.5 and 4.6? or it is already in there?
other than knowing why we are sending this commit straight to 4.4, everything LGTM

**Comment by aleksbykov** [comment]
@fgelcer , i asked Benny, but he didn't answered yet. if same error is the reason of job failing, than i will prepare fix for master

**Comment by fgelcer** [comment]
> @fgelcer , i asked Benny, but he didn't answered yet. if same error is the reason of job failing, than i will prepare fix for master

@aleksbykov , if you added "new" tests (invalid queries), why not all the way to master and other newer branches as well?

**Comment by aleksbykov** [comment]
Do not merge the request.  The original commit was reverted from branch-4.4

**Comment by fgelcer** [comment]
> Do not merge the request. The original commit was reverted from branch-4.4

following this comment, i will close this PR to not get it mistakenly merged, and if needed, it could be reopened, if the original commit in scylla.git will be re-added.

**Pull request closed without merging**
