### PR TITLE
sdcm/fill_db_data: fix expect result bype of empty blob

### PR DESCRIPTION
**Pull request by amoskong**
In Python3 the driver returns blob as byte object.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by bentsi** [comment]
@amoskong 
1. why to backport to 3.2? this is Python 3 related fix, right?
2. unit tests failed

**Comment by fruch** [comment]
I agree with @bentsi, not backport is needed here

**Comment by amoskong** [comment]
> @amoskong
> 
> 1. why to backport to 3.2? this is Python 3 related fix, right?

You are right, no backport needed.

> 2. unit tests failed

Not caused by this PR, I will check again.

**Comment by fruch** [comment]
regarding the unittest - I'm rerunning it
and raise it as SCT issue:
https://github.com/scylladb/scylla-cluster-tests/issues/1507

**Pull request merged**
