### PR TITLE
Grant revoke ldap dbg

### PR DESCRIPTION
**Pull request by yarongilor**
not a real PR , just for debugging

### CODE REVIEW

**Comment by yarongilor** [comment]
failing with:
```
12:21:40  < t:2022-09-08 09:21:39,141 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-09-08 09:21:39.138: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=462206a1-429d-48cc-b4bc-7c9002e18f60: nemesis_name=LdapGrantRevokeRoles target_node=Node longevity-grant-revoke-grant-re-db-node-791bdbb6-2 [13.53.38.104 | 10.0.2.177] (seed: False)
12:21:41  < t:2022-09-08 09:21:41,667 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "cqlsh --no-color -u scylla-qa -p 'scylla-0'  --request-timeout=120 --connect-timeout=60  -e "ALTER ROLE 'authorized_ldap_user' with password='scylla-0'" 10.0.2.91 9042"; Exit status: 2
12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.LdapGrantRevokeRolePermission: disrupt_ldap_grant_revoke_roles got exception: Encountered a bad command exit code!
12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > 
12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > Command: 'cqlsh --no-color -u scylla-qa -p \'scylla-0\'  --request-timeout=120 --connect-timeout=60  -e "ALTER ROLE \'authorized_ldap_user\' with password=\'scylla-0\'" 10.0.2.91 9042'
12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > 
12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > Exit code: 2
12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > 
12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > Stdout:
12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > 
12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > 
12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > 
12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > Stderr:
12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > 
12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > <stdin>:1:BadCredentials: Cannot modify passwords with SaslauthdAuthenticator
```

**Comment by fgelcer** [comment]
> failing when adding a password to new user role. otherwise, cannot login without it..
> 
> ```
> 12:21:40  < t:2022-09-08 09:21:39,141 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-09-08 09:21:39.138: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=462206a1-429d-48cc-b4bc-7c9002e18f60: nemesis_name=LdapGrantRevokeRoles target_node=Node longevity-grant-revoke-grant-re-db-node-791bdbb6-2 [13.53.38.104 | 10.0.2.177] (seed: False)
> 12:21:41  < t:2022-09-08 09:21:41,667 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "cqlsh --no-color -u scylla-qa -p 'scylla-0'  --request-timeout=120 --connect-timeout=60  -e "ALTER ROLE 'authorized_ldap_user' with password='scylla-0'" 10.0.2.91 9042"; Exit status: 2
> 12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.LdapGrantRevokeRolePermission: disrupt_ldap_grant_revoke_roles got exception: Encountered a bad command exit code!
> 12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > 
> 12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > Command: 'cqlsh --no-color -u scylla-qa -p \'scylla-0\'  --request-timeout=120 --connect-timeout=60  -e "ALTER ROLE \'authorized_ldap_user\' with password=\'scylla-0\'" 10.0.2.91 9042'
> 12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > 
> 12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > Exit code: 2
> 12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > 
> 12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > Stdout:
> 12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > 
> 12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > 
> 12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > 
> 12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > Stderr:
> 12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > 
> 12:21:41  < t:2022-09-08 09:21:41,668 f:nemesis.py      l:1121 c:sdcm.nemesis         p:ERROR > <stdin>:1:BadCredentials: Cannot modify passwords with SaslauthdAuthenticator
> ```

all this mgmt (creating roles, adding password to users...) must be done from one of the super users, or any user with the correct permissions for that...
what you are seeing is that you don't have permission to login with that user and change the password

**Comment by fgelcer** [comment]
@yarongilor , also, put in here the `scylla.yaml` for better understanding of the current configuration

**Comment by yarongilor** [comment]
The job is here: https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-100gb-4h-ldap-authorization-authenticator-test-yg/16/execution/node/142/log/

**Comment by fgelcer** [comment]
from a previous, working test, we need:
```
authenticator: PasswordAuthenticator
authenticator_password: cassandra
authenticator_user: cassandra
authorizer: CassandraAuthorizer
ldap_server_type: 'openldap'
use_ldap_authorization: true

prepare_saslauthd: false
use_ldap_authentication: false
```

**Comment by yarongilor** [comment]
rerunning without authentication in: https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-100gb-4h-ldap-authorization-test-yg/2/

**Comment by fgelcer** [comment]
here it is being tested:
https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-100gb-4h-ldap-authorization-authenticator-test-yg/

**Pull request closed without merging**
