### PR TITLE
refactor(test_default): Set master branch to use manager 2.5

### PR DESCRIPTION
**Pull request by roydahan**
Manager mastr isn't stable and changes aren't communicated well to
the QA team. Hence, I decided to test scylla master with a "Fixed"
latest released manager version.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
IMPORTANT!!
@ShlomiBalalis FYI, you'll need to set manager master tests to use new branch or override the default with "manager:latest" instead of 2.5!

Once manager 2.6 is released, we need to switch to that.

**Comment by roydahan** [comment]
@scylladb/qa-maintainers if someone can review and merge today, we will have it for our weekly runs.

**Review by fgelcer — APPROVED** [review]
LGTM (although there shall be released soon 2.6, but i understand it won't wait)

**Comment by roydahan** [comment]
ping

**Review by bentsi — APPROVED** [review]

**Pull request merged**
