### PR TITLE
improvement(sdcm/cluster): Store dc and rack information in argus

### PR DESCRIPTION
**Pull request by k0machi**
This commit brings updated argus client version that supports storing dc
and rack information, and a change to submit it.

Fixes scylladb/qa-tasks#1657

### Testing

- [ ] [Jenkins](https://jenkins.scylladb.com/job/scylla-staging/job/alexey/job/alexey-argus-testing/87/)
- [ ] [Argus](https://argus.scylladb.com/test/b0b22734-758e-47b4-b6ec-29e64d212d52/runs?additionalRuns[]=4f268aa4-6f3f-4e9f-a530-28b64cc0cee1)

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by k0machi** [comment]
Seems to be working, aside from crashing on not finding the `cassandra-stress` executable..? I'm assuming  some kind of packaging issue
image

**Comment by soyacz** [comment]
> Seems to be working, aside from crashing on not finding the `cassandra-stress` executable..? I'm assuming some kind of packaging issue

no, see https://github.com/scylladb/scylla-cluster-tests/issues/7430

**Comment by soyacz** [comment]
if you rebase, https://github.com/scylladb/scylla-cluster-tests/issues/7430 should be workarounded

**Review by fruch — APPROVED** [review]
LGTM

**Review by fruch — CHANGES_REQUESTED** [review]
This doesn't work as expected from Argus end

**Comment by k0machi** [comment]
> This doesn't work as expected from Argus end

Yeah I'm putting out a client update soon, seems like Rack and DC information isn't available at the resource creation.

**Comment by fruch** [comment]
@k0machi 

image


this has multiple issues:
1) the title say Provider twice, which the 2nd one should be region
2) only the loaders and monitors, show the DC and rack information, which DB node do not.
3) can we get the actual rack names, and not their indexes ?

**Comment by k0machi** [comment]
>     1. the title say Provider twice, which the 2nd one should be region

Seems like a display bug, I'll check.

>     2. only the loaders and monitors, show the DC and rack information, which DB node do not.

As I said, the information isn't available at the resource creation.

>     3. can we get the actual rack names, and not their indexes ?

Yes, the rack names aren't provided by monitor and loader nodes - they always report 0

**Comment by fruch** [comment]
> > ```
> > 1. the title say Provider twice, which the 2nd one should be region
> > ```
> 
> Seems like a display bug, I'll check.
> 
> > ```
> > 2. only the loaders and monitors, show the DC and rack information, which DB node do not.
> > ```
> 
> As I said, the information isn't available at the resource creation.

so we might need a way to update it at a later stage...

> 
> > ```
> > 3. can we get the actual rack names, and not their indexes ?
> > ```
> 
> Yes, the rack names aren't provided by monitor and loader nodes - they always report 0

they are not running scylla, so it's irrelevant reporting/showing those.

**Comment by k0machi** [comment]
> > > ```
> > > 1. the title say Provider twice, which the 2nd one should be region
> > > ```
> > 
> > 
> > Seems like a display bug, I'll check.
> > > ```
> > > 2. only the loaders and monitors, show the DC and rack information, which DB node do not.
> > > ```
> > 
> > 
> > As I said, the information isn't available at the resource creation.
> 
> so we might need a way to update it at a later stage...
> 
> > > ```
> > > 3. can we get the actual rack names, and not their indexes ?
> > > ```
> > 
> > 
> > Yes, the rack names aren't provided by monitor and loader nodes - they always report 0
> 
> they are not running scylla, so it's irrelevant reporting/showing those.

PR https://github.com/scylladb/argus/pull/361 adds update_resource method which allows updating resource fields post creation, needed for this PR to continue

**Comment by k0machi** [comment]
Updated to include new `update_resource` call, veryfying that it works now.

**Comment by k0machi** [comment]
Works now, but small issue - new nodes added via a nemesis don't have dc/rack information

**Comment by k0machi** [comment]
@soyacz @fruch Ready for review and merge it seems.

**Pull request merged**
