### PR TITLE
fix(sla system): fix run_fullscan parameter

### PR DESCRIPTION
**Pull request by juliayakovlev**
After https://github.com/scylladb/scylla-cluster-tests/pull/5710 'run_fullscan' parameter have to be list.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fruch — DISMISSED** [review]
LGTM

**Comment by fruch** [comment]
@juliayakovlev how did you notice it ?

Can you check if we have more like those missed ?

**Comment by juliayakovlev** [comment]
> @juliayakovlev how did you notice it ?
 New test that I am working on failed due to this. So I looked on all test yaml and found that one test is not updated

> 
> Can you check if we have more like those missed ?

I found one test like this

**Comment by juliayakovlev** [comment]
@fruch Please, wait. I have to add "mode" that mandatory

**Comment by fruch** [comment]
@temichus it's a bit sad this configuration option doesn't have validation in sct_config.py that would have been picked in test case linting

**Comment by juliayakovlev** [comment]
> @fruch Please, wait. I have to add "mode" that mandatory

@fruch 
added

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by fruch — APPROVED** [review]

**Pull request merged**
