### PR TITLE
Run scylla io setup during install scylla

### PR DESCRIPTION
**Pull request by fgelcer**
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fgelcer** [comment]
this is my reproducer:
https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/upgrade_reproducer_for_9828/job/rolling-upgrade-centos8-test/

i tried few combinations, but seems still fails..

**Comment by fgelcer** [comment]
this is the relevant issue, we are trying to solve in here:
https://github.com/scylladb/scylla/issues/9828

**Comment by fgelcer** [comment]
and this is the Argus job i'm investigating:
http://argus.scylladb.com/test/ec98cdaa-7002-4bdf-b3fc-f930ccfaf73c/runs?additionalRuns%5B%5D=1d4e95e4-9122-4252-8e23-033b3219d0cb

**Comment by fruch** [comment]
I think you are barking at the wrong tree here.

As I wrote in the Scylla issue (and you guys should open a new scylla issue for the rolling upgrade), the issue there was the command line args were messed up after the upgrade)

**Comment by fgelcer** [comment]
> I think you are barking at the wrong tree here.
> 
> As I wrote in the Scylla issue (and you guys should open a new scylla issue for the rolling upgrade), the issue there was the command line args were messed up after the upgrade)

@fruch , we are trying to identify the issue, and because of people going off vacation, this issue has been moving around many people... so while i was trying to chase it, i have started running with this code in my "reproducer", and now that @soyacz was looking into it, i created this PR to share my WIP.
this is not a PR that is meant to be merged, but we are trying to identify the root cause (and i think by now we should already know it)..

**Comment by fgelcer** [comment]
@soyacz , remind me please, but IIUC we don't need this anymore, as it seems to be working fine for 5.0

**Comment by soyacz** [comment]
> @soyacz , remind me please, but IIUC we don't need this anymore, as it seems to be working fine for 5.0

yes, it's not required, issue was with recover backup problem in SCT. Already fixed.

**Pull request closed without merging**
