### PR TITLE
TWCS longevities workload refactor

### PR DESCRIPTION
**Pull request by roydahan**
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by roydahan** [comment]
@aleksbykov please take a look.

After testing, I will replace the followings:
-start-timestamp=SCT_TIME -write-rate 125
With
-start-timestamp=GET_WRITE_TIMESTAMP -write-rate GET_WRITE_RATE

So you can start working on getting it from the write output (if possible)

**Review by aleksbykov — DISMISSED** [review]

**Comment by roydahan** [comment]
@aleksbykov now it's ready for review, but it won't be complete without fixing issue #4241 .
Will you be able to do the requested in that issue soon?

If so, we can wait with this merge or at least merge but not run.

**Comment by aleksbykov** [comment]
@roydahan i working on fix for this issue

**Comment by roydahan** [comment]
Ok, so we can merge this one and @aleksbykov will rebase his fix on top of this.

**Comment by roydahan** [comment]
> @aleksbykov please take a look.
> 
> After testing, I will replace the followings: -start-timestamp=SCT_TIME -write-rate 125 With -start-timestamp=GET_WRITE_TIMESTAMP -write-rate GET_WRITE_RATE
> 
> So you can start working on getting it from the write output (if possible)

So, @aleksbykov you will take care of the parameters replacements in your PR.

**Review by aleksbykov — APPROVED** [review]
LGTM

**Pull request merged**
