### PR TITLE
fix(trigger): remove grow-shrink test from nightly run

### PR DESCRIPTION
**Pull request by soyacz**
We don't want this test to stay in nighlty trigger - was left by mistake.

### Testing

- [ ]

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by soyacz** [comment]
@fruch is backport needed?
Any other tests to include/remove?

**Comment by soyacz** [comment]
is backport needed?

**Comment by fruch** [comment]
> is backport needed?

Backport won't be needed 

But we need to disable this whole trigger 

It was disabled, but wasn't updated in the code

And last week I fixed the update code for pipeline and freestyle job to "really" update thinks based on the code 

Can you change it to disable all of this trigger for now ?

**Comment by fruch** [comment]
I've disable this trigger in
https://github.com/scylladb/scylla-cluster-tests/pull/8158

**Pull request closed without merging**
