### PR TITLE
URGENT: server encryption: extend period of validity for db.crt

### PR DESCRIPTION
**Pull request by amoskong**
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I gave variables/functions meaningful self-explanatory names
- [x] I didn't leave commented-out/debugging code
- [x] I didn't copy-paste code
- [x] I added the relevant `backport` labels
~- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)~
~- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~
~- [ ] All new and existing unit tests passed (CI)~
~- [ ] I have updated the Readme/doc folder accordingly (if needed)~

### CODE REVIEW

**Comment by amoskong** [comment]
This PR extended another 514 days for current db.crt key, then the new expired date will be `notAfter=Jan  1 10:05:27 2021 GMT`

We can extended the expired data with a big period (eg: 10 years), what's your opinion?
It's good to add a dtest to verify the expired certificate keys.

Reference:
- http://docs.scylladb.com/operating-scylla/security/generate_certificate/

**Comment by amoskong** [comment]
The expired data of current key (db.crt):

```
$ openssl x509 -enddate -noout -in db.crt
notAfter=Aug  6 08:35:12 2019 GMT
```

If server encryption is enabled, the node won't start for error:
`rpc - client 10.0.139.141: client connection dropped: The certificate is NOT trusted. The certificate chain uses expired certificate.`

**Comment by amoskong** [comment]
Hi @bentsi, 3.0 upgrade jobs also need this PR

**Comment by bentsi** [comment]
backported

**Comment by amoskong** [comment]
@bentsi @roydahan This PR had `2019.1-backported`, but it's actually not backported to branch-2019.1. All 2019.1 upgrade jobs failed for lacking of this PR.

Please help to backport it.

**Comment by roydahan** [comment]
I think it backported to the new pending 2019.1-next which is the branch of 2019.1 that is similar to 3.1.
@bentsi, we need to decide how to handle it.
I see 3 options:
- we start the full switchover
- we tell people to use the new branch, 
- we backport things also to the old branch.

**Comment by bentsi** [comment]
Option 3 is not possible.
The full switchover is ready (Jenkins jobs and code), we postponed it due to Scylla issue that we didn't understand why it happened. I think we can move gradually, job by job, disable old job and enable new pipeline job

**Comment by bentsi** [comment]
Meanwhile I can try to backport this specific PR to old branch

**Pull request merged**
