### PR TITLE
Change monitor branch to 'branch-2.1'

### PR DESCRIPTION
**Pull request by yarongilor**
Change monitor branch to 'branch-2.1' to be used as default. and also in Scylla-Manager yaml file.

### CODE REVIEW

**Comment by bentsi** [comment]
@yarongilor did you test that this works?

**Comment by roydahan** [comment]
@yarongilor did you test it?
Does monitor branch-2.1 works?

If so, approved.

**Comment by amoskong** [comment]
tests/sample.yaml still use `branch-2.0`, let's update it to branch-2.1 or master?

**Comment by yarongilor** [comment]
the PR tested and pass OK.
logs are in:
http://jenkins.cloudius-systems.com:8080/job/mermaid-1.3/job/mermaid-1.3.1-centos-client-encryption-test/label=aws-scylla-qa-builder4/4/consoleFull

**Pull request merged**
