### PR TITLE
Stop scylla before running scylla_create_devices to prevent false pos…

### PR DESCRIPTION
**Pull request by bentsi**
…itive error events

### CODE REVIEW

**Comment by amoskong** [comment]
I had a similar PR in the past, which was closed without merge.
- https://github.com/scylladb/scylla-cluster-tests/pull/1040

**Comment by fruch** [comment]
@bentsi any reason why we are waiting with merging this one ?

**Comment by amoskong** [comment]
> I had a similar PR in the past, which was closed without merge.
> 
> * #1040

@roydahan any comment?

**Comment by roydahan** [comment]
thanks @amoskong for raising, the PRs are little bit different.
What @bentsi did here was to stop scylla after it was started or probably during starting.
I'm not crazy about it, but it's different from your case where you disabled scylla not even try to start after the restart.

@bentsi did you test it?
Does scylla is able to start or trying to start after reboot or the stop command is very early?
If it's done very early and scylla doesn't even try to start, I would like it to be reverted.

**Comment by bentsi** [comment]
@amoskong in #1040 you disabled the `scylla-server` service, this is AMI specific, in production users won't do it, I assume that's why Roy disagreed to your solution

**Comment by bentsi** [comment]
@roydahan I didn't test it, but logically it is correct, that's what users will be.
Nobody will format the disk when Scylla is running, but if you won't to test this case better to add specific nemesis for that

**Comment by amoskong** [comment]
Thanks for your response.

**Pull request merged**
