### PR TITLE
refactor(tester.py, cluster.py): Refactor LDAP Initialization

### PR DESCRIPTION
**Pull request by k0machi**
This refactor fixes code duplication related to ldap setup, assures
authentication is available at all times during setup and splits
configuration into different methods, simplifying conditionals used when
configuring ldap

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [x] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [x] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Review by fgelcer — DISMISSED** [review]
have this code run with success?
in any case, LGMT

**Comment by k0machi** [comment]
> have this code run with success? in any case, LGMT

Running right now in [staging](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/alexey/job/longevity-10gb-3h-saslauthd-authenticator-ms-ad-test/), mostly worked on a previous try, failed because I used 2 nodes for replication factor of 3, but auth worked. Currently still checking using a full run.

**Comment by fgelcer** [comment]
> > have this code run with success? in any case, LGMT
> 
> Running right now in [staging](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/alexey/job/longevity-10gb-3h-saslauthd-authenticator-ms-ad-test/), mostly worked on a previous try, failed because I used 2 nodes for a replication factor of 3, but auth worked. Currently still checking using a full run.

i see the test ran for more than 4 hours, but it has a failure, that seems to be related:
```
03:08:00  Command: 'cqlsh --no-color -u cassandra -p \'cassandra-0\'  --request-timeout=120 --connect-timeout=60  -e "ALTER ROLE \'scylla-qa\' with password=\'scylla-0\'" 10.0.2.123 9042'
03:08:00  Exit code: 2
03:08:00  Stdout:
03:08:00  Stderr:
03:08:00  <stdin>:1:InvalidRequest: Error from server: code=2200 [Invalid query] message="Role scylla-qa doesn't exist."
```

**Comment by k0machi** [comment]
> > > have this code run with success? in any case, LGMT
> > 
> > 
> > Running right now in [staging](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/alexey/job/longevity-10gb-3h-saslauthd-authenticator-ms-ad-test/), mostly worked on a previous try, failed because I used 2 nodes for a replication factor of 3, but auth worked. Currently still checking using a full run.
> 
> i see the test ran for more than 4 hours, but it has a failure, that seems to be related:
> 
> ```
> 03:08:00  Command: 'cqlsh --no-color -u cassandra -p \'cassandra-0\'  --request-timeout=120 --connect-timeout=60  -e "ALTER ROLE \'scylla-qa\' with password=\'scylla-0\'" 10.0.2.123 9042'
> 03:08:00  Exit code: 2
> 03:08:00  Stdout:
> 03:08:00  Stderr:
> 03:08:00  <stdin>:1:InvalidRequest: Error from server: code=2200 [Invalid query] message="Role scylla-qa doesn't exist."
> ```

I'm not 100% sure why it wants to run that query in `update_authenticator`, investigating currently, scylla-qa does not exist in this test indeed, as this is an authentication test, where normal `cassandra` user is still being used, from my understanding, this test should not create extra roles on ldap

**Comment by k0machi** [comment]
[#11](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/alexey/job/longevity-10gb-3h-saslauthd-authenticator-ms-ad-test/12/) looks like a pass to me, only nemesis that failed is truncate_large_partition due to it not supporting saslauthd authentication, everything else seems to work.

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by bentsi — DISMISSED** [review]

**Pull request merged**
