### PR TITLE
fix(jenkinsfile): set PR jobs timeout to 90 minutes

### PR DESCRIPTION
**Pull request by enaydanov**
1 hour is not always enough to complete all provision tests, so I've added 30 minutes to timeout.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [x] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [x] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

### CODE REVIEW

**Comment by fruch** [comment]
@enaydanov can you look into having timeout per stage ? so we'll have 30min for each backend ?

**Comment by enaydanov** [comment]
> @enaydanov can you look into having timeout per stage ? so we'll have 30min for each backend ?

They run in parallel and looks like any of them requires 40-60 mins.

**Comment by enaydanov** [comment]
@fruch overall it's pretty easy to set timeouts per stage. Like, 5 minutes for precommit, 10 minutes for unit tests and linting test cases (each), and 60-90 minutes for each provision test. It'll be more granular in that case. But it'll not add any value over having global job timeout except failing faster if something will go wrong in first three stages.

**Comment by fruch** [comment]
> @fruch overall it's pretty easy to set timeouts per stage. Like, 5 minutes for precommit, 10 minutes for unit tests and linting test cases (each), and 60-90 minutes for each provision test. It'll be more granular in that case. But it'll not add any value over having global job timeout except failing faster if something will go wrong in first three stages.

Only one thing, when this job would be waiting in line, the waiting time would be counted.

Not the critical for the PR job, but in the regular SCT pipelines I bite me a few times

**Pull request merged**
