### PR TITLE
fix(aws_config): new loader ami

### PR DESCRIPTION
**Pull request by dkropachev**
Introduce loader with c-s from `master` ([b1e09c8b8ffeb8ab9a30612693869405dd41b15c](https://github.com/scylladb/scylla-tools-java/commit/b1e09c8b8ffeb8ab9a30612693869405dd41b15c)) of [scylla-tools-java](https://github.com/scylladb/scylla-tools-java) and `3.10.2-scylla-1` scylla-driver-core

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

### CODE REVIEW

**Review by fgelcer — APPROVED** [review]
LGTM

**Review by enaydanov — APPROVED** [review]

**Comment by roydahan** [comment]
Now I'm afraid to FF 4.6 because this one.

**Comment by roydahan** [comment]
I don't know what will be the changes and how it's going affect results and if they will be comparable.
@fgelcer run the job that failed and needed that.
@scylladb/qa-maintainers  For now, no one to backport this or FF any branch.

**Comment by fgelcer** [comment]
> I don't know what will be the changes and how it's going affect results and if they will be comparable. @fgelcer run the job that failed and needed that. @scylladb/qa-maintainers For now, no one to backport this or FF any branch.

running it in [here](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/4.6/job/loader-v17/job/upgrade-ami-new-loader/)

**Pull request merged**
